### ISSUE TITLE
Generated sqlite datetime with default is lacking whitespace

### ISSUE THREAD

**Issue by hsorbo** [ErikEJ/SqlCeToolbox#100]
When i choose script database from sqlce to sqlite I end up with datetime fields missing a whitespace between default and nullable

```
CREATE TABLE [X] (
  [id] INTEGER NOT NULL
.....
, [date] datetime current_timestampNOT NULL
.....
);
```

Perhaps this string should have a trailing whitespace?
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/API/Generator/Generator.cs#L1842

Toolbox version 4.5.0.2

**Comment by ErikEJ** [comment]
Fixed in the latest "daily" build - let me know if it works for you - and thanks for reporting this!
