### ISSUE TITLE
Unable to connect to the database, wizard

### ISSUE THREAD

**Issue by Pat195** [ErikEJ/SqlCeToolbox#1002]
When I connect with the code it works, but if I connect with the wizard it doesn't work.
Error : "Failed to find or load the registered .Net Framework data provider".

Visual Studio 2022

Version 4.8.776.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No
Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite Engine in use - 3.40.0
SQLite ADO.NET provider loaded - 1.0.117.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by ErikEJ** [comment]
Have you tried the daily build? 

What provider do you choose (share a screenshot perhaps) ?

**Comment by Pat195** [comment]
What is daily built and where to find it ?

**Comment by ErikEJ** [comment]
What provider did you choose??

Here: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by ErikEJ** [comment]
What "Wizard" ??

**Comment by Pat195** [comment]
.Net Framework 4.7.2
![Capture d’écran 2024-11-01 143307](https://github.com/user-attachments/assets/bf08dbde-6562-4a5d-9e4d-4289dd7a751d)
![Capture d’écran 2024-11-01 143615](https://github.com/user-attachments/assets/0cbe966b-e795-4d17-8b5d-5dcd42839e99)

**Comment by ErikEJ** [comment]
Please check this wiki post (it is complex) https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider
