### ISSUE TITLE
Does not appear in SSMS 19 or 20 even manually copying into Extensions folder

### ISSUE THREAD

**Issue by Greg90277** [ErikEJ/SqlCeToolbox#1004]
The Compact Toolbox does not appear anywhere in SSMS - none of the functionality is available. Nothing appears in the Windows or Tools menus. 

### Steps to reproduce
Follow your own installation instructions. They do not work.

### Further technical details
All files copied and extracted to C:\Program Files (x86)\Microsoft SQL Server Management Studio 20\Common7\IDE\Extensions

SSMS 20

**Comment by ErikEJ** [comment]
@Greg90277 Did you look under the View menu?

**Comment by Greg90277** [comment]
Hi Erik.

Thanks for the quick response!

There are no new menu items under the View menu or anywhere else.




[daazzle_IB8-R]

Greg Dobbs, Founder & President
daazzle, LLC

daazzle solutions<https://www.solutions.daazzle.com/>

**Comment by ErikEJ** [comment]
Did you copy the vsix contents to: C:\Program Files (x86)\Microsoft SQL Server Management Studio 20\Common7\IDE\Extensions\SqlCeToolbox

**Comment by ErikEJ** [comment]
Make sure to use build .804, I think build .802 might have been broken

**Comment by Greg90277** [comment]
Yup:

***@***.***




[daazzle_IB8-R]

Greg Dobbs, Founder & President
daazzle, LLC

daazzle solutions<https://www.solutions.daazzle.com/>

**Comment by Greg90277** [comment]
Using 4.8.803:

***@***.***





[daazzle_IB8-R]

Greg Dobbs, Founder & President
daazzle, LLC

daazzle solutions<https://www.solutions.daazzle.com/>

**Comment by ErikEJ** [comment]
Please use .804 - publishing of .803 was broken

**Comment by Greg90277** [comment]
Where would I find that? I downloaded from Visual Studio Marketplace…




[daazzle_IB8-R]

Greg Dobbs, Founder & President
daazzle, LLC

daazzle solutions<https://www.solutions.daazzle.com/>

**Comment by ErikEJ** [comment]
@Greg90277  Ah - the extension from marketplace does not work with SSMS 20! Please consult the readme! https://github.com/ErikEJ/SqlCeToolbox?tab=readme-ov-file#sql-server-management-studio-ssms-20-and-17-extension

**Comment by Greg90277** [comment]
So I copied the above and extracted it as below – still not working. Nothing in SSMS.




***@***.***





[daazzle_IB8-R]

Greg Dobbs, Founder & President
daazzle, LLC

daazzle solutions<https://www.solutions.daazzle.com/>

**Comment by ErikEJ** [comment]
Please post screen shots directly on GitHub, I cannot see them when you reply via email!

**Comment by ErikEJ** [comment]
I have updated the readme
