### ISSUE TITLE
Could not load file or assembly Microsoft.VisualStudio.Shell.15.0

### ISSUE THREAD

**Issue by mlaity** [ErikEJ/SqlCeToolbox#1009]
I'm trying to use the latest stable release of SSMS, which is 20.2, with your SQL Server Compact and SQLite Toolbox for SSMS v4.8.814.  I copied in the extracted .vsix files to C:\Program Files (x86)\Microsoft SQL Server Management Studio 20\Common7\IDE\Extensions\SqlCeToolbox_v4.8.814.  When trying to access the SqlCeToolboxPackage from the View menu in SSMS, I get the error:

> The 'SqlCeToolboxPackage' package did not load correctly.

The ActivityLog.xml file has the following error related to this:

> CreateInstance failed for package [SqlCeToolboxPackage]Source: mscorlib Description: Could not load file or assembly Microsoft.VisualStudio.Shell.15.0, Version=17.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a or one of its dependencies. The system cannot find the file specified.

Microsoft.VisualStudio.Shell.15.0 seems to be from Visual Studio 2017, which I am hoping to not have to install since I use Visual Studio 2022 primarily.

### Steps to reproduce
Install SSMS 20.2
Download add-in from https://www.vsixgallery.com/extension/d6c77c32-fe4b-4f6d-ad5d-f7b755212760
Extract .vsix file to a SqlCeToolbox folder
Copy that folder and it's contents to C:\Program Files (x86)\Microsoft SQL Server Management Studio 20\Common7\IDE\Extensions
Launch SSMS
Click the View menu and choose "SQLite / SQL Server Compact Toolbox"

### Further technical details
SSMS v20.2.30.0
No Database engine installed, only needing to use SQLite files.
Visual Studio Community 2022 v17.12.3

Any assistance would be greatly appreciated!

**Comment by ErikEJ** [comment]
I only support SSMS 21 preview.

**Comment by mlaity** [comment]
Thank you for the quick response.  Migrated to SSMS 21 Preview 1, working good now.  Thanks!

**Comment by ErikEJ** [comment]
You can easily have both 20 and 21 installed on the same machine.

**Comment by ErikEJ** [comment]
@mlaity If you like my free tools, I would be very grateful for a rating/review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) and/or a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
