### ISSUE TITLE
Can't export data from sql server

### ISSUE THREAD

**Issue by goldengrisha** [ErikEJ/SqlCeToolbox#105]
I've had some problems with exporting, not just in my compyter.
I've attached png to show the problem.
![error](https://cloud.githubusercontent.com/assets/1469234/17243018/1556a902-5583-11e6-8e3a-04a00491f32b.png)

**Comment by ErikEJ** [comment]
Add a server connection in Server Explorer, as the text says. 

(View menu, Server Explorer, Data Conections)

**Comment by goldengrisha** [comment]
Thank you) Sorry for the question.

**Comment by ErikEJ** [comment]
No worries - please let me know how I can make it clearer?
