### ISSUE TITLE
Can't generate .cs file for SQLLite used in solution made by 'Dotnet'

### ISSUE THREAD

**Issue by theDiverDK** [ErikEJ/SqlCeToolbox#107]
I made a new solution via:

dotnet new -t web

By default that type of projects uses sqllite for usermanagement.

But when using your tool, to 
![image](https://cloud.githubusercontent.com/assets/1545703/17271303/f786033c-5677-11e6-961c-0609e3442e3d.png)
I get the following error:
![image](https://cloud.githubusercontent.com/assets/1545703/17271304/0110304e-5678-11e6-881e-9728cf027d7f.png)

It might be me using the program wrongly ? :)

**Comment by ErikEJ** [comment]
Thanks for reporting this - you are not doing anything wrong! This is now fixed in the latest daily build, please let me know if it works for you!
