### ISSUE TITLE
Query editor and Grid - use the same fonts as Text editor in the VS font options

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#110]
from @zspitz  
Shouldn't the query editor and grid use the same fonts as Text editor in the VS font options?

**Comment by ErikEJ** [comment]
http://www.mztools.com/articles/2008/MZ2008008.aspx

**Comment by ErikEJ** [comment]
Fixed in latest daily! Thanks for reporting this!

**Comment by zspitz** [comment]
Thanks to you both for an amazing and useful project, and for the quick response.
