### ISSUE TITLE
Dark theme issues

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#111]
From @zspitz 

The query editor is dark text on white background, which is incompatible with the dark theme.
 (Also, the main toolbox window's butons have a light background.)

**Comment by ErikEJ** [comment]
https://stackoverflow.com/questions/18913208/colors-in-visual-studio-extension

**Comment by ErikEJ** [comment]
Not possible due to backwards compat with previous VS versions

**Comment by zspitz** [comment]
@ErikEJ Is there no mechanism for creating cross-version Visual Studio extensions?

**Comment by ErikEJ** [comment]
Yes, my extension is already targeting VS 2012 and all later VS versions. The issue is that the mechanism for handling themes is only available from VS 2015 and onward.. https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.platformui.environmentcolors?view=visualstudiosdk-2017
