### ISSUE TITLE
Composite Foreign Key

### ISSUE THREAD

**Issue by croban** [ErikEJ/SqlCeToolbox#115]
I have table with composite FK e.g.
```
CREATE TABLE [BEVERAGE_DIRECTORY] (
  [ID] bigint NOT NULL
, [LANGUAGE] text NOT NULL
, [PARENT_ID] bigint NULL
, CONSTRAINT [sqlite_autoindex_BEVERAGE_DIRECTORY_1] PRIMARY KEY ([ID],[LANGUAGE])
, FOREIGN KEY ([PARENT_ID], LANGUAGE) REFERENCES [BEVERAGE_DIRECTORY] ([ID], LANGUAGE) 
);

```
after executing "script as CREATE" following code is returned
```
CREATE TABLE [BEVERAGE_DIRECTORY] (
  [ID] bigint NOT NULL
, [LANGUAGE] text NOT NULL
, [PARENT_ID] bigint NULL
, CONSTRAINT [sqlite_autoindex_BEVERAGE_DIRECTORY_1] PRIMARY KEY ([ID],[LANGUAGE])
, FOREIGN KEY ([PARENT_ID]) REFERENCES [BEVERAGE_DIRECTORY] ([ID])
, FOREIGN KEY ([LANGUAGE]) REFERENCES [BEVERAGE_DIRECTORY] ([LANGUAGE]) 
);
```
now i have 2 FKs

**Comment by ErikEJ** [comment]
Fixed in the latest "daily" build - thanks for reporting this

**Comment by croban** [comment]
I have installed daily build (4.5.129) from VSIX Gallery. 
Adding new connection for a sqlite couse this error:

![image](https://cloud.githubusercontent.com/assets/7048578/17511302/9b60015e-5e22-11e6-9404-347d476b7d37.png)

**Comment by ErikEJ** [comment]
Do you have sqlite installed in GAC? Have you tried restarting Visual Studio?

**Comment by croban** [comment]
This version is inside GAC:
System.Data.SQLite, Version=1.0.102.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=MSIL

VS Restart does not help.

**Comment by ErikEJ** [comment]
Hhmmm... unable to repro - what happens if you remove from gac?

**Comment by croban** [comment]
That resolved my issue, 
thanks a lot!

**Comment by ErikEJ** [comment]
Thank, I will

**Comment by ErikEJ** [comment]
I will investigate!

**Comment by ErikEJ** [comment]
I am assuming your sqlite gac install was broken
