### ISSUE TITLE
WinRT, Not able to add a connection with SQLite database.

### ISSUE THREAD

**Issue by sujeetsingh2030** [ErikEJ/SqlCeToolbox#119]
Hi EricEJ,

Thanks for the nice tool. I am having problem when i try to add a new connection with my db Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "TestDB");

How to specify a connection in my case? Please guide me a little.
thanks

**Comment by ErikEJ** [comment]
Could you share some more code for me to understand the context?
And what does "having problem" mean?

**Comment by sujeetsingh2030** [comment]
Actually i am using Sqlite with Sqlite-net. Here is the code..

public string DBPath { get; set; }
 this.DBPath = Path.Combine(Windows.Storage.ApplicationData.Current.LocalFolder.Path, "TestDB");
                // Initialize the database if necessary
                using (var db = new SQLiteConnection(this.DBPath))
                {
                    // Create the tables if they don't exist
                    db.CreateTable<Doctors>();
                }

My question is, how can i make Sqlite connection with 'TestDB' database with Sqlite Toolbox?
I mean how to specify db file path?

**Comment by ErikEJ** [comment]
The file would reside in a protected location on your pc if you use the emulator or your own device. If you are able to find that location, then you can connect to the file, otherwise no.
