### ISSUE TITLE
Add Export To Excel to standalone version. (SELECT with a few thousand rows crashes the toolbox)

### ISSUE THREAD

**Issue by nicolasr75** [ErikEJ/SqlCeToolbox#120]
Hello Erik,
we have an SqlCe 4.0 database table with around 50000 records. We want to export each month separately to CSV. This makes around 3600 records per month. The SELECT statements execute successfully. It seems the only way to export the data is to select all lines in the result view and copy it to the clipboard. The problem is that it is almost impossible to select the data and open the context menu for copying it. Windows reports that the program does not react multiple times.
Do I overlook something here?
If not, there would be two improvements I could think of:
- add "Copy all" to the context menu so we don't need to select it first
- add "Export data to CSV" in the table context menu (next to Import data from CSV...)

Thanks for the great tool!
Nicolas

**Comment by ErikEJ** [comment]
Did you try the Export t Excel button in the query editor?

**Comment by nicolasr75** [comment]
It looks like this is a feature of the VS plugin only. Am I right? I am using the standalone version because I am on a customers computer.

**Comment by ErikEJ** [comment]
Yes, it currently this feature is only available in the VS extension - have you tried the command line tool ?
http://erikej.blogspot.dk/2009/07/sqlcecmd-tutorial-part-three-query.html

**Comment by nicolasr75** [comment]
Oh, I wasn't aware of the command line tool. Thanks for the pointer! It worked great and solved the problem. Nevertheless, adding the Excel button to the standalone version would be great for a future version of the toolbox. (Most of my customers always want to analyze data in Excel. They are the sort of users that get fear and consternation when confronted with a command line program ;-) )

**Comment by ErikEJ** [comment]
@nicolasr75 Did you try this?

- un-check the option to Show Results In Grid
- Run the SELECT query
- Mark all the result text and copy (Ctrl+A, Ctrl+C)
- Open a blank Excel sheet and paste

**Comment by nicolasr75** [comment]
This is actually the setting I used. I tested again with 14000 records. With the grid display the loading of the results takes very long and takes huge amounts of RAM. Without grid display the results load in 2 seconds with very little RAM. But trying to select all records with Ctrl-Shift-End breaks it. I guess it's the virtualization of the list control which makes it show the first records so fast.

**Comment by ErikEJ** [comment]
>> I guess it's the virtualization of the list control which makes it show the first records so fast.

Without the grid display there is no list control involved, so not sure what you mean by this.

Have you tried with Ctrl+A and then Ctrl+C in the text result pane??

**Comment by nicolasr75** [comment]
Ok, no list control but it remembered me of loading huge text files into Notepad, at least in older versions of Windows. When you loaded the same file into, f.e., Notepad++, there was never a problem. So I always assumed there is some sort of virtualization involved too.
Regarding Ctrl+A: it behaves the same as Ctrl-Shift-End. It takes several minutes until the results are shown selected. Ctrl-C helps somewhat though, because the copy actually works once the lines are selected. (bringing up the context menu never worked with so many lines).

**Comment by ErikEJ** [comment]
OK, I will keep this open,,,,

**Comment by ErikEJ** [comment]
Hi, this is now fixed, please let me know if you would like an updated build with the fix

**Comment by nicolasr75** [comment]
Hello Erik, thanks for letting me know. Yes I would still be very interested. This is a very important feature for my users.

**Comment by ErikEJ** [comment]
You can try it out here: https://sqlcetoolbox.codeplex.com/releases/view/104096 (NOT the ClickOnce installer)

**Comment by nicolasr75** [comment]
I tried it and it works great! Thanks for the update.
Something unrelated but I just want to mention it because other users may find it here when searching for export possibilities: the exported CSV contains datetime columns in the format yyyy-mm-ddThh:mm:ss.zzzzzz (ISO8601) which is great because it should be standard. Excel, however, does not automatically seem to recognize it. I was able to convert it in Excel with this formula: =DATEVALUE(MID(A1,1,10))+TIMEVALUE(MID(A1,12,8)). Works, but I guess not every user has that easily available.

**Comment by ErikEJ** [comment]
Did you export from the Grid or from Text results?

**Comment by nicolasr75** [comment]
The grid mode is actually not useable for me when I export that many records, in my current test case around 14000. The RAM consumption rises up to over 1 GB quickly and the program does not react anymore, actually my whole system slows down remarkably. I then closed the program because it seems like it takes forever (I repeated that test multiple times). Is that normal? I mean, current Excel versions can handle CSV files with far more records with almost no stuttering. When I switch off the grid mode, both the SELECT and the Excel Export finish in less than a second! Coming back to the datetime format: I don't know what it would be in grid mode, because I can not test it :-(

**Comment by ErikEJ** [comment]
The grid in the standalone edition is slow, and has not received the same "love" as the one in the VS edition (which performs much, much better) - and the VS edition is a much higher priority for me. 

I have opened an issue here: https://github.com/ErikEJ/SqlCeToolbox/issues/147

What text result date format would work well in Excel for you?

**Comment by nicolasr75** [comment]
Ok, I did quite a few tests now with Excel and Visual Studio. The timestamps you currently write out to the CSV work perfectly with DateTime.Parse in both full .NET and .NET Core, so that is great. Now for the Excel user: the only format that I was able to easily import without any VB code or formulas was the fully localized format. F.e. in French 2016-11-10T20:15:07.1234567 would be 10/11/2016 20:15:07,1234567. It looks like the millisecond separator also needs to be localized, i.e. comma instead of period. I would like to test german format but can not do it right now. Since both scenarios (programmer and Excel user) occur frequently in my case, there is probably no way around a customization dialog that would allow me to specify the datetime format (localized or culture invariant or ISO 8601). At the same time this could support specifying the CSV separator, string enclosing by "" etc (I am not an expert in CSV specs). As I said, I can live with the current format but for the average Excel user it may seem hard to handle.

**Comment by ErikEJ** [comment]
@nicolasr75 I have made a new release available here: https://github.com/ErikEJ/SqlCeToolbox/releases (new location!) - that might be able to fix the Grid performance issue (to soem extent)

**Comment by nicolasr75** [comment]
@ErikEJ Thanks for this new release. The grid performance problem is definitely solved for me! The SELECT query for my 14000 records now takes 10 ms as opposed to several minutes in the previous version. 

Now that I can export the result from the grid view, it is interesting to see that the resulting CSV format is different from the CSV exported from the plain text view. Date/Time are localized and a comma is chosen as the delimiter. At first I was afraid that the comma would conflict with the french/german floating point delimiter but it does not because the floating point numbers are enclosed in double quotes. 

That means the issues with getting the CSV correctly recognized in Excel are also gone. So everything is working fine for me now! Keep up the good work and thanks again!

**Comment by ErikEJ** [comment]
@nicolasr75 Great news - best of both worlds! Yes, the implementation of paste from the grid is much better than the "hand-coded" one from the text results: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/ToolWindows/SqlEditorControl.xaml.cs#L745 

If you use my tools, I would be very grateful for a rating or review here:
https://visualstudiogallery.msdn.microsoft.com/0e313dfd-be80-4afb-b5e9-6e74d369f7a1/view/Reviews
