### ISSUE TITLE
File version mismatch detected between ADO.NET Provider and SQL Server Compact

### ISSUE THREAD

**Issue by fireundubh** [ErikEJ/SqlCeToolbox#121]
When I load the toolbox for the first time, I see this error:

> File version mismatch detected between ADO.NET Provider and native binaries of SQL Server Compact which could result in an incorrect functionality.

Attempting to add an SQLite connection fails. The database, whose connection tested successfully, is not added to Data Connections.

**Comment by ErikEJ** [comment]
Your SQL Compact install is broken, remove and reinstall the versions installed on your machine (3,5 and/or 4,0) 

Not sure what the sqlite issuue is, could you provide detailed steps to reproduce

**Comment by fireundubh** [comment]
Thank you. Reinstalling SQL CE 4 SP1 x64 did not help. I had to install SQL CE 3.5 SP2 x86 and x64.

Links for anyone who finds this:

* [Microsoft SQL Server Compact Edition 3.5 SP2](https://www.microsoft.com/en-us/download/details.aspx?id=5783)
* [Microsoft SQL Server Compact Edition 4.0 SP1](https://www.microsoft.com/en-us/download/details.aspx?id=30709)

**Comment by ErikEJ** [comment]
You are welcome - yes, for historical reasons, I prefer 3.5 for Data Connection storage over 4.0 - I am considering always preferring SQLite, but that will be a breaking change (users will lose their connections) - maybe I can make some feature to move hem over...
