### ISSUE TITLE
SQLite scripts run very slow - needs transactions

### ISSUE THREAD

**Issue by steronydh** [ErikEJ/SqlCeToolbox#122]
I've got an SQL CE file about 2MB in size, from which ExportSqlCE.exe exports an SQLite scripting file of ~9MB. If I then import the script into an SQLite database, it takes about 5 minutes. I manually added a transaction wrapping the whole data insertion, and it now takes about 1 second. 

I made this change to Generator.GenerateTableContent() to generate this automatically:

```
        internal void GenerateTableContent(bool saveImageFiles)
        {
            if (_sqlite)
            {
                _sbScript.Append("BEGIN;");
                _sbScript.Append(Environment.NewLine);
            }

            foreach (string tableName in _tableNames)
            {
                GenerateTableContent(tableName, saveImageFiles);
            }

            if (_sqlite)
            {
                _sbScript.Append("COMMIT;");
                _sbScript.Append(Environment.NewLine);
            }
        }

```

Hope that's helpful.

**Comment by ErikEJ** [comment]
Fixed in latest daily build! (Except that does not include the command line tools)

**Comment by steronydh** [comment]
Great, thanks Erik! I'll patch my copy of the command line tools to match this change tomorrow and test it.

**Comment by ErikEJ** [comment]
Great - then I will update the download files on CodePlex (based on your feedback)

**Comment by steronydh** [comment]
If I run `sqlite3 database.db < script.sql` it prints out `1` - is that expected? Other than that, my 9MB script took ~1 second to run. :)

**Comment by ErikEJ** [comment]
Yes, that is expected - due to some quirk with having PRAGMA as first statement - thanks for the heads up - will leave open to remind me to build and upload new .exe files to codeplex

**Comment by ErikEJ** [comment]
Update the latest .exe files here: https://exportsqlce.codeplex.com/releases/view/116839
