### ISSUE TITLE
Export triggers/views from SQLite DBs

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#123]
I pretty much enjoy Toolbox's "Script Database" feature. Unfortunately I noticed that this function is limited to tables and does not work with triggers and views yet.

Erik, are there any plans to add this?

**Comment by ErikEJ** [comment]
I think I just forgot about it, I even have methods to get the views, and triggers definitions

**Comment by ErikEJ** [comment]
Feel free to do a Pull Request :smile:

**Comment by ErikEJ** [comment]
This has been added to the latest daily build, please let me know if it works for you (particular in doubt if triggers are scripted correctly)

**Comment by mwallnoefer** [comment]
Sorry for not responding so long. I have tried today with release 4.6.11.0 (the latest version from NuGet) and it did not work (the trigger did not appear in the export output, just the table definitions).

Do I need to activate something?

Thanks

**Comment by ErikEJ** [comment]
You need to install the latest daily build - see links here: https://github.com/ErikEJ/SqlCeToolbox

**Comment by mwallnoefer** [comment]
Okay, done, Erik.

(I can speak only for SQLite)
- The exported triggers should be terminated by a semicolon:
`CREATE TRIGGER [PointsRowIndex] AFTER INSERT ON [Points]
BEGIN
    UPDATE
        [Points]
    SET
        [RowIndex] = [rowid]
    WHERE
        [idPoint] = [new].[idPoint];
END`**;**
- In my opinion, only the triggers and views derived from the selected tables should be exported
  - For triggers obvious (are dependent on a single table)
  - For views: _if just one table_ mentioned in the AS clause is selected or _if each one_; what about views referring to system tables (discussion)?
- The **Views** and **Triggers** divisions unlike **Tables** do not contain any Refresh function in their context menu, so I need to use the global Refresh

**Comment by ErikEJ** [comment]
I have added semicolon to the end of the trigger definition.
I only script triggers if they are for the selected tables.

Both fixes are in the latest daily build 

For views, this seems like an impossible issue to solve... (I have no structured information about the tables included in the view)

Missing Refresh: I think I should move the triggers node under the Tables node... 
I have logged: https://github.com/ErikEJ/SqlCeToolbox/issues/187

**Comment by ErikEJ** [comment]
Showing the triggers in the correct place has been fixed in the latest daily build

**Comment by mwallnoefer** [comment]
Hi Erik, I am impressed by your changes, especially to put the triggers under the tables - that's amazing.

But still I would add the _Refresh_ button in the context menu of the views.  When you load a SQL script into a DB you as user may update the tables list, but not the views one. Or maybe I got something wrong, that I do not understand the reason of having _Refresh_ on the tables but not on the views. Or maybe the circular arrow on the top is enough for both, to remove the _Refresh_ on the tables?

**Comment by ErikEJ** [comment]
@mwallnoefer View refresh - I just have not gotten around to it, basically (as SQL Compact did not have views at all, it was never on my radar)  - I have logged https://github.com/ErikEJ/SqlCeToolbox/issues/189

**Comment by ErikEJ** [comment]
@mwallnoefer If you like my tools, I would be very grateful for a rating or review here:

https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details

**Comment by mwallnoefer** [comment]
Thanks for pointing this out to me, I will add some comment there.

**Comment by ErikEJ** [comment]
Added Views/Refresh menu item in latest build!
