### ISSUE TITLE
Table drop/create script problem

### ISSUE THREAD

**Issue by dav1dsm1th** [ErikEJ/SqlCeToolbox#126]
The table drop/create script moves INTEGER PRIMARY KEY definitions to a CONSTRAINT (and redefines the PK column as BIGINT) - which, for me, then causes the default behaviour of sqlite to stop working (as per https://www.sqlite.org/lang_createtable.html - "If an INSERT statement attempts to insert a NULL value into a rowid or integer primary key column, the system chooses an integer value to use as the rowid automatically").

With the PK column defined as a BIGINT an INSERT which doesn't specify a value for the PK column fails with a NOT NULL exception (as sqlite doesn't appear to allocate a new value).

**Comment by ErikEJ** [comment]
Does this also affect the standard CREATE TABLE script (no DROP involved)?

**Comment by dav1dsm1th** [comment]
Yes, it translates the "integer primary key" on the column definition to a "primary key" constraint definition on the table - so the same outcome would occur - it would no longer fill in a value if the column was omitted/null.

**Comment by ErikEJ** [comment]
Fixed in the latest "daily" build, pls let em know if it fixes your issue
https://github.com/ErikEJ/SqlCeToolbox/commit/e6bf3ef1317965c13a808eb170916078ed266a40

**Comment by dav1dsm1th** [comment]
Yes.  That fixed the issue.  Thanks for the quick turn around.
