### ISSUE TITLE
calcul delta

### ISSUE THREAD

**Issue by bouazaoui** [ErikEJ/SqlCeToolbox#129]
I am writing a query with subqueries to do the same result of this , but it must be compatible with sqlServerCe

![image](https://cloud.githubusercontent.com/assets/17064603/19730164/9869a84c-9b99-11e6-89e8-b4940d76c54b.png)

with subqueries
![image](https://cloud.githubusercontent.com/assets/17064603/19730022/2e52c25e-9b99-11e6-9708-679c835eb373.png)

datas : 
![image](https://cloud.githubusercontent.com/assets/17064603/19730269/ed31c454-9b99-11e6-8797-308264b90ffa.png)

**Comment by ErikEJ** [comment]
I you are hit by limitations in the SQL CE T-SQL syntax, you can use a code based approach instead, ie load the initial data from the database and use LINQ to Objects to transform it.
