### ISSUE TITLE
Update requires a valid UpdateCommand...

### ISSUE THREAD

**Issue by dav1dsm1th** [ErikEJ/SqlCeToolbox#130]
After subscribing to the daily build - I now get the following error message whenever I try to use "edit top 200 rows."  I can't track down a fix, so wonder if I'm doing something unusually dumb (wouldn't be the first time).

![sqlite daily build error message](https://cloud.githubusercontent.com/assets/5616164/19762474/fd2752aa-9c31-11e6-8cbe-ce2bdfe54224.JPG)

**Comment by ErikEJ** [comment]
SQLite or SQL Compact ? Have you changed the option: 
•Enable SQLite datetime editing in "Edit Table Data" to be optional

**Comment by dav1dsm1th** [comment]
SQLite.  The option "Make SQLite datetime read-only" is set false.

**Comment by dav1dsm1th** [comment]
Same error if I switch it to true.

**Comment by ErikEJ** [comment]
And if you revert to the "official" build?

**Comment by dav1dsm1th** [comment]
That was my first thought - so I reverted and the current stable works perfectly - re-enabled daily build and the error came back.

**Comment by ErikEJ** [comment]
Thanks, I will try to figure out what has changed!

**Comment by ErikEJ** [comment]
I suspect it is a bug in the System.Data.SQLite ADO.NET provider that I use...

**Comment by dav1dsm1th** [comment]
You managed to reproduce?

**Comment by ErikEJ** [comment]
Yes, and it has nothing to do with the datetime "feature"

**Comment by dav1dsm1th** [comment]
Well that's a relief.  I started to assume it was something to do with my environment.  Reproducing is the first step in fixing (but you know that better than me, probably).  Good look in your quest and thanks for the fast responses.

**Comment by ErikEJ** [comment]
Fixed in the latest daily build, let me know if it works for you!

**Comment by dav1dsm1th** [comment]
The daily build feed seems to be broken.  The last update that applied for me was 4.5.135.0.  The "download" button at http://vsixgallery.com/ is erroring with "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable." so maybe it's an issue at vsixgallery.  I'll check the fix as soon as I can get the daily builds applying again at my end.

**Comment by ErikEJ** [comment]
The feed should be in working order now!

**Comment by dav1dsm1th** [comment]
Perfect.  Can confirm the feed is working and the error is now fixed.  Thanks again for the quick responses.
