### ISSUE TITLE
SQL Server TimeStamp

### ISSUE THREAD

**Issue by iqmeta** [ErikEJ/SqlCeToolbox#131]
Hi, nice work. 

The SQL TimeStamp Type is currently ignored in the CREATE TABLE Script.

![image](https://cloud.githubusercontent.com/assets/7533842/19767025/22998a7a-9c51-11e6-9c2d-fd6d78881511.png)

Is it possible to generate these fields at least as TEXT for SQL Lite? (switchable) 
So for sync context it's possible to use the BASE64 interpretation from the SQL TimeStamp...

Kind regards.

**Comment by ErikEJ** [comment]
Is that SQLite or SQL Compact? Or when migrating from SQL Server?

**Comment by ErikEJ** [comment]
Bump!?

**Comment by iqmeta** [comment]
Oh sry.

Example: 

I create a SQL DB with Code First an have a TimeStamp (rowversion)
for syncing => see Timestamp: https://msdn.microsoft.com/en-us/data/gg193958.aspx

I create a OData Endpoint with WebAPI which gives me the TimeStamp
as an Base64 Interpretation like  "RowVersion":"AAAAAAAAB98="

So everytime the row changes the TimeStamp is updated proper by SQL Server.
Increment, and fast for index.

(eg: https://groups.google.com/forum/embed/#!topic/codenameone-discussions/LZroa9vhRCo)

I used your nice tool to create (http://stackoverflow.com/a/26059256) SQL Lite DB.
Everything is great. But "timestamp" field is just ignored.

My suggesstion is, to have option to get also the TIMESTAMP as TEXT and the BASE64,
with a command switch, because is not SQL Standard for SQLite.

This would be awesome to integrate with Mobile Apps (using SQLite) initial DB Creation and
proper sync afterwards with Odata Filter on TimeStamp for changes.

Kind regards.

**Comment by ErikEJ** [comment]
So you use the command line tool?

**Comment by ErikEJ** [comment]
OK, did some digging - looks like the timestamp column is present in the table, but the INSERT statement ignores the column, is that correctly understood? Maybe you could attach the created .sql script to this issue?

**Comment by ErikEJ** [comment]
Fixed, and new export2sqlce.exe available here: https://exportsqlce.codeplex.com/releases/view/116839

**Comment by iqmeta** [comment]
wow. that was quick. thanks going to test it next week. cheers. ;)
