### ISSUE TITLE
"View Data as Report" on table shows error message instead of report

### ISSUE THREAD

**Issue by AuleSan** [ErikEJ/SqlCeToolbox#152]
I get the following error message when I try to use the function mentioned above:

An error occurred during local Report processing.
The Definition of  the Report '' is invalid.
A field in the dataset '<MyDataSetName>' has the Name '__sysChangeTxBsn'. Field names must be CLS-compliant identifiers.

The field relates to the Synchronisation with SQLServer.

Thanks in advance for your help.

Regards
Uwe

**Comment by ErikEJ** [comment]
Are you able to share your SDf file privately?

**Comment by AuleSan** [comment]
Yes, I could provide you a small file that exhibits the problem. How should we transfer it?

**Comment by ErikEJ** [comment]
E-mail me ejlskov at hotmail dot com

**Comment by AuleSan** [comment]
It's on its way
