### ISSUE TITLE
"Generate local database cache code" grayed out

### ISSUE THREAD

**Issue by AuleSan** [ErikEJ/SqlCeToolbox#153]
My Project uses Sync Framework to synchronize SQL CE 3.5 and SQL Server. For that I have used the MSDataSyncGenerator in VS 2010 that maintained the .sync files and the accompanied .Designer files. 
Unfortunately this is no longer possible after I have moved my Project to .NET 4.6.
I only need the implementation files. My local database is created from scratch (no pre-provisioning) and I can enable Change Tracking in the relevant tables in SQLServer manually.
Is it possible to maintain those filed with this tool or am I missing something here?
I'm using VS 2015 Update 3.

Thanks in advance for your help.

Regards
Uwe

**Comment by ErikEJ** [comment]
Did you move to a new PC?

**Comment by AuleSan** [comment]
Yes, it is a new development machine, but it was the first installation of the toolkit and the machine was build from scratch...

**Comment by ErikEJ** [comment]
You need to install the Sync FX runtime, see my blog post here, with links to a JuneT blog post and the Sync FX download http://erikej.blogspot.dk/2012/05/sql-server-compact-toolbox-30visual.html

**Comment by AuleSan** [comment]
Hello Erik,
thanks fort he input. I’ve downloaded SyncFX 2.1 and now the code is working.
Unfortunately this is a different version from what I need. I’m still using the old .sync files (I think this is Sync Frameworj 1.0) that are generated by VS 2010’s MSDataSyncGenerator. This tool had a nice Wizard that generated the .sync files (XML-Definiton) and the class files as well

Is there any chance to get this with VS 2015? I’ve upgraded my project to .NET 4.6 and now I’m unable to open it in VS 2010 anymore.

Thanks again for your help.

Best Regards
Uwe


Viele Grüße / Best Regards
Uwe Reisewitz
Strategische Entwicklung
Architektur & Infrastruktur
______________________________________________________

Tel.:  +49 (641) 7941-110

Fax:  +49 (641) 7941-132

Mob: +49 (173) 3022005

E-Mail: uwe.reisewitz@ordat.com
______________________________________________________

[www.ordat.com]<http://www.ordat.com>

ORDAT Gesellschaft für Organisation und Datenverarbeitung mbH & Co. KG
Rathenaustr. 1, 35394 Gießen/Germany, <http://www.ordat.com> www.ordat.com<http://www.ordat.com/>
HRA 1192 Giessen , Geschäftsführer: J. Markus Schäfer, Gerhard Volk
Pers. haftende Ges.: ORDAT Verwaltungsgesellschaft für Organisation und Datenverarbeitung mbH, HRB 3887 Giessen

[cid:ordat-website_final_02c85c87-51fb-4623-9406-32890a5ab4ab.jpg]<http://www.ordat.com/>
Von: Erik Ejlskov Jensen [mailto:notifications@github.com]
Gesendet: Montag, 14. November 2016 17:48
An: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Cc: Reisewitz, Uwe <uwe.reisewitz@ordat.com>; Author <author@noreply.github.com>
Betreff: Re: [ErikEJ/SqlCeToolbox] "Generate local database cache code" grayed out (#153)


You need to install the Sync FX runtime, see my blog post here, with links to a JuneT blog post and the Sync FX download http://erikej.blogspot.dk/2012/05/sql-server-compact-toolbox-30visual.html

**Comment by ErikEJ** [comment]
I am sorry, this is not available (and no plans to implement either)

**Comment by AuleSan** [comment]
Ok, no problem.
At least I can open the database in VS 2015 with your great toolbox☺.

I think I will create a VS 2010 project and share my .sync files into that projext to be able to use the Sync Wizard. This form of sync framework will be replaced anyway in the future.

Thanks again for your help.

Best Regards
Uwe


Viele Grüße / Best Regards
Uwe Reisewitz
Strategische Entwicklung
Architektur & Infrastruktur
______________________________________________________

Tel.:  +49 (641) 7941-110

Fax:  +49 (641) 7941-132

Mob: +49 (173) 3022005

E-Mail: uwe.reisewitz@ordat.com
______________________________________________________

[www.ordat.com]<http://www.ordat.com>

ORDAT Gesellschaft für Organisation und Datenverarbeitung mbH & Co. KG
Rathenaustr. 1, 35394 Gießen/Germany, <http://www.ordat.com> www.ordat.com<http://www.ordat.com/>
HRA 1192 Giessen , Geschäftsführer: J. Markus Schäfer, Gerhard Volk
Pers. haftende Ges.: ORDAT Verwaltungsgesellschaft für Organisation und Datenverarbeitung mbH, HRB 3887 Giessen

[cid:ordat-website_final_02c85c87-51fb-4623-9406-32890a5ab4ab.jpg]<http://www.ordat.com/>
Von: Erik Ejlskov Jensen [mailto:notifications@github.com]
Gesendet: Montag, 14. November 2016 20:57
An: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Cc: Reisewitz, Uwe <uwe.reisewitz@ordat.com>; Author <author@noreply.github.com>
Betreff: Re: [ErikEJ/SqlCeToolbox] "Generate local database cache code" grayed out (#153)


I am sorry, this is not available (and no plans to implement either)
