### ISSUE TITLE
Add standalone .zip package with private deployed binaries

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#156]
I need to run SQL CE Toolbox Standalone on a client machine. Can I run, without installing SQL CE runtime into GAC? May be keeping necessary assemblies inside the same folder... Is there any possibility to do this?
from:
https://www.blogger.com/comment.g?blogID=5238131531249720750&postID=3217060454188121813

**Comment by ErikEJ** [comment]
[PrivateTest.zip](https://github.com/ErikEJ/SqlCeToolbox/files/595369/PrivateTest.zip)

Try this out on a machine without sqlce 4 installed, and let me know if it works for you!

**Comment by kdlkdhanuka** [comment]
Thank you so much Erik. It is working perfectly.

**Comment by ErikEJ** [comment]
@kdlkdhanuka I have added this wiki page: https://github.com/ErikEJ/SqlCeToolbox/wiki/Running-the-standalone-edition-really-standalone 

If you use my tools, I would be very grateful for a rating or review here:
https://visualstudiogallery.msdn.microsoft.com/0e313dfd-be80-4afb-b5e9-6e74d369f7a1/view/Reviews

**Comment by kdlkdhanuka** [comment]
Thanks for the wiki page. 
Reviewed 👍
