### ISSUE TITLE
Copy sql scripts for c#

### ISSUE THREAD

**Issue by radegast** [ErikEJ/SqlCeToolbox#159]
I have a plugin called sql asistant. Can work in sql server menagement studio program. When we copy the SQL queries that we write, it automatically copies it as follows.

String sql = "SELECT * FROM TABLE"

If there is an improvement like this, it will make my job very easy. We always have to put quotation marks. Thank you.

**Comment by ErikEJ** [comment]
Is that VB or C# code?

**Comment by ErikEJ** [comment]
I have also logged this: https://github.com/ErikEJ/SqlCeToolbox/issues/160

**Comment by radegast** [comment]
i mean c#, but it can might assist VB code, too.

thank you.

**Comment by ErikEJ** [comment]
I will add a dropdown button to the query editor to do this

**Comment by ErikEJ** [comment]
This has now been implemented in the latest daily build, please let me know if it works for you!
