### ISSUE TITLE
Perf issue

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#167]
Let me explain with real example. Local .sdf file. File as all data.

There is .sdf file in the solution windows app with 20 tables. I am filling all tables using Fill() on by one at once when application starts. The only reason I am doing this coz, then application run quick as all data is in object.

see example below
Public Contractors As New ds.ContractorsDataTable
Public ContractorsTA As New dsTableAdapters.ContractorsTableAdapter
 ContractorsTA.Fill(Contractors)

If i try to ready using sql query program goes slower. When I test this in SSD drive its faster but normal drive is 4 times slower.

Can you also provide me URl to look at SQLbulkcopy code

**Comment by Harry2616** [comment]
Hi Erik,

I am here

**Comment by ErikEJ** [comment]
Hi, you can find SqlCeBulkCopy here: http://sqlcebulkcopy.codeplex.com/

But I think I misunderstood your question - you are looking for a way to get data from the database quickly, I think?

In that case, you should not be using typed DataSets, as they incur a large memory overhead and performance hit, consider using just CLR classes or SqlCeResultSet - see my performance blog series here: http://erikej.blogspot.dk/2015/07/sql-server-compact-adonet-data-access.html

**Comment by ErikEJ** [comment]
Feel free to re-open if you want to follow up!
