### ISSUE TITLE
Font size in Script window is awfully small

### ISSUE THREAD

**Issue by byyyt** [ErikEJ/SqlCeToolbox#168]
Font size inside script window (New Query, Script AS *) is way too small. Everywhere else it's fine.
Using VS 15, Dark Theme. Font settings are at default.

**Comment by ErikEJ** [comment]
I am using the Text Editor font and font size - what are they set at?

Are you able to share a screenshot!

Arie you using high dpi monitor?

**Comment by byyyt** [comment]
> Are you able to share a screenshot!
>Arie you using high dpi monitor?
Sure, I should have done that in the first place. However I'll be back at my workstation on Monday. That's when I'll reply with the specifics and screenshots. The settings in VS are the default ones, Text Editor Consolas 10, off the top of my head. Aforementioned Query/Script editor font size appears to be like 40% smaller than the one in VS Text Editor.

The monitor is ultrawide 34uc88, 100% scaling is set on Windows 10. However I havent had any issues with any other apps or VS extensions, apart from few really old legacy apps.

**Comment by ErikEJ** [comment]
What version of the extension?

**Comment by byyyt** [comment]
I have just installed it on my home pc just to check if it's the same. Results are similar. Work monitor has higher resolution so the difference seems bigger as well.

This is from my home pc.
![ss](https://cloud.githubusercontent.com/assets/20060817/20764671/ed391006-b737-11e6-9206-e0671e0bbfac.png)

Extension version 4.6. Just installed it (clean). Also just noticed the white bar at the top off the toolbox window. Yellow text there is unreadable.

**Comment by ErikEJ** [comment]
Interesting - I am using AvalonEdit, and it seems to have a zomm issue or similar: https://github.com/icsharpcode/AvalonEdit - will see what I can do.

I will remove the yellow text, it is obsolete.

Thanks for reporting this!

**Comment by ErikEJ** [comment]
This bug is fixed in the latest daily build

Bug was this: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/ToolWindows/SqlEditorControl.xaml.cs#L159

Latest daily build is available from https://github.com/ErikEJ/SqlCeToolbox

**Comment by byyyt** [comment]
Much better now. Thank you!

**Comment by ErikEJ** [comment]
Thank you for reporting this!
