### ISSUE TITLE
Hebrew characters appear as question marks in Windows 10

### ISSUE THREAD

**Issue by memilavi** [ErikEJ/SqlCeToolbox#17]
After upgrading to the newest version of Win10, Hebrew characters appear as question marks intead of the characters themselves.
With this issue, it's virtually impossible to write SQL statements which involve Hebrew characters.

The problem is maybe related to this:
https://support.microsoft.com/en-us/kb/3083806

**Comment by ErikEJ** [comment]
Does this only apply to the Toolbox? Does it also apply to for example text in Notepad?

**Comment by memilavi** [comment]
t happens only in toolbox.

In fact, it happens only when writing SQL statements.

When I “Edit top 200 rows”, Hebrew shows fine. 

I’m attaching screenshot of the problem.

 

Thanks,

 

Memi

**Comment by ErikEJ** [comment]
Could you go to github and upload the screenshot?

**Comment by ErikEJ** [comment]
Could you try  the latest daily build here and let me know if that fixes the issue: https://sqlcetoolbox.codeplex.com/releases/view/618303 - I have updated the text editor library to the latest version on NuGet

**Comment by memilavi** [comment]
I see it’s the Add-In, I’m using the Standalone app, could you please update it also?

**Comment by memilavi** [comment]
Meanwhile, I tested the updated Add-In in VS2013, and the problem is still there...

**Comment by ErikEJ** [comment]
Can you paste in hebrew text?

**Comment by memilavi** [comment]
Sure:
דוגמה

(Hebrew for "Sample")

**Comment by ErikEJ** [comment]
Thansk, I meant in the editor in the Toolbox !

**Comment by memilavi** [comment]
Oh, sorry...

Already tested it, I'm getting the same results.
The text becomes a series of question marks.

**Comment by ErikEJ** [comment]
Works fine for me with Win 10 build 10124

**Comment by memilavi** [comment]
Mine is build 10586. It worked for me also in 10124.
Are you planning an upgrade soon? :-)

**Comment by ErikEJ** [comment]
Is that a developer preview version? I have not been offered that update - so is it an OS bug?

**Comment by ErikEJ** [comment]
Closing as your build is a beta/preview build.

**Comment by memilavi** [comment]
Perhaps I wasn't clear enough...
This build is an RTM, official build, and not a preview one.
You can read about it here:
http://www.windowscentral.com/windows-10-november-update-rolling-out-now-build-10586

**Comment by ErikEJ** [comment]
Hm.. wonder why I have not been offered that yet?

**Comment by ErikEJ** [comment]
Closing as I can paste the sample hebrew text abovme using build 10586
