### ISSUE TITLE
Query Font Size

### ISSUE THREAD

**Issue by berny900** [ErikEJ/SqlCeToolbox#170]
Since Release 4.6 Query Font Size is  supposed to be the default Text Editor font size.
My default Text Editor font size is 10 points but the Query Font Size is 8.

How can I change that?
![sql compact](https://cloud.githubusercontent.com/assets/13867370/20835866/0ef85074-b89d-11e6-9444-b9c8dd1f8a1b.PNG)

**Comment by ErikEJ** [comment]
I had a bug - https://github.com/ErikEJ/SqlCeToolbox/issues/168 - it is fixed in the latest daily, download from here: https://github.com/ErikEJ/SqlCeToolbox - let me know if this works for you...

**Comment by berny900** [comment]
Hi Erik,
yes it worked perfectly!

Thanks a lot for the quick response and the good work you are delivering for us!!

Berni

**Comment by ErikEJ** [comment]
Thanks,  If you like my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details

**Comment by berny900** [comment]
I wrote a review under Bernhard Roos.
Thanks again.
