### ISSUE TITLE
ExcludeTables and QuickGraph.Data dependency issue

### ISSUE THREAD

**Issue by Down2Earth** [ErikEJ/SqlCeToolbox#172]
Hi, I'm using the Nuget packages of the SqlCe Scripting API.
But everytime I use the method 

`generator.ExcludeTables(new List<string>() { "myTable" });`

I get the exception:
`exception: 
System.IO.FileLoadException: Impossible de charger le fichier ou l'assembly 'QuickGraph.Data, Version=3.6.61114.0, Culture=neutral, PublicKeyToken=3681435cabd17ad2'`

Any help would be very appreciated.

**Comment by ErikEJ** [comment]
The Scripting package depends on the QuickGraph package, so that should always be included - check your packages.config file, and maybe try to install manually (the correct dependent version)

**Comment by Down2Earth** [comment]
Hi Erik, thank you for your answer.

I Do have the QuickGraph 3.6.61119.7 installed (through Nuget) on both projects A and B. 
However the version of the QuickGraph.Data.dll which ends up in the packages folder of my solution says:

` QuickGraph.Data, Version=**3.6.61114.0,** Culture=neutral, PublicKeyToken=3681435cabd17ad2`

In my build I have the following assemblies conflicts:
```
There was a conflict between "QuickGraph.Data, Version=3.6.61114.0, Culture=neutral, PublicKeyToken=null" and "QuickGraph.Data, Version=3.6.61114.0, Culture=neutral, PublicKeyToken=3681435cabd17ad2".
QuickGraph.Data, Version=3.6.61114.0, Culture=neutral, PublicKeyToken=null" was chosen because it was primary and "QuickGraph.Data, Version=3.6.61114.0, Culture=neutral, PublicKeyToken=3681435cabd17ad2" was not.
References which depend on "QuickGraph.Data, Version=3.6.61114.0, Culture=neutral,   PublicKeyToken=null" ...
```
(My c# solution is built for the .Net 4.5.1).
So there are two references to the QuickGraph.Data: 3.6.61114.0 with a different PublicKeyToken (3681435cabd17ad2 and "null"). 

Everything compiles as expected but I get the previously described Exception at runtime :-/

I tried using Assembly redirection in my App.config but no luck.

Any idea (using SqlCeScripting with an alternative to QuickGraph)?
Thank you in advance.

**Comment by ErikEJ** [comment]
Can you recreate/fix the "null" reference, or share a sample repro....

**Comment by Down2Earth** [comment]
Sure, here is some code to reproduce the Exception:

- Create a sample C# console application in VisualStudio (community 2015) for .Net 4.5.1.
- Add the following code to Program1.cs:

`using ErikEJ.SqlCeScripting;
using System.Collections.Generic;
using System.Data.SqlServerCe;
using System.IO;

namespace ConsoleApplication1
{
    class Program
    {
        static void Main(string[] args)
        {
            var connString = "Data Source =" + Path.GetTempFileName();
            var seqFile = new SqlCeEngine(connString);
            DB4Repository srcRepository = new DB4Repository(connString);
            var generator = new Generator4(srcRepository);
            using (srcRepository)
            {
                generator.ExcludeTables(new List<string>() { "__MigrationHistory" }); // <---- FAILS here
                generator.ScriptDatabaseToFile(Scope.SchemaData);
            }
        }
    }
}
`
The Exception I get a FileLoadException:

`Unable to load the file or assembly 'QuickGraph, Version=3.6.61114.0, Culture=neutral, PublicKeyToken=f3fb40175eec2af3' or one of its dependencies. The definition of the manifest of the assembly does not match the assembly's reference.`

Attached is the zipped Solution directory :+1:

[ConsoleApplication1.zip](https://github.com/ErikEJ/SqlCeToolbox/files/656834/ConsoleApplication1.zip)

Thank you.

**Comment by ErikEJ** [comment]
Thanks very much for reporting this - I have uploaded a new package to nuget.org, please remove the current package and the QuickGraph package from your project - and install the updated package: https://www.nuget.org/packages/ErikEJ.SqlCeScripting/3.5.2.64 - looking forward to hearing how it goes!

**Comment by Down2Earth** [comment]
Just updated the package and... it Works like a charm!
Can you please give me some info on what was happening (as I spent way too many hours on this ;-) ... would love to understand).

Thank you very much for your great support, and overall for you great work on this project. :+1:

**Comment by ErikEJ** [comment]
Thanks for the heads up - let me try to give you some background: 
I basically think it has never worked - I have be using a local, code signed copy of the QuickGraph DLLs for local development and for inclusion with the Toolbox - the Scripting nuget package was intended to use the published QuickGraph package - but the versions did not match, and the published QuickGraph DLLs ae not signed. "luckilly" only few users need the ExcludeTables method, which is the only one using the QuickGraph lib.

My solution was to simply include the signed, "correct" quickgraph dll files directly in the Scripting package, and remove the dependency on the published QuickGraph package.

If you use my tools, I would be very grateful for a rating or review here: https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details

**Comment by Down2Earth** [comment]
Thanks for the background info. 
I had noticed the signature issue ont the QuickGraph.Data.dll but tried to get around it with assembly redirection... Merci.

I left a review on the market place :)

**Comment by ErikEJ** [comment]
Thanks  lot!
