### ISSUE TITLE
Forgets grid options after rebuild/debug

### ISSUE THREAD

**Issue by denisz1** [ErikEJ/SqlCeToolbox#174]
If I tick "Show result in grid", then it forgets that option is ticked, and I need to tick it again, when:
- after a debug sessions ends, or I recompile
- when a change is made to the database from some other place (e.g. from my app) then SqlCeToolbox detects the change, and when I run the query again the grid is off and I need to retick the option

Also, not sure if this is somehow related, but the order of the tab is changed, and I have to go hunting for it. Usually it moves to the first tab on the very left.

**Comment by ErikEJ** [comment]
Thanksfor reporting this, it is fixed in the latest daily build

**Comment by denisz1** [comment]
😄
