### ISSUE TITLE
For VS Code

### ISSUE THREAD

**Issue by mozsoyler** [ErikEJ/SqlCeToolbox#180]
Do you plan to support Visual Studio Code? As VS Code gaining acceleration it would be a major contribution to the community. A restricted feature set would suffice. Just querying and basic structural creation and modification commands would do the job.

Thank you by the way this excellent tool which I am using constantly in VS 2105.

**Comment by ErikEJ** [comment]
Great idea, but since VS Code is JavaScript based, I doubt I could do it - but will have a look at the SQL Server extension
