### ISSUE TITLE
SQLite Views

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#191]
The view's context menu should basically be the same as the table's one with the exception, that a view may not be renamed (there is no ```ALTER VIEW``` command in SQLite).

Views are read-only per default, but can be transformed in R/W with apposite triggers (http://www.sqlite.org/lang_createview.html).

So each view object should also include a _Triggers_ subfolder, like the tables do.

Maybe the most part of the code could be shared between tables and views.

**Comment by ErikEJ** [comment]
The following menu items currently exists for a table:

- [ ] ~~Edit Top x Rows~~ - N/A, as views are read only
- [ ] View Data as Report - I have attempted this earlier, did not work for some quirky SQLite reason, will try again
- [ ]  New Query (superflous?)
- [ ]  Script as DROP and CREATE - possible?
- [ ] Script as SELECT - possible?
- [ ] ~~Script as INSERT/UPDATE/DELETE/as Data~~ N/A
- [ ] ~~Import Data from CVS~~ N/A
- [ ] ~~Rename~~ N/A

**Comment by mwallnoefer** [comment]
I disagree on this sentence: "N/A, as views are read only". If you look at the SQLite documentation (link in the first post) they can be transformed into read-write by using instead-of triggers.

So I would provide all the read-write operations though. And when an operation is not possible, the user gets the message box with the concerning SQL exception as in general.

It could also be that in some future release SQLite gets auto-updateable views like PostgreSQL did (which in the past was also limited to read-only ones).

**Comment by ErikEJ** [comment]
I will await comment from other users, it sounds like quite advanced/unusual scenarios to have writeable views in an embedded database.

**Comment by mwallnoefer** [comment]
Regarding the other operations:

- **New Query** - opens a blank query window and is very handy, why not?
- **Script as DROP and CREATE** - the composition of the existing DROP and CREATE commands, is perfectly valid
- **Script as SELECT, INSERT, UPDATE, DELETE** - agreed this could be tricky to get the view's columns. I have no idea how this works in SQLite, so we can drop this proposal for now.

But option 1 and 2 should be added I think.

**Comment by ErikEJ** [comment]
Option 1 and 2 added in latest daily build

**Comment by mwallnoefer** [comment]
Fine. Yes, I agree that writeable views might not be the most common scenario.

**Comment by mwallnoefer** [comment]
I think we have lost one option: _Script as SELECT_. If I want to construct a query on the base of a view and make some join it becomes handy, true?
But it makes sense only if we get all the single attributes out of the view (I mean not just a plain _SELECT *_).

**Comment by mwallnoefer** [comment]
Further, if I compare to the SQL Server Tools, the view columns are not shown as children of the view (no idea if this is possible with SQLite).

**Comment by ErikEJ** [comment]
Could I ask you to open a new issue, please
