### ISSUE TITLE
Toolbar Enhancements

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#194]
Another proposal which would make SqlCeToolbox a bit more consistent to MS SQL Data Tools Plugin.

I would provide the **Add Connection** (for SqlCeToolbox the four plugs found in the context menu) and the **New Query** buttons in the toolbar between the **Refresh** arrow and the **Settings** wheel. What do you think?

![capture](https://cloud.githubusercontent.com/assets/7541399/21562908/d80b69e8-ce7c-11e6-9979-0b3a59bee327.PNG)

**Comment by ErikEJ** [comment]
New Query sounds like an excellent idea!

Add Connection - in SSDT this is always to SQL Server, but here it is to 3 different engines - not sure how to do that?

**Comment by mwallnoefer** [comment]
I would have put all 4 plugs into the toolbar, since you may distinguish them using the tool-tip.

**Comment by ErikEJ** [comment]
Notes: 

Add to Toolbar: New Query, Scan Solution (use current Icon), Add SQLite Database (use AddDatabase icon).

In Current Context menu: Change to use AddDatabase icon for the 3 database types

**Comment by mwallnoefer** [comment]
Excellent, Erik. For me it is important to have the SQLite icon on the top.

**Comment by ErikEJ** [comment]
Yes, for me too, as fewer and fewer people use SQL CE these days.

**Comment by ErikEJ** [comment]
Fixed in latest daily build - thanks aganin for your contributions and feedback!
