### ISSUE TITLE
ErrorCode 26

### ISSUE THREAD

**Issue by henrikm** [ErikEJ/SqlCeToolbox#196]
Message: file is encrypted or is not a database
Result: NotADb

Hi,

created a project with vs 2017 RC with a DB (SQL CE lokal File on hd) that comes with the project wizard. Want now to migrate to SQL Server. Need to reverse engineer this DB. But NO tool can open this DB. 

What means errorcode 26. And is there a workaround?

Regards

Henrik

**Comment by ErikEJ** [comment]
That does not look like a SQL CE error message, where do you see that error message? 

Did you try the SQL Compact version detector built into the Toolbox?

**Comment by henrikm** [comment]
![1](https://cloud.githubusercontent.com/assets/3972559/21577431/819050ae-cf5a-11e6-8893-dbd347b49a25.PNG)
![2](https://cloud.githubusercontent.com/assets/3972559/21577432/819189a6-cf5a-11e6-9e90-8aad7e3fdffb.PNG)

**Comment by ErikEJ** [comment]
You have it connected as a SQLIte database, which it is not, I guess.
So:
remove the connection, 
run the version detector to find the SQL CE version
connect using the found database type
Migrate

**Comment by henrikm** [comment]
![3](https://cloud.githubusercontent.com/assets/3972559/21577581/759931f2-cf60-11e6-9349-0c853b0c3e4a.PNG)


The database type is missing.

**Comment by ErikEJ** [comment]
Did you run detect? What is the database type?

**Comment by ErikEJ** [comment]
And what is the file name?

**Comment by henrikm** [comment]
Run detect. 

Version is sql ce 4.0. 

Filename is Startersite.sdf

**Comment by ErikEJ** [comment]
So then you just need to:
remove the connection from the Toolbox,
Install the SQL CE 4.0 MSI https://github.com/ErikEJ/SqlCeToolbox/wiki
Connect using SQL CE 4.0
Migrate

Let me know if any of these steps are unclear!

**Comment by henrikm** [comment]
Perfect.

Thanks a lot.

**Comment by ErikEJ** [comment]
You are welcome - let me know if you encounter any other issues. If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
