### ISSUE TITLE
[question] Keeping SQL CE and SQL Server in sync

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#204]
Question: There is App-A which generates data & stores in SQL Server Compact. There is App-B which needs above generated data but uses SQL Server. SQL server needs to be in sync with SQL Server Compact. Is there a way to programmaticaly migrate SQL Server Compact to SQL Server?

**Comment by ErikEJ** [comment]
Yes, there are several ways to achieve this - do you load the full SQLCE database into SQL and how often? How are the databases connected (Device with SQLCE on the same network as SQL Server)

**Comment by Anil86** [comment]
1. Yes the whole SQLCE will have to be migrated. 
2. Syn frequency should be in real time. Whenever user accesses App-B, this app should sync itself with SQL server.
3. Both SQLCE & SQL Server are on the same device.

**Comment by ErikEJ** [comment]
Not sure I understand this: Whenever user accesses App-B, this app should sync itself with SQL server. - Is app-b not always connected to SQL Server?

You have a number of options:

- Use my scripting API together with ADO.NET to script and move the SQL CE database, like in my blog sample here: http://erikej.blogspot.dk/2013/03/sql-server-compact-code-snippet-of-week_8.html 

- Add code in App-A to keep SQL Server up to date

- Access the SQL Compact file directly from SQL Server via SQLCLR, as described here - this open up for various scenarios: http://erikej.blogspot.dk/2008/10/accessing-sql-compact-from-sql-server.html

**Comment by Anil86** [comment]
I'm satisfied with the first option. Thanks a lot.

Very sorry for the typo. Updated my comment.

**Comment by ErikEJ** [comment]
You are welcome, let me know if you need more help - if you are exporting a large database, be aware that the export can consist of several files
