### ISSUE TITLE
Export SQL Server to SQL Server Compact 4.0

### ISSUE THREAD

**Issue by dlager** [ErikEJ/SqlCeToolbox#208]
When using "Export SQL Server to SQL Server Compact 4.0" I received the following error: 
"SQLite/SQL Server Compact Toolbox
Error Code: 80040E11
Message : Invalid column ID. [ProductPfhhlKey]
Minor Err.: 0
Source : SQL Server Compact ADO.NET Data Provider
Err. Par : ProductPfhhlKey"

My guess is that it cannot handle Persisted Computed Columns.

Here is the original build script for the table in SQL Server:

USE [FTC2]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ARITHABORT ON
GO
SET ANSI_PADDING ON
GO

CREATE TABLE [ftcr].[BridgeProductFamilyPfhhlFamily](
	[ProductPfhhlKey]  AS ([ProductFamilyKey]+[PfhhlFamilyKey]) PERSISTED NOT NULL,
	[ProductFamilyKey] [nchar](2) NOT NULL,
	[PfhhlFamilyKey] [nchar](2) NOT NULL,
	[MilesUpd] [datetime] NULL CONSTRAINT [DF_BridgeProductFamilyPfhhlFamily_MilesUpd]  DEFAULT (getdate()),
	[IsDisabled] [bit] NULL CONSTRAINT [DF_BridgeProductFamilyPfhhlFamily_IsDisabled]  DEFAULT ((0)),
 CONSTRAINT [PK_BridgeProductFamilyPfhhlFamily] PRIMARY KEY CLUSTERED 
(
	[ProductPfhhlKey] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [ftcr].[BridgeProductFamilyPfhhlFamily]  WITH CHECK ADD  CONSTRAINT [FK_BridgeProductFamilyPfhhlFamily_PfhhlFamily] FOREIGN KEY([PfhhlFamilyKey])
REFERENCES [ftcr].[PfhhlFamily] ([PfhhlFamilyKey])
GO

ALTER TABLE [ftcr].[BridgeProductFamilyPfhhlFamily] CHECK CONSTRAINT [FK_BridgeProductFamilyPfhhlFamily_PfhhlFamily]
GO

ALTER TABLE [ftcr].[BridgeProductFamilyPfhhlFamily]  WITH CHECK ADD  CONSTRAINT [FK_BridgeProductFamilyPfhhlFamily_ProductFamily] FOREIGN KEY([ProductFamilyKey])
REFERENCES [ftcr].[ProductFamily] ([ProductFamilyKey])
GO

ALTER TABLE [ftcr].[BridgeProductFamilyPfhhlFamily] CHECK CONSTRAINT [FK_BridgeProductFamilyPfhhlFamily_ProductFamily]
GO

![sqlce4_error](https://cloud.githubusercontent.com/assets/25089593/21909630/baa8d65a-d8e6-11e6-932c-f51a5a5f6e5f.PNG)

**Comment by ErikEJ** [comment]
Good catch! I think I should allow Computed, Persisted columns! (But still ignore just computed columns)

**Comment by ErikEJ** [comment]
This is fixed in the latest daily build of the SSMS and VS extensions, please let me know if it works for you.

**Comment by dlager** [comment]
Downloaded the Daily Build and it worked perfectly! Computed Persisted Columns, primary keys, and multiple foreign keys and indexes worked great!

I agree that non-persisted computed columns should likely be ignored. Might as well be a view anyway.

**Comment by ErikEJ** [comment]
Great, thanks for confirming!  If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
