### ISSUE TITLE
Failed install on Visual Studio Pro 2017 RC

### ISSUE THREAD

**Issue by josebsalazar** [ErikEJ/SqlCeToolbox#216]
I tried to install the toolbox using VSP 2017 and it failed. Im not sure what would have caused it but its has been a trial to get it installed. 

Very best, 

-jbs

**UPDATE** Verified fix: https://developercommunity.visualstudio.com/content/problem/7936/unable-to-install-extensions-after-updating-vs2017.html

1/19/2017 1:01:27 PM - Microsoft VSIX Installer
1/19/2017 1:01:27 PM - -------------------------------------------
1/19/2017 1:01:27 PM - vsixinstaller.exe version:
1/19/2017 1:01:27 PM - 15.0.26020.0 built by: D15REL
1/19/2017 1:01:27 PM - -------------------------------------------
1/19/2017 1:01:27 PM - Command line parameters:
1/19/2017 1:01:27 PM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\vsixinstaller.exe,/appidinstallpath:C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\devenv.exe,/skuName:Pro,/skuVersion:15.0.26020.0,/appidname:Microsoft Visual Studio Professional 2017 RC,C:\Users\JSr\AppData\Local\Temp\VSIXzuqhbfuo.vsix
1/19/2017 1:01:27 PM - -------------------------------------------
1/19/2017 1:01:27 PM - Microsoft VSIX Installer
1/19/2017 1:01:27 PM - -------------------------------------------
1/19/2017 1:01:27 PM - Initializing Install...
1/19/2017 1:01:28 PM - Extension Details...
1/19/2017 1:01:28 PM - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
1/19/2017 1:01:28 PM - 	Name               : SQLite / SQL Server Compact Toolbox
1/19/2017 1:01:28 PM - 	Author             : ErikEJ
![screen shot 2017-01-19 at 1 08 14 pm](https://cloud.githubusercontent.com/assets/20861565/22123419/c2b8c384-de48-11e6-99eb-5846efa4ea5d.jpg)
1/19/2017 1:01:28 PM - 	Version            : 4.6.11
1/19/2017 1:01:28 PM - 	Description        : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
1/19/2017 1:01:28 PM - 	Locale             : en-US
1/19/2017 1:01:28 PM - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
1/19/2017 1:01:28 PM - 	InstalledByMSI     : False
1/19/2017 1:01:28 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/19/2017 1:01:28 PM - 
1/19/2017 1:01:28 PM - 	SignatureState     : Unsigned
1/19/2017 1:01:28 PM - 	Supported Products : 
1/19/2017 1:01:28 PM - 		Microsoft.VisualStudio.Pro
1/19/2017 1:01:28 PM - 			Version : [11.0,16.0)
1/19/2017 1:01:28 PM - 		Microsoft.VisualStudio.Community
1/19/2017 1:01:28 PM - 			Version : [12.0,16.0)
1/19/2017 1:01:28 PM - 
1/19/2017 1:01:28 PM - 	References         : 
1/19/2017 1:01:28 PM - 		-------------------------------------------------------
1/19/2017 1:01:28 PM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
1/19/2017 1:01:28 PM - 		Name         : Visual Studio MPF 11.0
1/19/2017 1:01:28 PM - 		Version      : [11.0]
1/19/2017 1:01:28 PM - 		MoreInfoURL  : 
1/19/2017 1:01:28 PM - 		Nested       : No
1/19/2017 1:01:28 PM - 
1/19/2017 1:01:28 PM - 	Prerequisites      : 
1/19/2017 1:01:28 PM - 		-------------------------------------------------------
1/19/2017 1:01:28 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/19/2017 1:01:28 PM - 		Name         : Visual Studio core editor
1/19/2017 1:01:28 PM - 		Version      : [11.0,16.0)
1/19/2017 1:01:28 PM - 
1/19/2017 1:01:28 PM - Signature Details...
1/19/2017 1:01:28 PM - 	Extension is not signed.
1/19/2017 1:01:28 PM - 
1/19/2017 1:01:30 PM - The extension with ID '41521019-e4c7-480c-8ea8-fc4a2c6f50aa' is not installed to Microsoft Visual Studio Professional 2017 RC.
1/19/2017 1:02:38 PM - The following target products have been selected...
1/19/2017 1:02:38 PM - 	Microsoft Visual Studio Professional 2017 RC
1/19/2017 1:02:38 PM - 
1/19/2017 1:02:39 PM - Beginning to install extension to Microsoft Visual Studio Professional 2017 RC...
1/19/2017 1:02:39 PM - Install Error : System.IO.FileNotFoundException: Unable to find the specified file.
 at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.GetCurrentSetupInstance()
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.PerformSetupEngineInstall(InstallableExtensionImpl extension, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, IInstalledExtension& newExtension)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)

**Comment by ErikEJ** [comment]
Please use the Daily build, looking forward to the resultat 😀

**Comment by josebsalazar** [comment]
Just tried, I had to use the manual method of install using vsixinstaller.exe as admin because when I click on it VS2017 would not open it. I had community installed before but uninstalled it. Any help would be appreciated. 

http://vsixgallery.com/extensions/41521019-e4c7-480c-8ea8-fc4a2c6f50aa/extension.vsix <http://vsixgallery.com/extensions/41521019-e4c7-480c-8ea8-fc4a2c6f50aa/extension.vsix>



1/19/2017 2:03:22 PM - Microsoft VSIX Installer
1/19/2017 2:03:22 PM - -------------------------------------------
1/19/2017 2:03:22 PM - vsixinstaller.exe version:
1/19/2017 2:03:22 PM - 15.0.26020.0 built by: D15REL
1/19/2017 2:03:22 PM - -------------------------------------------
1/19/2017 2:03:22 PM - Command line parameters:
1/19/2017 2:03:22 PM - VSIXInstaller.exe,C:\Temp\SqlCe40ToolboxDailyBuild.vsix
1/19/2017 2:03:22 PM - -------------------------------------------
1/19/2017 2:03:22 PM - Microsoft VSIX Installer
1/19/2017 2:03:22 PM - -------------------------------------------
1/19/2017 2:03:24 PM - Initializing Install...
1/19/2017 2:03:24 PM - Extension Details...
1/19/2017 2:03:24 PM - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
1/19/2017 2:03:24 PM - 	Name               : SQLite / SQL Server Compact Toolbox
1/19/2017 2:03:24 PM - 	Author             : ErikEJ
1/19/2017 2:03:24 PM - 	Version            : 4.6.103
1/19/2017 2:03:24 PM - 	Description        : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
1/19/2017 2:03:24 PM - 	Locale             : en-US
1/19/2017 2:03:24 PM - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
1/19/2017 2:03:24 PM - 	InstalledByMSI     : False
1/19/2017 2:03:24 PM - 	SupportedFrameworkVersionRange : [4.5,)
1/19/2017 2:03:24 PM - 
1/19/2017 2:03:24 PM - 	SignatureState     : Unsigned
1/19/2017 2:03:24 PM - 	Supported Products : 
1/19/2017 2:03:24 PM - 		Microsoft.VisualStudio.Pro
1/19/2017 2:03:24 PM - 			Version : [11.0,16.0)
1/19/2017 2:03:24 PM - 		Microsoft.VisualStudio.Community
1/19/2017 2:03:24 PM - 			Version : [12.0,16.0)
1/19/2017 2:03:24 PM - 
1/19/2017 2:03:24 PM - 	References         : 
1/19/2017 2:03:24 PM - 		-------------------------------------------------------
1/19/2017 2:03:24 PM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
1/19/2017 2:03:24 PM - 		Name         : Visual Studio MPF 11.0
1/19/2017 2:03:24 PM - 		Version      : [11.0]
1/19/2017 2:03:24 PM - 		MoreInfoURL  : 
1/19/2017 2:03:24 PM - 		Nested       : No
1/19/2017 2:03:24 PM - 
1/19/2017 2:03:24 PM - 	Prerequisites      : 
1/19/2017 2:03:24 PM - 		-------------------------------------------------------
1/19/2017 2:03:24 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
1/19/2017 2:03:24 PM - 		Name         : Visual Studio core editor
1/19/2017 2:03:24 PM - 		Version      : [11.0,16.0)
1/19/2017 2:03:24 PM - 
1/19/2017 2:03:24 PM - Signature Details...
1/19/2017 2:03:24 PM - 	Extension is not signed.
1/19/2017 2:03:24 PM - 
1/19/2017 2:03:24 PM - Searching for applicable products...
1/19/2017 2:03:24 PM - Found installed product - Global Location
1/19/2017 2:03:24 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ErikEJ** [comment]
Which vs versions do you have installed?

**Comment by josebsalazar** [comment]
I had Community first installed, but then I removed it and installed professional. Could the problem be with the symbolic links are still pointing to community which no longer exists? I think I saw some of the directories which were not properly installed.

Very best, 

-jbs

**Comment by ErikEJ** [comment]
Are you able to test on another PC / VM

**Comment by josebsalazar** [comment]
Sure am. I’l need a little bit of time to spin another one up or I might just revert this install via snapshot.. The install time for VS2017 while much improved is torturous! 

-jbs

**Comment by LFoat** [comment]
I think I have been struggling with the same problems tonight. The toolbox works fine on VS2017 Pro running in a VM on my Lenovo P50. Tonight on my HPx360, I have problems like Jose. On the one where it works, it's possible that I installed the previous version and then upgraded to 4.6.11. Tonight I have been starting with the latest.

BTW Erik, I have really appreciated your many contributions over the years. Thanks!

**Comment by ErikEJ** [comment]
@lfoat did you install 4.6.11 or latest daily?

**Comment by LFoat** [comment]
Mostly I got it via VS2017 Pro Tools > Extensions and updates. I just went looking for dailies at http://vsixgallery.com/, but that source is "temporarily unavailable." I just followed your instructions for latest daily at https://github.com/ErikEJ/SqlCeToolbox/wiki/Subscribing-to-latest-%22daily%22-build, but nothing shows up there yet.

**Comment by LFoat** [comment]
I was getting 4.6.11, and it looks like the latest is 4.6.103.

**Comment by ErikEJ** [comment]
Use the direct link from the readme.md in the repo

**Comment by LFoat** [comment]
I think the ReadMe sends me here: http://vsixgallery.com/extensions/41521019-e4c7-480c-8ea8-fc4a2c6f50aa/extension.vsix, and that fails with "not installable on any current products." All the links in VSIX gallery (such as http://vsixgallery.com/extensions/41521019-e4c7-480c-8ea8-fc4a2c6f50aa/SQLite%20%2F%20SQL%20Server%20Compact%20Toolbox%20v4.6.103.vsix) return "The resource you are looking for has been removed, had its name changed, or is temporarily unavailable."

**Comment by ErikEJ** [comment]
Yes, the GUI links in vsix gallery are pretty broken, I know. 
I will do some verification on my VS 2017 VM (might be a day or two), I recently made some build changes, that might have had a bad effect..

**Comment by ErikEJ** [comment]
@LFoat @josebsalazar Unable to repro, I am however using Ent Edition on my VM image. My build version is 26020 - what is yours?

**Comment by LFoat** [comment]
It looks the same: Microsoft Visual Studio Professional 2017 RC, Version 15.0.26020.0 D15REL--on both the machine that has toolbox working and the machine where it will not load. Where it's working, I'm pretty sure I loaded toolbox before the latest 2017 RC update; I wonder if that matters.

**Comment by ErikEJ** [comment]
Let us wait and see how it all works out when RC3 is released (very soon)

**Comment by LFoat** [comment]
Seems like a reasonable idea. Thanks.

**Comment by josebsalazar** [comment]
Sounds like a plan, any idea when RC3 will be released? 

Very best, 

-jbs

**Comment by ErikEJ** [comment]
Within a single digit number of days, I think...

**Comment by LFoat** [comment]
FYI, the last update of Paket.VisualStudio "supports Visual Studio 2007", and it appears to have the same install problem.

**Comment by ErikEJ** [comment]
@josebsalazar  @LFoat  Some tips here, maybe (possible broken VS RC install) https://developercommunity.visualstudio.com/content/problem/7936/unable-to-install-extensions-after-updating-vs2017.html

**Comment by LFoat** [comment]
I think that's it, Erik. It looks like the basic VS RC install has problems that do not necessarily show up in the installation messages. After a couple attempts with Repair and Modify, both SqlCeToolbox and Paket installed successfully. Thanks!

**Comment by ErikEJ** [comment]
@LFoat Great news! - @josebsalazar - do you have an update?

**Comment by josebsalazar** [comment]
Ill try this afternoon!

<---- Sent from my iPad --->

**Comment by josebsalazar** [comment]
I finally got it to work. I had to ditch/get rid of Windows 7, and used a fresh VM with Windows 10 on it. The first few installs didn’t work, with stalling at the perfwatson. After an update and repair it worked just fine. 

-jbs
