### ISSUE TITLE
Keyboard cursors don't work in query window

### ISSUE THREAD

**Issue by grimreaper38uk** [ErikEJ/SqlCeToolbox#221]
When you open a table (Edit top 200 rows from the tree), then click the SQL button at the bottom to open the query text, the text cannot be easily manipulated because most of the keyboard controls don't work!

The arrow cursor keys don't work at all, backspace works, but delete doesn't - it just makes it a major pain to tweak the query slightly/quickly.

**Comment by ErikEJ** [comment]
Consider changing 

      dataGridView1.Controls.Add(_pnlSql);

to

      this.Controls.Add(_pnlSql);

(Fix forms designer issue??)

**Comment by ErikEJ** [comment]
Fixed in the latest daily build, pls let me know if it works for you! And thanks for reporting this

**Comment by grimreaper38uk** [comment]
Thanks for the quick response Erik!  Unfortunately, I've updated to the latest build, and it's worse than before!
The delete/backspace keys now both work, but the arrow keys do not move the text editing cursor - the focus shifts to the grid and the selected cell moves with each key press (as you'd expect if the grid was the focus).
Sorry!

**Comment by ErikEJ** [comment]
What version is that? (blue question mark)

**Comment by grimreaper38uk** [comment]
Version 4.6.11.0 - updated via Options -> Extensions in Visual Studio (2013).

**Comment by ErikEJ** [comment]
Aaah.. You need to get the latest "daily" build! Instructions here: https://github.com/ErikEJ/SqlCeToolbox

**Comment by grimreaper38uk** [comment]
Yes, I was just looking at that.  I take it the 'built-in' VS extensions manager doesn't grab the daily build then??

**Comment by ErikEJ** [comment]
Correct, that would be to much "noise" and cause for disruption

**Comment by ErikEJ** [comment]
But you can configure VS to grab the daily build, if you wish!

**Comment by grimreaper38uk** [comment]
I do wish... and I have configured.

Happy to report that everything in today's build is working perfectly.  Thanks again for your prompt replies!

**Comment by ErikEJ** [comment]
Great news - and you are very brave! 
If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
