### ISSUE TITLE
Unable To Create Or Open Database

### ISSUE THREAD

**Issue by koimad** [ErikEJ/SqlCeToolbox#225]
When I either create or try to open a existing sdf file I get the following error, saying it need to update.
![image](https://cloud.githubusercontent.com/assets/5713482/22625975/7e8da940-eb9a-11e6-8fe0-e084835ed2ec.png)
I'm using visual studio 2015 on a surface 3.

**Comment by ErikEJ** [comment]
I think I have a fix the latest daily build, please let me know if it fixes your issue - instructions for getting the latest daily build: https://github.com/ErikEJ/SqlCeToolbox

**Comment by koimad** [comment]
Hi Erik,
             The lest daily build daily build work fine.

Many Thanks
                   Brian

**Comment by ErikEJ** [comment]
Thank you for reporting this!
