### ISSUE TITLE
sqlce Insert bulk of data on windows embedded using ErikEJ.SqlCe.NetCF

### ISSUE THREAD

**Issue by ahmedatefsultan** [ErikEJ/SqlCeToolbox#226]
am using this script to doing this requirment

using System.Data.SqlServerCe;
public void DoBulkCopy(bool keepNulls, DataTable reader)
        {
            SqlCeBulkCopyOptions options = new SqlCeBulkCopyOptions();
            if (keepNulls)
            {
                options = options |= SqlCeBulkCopyOptions.KeepNulls;
            }
            using (SqlCeBulkCopy bc = new SqlCeBulkCopy(sqlconnection, options))
            {
                bc.DestinationTableName = "table_name";
                bc.WriteToServer(reader);
            }
        }

but it fail on and give me a message File or assembly 'System.Data.SqlServerCe version=3.5.1.0 , Culture=neutral ,PublicKeyToken=3BE235DF1C8D2DAD3', or one of its dependencies was not found

**Comment by ErikEJ** [comment]
Is the SQL Compact cab file installed ?
What platform/OS are you using?

**Comment by ahmedatefsultan** [comment]
my platform/OS Embeded Handheld 6.5 classic
and i installed SqlServerCompact 3.5 Core

**Comment by ErikEJ** [comment]
Are you sure it is version 3.5.1? 
Alternatively, simply include the source from my project and fix the references...

**Comment by ahmedatefsultan** [comment]
thank you mr ErikEJ for your time
when addedd System.Data.SqlServerCe version=3.5.1.0 make error on vs2008

Error	1	The type 'System.Data.Common.DbConnection' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Error	2	The type 'System.Data.Common.DbParameter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

but i addedd System.Data version=3.5.0.0

**Comment by ErikEJ** [comment]
Did you try including the source?

**Comment by ahmedatefsultan** [comment]
you mean add ErikEJ.SqlCe.sln project to my entire solution

**Comment by ErikEJ** [comment]
Just the csproj

**Comment by ErikEJ** [comment]
Source of SqlCeBulkCopy!

**Comment by ahmedatefsultan** [comment]
i included Source of SqlCeBulkCopy! and still give me
Error	1	The type 'System.Data.Common.DbConnection' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

Error	2	The type 'System.Data.Common.DbParameter' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Data, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.

from Source of SqlCeBulkCopy it self

**Comment by ErikEJ** [comment]
Have a look here, you are refereicing the wrong system.data assembly! http://stackoverflow.com/questions/19865393/missing-assembly-reference-that-is-there

**Comment by ErikEJ** [comment]
You must reference the one here: C:\Program Files (x86)\Microsoft SQL Server Compact Edition\v3.5\Devices

**Comment by ahmedatefsultan** [comment]
System.Data Verison=3.5.0.0
 System.Data.SqlServerCe Verison=3.5.0.0
 ErikEJ.SqlCe.NetCF Verison=2.1.6.7
 System.Data.SqlClient version=3.0.3600.0

this all DLL which i'm using on Windows Embedded side to run this script

 public void DoBulkCopy(bool keepNulls, DataTable reader)
        {
            SqlCeBulkCopyOptions options = new SqlCeBulkCopyOptions();
            if (keepNulls)
            {
                options = options |= SqlCeBulkCopyOptions.KeepNulls;
            }
            using (SqlCeBulkCopy bc = new SqlCeBulkCopy(sqlconnection, options))
            {
             
                bc.DestinationTableName = "Table_Name";
                bc.WriteToServer(reader);
            }
        }

all compilation on vs2008 is fine  but when click button on Pocket PC to run previous script it give me error message
File or assembly 'System.Data.SqlServerCe version=3.5.1.0 , Culture=neutral ,PublicKeyToken=3BE235DF1C8D2DAD3', or one of its dependencies was not found
so mr.Erik why this happened

**Comment by ErikEJ** [comment]
Are you able to use SQL CE on your device otherwise? If yes, just include my source, and fix the reference

**Comment by ahmedatefsultan** [comment]
yes sir i can do any query and DML transactions on my device on local database sdf

**Comment by ErikEJ** [comment]
Well, then my best proposal is to use the source code directly, as you seem unable to upgrade to SQL CE 3.5.1

**Comment by ErikEJ** [comment]
Pls note the #POCKETPC conditional compiler directive in the code!

**Comment by ahmedatefsultan** [comment]
sorry but i didn't get you

**Comment by ahmedatefsultan** [comment]
also i tried to add  the source code directly but it giving me also error for version of System.Data.SqlServerCe

**Comment by ErikEJ** [comment]
You need to fix the reference in the csproj file, of course

**Comment by ErikEJ** [comment]
I do not think I can help you any further, we are going in circles - happy to assist on a per hour consultancy basis
