### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by JueMueller** [ErikEJ/SqlCeToolbox#231]
Hi, Erik.

First of all: great job!

My question: when creating a sqlite db, i can set a password and the file is encrypted (I've checked it with a hex editor). What encryption method is used? SQLCypher? Which sqlite3.dll is used by your toolbox?

Regards
Juergen

**Comment by ErikEJ** [comment]
I am using System.Data.SQLite, which includes it's own encryption: https://system.data.sqlite.org/index.html/artifact/56333e5065df7518 

The latest daily Toolbox build uses build 1.0.103.0, which includes SQLite 3.14.2
I will update to 1.0.104.0, which includes 3.15.2 soon (before release of Toolbox 4.7 by the end of Feb)
