### ISSUE TITLE
Generator4 hits out of memory exception when outfile is not defined

### ISSUE THREAD

**Issue by Sarculare** [ErikEJ/SqlCeToolbox#235]
Using GenerateTableContent in Generator4 (and Generator) without providing an _outfile makes it possible to hit an out of memory exception.  There isn't a way to limit the amount of statements generated further than by table (GenerateTableData)

Large output is handled when providing an output file
```
// Split large output!
if (_sbScript.Length > 9485760 && !string.IsNullOrEmpty(_outFile))
```

With this the saveImageFiles parameters it makes it clear that while it is possible to create an instance of Generator4 without an outFile, this option is not well supported.

**Comment by ErikEJ** [comment]
Thanks - Assume the title of this should be: "when an outfile is **not** defined" ?

Do you have any suggestions for how to fix this?

"this option is not well supported" - not sure what you mean by that? Do you suggest removing the option to script data without specifying an outfile? It works well in 99% of scenarios, only fails when a table is huge.

**Comment by Sarculare** [comment]
Yes, I've updated it.

Providing ways to retrieve generated SQL statements incrementally would be a big help here. Doing something like a method returning an IEnumerable<string> of statements where each string is a single statement or a bunch of statements that hit some defined threshold (similar to the _sbScript.Length limit that's already being used) could work.

Large databases, not just tables, are a problem as well as _sbScript is only ever cleared out when providing an outfile so calling GenerateTableData directly multiple times would return the script for the first table, then the first and the second, and so on.
The saveImageFiles argument expects the consumer of the API will be using a directory to store files. If this is set and outfile isn't a different unhandled exception occurs.

**Comment by ErikEJ** [comment]
Thanks, I have logged issue #237 for the issue with multiple calls, that should be an easy fix! And thanks for the clarification

**Comment by ErikEJ** [comment]
I have also logged #238 !

**Comment by ErikEJ** [comment]
FYI, GenerateTableContent actually allows you to limit the data returned by passing a "WHERE" clause!

**Comment by ErikEJ** [comment]
Closing as there are workable workarounds (use files or limit results with WHERE clause)
