### ISSUE TITLE
Edit Top 200 Rows - cannot insert a new record

### ISSUE THREAD

**Issue by wvmstr** [ErikEJ/SqlCeToolbox#236]
I am on version 4.6.0.

Fill in all the columns I want then hit save and refresh.  Nothing added, no errors.

**Comment by ErikEJ** [comment]
Have  you tried moving the cursor to e new row?

Are you using SQLite or SQL Compact?

**Comment by wvmstr** [comment]
I am using SQL Compact.

Had to restart my computer then it all worked again.

**Comment by ErikEJ** [comment]
Great!
