### ISSUE TITLE
Invalid alterations made to imported .csv

### ISSUE THREAD

**Issue by consultli** [ErikEJ/SqlCeToolbox#245]
When one tries to use the CSV import utility to populate a table in a SQLite DB, the add-in attempts to replace what appear to be date/time (or timestamp) values with some token e.g. {ts '1900-01-01 23:59:59'}, which is find IF ONLY IT WORKS. When one attempts to execute the results INSERT INTO ... script, these tokens that are automatically embedded cause the import to fail! Is there a way to get the import as CSV function to NOT make any "intelligent" replacements? There should be an option that will allow the utility to simply pull in what it finds in a CSV and NOT try to modify it.

**Comment by ErikEJ** [comment]
Seems like a SQLite related omission, sorry 😐 could you provide a sample cab and create table statement?

**Comment by ErikEJ** [comment]
I meant sample CSV file

**Comment by consultli** [comment]
Here is a sample of a record in the source .csv:
"ParentProjectID","ProjectType","ProjectID","Analyte","CasID","AnalyteLabID","SampleTypeCode","DWRowVersion","DWRowSID","DWCreatedDts","DWUpdatedDts","DWTombstoneDts","CreatedDts","UpdatedDts","TombstoneDts","IsNew","IsUpdate","IsTombstone","AuthorUser","AuthorMachine","LastEditorUser","LastEditorMachine","SrcRowSID"
"","","PRIORITY POLLUTANTS","1,1,1-Trichloroethane","71-55-6","TESTAMERICA","NORM","103298","1",""2015-04-02 03:38:00"",""2015-04-16 01:15:00"","",""2015-04-02 03:38:00"",""2015-04-02 03:38:00"","","False","False","False","SYSADMIN","ENDVx7F95","SYSADMIN","ENDVx7F95","1"

Here is the translation of the same data from above using the SQLite csv import utility:
INSERT INTO [AnalyteGroups] ([ParentProjectID],[ProjectType],[ProjectID],[Analyte],[CasID],[AnalyteLabID],[SampleTypeCode],[DWRowVersion],[DWRowSID],[DWCreatedDts],[DWUpdatedDts],[DWTombstoneDts],[CreatedDts],[UpdatedDts],[TombstoneDts],[IsNew],[IsUpdate],[IsTombstone],[AuthorUser],[AuthorMachine],[LastEditorUser],[LastEditorMachine],[SrcRowSID]) 
VALUES (NULL,NULL,'PRIORITY POLLUTANTS','1,1,1-Trichloroethane','71-55-6','TESTAMERICA','NORM',103298,1,{ts '2015-04-02 03:38:00'},{ts '2015-04-16 01:15:00'},NULL,{ts '2015-04-02 03:38:00'},{ts '2015-04-02 03:38:00'},NULL,0,0,0,'SYSADMIN','ENDVx7F95','SYSADMIN','ENDVx7F95',1);

These values (please see below) are causing the error:
{ts '2015-04-02 03:38:00'}

Here's the error:
ErrorCode : 1
Message   : SQL logic error or missing database
unrecognized token: "{"
Result    : Error

Thank you, in advance, for your help with this.

Regards,
Li

**Comment by ErikEJ** [comment]
Please gie me the CREATE TABLE statement, thanks

**Comment by consultli** [comment]
This is the target table:
-- Script Date: 2/20/2017 12:20 AM  - ErikEJ.SqlCeScripting version 3.5.2.64
CREATE TABLE [AnalyteGroups] (
  [ParentProjectID] nvarchar(250) NULL
, [ProjectType] nvarchar(64) NULL
, [ProjectID] nvarchar(250) NULL
, [Analyte] nvarchar(128) NULL
, [CasID] nvarchar(128) NULL
, [AnalyteLabID] nvarchar(30) NULL
, [SampleTypeCode] nvarchar(8) NULL
, [DWRowVersion] bigint NULL
, [DWRowSID] int NULL
, [DWCreatedDts] datetime NULL
, [DWUpdatedDts] datetime NULL
, [DWTombstoneDts] datetime NULL
, [CreatedDts] datetime NULL
, [UpdatedDts] datetime NULL
, [TombstoneDts] datetime NULL
, [IsNew] bit NOT NULL
, [IsUpdate] bit NOT NULL
, [IsTombstone] bit NOT NULL
, [AuthorUser] nvarchar(128) NULL
, [AuthorMachine] nvarchar(128) NULL
, [LastEditorUser] nvarchar(128) NULL
, [LastEditorMachine] nvarchar(128) NULL
, [SrcRowSID] INTEGER NOT NULL
, CONSTRAINT [sqlite_master_PK_AnalyteGroups] PRIMARY KEY ([SrcRowSID])
);

**Comment by ErikEJ** [comment]
This is fixed in the latest daily build, download link here: https://github.com/ErikEJ/SqlCeToolbox 

If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
