### ISSUE TITLE
Visual Studio Community Edition 2015

### ISSUE THREAD

**Issue by geonautika** [ErikEJ/SqlCeToolbox#25]
I installed the latest version of the tools, but it did not work; nothing happen when I clicked on the Tools->SQLServer Compact/SQLite Toolbox nor on Server Explorer.

**Comment by ErikEJ** [comment]
Is the extension enabled (Check in Tools - Extensions and Updates) ?

**Comment by ErikEJ** [comment]
Closing as not additional info has been provided
