### ISSUE TITLE
SqlCeVsToolbox4.6.11 doesn't install

### ISSUE THREAD

**Issue by PauloRic** [ErikEJ/SqlCeToolbox#262]
Hi there!
I ran the vsix file and the installation failed. The message I got is:
The installation was unable to install the extension to all the selected products ...
This extension is not installable on any currently installed products.

VS Express 2015 for Web is not an installable product? Am I missing anything?

Thanks for your time.
Paulo Ricardo Ferreira

**Comment by ErikEJ** [comment]
You cannot install any extensions in Express editions, use Community or Pro instead

**Comment by PauloRic** [comment]
Thanks for your attention.
Best regards,Paulo Ricardo Ferreira
 
 
  Em sex, 24 fev, 2017 às 11:27, Erik Ejlskov Jensen&It;notifications@github.com> escreveu:   
You cannot install any extensions in Express editions, use Community or Pro instead
