### ISSUE TITLE
Toolbox set to disabled

### ISSUE THREAD

**Issue by RudolfJan** [ErikEJ/SqlCeToolbox#270]
When I start Visual Studio 2015, the toolbox is disabled. I can enable it, then I must restart Visiual Studion and it works fine. If I close Visual Studio and the start Visual Studio again, it is disabed again.

I will check if the issue still exists when I migrate to Visual Studio 2017 after launch, but I thought it may be useful to report it now. Its not a big issue, but a bit annoying. (Otherwise it's a great tool I appreciate very much).

**Comment by ErikEJ** [comment]
I am unable to reproduce this, do you have other extensions installed?

**Comment by ErikEJ** [comment]
Which version?

**Comment by RudolfJan** [comment]
I installed the latest version, 4.6.11

Yes, I also use a number of other extensions. I just hope you have a brilliant idea about what may cause this …

 

Regards,

 

Rudolf

 

Van: Erik Ejlskov Jensen [mailto:notifications@github.com] 
Verzonden: zaterdag 25 februari 2017 17:07
Aan: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
CC: RudolfJan <rudolfjan@klantprocessenboek.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ErikEJ/SqlCeToolbox] Toolbox set to disabled (#270)

 

Which version?

**Comment by ErikEJ** [comment]
No idea, actually, other than issue/conflict with another extension.., Also never heard about this issue from other of my 1000s of users

**Comment by ErikEJ** [comment]
My Bing Fu lead me to this: https://github.com/remcoros/DuplicateExtensionFinder

**Comment by RudolfJan** [comment]
Thanks,

 

I think I will go for a fresh install for Visual Studio 2017 … Got a lot of things reported.

 

Van: Erik Ejlskov Jensen [mailto:notifications@github.com] 
Verzonden: zondag 26 februari 2017 14:32
Aan: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
CC: RudolfJan <rudolfjan@klantprocessenboek.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ErikEJ/SqlCeToolbox] Toolbox set to disabled (#270)

 

My Bing Fu lead me to this: https://github.com/remcoros/DuplicateExtensionFinder
