### ISSUE TITLE
Error when Migrating SQL Database to SQL CE 4.0 (Version 4.7)

### ISSUE THREAD

**Issue by Danckwardt** [ErikEJ/SqlCeToolbox#280]
As part of my database management for the software I manage, I convert an Access Database to SQL, then use SQL Compact Toolbox to migrate that SQL Database to SQL CE 4.0, which my software then reads. This worked perfectly up until yesterday. After getting the 4.7 update, I now receive the following error when I script the SQL CE 4.0 DB. 

![image](https://cloud.githubusercontent.com/assets/26109989/23453111/561d58d6-fe67-11e6-8936-3c06f069c8b0.png)

I first believed that a change to the database was the issue. But after attempting the migration with an old database that I had previously been able to migrate to SQL CE 4.0, I got the same error. I was able to do the migration yesterday morning, but after restarting Visual Studio 2015 to pick up the update, it is no longer possible. 

Thank you, 

Ola Danckwardt

**Comment by ErikEJ** [comment]
Thanks for reporting this, the fix is now on MarketPlace (build 4.7.61)
