### ISSUE TITLE
Found conflicts between different versions of the same dependent assembly that could not be resolved

### ISSUE THREAD

**Issue by manishkrai** [ErikEJ/SqlCeToolbox#281]
I have added ErikEJ.SqlCeBulkCopy through nuget in my project but getting below error. - _Found conflicts between different versions of the same dependent assembly that could not be resolved_.

After analysis I found that while installing ErikEJ.SqlCeBulkCopy it add below entries in app.config file

`<runtime>
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="System.Data.SqlServerCe" publicKeyToken="89845dcd8080cc91" culture="neutral"/>
        <bindingRedirect oldVersion="0.0.0.0-4.0.0.1" newVersion="4.0.0.1"/>
      </dependentAssembly>
    </assemblyBinding>
  </runtime>`

Here, Its redirecting to newVersion="4.0.0.1" but the version of System.Data.SqlServerCe assembly that is refereneced in project is (System.Data.SqlServerCe(Microsoft.SqlServer.Compact.4.0.8876.1) and It's version is showing as 4.0.0.0. 

After doing below manual changes in app.config, warning is gone. Is It Ok to manually edit it ?
`        <bindingRedirect oldVersion="0.0.0.0-4.0.0.0" newVersion="4.0.0.0"/>`

**Comment by manishkrai** [comment]
Error Detail - 

There was a conflict between "System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" and "System.Data.SqlServerCe, Version=4.0.0.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91".
    "System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" was chosen because it was primary and "System.Data.SqlServerCe, Version=4.0.0.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91" was not.

References which depend on "System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" [C:\Myproject\Components\Packages\Microsoft.SqlServer.Compact.4.0.8876.1\lib\net40\System.Data.SqlServerCe.dll].
        C:\MyProject\Components\Packages\Microsoft.SqlServer.Compact.4.0.8876.1\lib\net40\System.Data.SqlServerCe.dll
          Project file item includes which caused reference "C:\MyProject\Components\Packages\Microsoft.SqlServer.Compact.4.0.8876.1\lib\net40\System.Data.SqlServerCe.dll".
            System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91, processorArchitecture=MSIL

References which depend on "System.Data.SqlServerCe, Version=4.0.0.1, Culture=neutral, PublicKeyToken=89845dcd8080cc91" [C:\MYProject\ABC\System.Data.SqlServerCe.dll].
        C:\MyProject\Components\Packages\ErikEJ.SqlCeBulkCopy.2.1.6.9\lib\net40\ErikEJ.SqlCe40.dll
          Project file item includes which caused reference "C:\MyProject\Components\Packages\ErikEJ.SqlCeBulkCopy.2.1.6.9\lib\net40\ErikEJ.SqlCe40.dll".
            ErikEJ.SqlCe40, Version=2.1.6.9, Culture=neutral, PublicKeyToken=03b0b5a60fec3719, processorArchitecture=MSIL
Install-Package Microsoft.SqlServer.Compact

**Comment by ErikEJ** [comment]
yes, it is perfectly OK - no sure what that happens, though - are you abe to share a repro project?

**Comment by ErikEJ** [comment]
Closing and further info was not supplied, feel free to re-open when you have more info or repro steps/project
