### ISSUE TITLE
Missing "EDMX generation" in latest Toolbox version

### ISSUE THREAD

**Issue by kharze** [ErikEJ/SqlCeToolbox#287]
Hey Erik, we are a group of students at aalborg university. We used your very great tool to generate edmx, but as we have seen in your new update it was removed. 
Is it possible that you can provide us with an elder version or include it again? So that we can continue with our project :) Thanks

**Comment by ErikEJ** [comment]
You can generate EDMX files using VS 2012 or later with the lastest EF 6 Tools and my Toolbox on top! Please let me know if that unblocks you! 😀

**Comment by ErikEJ** [comment]
Are you using SQL Compact?

**Comment by kharze** [comment]
Yes we are using SQL compact 4.0, so is it possible to generate it through the entity wizard? how do i activate the provider? 😄

**Comment by ErikEJ** [comment]
If you use VS 2012 or VS 2013:
- Install the latest EF 6 VS Tools - https://www.microsoft.com/en-us/download/details.aspx?id=40762
- Install the SQLite/SQLCE Toolbox
- Run the EDMX Wizard, and use the "Simple by ErikEJ" DDEX data source/provider to connect to your database file

If you use VS 2015:
- Install the SQLite/SQLCE Toolbox
- Run the EDMX Wizard, and use the "Simple by ErikEJ" DDEX data source/provider to connect to your database file

**Comment by kharze** [comment]
Thank you! that solved the issue 👍

**Comment by ErikEJ** [comment]
Great - If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details

**Comment by rizksobhi** [comment]
Hi Erik, I use your tool to generate edmx model, and I have the same issue above.
I can't find the EDMX generation wizard
![sqllite](https://cloud.githubusercontent.com/assets/24998061/23783423/1b9d6460-0521-11e7-9ea5-eb87038ad88d.jpg)

and the first selection generates .cs file
Any help will be appreciated.

Thanks
Rizk

**Comment by ErikEJ** [comment]
@rizksobhi Just follow the steps outlined above
