### ISSUE TITLE
Possible inclusion of LiteDB into the target?

### ISSUE THREAD

**Issue by xied75** [ErikEJ/SqlCeToolbox#289]
https://github.com/mbdavid/LiteDB

Reasons to support this:

1, probably the only viable NoSQL solution that can be used in UWP currently.
2, pure C# rather than C++ compiled lib.

**Comment by ErikEJ** [comment]
Hmmm... This to is for relational embedded databases - what do you mean by "include in target" ?

**Comment by xied75** [comment]
I understand it's all relational to you now. :)

What I mean is to enable the toolbox to be able to open up LiteDB files and browse the content, even it's not relational, but the API is extremely simple.

**Comment by ErikEJ** [comment]
There already is an app: https://github.com/falahati/LiteDBViewer - seems like a lot of redundant work to port to run under VS - PRs accepted!

**Comment by xied75** [comment]
Right, I'll see if the tool author is interested then. Feel free to close for now.
