### ISSUE TITLE
Scrolling 

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#29]
Just a small improvement: other Visual Studio components support the mouse wheel scrolling also when the pointer is not located over the scrollbar, SQL CE Toolbox seems not.

**Comment by ErikEJ** [comment]
I think it may have been fixed in the latest preview: http://sqlcetoolbox.codeplex.com/releases/view/618303 - please try it out an let me know

**Comment by mwallnoefer** [comment]
works perfectly

**Comment by ErikEJ** [comment]
Thansk for the feedback!
