### ISSUE TITLE
Missing Sqlite for data connection

### ISSUE THREAD

**Issue by dpodgors** [ErikEJ/SqlCeToolbox#290]
Erik,
This is kicking my butt. I can't get Sqlite to show up in the data source dialog. THe compact shows up but not Sqlite. What the heck am I doing wrong?

![image](https://cloud.githubusercontent.com/assets/2764091/23688303/5dca6314-0379-11e7-93fb-254726562363.png)

**Comment by ErikEJ** [comment]
Did you read my blog post here? http://erikej.blogspot.dk/2014/11/using-sqlite-with-entity-framework-6.html

**Comment by dpodgors** [comment]
Yes and went through it again. While I think I matched up everything with regards to VS 2015 / SQLite 1.0.104 and EF 6.1.3. 
I think I got a little farther as I have a connection now in the Server Explorer but still can get anything in the Entity Data Model.

![image](https://cloud.githubusercontent.com/assets/2764091/23734678/4249385e-0446-11e7-8ece-83f0218013b4.png)


Any thoughts?

**Comment by ErikEJ** [comment]
Not really, there are some tips in the blog post comments that might be able to help you - generally, this is not a very well supported scenario

**Comment by dpodgors** [comment]
Thanks for your help. I was going to respond tonight when I got off work.


Thanks again

Don

**Comment by ErikEJ** [comment]
Feel free to re-open if you want to share any findings!

**Comment by dpodgors** [comment]
Will do, just wondering if CE can handle the same amount of data as 
SQLite? I have an app that I need to scale to many devices but not 
necessarily have a server for the back end data. So I was looking at 
SQLite and having it replicate among the devices running the app.


Any thoughts?

**Comment by ErikEJ** [comment]
SQL CE has a ¤ GB size limit per database file, but yes, it can handle large amounts of data

**Comment by dpodgors** [comment]
I just saw it was deprecated. Are there any other MS SQL solution that 
could be synchronized across devices?

**Comment by ErikEJ** [comment]
Nope...
