### ISSUE TITLE
Unable to add dates to fields with the datetime datatype

### ISSUE THREAD

**Issue by Adeian** [ErikEJ/SqlCeToolbox#30]
I am unable to import data from a CSV file.  I receive the error:
    -- Script Date: 1/28/2016 11:50 PM  - ErikEJ.SqlCeScripting version 3.5.2.58
    -- Cannot create script, one or more field names on first line are invalid:-- Wrong column names        WINDOWSTART WINDOWEND 
    -- Also check that correct separator is chosen.

The first two lines I'm trying to import are 
   movieAssetID,NvisRunTime,Title,titleAssetId,packageAssetId,TmsStatus,TmsId,WindowStart,WindowEnd,expectedDivCodes
AESM1589691601110000,2016-01-16 16:31:58,First 48 01-14,AEST1589691601110000,AESP1589691601110000,MAPPED,EP006609610497,2016-01-18,2016-04-14,CLT CSC WIL

Also if I try to add dates in any of the supported SQLite date formats I get an error about null fields.  They are configured to be NULL.

**Comment by ErikEJ** [comment]
The first error means that there are no columns named WindowsStart and WindowEnd in your table, I believe. (Or I have a bug...)

Would be helpful if you could share a sample database and csv file.

**Comment by ErikEJ** [comment]
No info received, closing for now
