### ISSUE TITLE
SQL CE Toolbox query window comment processing.

### ISSUE THREAD

**Issue by Maximushep** [ErikEJ/SqlCeToolbox#303]
Hi Erick,

I have a 
Insert Into <tbl>
Select <huge query>

When i comment the first line with a -- Insert Into <tbl> and use CTRL + E to run, it says query returned no data, even though the insert was commented out.

Looks like the parser is not detecting commented insert correctly.

Thanks,
Rajesh.

**Comment by ErikEJ** [comment]
Could you provide a sample using Northwind or Chinnok database, then I will investigate?

**Comment by Maximushep** [comment]
I had a temp table t1, where I run the query once.
Then I commented the insert and just wanted the select to run.

Try the following SQL.

-- Insert Into t1
Select * From Categories

The issue, I believe is system might be caching the type of SQL statement (Udi vs select), so first time it was UDI and next time it was select.
Not sure if that helps, but that is a thought.

**Comment by ErikEJ** [comment]
I think Ctrl+E is a bit shaky, what happens if you press the Execute button (green arrow) ?

**Comment by Maximushep** [comment]
Same thing, I tried the play button too, since I thought may be the keyboard accelerator code may not be right....

**Comment by ErikEJ** [comment]
Using the Play button I am not able to reproduce

**Comment by ErikEJ** [comment]
SQLite og SQLCE?

**Comment by ErikEJ** [comment]
Unable to reproduce, feel free to re-open if you can provide detailed steps to reproduce

**Comment by Maximushep** [comment]
It was SQLCE.

**Comment by Maximushep** [comment]
I am unable to attach a .ZIP with .SDF and .SQL file.
Can you tell me how to send those.

With the CE sdf file and appropriate SQL, you can reproduce both issues.

**Comment by ErikEJ** [comment]
Sounds great, you can email to: ejlskov@hotmail.com
