### ISSUE TITLE
Unable to register DDEX providers

### ISSUE THREAD

**Issue by pandenista** [ErikEJ/SqlCeToolbox#304]
Hello,
I've got Win 10, VS 2015 Enterprise ed., SQL Server Compact 4.0 installed and SQLite/SQL Server Compact Toolbox v 4.7.78.0 installed. When I open About dialog, DbProvider is OK but DDEX providers have flag No.
I pressed the button Register DDEX Providers, message box said it's installed to restart VS, but when I restart it, nothing has changed. When I want to attach sdf file, a red warning says it cannot save this connection for use with EF6 Tools. Is there any possibility to really register DDEX providers?
Thanks,
Martin.

**Comment by ErikEJ** [comment]
Looks like I have a bug, you can folow my discussion here: https://gitter.im/Microsoft/extendvs

**Comment by ErikEJ** [comment]
Looks like you just need to shut down all instances of VS or maybe even restart PC, at least that fixed it for me (and I faced the exact same issue)

**Comment by ErikEJ** [comment]
Consider using pkgdef file for DDEX registration:
here's some info on pkgdef files: https://msdn.microsoft.com/en-us/library/cc138553.aspx
basically, you need to add a pkgdef file to your vsix (make sure it's referenced in the vsixmanifest) and include entries like:
    
    [$RootKey$\DataProviders\{673BE80C-CB41-47A7-B0F3-9872B6DDE5E5}]
    ""="SQL Server Compact 4.0 Provider (Simple by ErikEJ)"

 
they're very similar to registry files (I'm pretty sure we just perform token replacement then install the registry file)

**Comment by ErikEJ** [comment]
Hi, I have attempted to fix this in the latest daily build, would be grateful if you could give it a try:
- Uninstall the existing extension
- Download and install the daily build
- Test if the DDEX provider for SQLCE 4.0 appears on first launch
