### ISSUE TITLE
Adding 'templates' for selecting tables to script

### ISSUE THREAD

**Issue by pawcio-g** [ErikEJ/SqlCeToolbox#307]
I am using your tools to script data to SQL. Databases I work with are large, they have 70-100 various tables, and I need to script only around 35 tables off that database. Would it be possible to add a feature to save a config/template file to disk which would remember which tables should be scripted and then to load that file and automatically pre-select tables for scripting?

**Comment by ErikEJ** [comment]
Sure, it would be possible - sounds like a nice feature suggestion - are you exporting from SQL Compact to SQL Server ?

**Comment by pawcio-g** [comment]
Yes, from SQL CE to SQL Server. Would be great to see that implemented at some point :)

**Comment by ErikEJ** [comment]
This is included in the latest daily build, would be grateful if you could try t out and let me know if it works for you!
