### ISSUE TITLE
Error when connect SQL Server compact 4.0

### ISSUE THREAD

**Issue by jeanspaulo** [ErikEJ/SqlCeToolbox#308]
Using Visual Studio 2015 update 3 and trying to connect to SQL Server compact 4.0 its throwing an exception.

System.ArgumentException: Format of the initialization string does not conform to specification starting at index 78 at System.Data.Common.DbConnectionOptions.GetKeyValuePair(String connectionString, int32 currentPostision, StringBuilder buffer, Boolean...... ) 

DataConnectionHelper.cs line 577
ExplorerControl.xaml.cs line 519

**Comment by ErikEJ** [comment]
Could you share a screenshot?

**Comment by jeanspaulo** [comment]
![captura de tela 2017-03-20 11 07 38](https://cloud.githubusercontent.com/assets/26546519/24105310/35d59af6-0d63-11e7-8b2e-e43ea9ec8d95.png)

**Comment by ErikEJ** [comment]
Could you please remove and redo the connection - or share the connectionstring (avaklable in Properties window) for the broken connection

**Comment by jeanspaulo** [comment]
the connection string is
Data Source=H:\Fenix\Sistema\V1.1\Fenix\AgilBox\AgilBox.sdf;Password=s{[4BaR!;G@&

**Comment by ErikEJ** [comment]
Ugh - it is a bug the SQL Server Compact SqlCeConnectionStringBuilder (outside of my control, sadly) - it is the semicolon ";" in the password that breaks it, I guess.

**Comment by jeanspaulo** [comment]
are there any workaround to solve this bug?

**Comment by ErikEJ** [comment]
use another password?

**Comment by ErikEJ** [comment]
You can try to use "sqlcecmd" to change the password...
