### ISSUE TITLE
Possible to see relationships like usual sql?

### ISSUE THREAD

**Issue by ozgurerdogan** [ErikEJ/SqlCeToolbox#31]
Possible to see relationships like usual sql.  Please see ss.

![tablerelation](https://cloud.githubusercontent.com/assets/231544/12729754/e5d71ff6-c930-11e5-8b0f-dc72276e1037.gif)

**Comment by ErikEJ** [comment]
Of course, use the Create database graph feature

**Comment by ozgurerdogan** [comment]
But there I do not see those yellow key or infinity sign which simply indicates relationship. What I see is gray arrows as:

![aaa](https://cloud.githubusercontent.com/assets/231544/12730500/f2e281fa-c934-11e5-8989-65fb0c5e720e.jpg)

**Comment by ozgurerdogan** [comment]
If I add edmx to project, I can see them. But wondering if it would make some other changes to my project?

**Comment by ErikEJ** [comment]
Nothing to do here..!?
