### ISSUE TITLE
Add ef core model to current project failed

### ISSUE THREAD

**Issue by evenlee** [ErikEJ/SqlCeToolbox#310]
I am trying to generate a model, when I used the menu and click the ok  button, an error popped up:

![capture](https://cloud.githubusercontent.com/assets/4009476/24129659/15805432-0e1f-11e7-9a11-1db41ca74f98.PNG)

**Comment by ErikEJ** [comment]
Looks like you are trying to generate code in a Database (SSDT) project - this is not supported - I will see if I can improve the error message.

**Comment by evenlee** [comment]
Actually, I am using a core class library project :)

**Comment by ErikEJ** [comment]
OK! What is the exact project type and VS version? I will investigate...

**Comment by ErikEJ** [comment]
Does your solution contain a Database project?

**Comment by ErikEJ** [comment]
I think I have a fix for this in the latest daily build - please let me know if it works for you! https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes
