### ISSUE TITLE
Provider issue

### ISSUE THREAD

**Issue by timov** [ErikEJ/SqlCeToolbox#312]
![image](https://cloud.githubusercontent.com/assets/4513692/24252471/d5d797c6-0fdd-11e7-843e-9f4516099b72.png)

**Comment by ErikEJ** [comment]
Nice srceen shot from the EF Tools - could you please provide a little context and explain how this relates to the Toolbox - ie, what are you trying to do, which Toolbox and VS Version etc?

**Comment by ErikEJ** [comment]
If this is SQL CE 4.0 DDEX releated, please try the latest daily build, where I have made some improvements to the DDEX registration https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes
