### ISSUE TITLE
Hitting about crashes VS 2017 unless CE 3.5 and 4.0 are installed

### ISSUE THREAD

**Issue by nasenbaer43** [ErikEJ/SqlCeToolbox#314]
Just installed the addon and it keeps crashing VS 2017 enterprise:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	devenv.exe
  Problem Signature 02:	15.0.26228.9
  Problem Signature 03:	58c7276d
  Problem Signature 04:	System.Data.SqlServerCe
  Problem Signature 05:	4.0.8876.1
  Problem Signature 06:	4fcd17f1
  Problem Signature 07:	401
  Problem Signature 08:	17
  Problem Signature 09:	System.Data.SqlServerCe.SqlCe
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1031
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

OK, might be my bad since I had neither CE installed, yet users who only want SQLite support shouldn't have to install them.
Tell me if you need any other log file....

**Comment by ErikEJ** [comment]
Thanks for reporting - I beleive I have fixed this is the latest daily build: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes - please let me know if that fixes your issue (caused by a broken SQL Server Compact installation)

**Comment by ErikEJ** [comment]
Also in the latest release version now (4.7.87)
