### ISSUE TITLE
VS2017 crash after "About" menu item clicked

### ISSUE THREAD

**Issue by robjuca** [ErikEJ/SqlCeToolbox#315]
Hi,
When open menu item "About" from toolbox VS2017 crash.
![new bitmap image](https://cloud.githubusercontent.com/assets/12336342/24333489/24e5fd1e-122f-11e7-9d32-ef0a8c34af94.jpg)

**Comment by ErikEJ** [comment]
Please try to install the latest version, and let me know if that fixes your issue (released today)

**Comment by robjuca** [comment]
Hi,
The release with issue is: 4.7.87.0 
Release 4.7.87 (March 26, 2017)) from release notes

**Comment by ErikEJ** [comment]
Sorry, I missed that - will have another look!

**Comment by ErikEJ** [comment]
Found the bug!
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/Dialogs/AboutDialog.xaml.cs#L48 (should have been more general)

**Comment by robjuca** [comment]
Glad to know and sorry boring you with this issue. BTW you made a great application congratulations, 8)

**Comment by ErikEJ** [comment]
Hi, I have attempted a fix in the latest daily build - could I ask you to give it a try? https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by robjuca** [comment]
Sorry not fixed...
![new bitmap image](https://cloud.githubusercontent.com/assets/12336342/24402711/1afa031a-1390-11e7-9298-93d2edd7d59d.jpg)
...

**Comment by ErikEJ** [comment]
That is not the latest daily build, download direct from this page: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by robjuca** [comment]
oops... doing now

**Comment by robjuca** [comment]
Fixed works fine 8).
![image 4](https://cloud.githubusercontent.com/assets/12336342/24417092/6f3fc64e-13bd-11e7-8129-4e3ca4c6cae1.jpg)
