### ISSUE TITLE
Tab gets lots in debug session

### ISSUE THREAD

**Issue by grokky1** [ErikEJ/SqlCeToolbox#321]
### Steps to reproduce
Run a SELECT against one of my tables, during a debugging session. It opens in a new tab.

Stop debugging. The tab disappears.

Start debugging, it reappears. Only then can I close it and reclaim memory/resources.

### Further technical details
Toolbox version: 4.7.87.0
Database engine: SQlite
Visual Studio version: Visual Studio 2015

**Comment by ErikEJ** [comment]
Wonder if the best approach would be to disallow opening new windows during a debug session (otherwise I do not have many suggestions for a fix) - what do you think?

**Comment by grokky1** [comment]
Sounds good to me

**Comment by ErikEJ** [comment]
Fixed in the latest daily build, please le me know if it fixes your issue - and thanks for reporting this!

**Comment by grokky1** [comment]
Thanks it's good

**Comment by ErikEJ** [comment]
Thanks for reporting back!
