### ISSUE TITLE
problem when i add sql server compact edition 3.5 database 

### ISSUE THREAD

**Issue by abdou31** [ErikEJ/SqlCeToolbox#322]
Hello Mr Erik , Im Student , and Im developing an application on Windows phone 8.0 , so im trying to a new database sql compact edtion 3.5 from server explorer i get this error (picture 1) that "cannot save this connection for use with EF6 Tools , make sur that SQL Server compact DbProvider is installed , so when i try to registry DbProvider and after restaring Visual Studio 2012 , i get this error (picture 2)
https://postimg.org/image/npnvhag97/
https://postimg.org/image/k0yub5d8f/

### Further technical details
Toolbox version: 4.7.93
Database engine: SQL Compact Edition 3.5 
Visual Studio version: Visual Studio 2012 Pro ( Windows Phone SDK 8.0 installed on it )

**Comment by ErikEJ** [comment]
This should be fixed in the latest daily build - Server Explorer integration with 3.5 has been removed
