### ISSUE TITLE
Problem when adding database Sql server compact 3.5

### ISSUE THREAD

**Issue by abdou31** [ErikEJ/SqlCeToolbox#324]
Hello Mr Erik , my problem is i can't show my database that using sql server compact 3.5 and i can't add database using sql server compact 3.5 , there is the picture that show my problem
http://img15.hostingpics.net/pics/247241problem.png

### Further technical details
Toolbox version: 4.7.87
Database engine: SQL Compact 3.5
Visual Studio version: Visual Studio 2012

**Comment by ErikEJ** [comment]
You need the latest daily build: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes 
and you must install SQL Server Comoact 3.5 SP2 runtime: https://github.com/ErikEJ/SqlCeToolbox/wiki 

Feel free to re-open if that does not work.

**Comment by abdou31** [comment]
When I try to the daily build from i get this error 

    Le Dimanche 2 avril 2017 20h05, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 Closed #324.—

**Comment by ErikEJ** [comment]
Which error?

**Comment by abdou31** [comment]
See the picture that showng problem 

    Le Dimanche 2 avril 2017 20h15, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 Which error?—

**Comment by ErikEJ** [comment]
Did you do this, as I wrote earlier: 

**you must install SQL Server Compact 3.5 SP2 runtime: https://github.com/ErikEJ/SqlCeToolbox/wiki**

**Comment by abdou31** [comment]
Yes i did Mr Erik , and the first problem solved and database (sql server compact 3.5) showed in server explorer but my problem 2 is when i try to install last update i get this error that in the picture 

    Le Dimanche 2 avril 2017 20h30, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 Did you do this, as I wrote earlier:you must install SQL Server Compact 3.5 SP2 runtime: https://github.com/ErikEJ/SqlCeToolbox/wiki—

**Comment by ErikEJ** [comment]
I cannot see any error in the picture??? !

**Comment by abdou31** [comment]
See this picture please  

    Le Dimanche 2 avril 2017 20h49, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 I cannot see any error in the picture??? !—

**Comment by ErikEJ** [comment]
I cannot see any picture, other than the one in your original question - attach a screenshot on the GitHub web site instead of replying by email, perhaps?

**Comment by abdou31** [comment]
https://s12.postimg.org/j8vf7g59p/prblm1.png

**Comment by abdou31** [comment]
I send it now on GitHub

    Le Lundi 3 avril 2017 9h36, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 Reopened #324.—

**Comment by ErikEJ** [comment]
OK, so you cannot install the latest build - finally you told me!

Please share the log file! (link shown in your screen shot)

Which VS version and edition do you have?

**Comment by abdou31** [comment]
I have Visual Studio 2012 Pro with Windows Phone SDK 8.1  

    Le Lundi 3 avril 2017 10h32, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 OK, so you cannot install the latest build - finally you told me!Please share the log file! (link shown in your screen shot)Which VS version and edition do you have?—

**Comment by ErikEJ** [comment]
I need to see the log file...

**Comment by ErikEJ** [comment]
BTW: I have improved the handling of numeric columns in the table designer in the latest daily build

**Comment by abdou31** [comment]
ah maybe but i think that problem is in version that me i use visual studio 2012 and the latest update require visual studio 2013 or 2015 , i send you the log file did you see it?
http://img4.hostingpics.net/pics/620607logfile.png

**Comment by ErikEJ** [comment]
You downloaded the wrong file :smile: - the one you downloaded is the SSMS extension! Use the Visual Studio extension download link on this page:  https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by abdou31** [comment]
thank you Mr Erik that work fine for me :)  

    Le Mardi 4 avril 2017 6h57, Erik Ejlskov Jensen <notifications@github.com> a écrit :
 

 Closed #324.—
