### ISSUE TITLE
Export my SQL db to SQLite db in SSMS

### ISSUE THREAD

**Issue by bnikollov** [ErikEJ/SqlCeToolbox#327]
Hello, I am having difficulties to find information about how to Export my SQL db to SQLite db. I have installed the SSMS Extension and what are the next steps?

**Comment by ErikEJ** [comment]
- Connect to your SQL Server database in Object Explorer
- Open the Toolbox (View menu) or Refresh
- The database should now appear in the Toolbox
- Right click and select "Migrate to SQLite"

**Comment by bnikollov** [comment]
![image](https://cloud.githubusercontent.com/assets/18344640/24661631/8f4e4a70-195b-11e7-81ad-715d394d7d2c.png)

I have connected to my server database. And when i open the toolbox there is nothing there?!

![image](https://cloud.githubusercontent.com/assets/18344640/24661705/c7d48288-195b-11e7-8be9-5e69e9d8037d.png)

**Comment by ErikEJ** [comment]
That's the wrong window! :smile: - from the View menu select SQLite Toolbox!

**Comment by bnikollov** [comment]
:D thanks! I found it and it works! Sorry for my ignorance.

**Comment by ErikEJ** [comment]
Great news! I plan to also add some context menu items to the database node in object explorer to make it easier to find!

**Comment by ErikEJ** [comment]
I have added a Object Explorer context menu in the latest daily build!

![ssmscontext](https://cloud.githubusercontent.com/assets/4169187/24702020/37ccc50e-19fd-11e7-9f1c-96375bb565af.png)
