### ISSUE TITLE
Subqueries against SQLite causing VS to lock up

### ISSUE THREAD

**Issue by amkuchta** [ErikEJ/SqlCeToolbox#33]
Running a query that contains a subquery against a SQLite database causes VS (2013 Pro) to lock up; full query below:

```SQL
SELECT 
	AssetToReport, 
	HostName, 
	IpAddress, 
	GroupName, 
	FileName, 
	(SELECT 
			OperatingSystem 
		FROM 
			UniqueFinding U2 
		NATURAL JOIN Vulnerbaility 
		WHERE 
			U1.AssetToReport = U2.AssetToReport 
		AND 
			VulnId = 'SpecifiedVulnId') AS OperatingSystem 
FROM 
	UniqueFinding U1 
NATURAL JOIN FindingTypes 
NATURAL JOIN Groups 
NATURAL JOIN FileNames 
NATURAL JOIN Vulnerability 
WHERE 
	FindingType = 'SpecifiedFindingType'
GROUP BY 
	AssetToReport
ORDER BY 
	AssetToReport;
```

Subquery runs fine as a standalone query, outer query runs fine without the inner query, and the query as a whole runs fine in code.

**Comment by ErikEJ** [comment]
Have you tried running the query in other tools?

For me to do any debugging (I have nothing to do with the sqlite engine), I need a copy of your database file

**Comment by amkuchta** [comment]
I am able to execute the query in code using an instance of SQLiteDataReader (C# .NET); the result set returns as expected.

I can generate a sample database file to send you (I need to scrub some data from it first).

**Comment by ErikEJ** [comment]
Thanks for the additional info - you can email me: ejlskov at Hotmail dot com

**Comment by ErikEJ** [comment]
Closing as not addtional info received - feel free to re-open
