### ISSUE TITLE
Migrating large SQL DB to SQLite just stops.

### ISSUE THREAD

**Issue by bnikollov** [ErikEJ/SqlCeToolbox#331]
Hi @ErikEJ it's me again :)

I have tested to migrate very small SQL DB before and it was working perfect. Now I try to migrate large SQL DB to SQLite in SSMS and Visual studio and the task just stops after 
"Creating SQLite database...
Starting import
Scripting server database..."
The SQLite DB file is 0kb. Is there any size limitations or something?

**Comment by ErikEJ** [comment]
No size limitations, but the process could take a long time for a large database.. 
- Check your %temp% folder for generated .sql files, to verify if the export is working..
- How large is large?
- No errors??

**Comment by bnikollov** [comment]
Ok, now I see that the SQLite file is growing. The db table that I am migrating from has 350 000 rows. If it is possible, where can I see total progress or some indication that it is running?

**Comment by ErikEJ** [comment]
You could also try the script to file option, and the run the generated scripts using SQLite3.exe to see if any errors occur.

**Comment by ErikEJ** [comment]
You should see Importing data...{0} in the status bar for each imported 18 MB file

**Comment by ErikEJ** [comment]
Check you %temp% folder to see how many .sql files were generated

**Comment by bnikollov** [comment]
Windows temp folder? Becouse there is no .sql files there.

**Comment by ErikEJ** [comment]
In %temp% look for the newest files, extension is .sqlce, not .sql, sorry.

**Comment by ErikEJ** [comment]
Closing, as the import is actually running... I have logged: https://github.com/ErikEJ/SqlCeToolbox/issues/334

**Comment by ErikEJ** [comment]
I have added improved feedback (progress bar) in the latest daily build - thanks for your valuable feedback!
