### ISSUE TITLE
SQL Server create default

### ISSUE THREAD

**Issue by reader-man** [ErikEJ/SqlCeToolbox#333]
Describe what is not working as expected.
  The Generation of Fluent API for the default value in Context.OnModelCreating(ModelBuilder modelBuilder), returns SQL Server comments which affects the compilation of the Project in VS, if this is using MS Generation Tool, then it also suffers from the same problem.

### Steps to reproduce
make a new database in sql server, and run the file "sqlSampleTableToProveGenerationProblem.sql" and don't delete the first empty lines:

[](https://goo.gl/w1Fb5v)

then generate the POCO Entities + the Context, and you will see these problematic lines:
```
                entity.Property(e => e.AnythingCol)
                    .HasColumnName("anythingCol")
                    .HasColumnType("TypeBoolean_Dom")
                    .HasDefaultValueSql("


/*==============================================================*/
/* Default: D_0                                                 */
/*==============================================================*/
create default D_0
    as 0
");
            });
```

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3)
Visual Studio 2017

as a note i gave this also to EF Core guys:
https://github.com/aspnet/EntityFramework/issues/8077

**Comment by ErikEJ** [comment]
I am simply using the EF Core reverse engineer code under the hood, som closing this here..

**Comment by reader-man** [comment]
Thanks, i thought that, because the code was almost the same.

Question: How to send messages to (you/any user) in github, as i wanted to ask how to use EF reverse Poco through ur tool?

**Comment by ErikEJ** [comment]
Just post an issue/question here! 😄

**Comment by reader-man** [comment]
Ok, thanks.
I installed ur tool, could not see where/how to use the EF reverse POCO?
just an info, i did not install EF reverse POCO, as i only use its .tt files.

Regards.

**Comment by ErikEJ** [comment]
Just right click a SQL Compact database, that will guide you through the process (does not work for SQLite)

**Comment by reader-man** [comment]
so its only SQL Compact, not SQL Server?

**Comment by ErikEJ** [comment]
Also SQL Server, of course! But that does not really relate to the Toolbox...
