### ISSUE TITLE
About box doesn't scale well with desktop scaling

### ISSUE THREAD

**Issue by frogger3d** [ErikEJ/SqlCeToolbox#34]
My screen is at 150% scale and the about box looks slightly mangled (the link).
<img width="231" alt="about" src="https://cloud.githubusercontent.com/assets/1745610/12854589/dcba5228-cc3a-11e5-9431-6f010f6ae85b.png">

**Comment by ErikEJ** [comment]
Thanks for reporting this!

**Comment by ErikEJ** [comment]
Are there any other mangled dialogs?

**Comment by frogger3d** [comment]
Not that I know of, but I don't reallly use the tool, so I only checked quickly.
