### ISSUE TITLE
"Build Table" generates an invalid script on Sqlite

### ISSUE THREAD

**Issue by michelevevy** [ErikEJ/SqlCeToolbox#35]
My target is to generate a table with an autoincrement integer id (as default in Sqlite [https://www.sqlite.org/autoinc.html](https://www.sqlite.org/autoinc.html)).
This is the result of "Build Table" generated script:
```
-- Script Date: 10-Feb-16 17:19  - ErikEJ.SqlCeScripting version 3.5.2.58
CREATE TABLE [Pippoes] (
  [Id] INTEGER NOT NULL
, [Name] nvarchar(100) NOT NULL
, CONSTRAINT [PK_Pippoes] PRIMARY KEY ([Id])
);
```

Adding a new row to this table throw this error:
**SQLite error (1299): abort at 5 in [INSERT INTO [Pippoes]([Name])
 VALUES (@p0);]: NOT NULL constraint failed: Pippoes.Id**

If instead I generate the table using the following script, it's succeeds:
```
CREATE TABLE [Pippoes] (
  [Id] INTEGER PRIMARY KEY NOT NULL
, [Name] nvarchar(50) NULL);
```

**Comment by ErikEJ** [comment]
Looks like the original syntax should work - will do some testing: https://www.sqlite.org/lang_createtable.html#rowid

**Comment by ErikEJ** [comment]
This INSERT statement works fine on my PC, and generates the autoincementing Id:

    INSERT INTO [Pippoes]
           ([Name])
     VALUES('test2');

I think you must have wrong syntax in your INSERT statement
