### ISSUE TITLE
Installation Problems

### ISSUE THREAD

**Issue by whahnenb** [ErikEJ/SqlCeToolbox#351]
I'm attempting to install the SQLCE Toolbox and getting this install log below.  Any ideas?

4/24/2017 11:20:14 AM - Microsoft VSIX Installer
4/24/2017 11:20:14 AM - -------------------------------------------
4/24/2017 11:20:14 AM - Initializing Install...
4/24/2017 11:20:14 AM - Extension Details...
4/24/2017 11:20:14 AM - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
4/24/2017 11:20:14 AM - 	Name               : SQLite / SQL Server Compact Toolbox
4/24/2017 11:20:14 AM - 	Author             : ErikEJ
4/24/2017 11:20:14 AM - 	Version            : 4.7.87
4/24/2017 11:20:14 AM - 	Description        : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
4/24/2017 11:20:14 AM - 	Locale             : en-US
4/24/2017 11:20:14 AM - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
4/24/2017 11:20:14 AM - 	InstalledByMSI     : False
4/24/2017 11:20:14 AM - 	SupportedFrameworkVersionRange : [4.5,)
4/24/2017 11:20:14 AM - 
4/24/2017 11:20:14 AM - 	SignatureState     : Unsigned
4/24/2017 11:20:14 AM - 	Supported Products : 
4/24/2017 11:20:14 AM - 		Microsoft.VisualStudio.Pro
4/24/2017 11:20:14 AM - 			Version : [11.0,16.0)
4/24/2017 11:20:14 AM - 		Microsoft.VisualStudio.Community
4/24/2017 11:20:14 AM - 			Version : [12.0,16.0)
4/24/2017 11:20:14 AM - 
4/24/2017 11:20:14 AM - 	References         : 
4/24/2017 11:20:14 AM - 		-------------------------------------------------------
4/24/2017 11:20:14 AM - 		Identifier   : Microsoft.VisualStudio.MPF.11.0
4/24/2017 11:20:14 AM - 		Name         : Visual Studio MPF 11.0
4/24/2017 11:20:14 AM - 		Version      : [11.0]
4/24/2017 11:20:14 AM - 		MoreInfoURL  : 
4/24/2017 11:20:14 AM - 		Nested       : No
4/24/2017 11:20:14 AM - 
4/24/2017 11:20:14 AM - Signature Details...
4/24/2017 11:20:14 AM - 	Extension is not signed.
4/24/2017 11:20:14 AM - 
4/24/2017 11:20:14 AM - Searching for applicable products...
4/24/2017 11:20:14 AM - Found installed product - Microsoft Visual Studio Express 2015 for Windows Desktop
4/24/2017 11:20:14 AM - Found installed product - Global Location
4/24/2017 11:20:14 AM - Found installed product - ssms
4/24/2017 11:20:14 AM - Found installed product - ssms
4/24/2017 11:20:14 AM - Found installed product - ssms
4/24/2017 11:20:14 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3)

**Comment by ErikEJ** [comment]
You are trying to install the VS extension, but you only have VS Express installed, and you cannot install extension in Express. Upgrade to the free Community edition or higher.
