### ISSUE TITLE
Include SQLite triggers in CREATE TABLE generation

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#357]
Triggers get not exported when using the two scripting functions _Script as CREATE_ and _Script as DROP and CREATE_.
This is especially problematic when using _Script as DROP and CREATE_ and running the script, since then all defined table triggers get lost.

### Steps to reproduce
Right-click on a SQLite table with triggers and choose one of the two mentioned functions.

### Further technical details
Toolbox version: 4.7.87.0
Database engine: SQlite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by mwallnoefer** [comment]
I am not fully convinced that this change is the right approach (of course you may see this differently than me), let me explain why: first of all SQLite has triggers, SQL CE does not. And it might be true that triggers in SQLite are not so common - agreed.

But for me a trigger is a child object of a table. It belongs only to that table and that's it. So I would not mind to see also the trigger exported when the _Script as CREATE_ function is used. And if I recall correctly the VS Database Tools for SQL Server do exactly this: if you open the table's definition you get also the triggers among the fields, constraints, indexes. And for a familiar user experience we should imitate it as much as possible -- just my two cents.

**Comment by ErikEJ** [comment]
Agree (though you are the only user ever reporting this)

**Comment by mwallnoefer** [comment]
Well done, works like a charm!

**Comment by ErikEJ** [comment]
No, thank YOU for all your help improving the tool 👍
