### ISSUE TITLE
Export SQLite DEFAULT constraints

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#359]
When I export a SQLite database, all `DEFAULT` constraints are lost (maybe other constraints as well).

### Steps to reproduce
Right-click a SQLite table and choose _Script as CREATE_, _Script as DROP and CREATE_.
Right-click a SQLite DB and choose the _Script database_ feature.

### Further technical details
Toolbox version: 4.7.87.0
Database engine: SQlite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by mwallnoefer** [comment]
Yes, please:
```
CREATE TABLE [RawEvents] (
  [idRawEvent] uniqueidentifier NOT NULL
, [idRace] uniqueidentifier NOT NULL
, [RowIndex] bigint NOT NULL DEFAULT -1
, [BibNumber] bigint NOT NULL
, [Ticks] bigint NOT NULL
, CONSTRAINT [sqlite_autoindex_RawEvents_1] PRIMARY KEY ([idRawEvent])
);
```

**Comment by ErikEJ** [comment]
Thanks for reporting this bug, a fix is in progress

**Comment by ErikEJ** [comment]
Fixed in the latest daily build
