### ISSUE TITLE
Test connection automatically before closing "Add SQL Server Compact/SQLite Connection" dialog

### ISSUE THREAD

**Issue by ajphall** [ErikEJ/SqlCeToolbox#36]
Very simple issue: often I try to open an SQLCe database that is more than the default 256 MB in size, and so when I press OK, I get an error message saying the database file is too large:

![image](https://cloud.githubusercontent.com/assets/5737406/13008366/e92d4ae6-d163-11e5-8f7b-e6922d99d362.png)

The problem is that after I press OK on the error window, the Add Connection form disappears and I have to reopen the window and then navigate to my database again.

This is a very minor problem, but it would save people a bit of time if:
1) the last used filename was stored somehow;
2) if there is an error you do not close the Add Connection form; or
3) the default Max database size in MB could just be 4091 by default (although I'm wondering if there is a reason you didn't already do this?).

Thank you for providing this tool for the community - it is excellent in every way, and after using it quite a lot for the past few years this is the only complaint I have...

**Comment by ErikEJ** [comment]
This is fixed in the latest "daily" - https://sqlcetoolbox.codeplex.com/releases/view/619815 - please let me knwo if that fixes the issue - and thanks for reporting this

**Comment by ajphall** [comment]
Hi Erik,

I just tested and it works as expected.  Thank you so much!

Andrew

**Comment by ErikEJ** [comment]
Great -
If you use my tools, I would be very grateful for a rating or review here:

https://visualstudiogallery.msdn.microsoft.com/0e313dfd-be80-4afb-b5e9-6e74d369f7a1/view/Reviews

**Comment by ajphall** [comment]
Yes, I already did this a couple of weeks ago, but I just added one for your SQLCe Bulk Copy on Codeplex which we also use.

**Comment by ErikEJ** [comment]
Thanks a lot!
