### ISSUE TITLE
FormatException string was not recognized as a valid boolean when import from .csv

### ISSUE THREAD

**Issue by zybbxm** [ErikEJ/SqlCeToolbox#362]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3)

**Comment by ErikEJ** [comment]
Most likely you have column contents that does not translate to a boolean value, but you are not sharing any info...

**Comment by ErikEJ** [comment]
Closing as I have not heard back, feel free to re-open if you want to respond.
