### ISSUE TITLE
Error in scripting DB Schema

### ISSUE THREAD

**Issue by cris651** [ErikEJ/SqlCeToolbox#363]
Hello, thank you for your precious work.
### Steps to reproduce
I'm trying to run "Script  Database Data" from within Visual Studio but I'm getting the error: "System.Data.SqlClientException (0x80131904): Invalid column name 'is_computed'." Choosing another table or trying  "Script Database Schema" results in the same error.
### Further technical details
Toolbox version: 4.7.87.0
Database engine: SQL Server 2005
Visual Studio version: Visual Studio Ultimate 2013, version 12.0.21005.1 REL

Thank you for any help!
Cristina

**Comment by ErikEJ** [comment]
Unfortunately, the toolbox does not support SQL Server 2005 (and neither does Microsoft) - are you able to restore the db to a newer SQL version? Let me know if that is not possible, and I will look into a fix...

**Comment by ErikEJ** [comment]
Closing as I have not heard back, feel free to re-open if you want to respond.

**Comment by cris651** [comment]
Hello, I'm sorry - I had replied but for some reason I can't have my mails delivered directly to your address.
I was planning to move my databases to SQL 2008, so now I will do it and I hope I'll be able to use SQLCeToolbox.
Thank you very much for your precious work!
Best regards, Cristina

**Comment by ErikEJ** [comment]
Great, let me know if the Toolbox is not working with SQL Server 2008, and I will fix it!
