### ISSUE TITLE
SQLite standard data types.

### ISSUE THREAD

**Issue by bkboggy** [ErikEJ/SqlCeToolbox#37]
You've asked me to post this on GitHub as an issue today after I wrote my review and mentioned that I don't see some standard SQLite data types being listed.

Here's what I mean:
![testtable](https://cloud.githubusercontent.com/assets/5036152/13485837/6e8cf0cc-e0c0-11e5-821f-b00d4dc5f821.png)

SQLite has five standard data types: NULL, INTEGER, REAL, TEXT, BLOB

It has excellent type affinity support, but my workflow has been such that I got used to using the five data types I'm given by SQLite and I know which one I need to use when.  I don't use other datatype representations, because I don't need to. 

The list in that screenshot does not display 'text', unless it's the 'ntext'?  It also does not list 'blob'.  Frankly, there's no point displaying all the other datatypes, since SQLite will convert them all to one of the five available types, so in the end they're a bit pointless.   nvarchar can have a limit of 10 characters and based on affinity will become a TEXT, voiding the length restriction.  Everything's Unicode on top of that, so varchar or nvarchar... it doesn't matter at all in the end (unless, of course, you play with the preprocessor macros... but very few will).  Now... it's a good idea, perhaps, to have them, so that individuals who don't know how their datatype should be represented by SQLite would have an option, but.... that's not up to me to decide.

Anyways, this is a very minor thing, in my opinion, and does not detract from the wonderful quality of the product.

**Comment by ErikEJ** [comment]
I plan to make showing only sqlite datatypes optional, and default to the four sqlite datatypes only for new sqlite tables...

**Comment by ErikEJ** [comment]
@bkboggy I have added the suggested change to the latest daily build, could you try it out? https://sqlcetoolbox.codeplex.com/releases/view/619815

**Comment by zspitz** [comment]
@ErikEJ This doesn't seem to be working, even though I am [susbcribed to the daily build](https://github.com/ErikEJ/SqlCeToolbox/wiki/Subscribing-to-latest-"daily"-build).

**Comment by ErikEJ** [comment]
@zspitz  Works on my PC :-) - could you share a screenshot of what is "not working" ?

**Comment by zspitz** [comment]
@ErikEJ I'm sorry. Apparently I was missing a restart of Visual Studio or something, becuase now the list of types in the table designer shows the SQLite data types instead of SQL Server types.

**Comment by ErikEJ** [comment]
@zspitz No worries, happy it is working for you

**Comment by bkboggy** [comment]
@ErikEJ Sorry I didn't respond sooner; I received no notifications and just happened to remember today that I placed a ticket for this issue.  Is the fix included in the current stable release or should I download a daily build?  Looking at my current version (4.5.0.2), nothing has changed:

![sqlite](https://cloud.githubusercontent.com/assets/5036152/17942480/6418a982-69ec-11e6-9e99-1092b9e3b840.gif)

**Comment by ErikEJ** [comment]
@bkboggy Use the latest daily build, and let m know if it works as desired :smile:

**Comment by bkboggy** [comment]
@ErikEJ Yep, that worked.  Thanks!
