### ISSUE TITLE
SSMS 16.X Connection problem

### ISSUE THREAD

**Issue by jfbleach** [ErikEJ/SqlCeToolbox#373]
Describe what is not working as expected.
This is an error triggered by user error.  I went to add my first connection in SQLite/ SQL Server Compact toolbox and didn't realize that what I clicked was for adding a SQL Server connection.  Thinking it was a general purpose connection dialog I found the AttachDB property under advanced and put the path to my SQLite file.  When I clicked OK, of coarse it gave me an error - "A network-related or instance-specific error occurred while establishing a connection to SQL Server...".  Realizing my mistake, I went to delete the connection but the only option I see to delete a connection is "remove broken connections".  This option goes and tries to check connections which runs into an error and doesn't remove anything (throws same error as above but with full trace in a popup dialog which I just can't find a way to copy - only screen shot).  So then I try adding an actual SQLite connection and click the "Test Connection" which works and so I click "Close".  This runs into the original connection entry error, so now I have 2 connections listed with both displaying the network error.  I can't find any way to delete the connections and start over.  I tried a new SMSS project but the bad connections still show in the new project.   Is there a file I can go manually edit to get rid of these, because nothing is usable in the toolbox at the moment?

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)
4.7.168.0
Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3)
SSMS 16.5.3

**Comment by ErikEJ** [comment]
Could you attach a screen shot?

**Comment by ErikEJ** [comment]
As a workaround you can delete the SQLiteAddinStore.db in %localappdata% folder

**Comment by ErikEJ** [comment]
I was able to repro, and it is fixed in the latest daily build (so you can see and remove the invalid connection)

**Comment by jfbleach** [comment]
Yes this fixed my problem.  Thanks so much for your quick response.  Great job!
