### ISSUE TITLE
when opening old sdf files it refuses to open it but forces to convert it to format 4?

### ISSUE THREAD

**Issue by eino-makitalo** [ErikEJ/SqlCeToolbox#38]
Is this bug or feature?

**Comment by ErikEJ** [comment]
If it really is "Forces", it sounds like a bug - but could you please provide more info? 
Is the "old" file version 3.5 or 3.1, and if you can provide a screenshot, that would be great

**Comment by eino-makitalo** [comment]
Sorry, I realized that it "forces" because I used "Add Sql Server compact 4.0 Connection..." :-)
And "Add Sql Server compact 3.5 is grayed out" and can't be chosen.  Probably I have to install some package to my Visual Studio 2015 to be able to use 3.5 versions too...

I think this is not bug nor feature but stupid user :-D  (= me)

**Comment by ErikEJ** [comment]
You must install the SQL CE 3.5 SP2 runtime to Work with 3.5 files
