### ISSUE TITLE
cant install extension for SSMS

### ISSUE THREAD

**Issue by d7coders** [ErikEJ/SqlCeToolbox#382]
SSMS version 13.0.15000.23
![photo_2017-06-05_10-23-06](https://cloud.githubusercontent.com/assets/4857706/26772200/53ea85bc-49d9-11e7-9015-2dd3aec791ce.jpg)

log:
6/5/2017 10:22:18 AM - Microsoft VSIX Installer
6/5/2017 10:22:18 AM - —---------------------------------------—
6/5/2017 10:22:18 AM - Initializing Install...
6/5/2017 10:22:18 AM - Extension Details...
6/5/2017 10:22:18 AM -   Identifier         : d6c77c32-fe4b-4f6d-ad5d-f7b755212760
6/5/2017 10:22:18 AM -   Name               : SQL Server Compact/SQLite Toolbox for SSMS
6/5/2017 10:22:18 AM -   Author             : ErikEJ
6/5/2017 10:22:18 AM -   Version            : 4.7.176
6/5/2017 10:22:18 AM -   Description        : SQL Server Compact/SQLite Toolbox add-in for Visual Studio. This add-in adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
6/5/2017 10:22:18 AM -   Locale             : en-US
6/5/2017 10:22:18 AM -   MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
6/5/2017 10:22:18 AM -   InstalledByMSI     : False
6/5/2017 10:22:18 AM -   SupportedFrameworkVersionRange : [4.5,)
6/5/2017 10:22:18 AM - 
6/5/2017 10:22:19 AM -   SignatureState     : Unsigned
6/5/2017 10:22:19 AM -   Supported Products : 
6/5/2017 10:22:19 AM -     ssms
6/5/2017 10:22:19 AM -       Version : [13.0,15.0)
6/5/2017 10:22:19 AM - 
6/5/2017 10:22:19 AM -   References         : 
6/5/2017 10:22:19 AM -     —---------------------------------------------------—
6/5/2017 10:22:19 AM -     Identifier   : Microsoft.VisualStudio.MPF.14.0
6/5/2017 10:22:19 AM -     Name         : Visual Studio MPF 14.0
6/5/2017 10:22:19 AM -     Version      : [14.0]
6/5/2017 10:22:19 AM -     MoreInfoURL  : 
6/5/2017 10:22:19 AM -     Nested       : No
6/5/2017 10:22:19 AM - 
6/5/2017 10:22:19 AM - Signature Details...
6/5/2017 10:22:19 AM -   Extension is not signed.
6/5/2017 10:22:19 AM - 
6/5/2017 10:22:19 AM - Searching for applicable products...
6/5/2017 10:22:32 AM - Found installed product - Microsoft Visual Studio Enterprise 2015
6/5/2017 10:22:32 AM - Found installed product - Microsoft Visual Studio Professional 2015
6/5/2017 10:22:32 AM - Found installed product - Microsoft Visual Studio Community 2015
6/5/2017 10:22:32 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
6/5/2017 10:22:32 AM - Found installed product - Global Location
6/5/2017 10:22:32 AM - Found installed product - ssms
6/5/2017 10:22:32 AM - This VSIX manifest format is not supported.
6/5/2017 10:22:32 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by d7coders** [comment]
yes, same result

**Comment by ErikEJ** [comment]
Do you have VS 2015 Update 3 installed, or an earlier build?

**Comment by d7coders** [comment]
yes

**Comment by ErikEJ** [comment]
In other words, what version is your vsixinstaller.exe ?

**Comment by ErikEJ** [comment]
Could you try to update ssms to latest version?

**Comment by ErikEJ** [comment]
I mean 16.5.3 https://docs.microsoft.com/en-us/sql/ssms/previous-sql-server-management-studio-releases

**Comment by ErikEJ** [comment]
I am unable to repro, but I also have VS 2017 and SSMS 17 installed...

**Comment by ErikEJ** [comment]
Any update?

**Comment by d7coders** [comment]
No

On 7 Jun 2017 12:26 pm, "Erik Ejlskov Jensen" <notifications@github.com>
wrote:

Any update?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ErikEJ/SqlCeToolbox/issues/382#issuecomment-306719069>,
or mute the thread

**Comment by ErikEJ** [comment]
Did you try updating SSMS to 16.5.3 ?

**Comment by d7coders** [comment]
No , I am the mobile developer in the team, the server side team can't
update the ssms for some reasons

**Comment by ErikEJ** [comment]
Are you able to install the VS extension - and does that unblock you?

**Comment by d7coders** [comment]
Yes, but I couldn't work with it, I want to convert ms sql sever DB to
sqlite db, can I do that with the vs extension?

**Comment by ErikEJ** [comment]
Yes, of course you can!  Install it and let me know if you have trouble doing it

**Comment by John-Blair** [comment]
Doesnt work for me on SSMS version v17.8.1 , i have vs 2015 sp 3 update....no errors just doesn't work.

**Comment by John-Blair** [comment]
"Doesn't work for me" was all i had no evidence of failure but couldn't connect via the Connect button. However, doing further research it does now work for me via another path. I see the SQL Server Compact Toolbox appears under the View menu of SSMS. I had expected it to appear under File, Connect Object Explorer, Server Type. Anyway, now working for me in both VS 2015 and SSMS....may be worth highlighting the View access in SSMS....Thank you.

**Comment by ErikEJ** [comment]
Thanks - readme updated! https://github.com/ErikEJ/SqlCeToolbox#sql-server-management-studio-ssms-17x-extension
