### ISSUE TITLE
Error - Unable to find requested .Net Framework Data Provider

### ISSUE THREAD

**Issue by tip2tail** [ErikEJ/SqlCeToolbox#383]
Hi,

As I advised on Twitter, getting the following error.
![untitled](https://user-images.githubusercontent.com/1719754/27005688-584f8c7e-4e1b-11e7-93b6-ef7e7fddf1cf.png)

VS2017 was a new install.  Project was new as well.  Followed the guide at: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

GAC listing attached: [yourassemblies.txt](https://github.com/ErikEJ/SqlCeToolbox/files/1066071/yourassemblies.txt)

About info:
![2017-06-10_20-22-53](https://user-images.githubusercontent.com/1719754/27005711-c864b0ac-4e1b-11e7-9664-2acc1d9e8f7f.png)

My code at:
https://github.com/tip2tail/mvcs/tree/master/MVCS

Repo should be private will be going back to that ASAP.

Hope you can help!

**Comment by ErikEJ** [comment]
Remove the 3rd line in the DbProviders section in app.config, so it looks EXACTLY like the one in my wiki post

**Comment by tip2tail** [comment]
![2017-06-10_21-13-03](https://user-images.githubusercontent.com/1719754/27005975-f049afc2-4e21-11e7-83dc-31c9041b802d.png)

Sorry I don't understand - I just compared my app.config to the one listed on https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider.  The only difference is whitespace.  Removing that 3rd line would make my app.config DIFFERENT from yours.

Left is mine, right is yours from above page.

**Comment by tip2tail** [comment]
I removed that line anyway to try it - same error! :(

**Comment by tip2tail** [comment]
I have uninstalled and reinstalled everything (for the second time) and it's now working!  Who knows why!  Thank you anyway!

**Comment by relbraun** [comment]
@tip2tail @ErikEJ 
I have the same problem.
What did you re-installed? I tried it and still get this error

**Comment by MMovasaghi** [comment]
I have this problem too, Is there anyone who can solve this problem ?

**Comment by ErikEJ** [comment]
@MMovasaghi  Have you looked at https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider ?
