### ISSUE TITLE
Navigation tree refresh

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#387]
Think about a method to not always need to re-open the navigation tree after performing a refresh. I mean if I have opened a table object in a DB, it would be nice to have it re-opened afterwards unless it has disappeared (in the latter case just expand the parent - the current DB).

This would reduce many clicks and augment the usability of _SQLCeToolbox_ a lot.

### Steps to reproduce
/

### Further technical details
Toolbox version: 4.7.166.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
What do you propose I do if many items are expanded in the treeview?

**Comment by mwallnoefer** [comment]
I need to render this more precisely, my fault. This situation seems to happen only on trigger DDL operations. For instance if I add a trigger and had the _Triggers_ subitem of the table expanded, it would be nice to have it re-expanded after the refresh.
At the moment Toolbox refreshes correctly, opens the DB but does not expand the table and not its _Triggers_ subfolder. It would be nice to have at least the table expanded.

**Comment by ErikEJ** [comment]
What are "triggers" 😈  - OK, I understand better now... Feel free to do a PR!

**Comment by ErikEJ** [comment]
I have thought about this - I simply detect that some DDL has been run against the database, and I have no safe way of detecting any details about the DDL, so I can only refresh of database level (it could be a CREATE TABLE statement)
