### ISSUE TITLE
Find and replace not working

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#388]
It would be fine to have the find and replace feature (Ctrl+F/H) in the SQL edit windows working.

### Steps to reproduce
Open an edit window (_New query_).

### Further technical details
Toolbox version: 4.7.166.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by mwallnoefer** [comment]
Okay, the glasses show up and searches are working. A replace feature is not available, correct?

**Comment by ErikEJ** [comment]
That is correct
