### ISSUE TITLE
EF6 and Visual Studio 2017

### ISSUE THREAD

**Issue by Xan-Kun** [ErikEJ/SqlCeToolbox#389]
Hello and thanks for the great toolbox!
This is not really an issue, but a question, that could clarify if there is an issue or not :-)

I want to start simple: I would love to use Visual Studio 2017 in combination with SQLite.

Is that possible / advisable?

To be more precise:
I am aware that a lot changed with VS2017 and all tutorials I could find are for VS2015.
I could easily install SQLite (via nuget) and toolbox (via extensions) for a .NET framework application .
The database got crated with SQLiteConnection.CreateFile and I was able to use Open(), Close() and ExecuteNonQuery().
This is a very basic setup.

I was not able to get more than that. Most approaches failed because VS insisted that the database was corrupt (it wasnt!) or I simply got the "no provider found" dialog when trying to add a ADO.NET object.

It would be superb to have EF6 support and maybe Linq (I love linq :-) ). Which way (code first, database first, schema first) doesn't really matter.
The framework version I chose so far was 6.0. Would it be wiser to start with 4.5.1?
Are the core components necessary for a .NET framework project?

As you might see I am a little confused about what should work in which circumstances.

If it is possible to get it decently working, I would love to write a wiki article about how to get it up and running.

Also: Am I correct that there is no way to get the Designer working with VS2017 due to installer changes? All tutorials mention the extra installer (bundle) witht the componen for either 2013 or 2015.

**Comment by ErikEJ** [comment]
I already have a fix and a wiki article to cover that: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by Xan-Kun** [comment]
Hi ErikEJ and thanks for the answer! So it definately should work and it also makes sense to try! (Meaning: I am not going back to VS2013 so quickly :-) ). I know the article and try again, coming back with more precise information on where I got stuck.

**Comment by ErikEJ** [comment]
That would be great,then I can update the wiki post

**Comment by Xan-Kun** [comment]
I think after installing the GAC components, windows needs a reboot, but couldn't test it properly so far.
It seems to wokr to that point in the wiki but where to go on from there?
The next dialogue is the ADO.NET Wizard
![adonet_wizard](https://user-images.githubusercontent.com/11686614/27262737-58fc23f6-545d-11e7-876a-7ece284b6f53.png)
As I understand, "Code First from Database" needs the reverse poco extension installed, the two empty ones are unclear how to proceed and "EFDesigner from Database" needs an already existing database.

Which of these could work and how?

**Comment by Xan-Kun** [comment]
BTW, in the wiki article you also have "System.Data.SQLite Database file".
I do not see that option/provider.

**Comment by Xan-Kun** [comment]
If I create the DB first with the Toolbox, I get the following error message
![providernotfound](https://user-images.githubusercontent.com/11686614/27262803-92dac518-545e-11e7-9f79-4d9fe30afd18.png)

**Comment by ErikEJ** [comment]
>> As I understand, "Code First from Database" needs the reverse poco extension installed, the two empty ones are unclear how to proceed and "EFDesigner from Database" needs an already existing database.
Which of these could work and how?

EF designer from database and code first from database both work, based on an existing database file.

**Comment by Xan-Kun** [comment]
I just followed the video https://www.youtube.com/watch?v=sAAKu_SsaoA step-by-step and ran into the same error message about the provider.

**Comment by ErikEJ** [comment]
>> BTW, in the wiki article you also have "System.Data.SQLite Database file".
I do not see that option/provider.

I did the screenshots in VS 2015!

**Comment by ErikEJ** [comment]
>> If I create the DB first with the Toolbox, I get the following error message

Sounds like you did not follow the steps in the wiki post

**Comment by ErikEJ** [comment]
>> I just followed the video 

Yes, there is much misinformation on the Internet!

Closing, as I cannot see anything that I can take action on here, apart from the added clarification to the wiki post, feel free to re-open if you have anything to add

**Comment by Xan-Kun** [comment]
I suspect my VS2017 installation got corrupted with all the different installations and deinstallations. I will try with a fresh VM from scratch. Do you know which "workloads" I should check for installation?

**Comment by ErikEJ** [comment]
"Desktop Development"  I think

**Comment by Xan-Kun** [comment]
Hi Erik, just tried again to no avail. Either something crucial is missing in the steps of the wiki page or it simply doesn't work on VS2017. I am pretty sure one also needs to have at least some of the .Net core components and probably the compact server installer. I give up for now and will go back to VS2015, as everything works just fine there.
Thanks for your time, if you ever need more information and someone to try things out, I still got the VMs lying around and it would be a pleasure to help.

**Comment by Xan-Kun** [comment]
Funny: I just tried with a WPF application instead of Forms, and it looks much better :-)

**Comment by ErikEJ** [comment]
Great news - thanks for the update

**Comment by Xan-Kun** [comment]
It seems to be a problem with the core-dependecies. But it's working now well enough, thanks to you great toolbox (it greatly facilitates the workflow).
BTW, saw your video interviews on youtube: Well done!

**Comment by abdulalimmasud** [comment]
Hi Erik, I'm facing same problem now. Can you help me?

**Comment by iabesadze** [comment]
Hello,
vs2017 v15.5.6
ado.net model wizard not working

my app.config
```<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <!-- For more information on Entity Framework configuration, visit http://go.microsoft.com/fwlink/?LinkID=237468 -->
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>  
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6" />
  </startup>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="mssqllocaldb" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer" />
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
      <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
    </DbProviderFactories>
  </system.data>
</configuration>```

error
![er](https://user-images.githubusercontent.com/30433818/50337698-5d62cf00-052b-11e9-9a06-32fe55466c87.png)


Thank anymore, help my please

**Comment by ErikEJ** [comment]
@iabesadze  I will look into upgrading to .109, please create a new issue!

**Comment by iabesadze** [comment]
> @iabesadze I will look into upgrading to .109, please create a new issue!

Thank You
I created new issue
