### ISSUE TITLE
Enhance SQL CE DDEX provider(s) to support Data Source Configuration Wizard

### ISSUE THREAD

**Issue by hydroWIN** [ErikEJ/SqlCeToolbox#39]
When creating a report from scratch and I'm using C# by the way.
It either gets stuck by the add connection form or it allows me to use the connection but gives an error on the part were you select which table or view to use. 
Am I just using it wrong or is there another area specifically for SqlCe reports?
![image](https://cloud.githubusercontent.com/assets/17716496/13592097/f548bb28-e4bc-11e5-85ce-dcc37ecbc082.png)
![image](https://cloud.githubusercontent.com/assets/17716496/13592102/0e77abb8-e4bd-11e5-8a95-902d2582871b.png)

**Comment by ErikEJ** [comment]
The DDEX provider I supply is "simple" (as is stated in the name) - so it does not support the "Data Source Configuration Wizard" - but I leave this open to consider extending its functionality.

**Comment by hydroWIN** [comment]
Ok sounds good, thanks Erick. 
Would I be the first to bring up this problem with the data source wizard? Was there a suggested work around in the meantime and this is actually my first time using GitHub so is it possible to help establish a working data source?

**Comment by ErikEJ** [comment]
The suggested workaround is to create a DataSet in code, and bind that to the report.

**Comment by ErikEJ** [comment]
Have decided not to do this, but have changed the description of the DDEX providers to clarify missing support for Data Source Config Wiz

**Comment by ErikEJ** [comment]
How to solve this in code: https://blogs.msdn.microsoft.com/sqlforum/2011/04/27/walkthrough-assign-dataset-dynamically-created-in-code-to-your-local-report-with-reportviewer/
