### ISSUE TITLE
[SQLITE] Views: add Script as SELECT

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#397]
Add the _Script as SELECT_ option to be able to create a query on the base of the view (like on tables)

### Steps to reproduce
/

### Further technical details
Toolbox version: 4.7.166.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Please split into two issues, thanks!
