### ISSUE TITLE
[SQLITE] Views: show columns in the navigation tree

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#398]
Show the view's columns with their name and types as children of the view (like the table columns)

### Steps to reproduce
/

### Further technical details
Toolbox version: 4.7.166.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
@mwallnoefer Build 4.7.198 is now official on VS MarketPlace - thanks for you feature suggestions!
