### ISSUE TITLE
SQLite datetime values not edited in visual mode

### ISSUE THREAD

**Issue by amastaneh** [ErikEJ/SqlCeToolbox#40]
Value of datetime fields in Table Edit (Edit Top 200 Rows) of SQLite table will be back (not saved) in visual mode. For example if you change value of all fields and press save and refresh buttons in below screen datetime values not saved and back to old value.

![image](https://cloud.githubusercontent.com/assets/6195199/13696355/1493fd38-e77b-11e5-93f0-eb058ba8abb0.png)

**Comment by ErikEJ** [comment]
I have implemented a fix for this in the latest "daily" here: https://sqlcetoolbox.codeplex.com/releases/edit/619815 - please let me know if that fixes your issue (I have also added an option to bring back the current behaviour, when the Edit grid cannot display SQLite datetime values.

**Comment by amastaneh** [comment]
We use of latest updated version of Visual Studio Gallery
SQL Server Compact/SQLite Toolbox for Visual Studio
Version: 4.5.0.3

![image](https://cloud.githubusercontent.com/assets/6195199/13723060/608f0374-e86e-11e5-87c7-e3bb57ebe47b.png)

**Comment by ErikEJ** [comment]
You need to download a newer update from the link above to test the fix (version 4,5,0,4)

**Comment by amastaneh** [comment]
Dear @ErikEJ 
The [link](https://sqlcetoolbox.codeplex.com/releases/edit/619815) is notallowed for me 

![image](https://cloud.githubusercontent.com/assets/6195199/13770423/2e0296fc-ea9c-11e5-9141-d674c21ce4ff.png)

Is it possible to update your project in [Visual Studio Gallery](https://visualstudiogallery.msdn.microsoft.com/0e313dfd-be80-4afb-b5e9-6e74d369f7a1) for me and all other people :+1:

**Comment by ErikEJ** [comment]
I have updated the link!

**Comment by amastaneh** [comment]
After updating, we have this error after change of any field's values of some tables.
And i'm not sure that's related to this issue and i'm working on it.

![image](https://cloud.githubusercontent.com/assets/6195199/13869207/344f61be-ece7-11e5-9bfb-8b44acf21644.png)

**Comment by ErikEJ** [comment]
Did you try the new option? What is your data format for datetimes, and what is your connection string?
