### ISSUE TITLE
Can not build from source

### ISSUE THREAD

**Issue by Makeshet** [ErikEJ/SqlCeToolbox#402]
I download the source and try to build your wonderfull toolbox as stand alone application with VS 2015.
There is an error that I can not figure out about  import the following key file:
Below in the output window.
Can you take a look and try to guess what I am missing?
Many thanks in advance:
E. Kaplansky 

1>------ Rebuild All started: Project: SqlCeToolbox.Common, Configuration: Debug x86 ------
1>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.CSharp.CurrentVersion.targets(133,9): warning MSB3884: Could not find rule set file "MinimumRecommendedRules.ruleset".
1>  SqlCeToolbox.Common -> H:\SQL_Samples\Sql_Ce_Toolbox\SqlCeToolbox-3.7.2.0\src\GUI\SqlCeToolbox.Common\bin\x86\Debug\SqlCeToolbox.Common.dll
2>------ Rebuild All started: Project: SqlCe40ToolboxExe, Configuration: Debug x86 ------
2>  Consider app.config remapping of assembly "System.Data.SqlServerCe, Culture=neutral, PublicKeyToken=89845dcd8080cc91" from Version "3.5.1.0" [C:\WINDOWS\assembly\GAC_MSIL\System.Data.SqlServerCe\3.5.1.0__89845dcd8080cc91\System.Data.SqlServerCe.dll] to Version "4.0.0.0" [C:\WINDOWS\assembly\GAC_MSIL\System.Data.SqlServerCe\4.0.0.0__89845dcd8080cc91\System.Data.SqlServerCe.dll] to solve conflict and get rid of warning.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(1820,5): warning MSB3276: Found conflicts between different versions of the same dependent assembly. Please set the "AutoGenerateBindingRedirects" property to true in the project file. For more information, see http://go.microsoft.com/fwlink/?LinkId=294190.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2884,5): warning MSB3327: Unable to find code signing certificate in the current user’s Windows certificate store. To correct this, either disable signing of the ClickOnce manifest or install the certificate into the certificate store.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2884,5): error MSB3326: Cannot import the following key file: . The key file may be password protected. To correct this, try to import the certificate again or import the certificate manually into the current user’s personal certificate store.
2>C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(2884,5): error MSB3321: Importing key file "SqlCe40ToolboxExe_1_TemporaryKey.pfx" was canceled.
========== Rebuild All: 1 succeeded, 1 failed, 0 skipped ==========

**Comment by ErikEJ** [comment]
Try to get the latest source, I have attempted to fix

**Comment by Makeshet** [comment]
Hi Erik

Now it is working!
**Thanks you very very much.**

E. Kaplansky PhD
CTO
Makeshet Information Systems
