### ISSUE TITLE
Can not find started guide for Stand alone or SSMS 2016

### ISSUE THREAD

**Issue by Makeshet** [ErikEJ/SqlCeToolbox#404]
Hi Erik

Thanks you for wonderful product.
My main need  is to manage SQLIte databases.
I succeed to build the stand alone product and install your extension into SSMS 2016.

However, I search your belog and can not find any belog 
for using your product with a  Stand alone or SSMS 2016 that enable one to create a new SQLite
database and manage it.
Can you please point me to one such belog?
Thanks a lot

E. Kaplansky

**Comment by ErikEJ** [comment]
There are a number of resources here: https://github.com/ErikEJ/SqlCeToolbox/wiki - the standalone edition is not available for SQLite

**Comment by Makeshet** [comment]
Hi Erik
Sorry for being unclear.
I watch the videos and read many of you belogs.

But the videos are about using the product from Visual Studio and not from SSMS 2016.
Is there a started guide or a video for using the toolbox on SSMS 2016?
For example: How one can create a new SQLite database from  SSMS 2016?
What I had miss in the  https://github.com/ErikEJ/SqlCeToolbox/wiki?

Thanks a lot
E. Kaplansky

**Comment by ErikEJ** [comment]
The SSMS and VS extensions both work the same way - Right click or use the Toolbar buttons to connect to a SQLite db, select "Create", and specify file path and name, then use CREATE TABLE or the table designer to create tables

**Comment by Makeshet** [comment]
Hi Erik

It seems to me that maybe there is a installation problem:
In SSMS 2016 I do not see on what UI element I can do the "Right click"?
Also I can not see any new Toolbar  button.
I know that your extension was been install because I can see a new section in the option menu.
So, where in the SSMS 2016 I can do the Right click"?
Tanks a lot for your patience but I spend few hours in order to find out by myself and failed.

E. Kaplansky

**Comment by ErikEJ** [comment]
No worries - did you actually read the wiki link I posted above? "Congratulations, you have now installed the add-in. To start using it in Visual Studio, launch the Toolbox from the button in Server Explorer, or from the Tools menu **(View menu in SSMS)**:"

Or you can to go to Tools, Other Windows
Or you can type "Toolbox" in the quick launch box.

Let me know if that works for you!

**Comment by Makeshet** [comment]
YES! YES! YES!
That part  (View menu in SSMS) is the item i had miss for so many hours.
Thanks you very very very much.
On this happy moment, can you tell me:
If I have the full source code complied and runs, how it happens that the stand alone app
does not SQLite?
Is it something that if I work a bit by myself I can contribute?
Tanks a lot!
Wonderful work!
E. Kaplansky

**Comment by ErikEJ** [comment]
Originally, I did not support SQLite at all, and the reason for the existence of the standalone editions for SQL Server Compact was that the free "VS Community" edition was not available then. Given that I have support for both SSMS and VS (both free applications), I would rather not spend time on a standalone SQLite edition - I have actually not updated the standalone editions with any new features in a long time, and consider dropping them all together - and there are other standalone tools for SQLite.
