### ISSUE TITLE
Can not use copy and paste in SSMS 2016

### ISSUE THREAD

**Issue by Makeshet** [ErikEJ/SqlCeToolbox#405]
![can_not_save](https://user-images.githubusercontent.com/500151/27556259-83d12412-5abd-11e7-8335-ffcc01e7c6b0.PNG)

Hi Erik

I can not use copy and past in SSMS 2016.
It ask me to save the file before use Ctrl C.
I save the file many time and it still complain about it.
I hope you can see the error massage in attached file.
Any advice?
Thanks a lot.
E. Kaplnasky

**Comment by ErikEJ** [comment]
Check out the known issues: https://github.com/ErikEJ/SqlCeToolbox/wiki/Known-issues#ssms-error-message-unsaved-documents-cannot-be-cut-or-copied-to-the-clipboard-from-the-miscellaneous-files-project

**Comment by IT-CASADO** [comment]
It's year 2023 and this annoying issue still exists :(

Why is this ticket closed? Is that the reason that this isn't fixed? What has cutting & copying in Search & Replace to do with unsaved documents?

Would love to see this fixed.

**Comment by ErikEJ** [comment]
Did you try the workaround mentioned in the "Known issues" ?

**Comment by IT-CASADO** [comment]
Yes I tried it (and it is working).

But why do we have such an option, if we cannot use it, because of this issue. This ticket needs to be re-opened.

**Comment by ErikEJ** [comment]
If you have a fix for this feel free to submit a PR

**Comment by IT-CASADO** [comment]
Sorry Erik, the title of this issue moved me into the wrong direction. I thought, this repository is about SQL Server Management Studio (SSMS).

Just for references: https://feedback.azure.com/d365community/idea/55c5d7b4-5125-ec11-b6e6-000d3a4f0da0
