### ISSUE TITLE
Compact 4.0 Databases not working

### ISSUE THREAD

**Issue by dlaukamp** [ErikEJ/SqlCeToolbox#406]
As of version Release 4.7.198 I cannot query SQL Server Compact 4.0 Databases, the query window simply does not open. I also can't remove any existing connections, I get the error:

```
SQLite/SQL Server Compact Toolbox

The DDEX provider is not installed, cannot remove connection
```

Which is also confirmed in the about tab:

```
Version 4.7.204.0 - 717.248 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No
```
I'm not sure whether this provider is just not recognized correctly any more or whether I suddenly need to install new software. I'm using Visual Studio 2015.

**Comment by ErikEJ** [comment]
How do you launch the query window?

Can you remove the invalid connections in Server Explorer/Data Connections?

**Comment by dlaukamp** [comment]
I open the Toolbox from the Menu and launch the Query from the Context Menu of the entry in the Data Connections list.

I can delete the invalid connection using the Server Explorer, the error message I posted is triggered from the same Context Menu I use to launch the Query Window.

**Comment by ErikEJ** [comment]
So you right click the connection, and select "New Query" - and no query window opens - is that correctly understood?

What happens when you select: "Database Information" menu item?

**Comment by ErikEJ** [comment]
Have you tried restarting VS?

**Comment by dlaukamp** [comment]
Correctly understood. Clicking on "Database Information" has the same effect - no window is opened (though I don't remember what used to happen here). When clicking on this item, Visual Studio gets unusable for a couple seconds though, so it is doing something.

When I add a new connection and I click the "Test Connection" button, I get the usual "Connection OK!".

I did restart VS and reinstalled the extension. All my colleagues have the exact same issue.

**Comment by ErikEJ** [comment]
Sadly, I am unable to repro!

**Comment by ErikEJ** [comment]
I saw build 204 - are you running build 204 or 198

**Comment by dlaukamp** [comment]
I upgraded from 198 to 204 hoping to solve the problem like this but it is happening with either build.

Too bad, that you cannot reproduce it (thanks for trying so quickly, anyway). Could you clarify what seems to be the problem on my end? Like, do I actually need the (non-simple) DDEX provider for what I'm trying to do and what package am I supposed to get it from?

**Comment by ErikEJ** [comment]
I have created a newer build, with some debugging message boxes - could I ask you to try that out?

**Comment by dlaukamp** [comment]
On it!

**Comment by ErikEJ** [comment]
Thanks! I have pushed another build with more debug messages... Could you show me the properties window for the database(s) where this happens? And does this also happen for a SQLite db?

**Comment by dlaukamp** [comment]
"Launch -4" is the only debug message for opening the query window now.

Properties (Assuming the one from the Server-Explorer is meant?):
![grafik](https://user-images.githubusercontent.com/18443156/27588232-c0b4ac98-5b47-11e7-879f-2a1420799fc9.png)

Will try SQLite db later, don't have any lying around right now.

**Comment by ErikEJ** [comment]
Thanks for you debugging help so far, I will try to dig deeper!

**Comment by dlaukamp** [comment]
Just tried an SQLite Database: Works flawlessly. Debug Messages popping up from -4 to -8 and finally the Query Window opens.

**Comment by ErikEJ** [comment]
1: Do you know which version of the Toolbox you were using before the latest update?

2: With Properties, I mean the information displayed in the Properties window, when the database is selected in the Toolbox.

3: Can you open the database, and see tables, columns etc?

**Comment by dlaukamp** [comment]
1: Since VS is set to auto-updating all extensions, I used the .87 till last Friday.
2:
![grafik](https://user-images.githubusercontent.com/18443156/27622700-f7c6c02c-5bd8-11e7-9e71-c5e0dbe804f5.png)
3: Yes, I can browse the tables and columns. All the "View Data As Report", "Rename", etc. options don't do anything, though.

**Comment by ErikEJ** [comment]
Attaching build 87 for you to confirm that it works for you (to confirm that the issue is caused by changes in latest build) 
Procedure: Rename to .vsix, uninstall current, and double click)

[SqlCeVsToolbox.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1107972/SqlCeVsToolbox.zip)

**Comment by dlaukamp** [comment]
Works like a charm! I can remove connections, query, ...

The entries in the "About"-Tab of the Toolbox haven't changed - still no DDEX provider, only the Simple [...] version.

**Comment by ErikEJ** [comment]
Thanks for your continued help with this - I have a hunch now about the issue - could I ask you to try the latest daily build ?  (.208 or later)

**Comment by dlaukamp** [comment]
You got it! I can open and use the Query Window in .208. When trying to remove a connection, there is still this error:

```
---------------------------
Microsoft Visual Studio
---------------------------
SQLite/SQL Server Compact Toolbox

The DDEX provider is not installed, cannot remove connection
---------------------------
OK   
---------------------------
```

**Comment by ErikEJ** [comment]
The DDEX error message is completely unrelated, I will look into it.

Are you running VS in Debug mode when using the Toolbox to query?

**Comment by dlaukamp** [comment]
Yes, I do.

**Comment by ErikEJ** [comment]
Aaah!

**Comment by ErikEJ** [comment]
Both your reported issues have been fixed in the latest daily build - thanks for all your help, and for reporting this!

**Comment by dlaukamp** [comment]
Confirming, everything is working fine again.

Thanks for responding and fixing things so quickly!

**Comment by ErikEJ** [comment]
@dlaukamp If you like my free tools, I would be very grateful for a rating or review here from you and your colleagues! 😄 
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
