### ISSUE TITLE
file is encrypted or is not a database

### ISSUE THREAD

**Issue by bhagwatposane** [ErikEJ/SqlCeToolbox#410]
Export2SQLCE.exe "Data Source=10.20.2.93;Initial Catalog=xyz;User Id=test;Password=abc" Northwind.db sqlite exclude:dbo.gdt,dbo.gfd

when I run this command on command prompt Northwind.db file is get created but when I try to access this file like

con = sqlite3.connect("Northwind.db")
p2=sframe.SFrame.from_sql(con,'select * from Elements')

I get this error : file is encrypted or is not a database
Please help

**Comment by ErikEJ** [comment]
You are creating a script, not a SQLite database file!
Use:

    Export2SQLCE.exe "Data Source=10.20.2.93;Initial Catalog=xyz;User Id=test;Password=abc" Northwind.sql sqlite exclude:dbo.gdt,dbo.gfd  

and then:

    sqlite3 chinook.db < chinook.sql

**Comment by bhagwatposane** [comment]
can you please explain sqlite3 chinook.db < chinook.sql

**Comment by bhagwatposane** [comment]
I am doing the same thing using SQLite & SQL Server Compact Toolbox from visual studio
when I do migrate to Sqlite it is directly creating .db file.
can I create .db file from above command ?

**Comment by ErikEJ** [comment]
Yes, the GUI tool creates the db for you, the command line tool does not, you must use a two step process, as I wrote above.

See my blog post here for infor about sqlite3.exe : http://erikej.blogspot.dk/2012/08/exporting-sql-server-compact-to-sqlite.html

**Comment by bhagwatposane** [comment]
ok.. thank you for your kind help.
