### ISSUE TITLE
No button in VS2017 in Server Explorer

### ISSUE THREAD

**Issue by jaquesburger** [ErikEJ/SqlCeToolbox#414]
I've installed the extention, It works in SSMS 17, but for some reason I don't have the button in Server Explorer on VS2017. Is there something that I can do to make the button available in VS2017?

I've downloaded the version from market place this morning again, but when I install, it just say that it is installed on all applicable products.

Thanks
Jaques

**Comment by ErikEJ** [comment]
Check that the extenison is enabled (In Tools, Extensions and Updates) - you can also start via Tools menu

**Comment by jaquesburger** [comment]
Hi Erik,

It was disabled, The funny part is that I didn't disable it. I enabled it now, restarted my VS, but it disable itself.

So I've uninstalled it, but PerfWatson2.exe was blocking it, so I had to go kill it manually in Task manager, and then it uninstalled fine. I've installed it again, and it is back now.

Thanks
Jaques
