### ISSUE TITLE
SQLite Index statistics do not work

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#419]
The SQL script created by _Script as Statistics_ on the index' context menu does not work on SQLite since it is based on proprietary SQL CE sp_* stored procedure calls.

### Steps to reproduce
Open some table index' context menu

### Further technical details
Toolbox version: 4.7.198.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Thanks for your continuing effort to improve the Toolbox SQLite support! As you can see from the release notes, many SQLite improvements have been made recently! https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by mwallnoefer** [comment]
Its due to our intensive use of SQLite as embedded DB on applications, devices and apps :).

One important thing which the tool is lacking is a comprehensive ALTER TABLE support, but on the other hand I think that it won't be easy to achieve. A first step of this task would be the possibility to add a new column.

**Comment by ErikEJ** [comment]
Nice to hear that you find my little tool helpful! Sadly, SQLite does not support ALTER TABLE, so you will have to go through hoops to do that! Suggest you file an issue for it, it might be possible to generate some useful script to do it.
