### ISSUE TITLE
Feature: ALTER TABLE support

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#422]
It would be nice to have at least some basic ALTER TABLE support in SqlCe Toolbox. SQLite for instance provides a limited [ALTER TABLE implementation](http://www.sqlite.org/lang_altertable.html) which allows appending new attributes to an existing table. It would be nice to have this better integrated within the UI (context menu option?)

Unfortunately I never worked with SQL CE so I don't know if it supports something similar or not.

This issue is more about a discussion, not a real bug.

### Steps to reproduce
/

### Further technical details
Toolbox version: 4.7.198.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Great idea - SQLCE already has a UI for this in the Toolbox - I will enable also for SQLite
