### ISSUE TITLE
Create Index without table suffix 

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#424]
The _Script as CREATE_ and the DB export commands shouldn't generate CREATE INDEX commands with the index name suffixed by the table name. In other words an index called `idxRankings` shouldn't become `idxRankings_Rankings` at least in SQLite (don't know if it makes sense in SQLCE though).

### Steps to reproduce
_Script as CREATE_ on index' context menu or the _Script Database_ commands.

### Further technical details
Toolbox version: 4.7.198.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
So a sqlite index name is unique across the entire database?

**Comment by mwallnoefer** [comment]
Yes, true.

**Comment by ErikEJ** [comment]
Hmm... I wonder why I have implemented this, then:

           if (_sqlite)
                   indexName = idx.IndexName + "_" + idx.TableName;

**Comment by mwallnoefer** [comment]
According to me this is unnecessary. If you drop me this code piece in the daily build I may test it and give you feedback.
