### ISSUE TITLE
Standalone daily build works, gitHub download doesn't (V4 toolbox)

### ISSUE THREAD

**Issue by ReyCBX** [ErikEJ/SqlCeToolbox#425]
Describe what is not working as expected.
Downloaded the standalone toolbox for both V3.5 and 4 and any attempt to add a field after the db is created fails w/attached file displayed. However, downloaded the daily build from the AppVeyor link and was able to add fields and then click the script btn to create the table.
This is on a 64bit box w/Win7 Pro. At home, on an XP sp3 box had no problems when I downloaded the standalone V4 toolbox and used it last year.
![v4_toolbox_err](https://user-images.githubusercontent.com/30509202/28690432-065493e2-72ce-11e7-9af1-190a46878bab.png)

Thanks, Rey

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)
V 3.7.20 standalone
![image](https://user-images.githubusercontent.com/30509202/28690614-ac704924-72ce-11e7-83f1-5abaef714b47.png)

The daily build version from AppVeyor does work.
![image](https://user-images.githubusercontent.com/30509202/28690683-edb547b8-72ce-11e7-853e-58b28798b6ab.png)

Database engine: (SQlite, SQL Compact or SQL Server)
sql compact
Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3)

**Comment by ErikEJ** [comment]
Where is the "Github download" located?

**Comment by ErikEJ** [comment]
Found it - I have removed the link to the Github release..
