### ISSUE TITLE
Correctly support SQLite unnamed indexes

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#429]
As a follow-up of issue #424 I am reporting another issue regarding to SQLite indexes. SQLite supports both named and unnamed indexes.

As far as I can tell SqlCeToolbox currently does not interpret the unnamed indexes correctly. Let me show some example:

This is the definition of a certain _Settings_ table in the command line tool sqlite3:
```
sqlite> .dump Settings
CREATE TABLE [Settings](
    [idSetting] uniqueidentifier CONSTRAINT [sqlite_autoindex_Settings_1] PRIMARY KEY NOT NULL, 
    [idRace] uniqueidentifier NOT NULL REFERENCES Races([idRace]) ON DELETE CASCADE ON UPDATE NO ACTION, 
    [ParameterName] text NOT NULL, 
    [DataValue] text NOT NULL, 
    UNIQUE([idRace], [ParameterName]) ON CONFLICT REPLACE);
```
And this is SqlCeToolbox's output of the same (command _Script as CREATE_):
```
CREATE TABLE [Settings] (
  [idSetting] uniqueidentifier NOT NULL
, [idRace] uniqueidentifier NOT NULL
, [ParameterName] text NOT NULL
, [DataValue] text NOT NULL
, CONSTRAINT [sqlite_autoindex_Settings_1] PRIMARY KEY ([idSetting])
, FOREIGN KEY ([idRace]) REFERENCES [Races] ([idRace]) ON DELETE CASCADE ON UPDATE NO ACTION
);
CREATE UNIQUE INDEX [sqlite_autoindex_Settings_2] ON [Settings] ([idRace] ASC,[ParameterName] ASC);
```
The differences:
- The explicit _CREATE UNIQUE INDEX_ instruction needs to be transformed in an implicit _UNIQUE_ clause which is part of _CREATE TABLE_
- The _ON CONFLICT_ resolution should be reproduced as well, but it is only permitted in the implicit _UNIQUE_ clause (http://www.sqlite.org/lang_createtable.html); NOT in the explicit _CREATE UNIQUE INDEX_ instruction (http://www.sqlite.org/lang_createindex.html). This is a SQLite inconsistency by design and at the moment it's perfectly valid to not make it show up in the _CREATE UNIQUE INDEX_ line.
- At the end please re-check the _Script as CREATE_ and _Script as DROP_ commands in the index' context menu.

(I know it's cumbersome, but this is how SQLite works)

### Steps to reproduce
/

### Further technical details
Toolbox version: 4.7.198.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Putting on the backlog for now, as the only missing part appears to be: ON CONFLICT REPLACE

**Comment by mwallnoefer** [comment]
One problem with the current situation is that a command like `CREATE UNIQUE INDEX [sqlite_autoindex_Settings_2] ON [Settings] ([idRace] ASC,[ParameterName] ASC);` does not work directly, since the index name is reserved.

**Comment by ErikEJ** [comment]
Hmm.. Need to give this some thought - sounds like UNIQUE and PRIMARY KEY "indexes" should not be considered as such at all.
