### ISSUE TITLE
Support for renaming indices

### ISSUE THREAD

**Issue by nicolasr75** [ErikEJ/SqlCeToolbox#43]
I'm not sure how much effort this would be but it would be great to be able to rename indices. 
It is not the first time that I had to dramatically redesign an existing database that already contained a lot of data in it.
SqlCeToolbox allows me to rename tables but most times the index names contain the table name too and for consistency I would like to rename these too.
SDViewer is able to rename indices but seems to crash (or at least take very very long) when I try to rename a table because it always seems to want to display the all (!) records.
At the moment I must use both programs. It would be very convenient to do it all with SqlCeToolbox.

**Comment by ErikEJ** [comment]
You could use the Script as DROP and Script as CREATE features in order to rename a table

**Comment by nicolasr75** [comment]
Thanks Erik. I don't understand though, as I wrote I do rename tables with SqlCeToolbox. What is missing for me is the ability to rename indices as is possible in SDViewer.

**Comment by ErikEJ** [comment]
Yes, but unlike table rename SQL Server Compact does not support rename of any other object types, including column and index names

**Comment by nicolasr75** [comment]
Ah, good to know. Thanks. Then I will have to do it via exporting the data, recreating the table and reimporting the data. I guess that is what SDViewer is doing because it takes so long for the renaming.

**Comment by ErikEJ** [comment]
You can just drop and rebuild the index...

**Comment by nicolasr75** [comment]
Of course that's much easier. Thanks.
