### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tasher05** [ErikEJ/SqlCeToolbox#430]
There is no issue. Only way I could find to ask your advice. I am trying to develop a sync between SQLExpress 10 and Sqlite. I have research a ton of different options. I love your tools and you seem to be an expert on Sqlite and DB's. So I would like to get your take on the best way to accomplish this task. I am using EFcore and have change tracking running on the sqlexpress db. I am possibly wanting to use the sync framework, but I can't find any good up to date examples for reference. Any help and guidance would be awesome.

**Comment by ErikEJ** [comment]
You could consider Zumero: http://erikej.blogspot.se/2014/04/an-alternative-to-merge-replication.html

**Comment by Tasher05** [comment]
Ya looked at that didn't want to fork that much out. There needs to be a bare bone-get started-open source project. That you can build on and not have to pay for. Basically Sync Framework, but current. Anyway thanks. Thought I would ask.
