### ISSUE TITLE
Migrate SQLCE Db to SQLServer throws IO error

### ISSUE THREAD

**Issue by DrewMann** [ErikEJ/SqlCeToolbox#434]
Trying to use the option in SQLLite Toolbox for visual studio to migrate a connected SQLCE Db to SQL Server.  We get the following error:. The migration starts and creates 1 table then this error is thrown.

The folder referenced c:\projects\... does not exist on our machine?  

![image](https://user-images.githubusercontent.com/16741567/29202297-6203ce48-7e99-11e7-8b16-ffae3e168c22.png)

## SQLIte Information

Version 4.7.232.0 - 728,190 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider - Yes

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - Yes

SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No

**Comment by ErikEJ** [comment]
Thanks for reporting this!

This is fixed in the latest daily build, please let me know if the fix works for you

**Comment by DrewMann** [comment]
Hi Eric,
thank you so much for your prompt response.  The daily update did the
trick!  Well done!

Cheers

Andrew

**Comment by ErikEJ** [comment]
Thanks, I will also update marketplace, this is a major bug!
