### ISSUE TITLE
Errors when using Visual Studio 2013 Community

### ISSUE THREAD

**Issue by seanrobertwright** [ErikEJ/SqlCeToolbox#44]
Hi,
I installed the add-in and everything seems to work fine, just as in your video. I am using SQLite 3 for a WPF project.  When I right click on my database and select 'Add sql-net DataAccess.cs to current project..' the class file is full of errors:

First:
using SQLite;  <---- **The** type or namespace 'SQLite' cannot be found (I resolved this by using System.Data.SQLite, is this **correct?)**

Second, in the Create() method:
db.CreateTable<xxx>(); <---- **System.Data.SQLIte.SQLiteconnection does not contain a definition for **'CreateTable'**

Third, in all the generated partial classes:
**The type or namespace name 'PrimaryKeyAttribute' could not be found (are you missing a using directive or an assembly reference?)**
Same goes for [NotNull], [Unique], and [MaxLength()]

Am I not adding a reference to the proper assembly?

**Comment by ErikEJ** [comment]
This is not for use with System.Data.SQLite - use this: https://www.nuget.org/packages/sqlite-net/ - do you have the latest version of the Toolbox installed? I think I have added some comments to the to of DataAccess.cs with details regarding this?

**Comment by seanrobertwright** [comment]
Thanks for this tip, it was not clear which library to use with the toolkit.  Now things are working fine, but I do notice that the toolbox does not work with the Dataset Designer.  Do you have plans to implement this?

**Comment by ErikEJ** [comment]
I thought I had put some comments at the top of DataAccess.cs?

Re DataSet designer - do you mean for sqlite or sql ce? For sqlite, that should be part of the sqlite vs tooling, which I do not provide...
