### ISSUE TITLE
Create "EF Core Power Tools" 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#445]
Why:
- Avoid making VS SQLite Toolbox depend on .NET 4.6.1 (.NET Standard 2.0) 
- More focus on EF Core than the specific databases
- Initial support for SQLCE 4, SQL Server/Azure SQL and SQLite
- Open up for additional features beyond Rev Eng
- For VS 2017 only

- [x] Icon
- [x] Link to relevant wiki page from extension manifest
- [x] Update of root readme.md
- [x] Ensure publish to vsixgallery
- [x] Add content to dedicated wiki page
- [x] Preview image (in package)

**Comment by ErikEJ** [comment]
List DDEX connections: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/Helpers/DataConnectionHelper.cs#L34

Prompt for and save  new DDEX connection: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/Commands/DatabasesMenuCommandsHandler.cs#L82

**Comment by julielerman** [comment]
The only feature I use but am DYING without it for EF Core is the model visualization. At this point I don't care if its not cross-platform. :)

**Comment by ErikEJ** [comment]
@julielerman Hi Julie, I have logged: https://github.com/ErikEJ/SqlCeToolbox/issues/462 - maybe you could add a couple of words about your "vision" for this, considering that EDMX is dead?
