### ISSUE TITLE
SQL CE TSQL commands ?

### ISSUE THREAD

**Issue by vbcodec** [ErikEJ/SqlCeToolbox#46]
I need to pass SQL commands (select, update, delete) to sql ce database (sdf) on phone 8.1 app. Is that possible ? Maybe there are some net libraries or via COM access (if possible on phone) ?

**Comment by ErikEJ** [comment]
No, you can only use LINQ to SQL - could you describe why you require this, and why the LINQ to SQL inteface would not work for you?
