### ISSUE TITLE
[EF Core Power Tools] Model visualizer

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#462]
https://github.com/ErikEJ/SqlCeToolbox/issues/445#issuecomment-326670723 

- [x] Gather sample DebugView (from various existing dbs) for testing, and add test project - use MSTest 
- [x] Create DebugViewParser, that returns DGML fragments: Model, Entities and ForeignKeys
- [x] Create DgmlComposer, that gather output from parser and produces a DGML doc
- [x] Add button and command "View Model as DGML Graph (alpha)"
- [x] Create handler method in ModelAnalyzer
- [x] Return doc to Extension, and open in VS (like in VS Toolbox, but do not prompt to save)
- [x] Add foreign keys
- [x] Add property annotations
- [x] Add Name model property to Entity and Property
- [x] Add missing productVersion value

**Comment by julielerman** [comment]
If this is for VS2017, is it possible to trigger the modelbuilder to read the EF Core model and display it in the EF6 designer?

**Comment by ErikEJ** [comment]
No, the EF6 DbContext and EF Core DBContext classes are too different/incompatible

**Comment by julielerman** [comment]
fair enough and good to know for avoiding wasting time on that path. Brice Lambson did some initial work on a NEW visualizer (xplat) a few years ago but hasn't picked it up again AFAIK. There is the debug info that you can see the model as text (only in VS so far, not VS Code), but that's all we got so far.

**Comment by ErikEJ** [comment]
>> There is the debug info that you can see the model as text (only in VS so far, not VS Code), but that's all we got so far. 

That sounds interesting...

**Comment by julielerman** [comment]
https://blog.oneunicorn.com/2016/11/17/ef-core-1-1-looking-at-your-model-in-the-debugger/  and 
my (unanswered) questions about it: https://twitter.com/julielerman/status/895740702935719936  , https://twitter.com/julielerman/status/895744823403192320

**Comment by ErikEJ** [comment]
@julielerman - Maybe I could start by:
1: Add additional menu item: Show DebugView
2: re-use EF6 PowerTools code to discover a DbContext in the selected project (handle multiple DbContexts later)
3: Use the EFCore.Design tools to get the DbContext simply based on name
4: Dump DebugView.View to a txt file and open it.

Later: Create a DebugView parser to construct a graph document (DGML?) and show this

PRs accepted!

**Comment by julielerman** [comment]
clever workflow.

**Comment by ErikEJ** [comment]
Current blocker: Activator.CreateInstance => Cannot load assembly 'C:\USERS\ERIK\APPDATA\LOCAL\MICROSOFT\VISUALSTUDIO\15.0_C5B80852EXP\EXTENSIONS\ERIKEJ\EF CORE POWER TOOLS\0.1.0\Microsoft.EntityFrameworkCore.dll'.

**Comment by ErikEJ** [comment]
@julielerman Model "dump" now works - paving the way for creating a graph similar to what I do now for the database schema in my Toolbox (using DGML), but for the model graph instead

**Comment by julielerman** [comment]
you are amazing! Can't wait to check it out.

**Comment by ErikEJ** [comment]
@julielerman Let me know if you encounter any issues, it is early days

**Comment by ErikEJ** [comment]
DGML links: https://en.wikipedia.org/wiki/DGML

**Comment by ErikEJ** [comment]
Adding sample DGML file (based on database schema, not EF model)
[graph.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1287551/graph.zip)

**Comment by ErikEJ** [comment]
Remaining issues are logged here: https://github.com/ErikEJ/SqlCeToolbox/issues/488
