### ISSUE TITLE
LINQ to SQLite DataContext Support

### ISSUE THREAD

**Issue by CincySteve** [ErikEJ/SqlCeToolbox#47]
Eric - 
I've written a block of C# code that generates in C# a strongly-typed LINQ DataContext with its associated Entity classes based on the schema in a SQLite database the Toolbox creates.   I spent a few minutes rattling around in the GitHub Toolbox repository to figure out how to contribute it, but don't have time to figure out how to integrate it into your code (if that's even appropriate to attempt).  I would be happy to contribute the code if you would be interested in wiring it in.  In my view, it would integrate as another right-click option on the database, mirroring the "Add SQLite-net DataAccess.cs to current Project..." option.  Please let me know if you are interested and willing to tell me how to post it.
Thanks.  Steve
P.S.  I've never done this type of thing before and thus am not sure how to go about it.  Apologies if this isn't appropriate.

**Comment by ErikEJ** [comment]
That sounds excellent - suggest you start by sharing your Tool, then I will evaluate and potentially "wire" it in! Thanks for the contribution so far!

**Comment by CincySteve** [comment]
I'm not able to attach a C# code file to this comment, so I'll need some guidance on how to contribute it.  

Things to note once I can contribute it:

1.  I've highlighted a couple places where you will need to change things to incorporate the code into the Toolbox.  Look for comments that start with 5 stars (*****).

2.  I've included code that sets DateTime columns to UpdateCheck = Never based on a problem I've discovered in my own testing.  May not be appropriate, but gets around the problem.  I've included a Forums link that provides additional background.

3.  If you agree it make sense to include this in the Toolbox, it may be appropriate to add something (even if just instructions) on Foreign Keys in the Toolbox somehow.  I'm not seeing how to include them using the Toolbox designer (I may be just missing it).

Please let me know how I can contribute the code and anything else you may need.  Steve

**Comment by ErikEJ** [comment]
Look at text at the bottom of a reply: attach files by dragging or dropping or selecting them!

**Comment by CincySteve** [comment]
I was trying to upload the C# file, which it wouldn't take.  So here's a txt version.
Steve

[GenDataContext.txt](https://github.com/ErikEJ/SqlCeToolbox/files/232956/GenDataContext.txt)

**Comment by ErikEJ** [comment]
Looks like there are tools for this already: https://github.com/dblinq/dblinq2007

**Comment by CincySteve** [comment]
Not sure what you are saying.  A quick glance does show that DBLinq ("an API close to LINQ to SQL") is a dead end, and it's disconnected from your Toolbox, which is a drawback.

Are you also suggesting that LINQ to SQL is dead?  There are lots of posts in the MS Forums about that from back in 2008-2010 (seemingly due to EF offering some sort of alternative), but hard to sift through to find out the current thinking since LINQ to SQL clearly still works.  Even from back then, there were signals of support for it from MS.

Perhaps I misunderstood your suggestion to me in a separate forum to move to LINQ and SQLite.  In any case, I have discovered LINQ to SQL works quite well, at least for my needs, because SQLite supports an IDbConnection interface.  But before I get too much more invested, ...  

Finally, does your note mean that you have no interest in the addition to your Toolbox?  That's OK.  I just won't spend any more time on it.

**Comment by ErikEJ** [comment]
Considering that the inclusion of this feature would require maintenance and support, deeming out of scope for now
