### ISSUE TITLE
Column Type for varchar(8000) incorrectly results in varchar(max) in model

### ISSUE THREAD

**Issue by zaceverett** [ErikEJ/SqlCeToolbox#475]
When reverse engineering for EF core a database field of varchar(8000) is given the data attribute of 
[Column(TypeName = "varchar(max)")] 
in the model

Surely this should be 
[Column(TypeName = "varchar(8000)")]

Toolbox version: 4.7.2340.0

Database engine: (SQL Server)

Visual Studio 2017

**Comment by ErikEJ** [comment]
Yes, you are right, this is a bug in EF Core scaffolding, will be fixed in EF Core 2.1
