### ISSUE TITLE
Download compiled stand-alone app?

### ISSUE THREAD

**Issue by rdogmartin** [ErikEJ/SqlCeToolbox#48]
Is it possible for one to download the compiled stand-alone app SqlCe40Toolbox.exe without going through the Visual Studio gallery or compiling the source code? Our application uses SQL CE on the back-end and we have historically recommended users use your stand-alone tool for manual database editing.

But since you moved to github, it is not clear to me how one can get the exe. It used to be a convenient link on the CodePlex home page.

Thanks,
Roger Martin
Gallery Server
galleryserverpro.com

**Comment by ErikEJ** [comment]
I have added links to the downloads in the readme.md displayed here: https://github.com/ErikEJ/SqlCeToolbox
