### ISSUE TITLE
Crash after selecting tables - Specified argument was out of the range

### ISSUE THREAD

**Issue by tomlindhe** [ErikEJ/SqlCeToolbox#480]
After selecting tables (all or simply one, same result) nothing happends and an error message is shown. I got th latest version of VS and is using Core 2.

### Steps to reproduce
Selects EF Core Power Tools => Reverse engineer
Select Microsoft SQL Server Database File (SqlClient) and database file
Select all (or just one) table(s)
OK

Dialog closes and the follwoing error message is shown:

System.ArgumentOutOfRangeException:  of valid values.
Parameter name: index
   at System.Char.IsLetter(String s, Int32 index)
   at EFCoreReverseEngineer.EfCoreReverseEngineer.GenerateClassName(String value)
   at EFCorePowerTools.Handlers.ReverseEngineerCodeFirstHandler.ReverseEngineerCodeFirst(Project project) in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerCodeFirstHandler.cs:line 90

### Further technical details
Toolbox version: 4.7.287

Database engine: SQL Server (file)

Visual Studio 2017

**Comment by ErikEJ** [comment]
Please show me the database connection dialog

**Comment by tomlindhe** [comment]
Hi Erik

Sure, see screen dump. I have used the Scaffold-DbContext earlier with the same database.

[cid:image001.png@01D32762.2E2DD430]

Regards
Tom

Från: Erik Ejlskov Jensen [mailto:notifications@github.com]
Skickat: den 6 september 2017 22:07
Till: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Kopia: Tom Lindhé <tom@lindhe.me>; Author <author@noreply.github.com>
Ämne: Re: [ErikEJ/SqlCeToolbox] Crash after selecting tables - Specified argument was out of the range (#480)


Please show me the database connection dialog

**Comment by ErikEJ** [comment]
You need to attach/upload the screen dump before I can see it

**Comment by tomlindhe** [comment]
![dump](https://user-images.githubusercontent.com/25530996/30149428-deb2b602-93a7-11e7-82cf-54feaad89a22.png)

**Comment by ErikEJ** [comment]
Fixed in the latest daily build - thanks for reporting this
