### ISSUE TITLE
"Use table and column names directly from the database" not completely working

### ISSUE THREAD

**Issue by tomlindhe** [ErikEJ/SqlCeToolbox#485]
When selecting option "Use table and column names directly from the database" only the tables names keep their original names, column names still got changed.

E.g. column ClientID ==> ClientId 

### Further technical details
Toolbox version: 4.7.294

**Comment by ErikEJ** [comment]
Are you running EF Core Power Tools? This is by design... (Names are still C# - ified)

**Comment by tomlindhe** [comment]
Ok, thanks for the clarification!

**Comment by ErikEJ** [comment]
Please let me know if you encounter any other issue with "EF Core Power Tools" - it is very new code!
