### ISSUE TITLE
Unified UI design same Visual Studio

### ISSUE THREAD

**Issue by mojtabakaviani** [ErikEJ/SqlCeToolbox#49]
please unified tree structure, table editor,query editor and result grid UI design and icons and theme same Visual Studio(SSDT)

**Comment by ErikEJ** [comment]
The project is open for pull requests!  😄

**Comment by ErikEJ** [comment]
@mojtabakaviani  Maybe you could share some screen shots to indicate what is missing in this area?

**Comment by mojtabakaviani** [comment]
I think some font size large than vs default font size, scrollbar borders, search columns and "group by" design.
![query editor](https://cloud.githubusercontent.com/assets/1667525/15077618/8bba8092-13c4-11e6-8b0b-fb651a5efb8d.PNG)

**Comment by mojtabakaviani** [comment]
so search in columns and group by area not very useful.

**Comment by ErikEJ** [comment]
Try to switch back to the "Classic" grid and let me know what you think

**Comment by ErikEJ** [comment]
I have logged this issue: https://github.com/ErikEJ/SqlCeToolbox/issues/55

**Comment by ErikEJ** [comment]
Issue #55 has been fixed

**Comment by ErikEJ** [comment]
I have made the "Classic" grin the default - please let me know if you have any other concrete suggestions for changes?

**Comment by ErikEJ** [comment]
Closing as there are no actionable suggestions - the Explorer tree and the SQL editor already uses SSDT icons, and the SSDT table editor is out of reach/scope

**Comment by zspitz** [comment]
Shouldn't the query editor and grid use the same fonts as Text editor in the VS font options?

**Comment by ErikEJ** [comment]
@zspitz This is implemented  in the latest release!
