### ISSUE TITLE
EF View Graph/Text Error: Cannot Load Type System.Reflection.IntrospectionExtensions

### ISSUE THREAD

**Issue by julielerman** [ErikEJ/SqlCeToolbox#492]
Getting this error message when I try to use EF Core powertools on a dbcontext to view graph or text. Screenshot because i can't copy text in message:

![image](https://user-images.githubusercontent.com/5007120/30252424-77c50aee-9640-11e7-80f1-fb229d940da9.png)

### Steps to reproduce
Here are the pieces of my little project:

csproj (cross targets so that I could run migrations)
```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="2.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="2.0.0" />
  </ItemGroup>

</Project>
```
Simple domain class:
```
namespace SamuraiApp.Domain {
  public class Samurai {
    public int Id { get; set; }
    public string Name { get; set; }
  }
}

```

Context:
```
using Microsoft.EntityFrameworkCore;
using SamuraiApp.Domain;
namespace EFCore2Library
{
    public class MyDbContext:DbContext
    {
        public DbSet<Samurai> Samurais { get; set; }
        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            string connectionString = "Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=EFCoreSamuraiConsole;Integrated Security=True;";
             optionsBuilder.UseSqlServer(connectionString);
            base.OnConfiguring(optionsBuilder);
        }
    }
}
```

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)
Version 4.7.234.0 

Database engine:  SQL Server localdb

Visual Studio or SSMS version: VS2017 15.3.3

**Comment by ErikEJ** [comment]
What happens if you dont crosstarget?

**Comment by ErikEJ** [comment]
Should it not be targetframeworks and a semicoln sepersted list?

**Comment by julielerman** [comment]
same problem when it's just:
```
<PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>
```

and rebuilt etc.

**Comment by julielerman** [comment]
same if it's just netcoreapp2.0 target framework

**Comment by ErikEJ** [comment]
Reboot VS?

**Comment by julielerman** [comment]
just doing that now including disabling the two redgate extensions just in case

**Comment by ErikEJ** [comment]
Remove tools and design nuget packsges?

**Comment by julielerman** [comment]
restart and disabling possibly conflictin tools did not work.
removing tools & design from csproj did not fix it. :(
I hate being so special. We have to keep playing "one of these things is not like the other" because I have something DIFFERENT.

**Comment by julielerman** [comment]
[project.assets.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1290908/project.assets.zip)
Here's the projects.assets.json file if you want to look at it.

**Comment by julielerman** [comment]
It's also happening with the simple repro you mentioned in https://github.com/ErikEJ/SqlCeToolbox/issues/491. It has to be something with my setup. Some conflicting extension. :(

**Comment by ErikEJ** [comment]
I have made some changes in the latest daily build https://github.com/ErikEJ/SqlCeToolbox/pull/494/files and with those, I am not able to repro your issue (I was not before, but never mind)

![image](https://user-images.githubusercontent.com/4169187/30264047-836f55e2-96d7-11e7-867b-7b637fe4d4ce.png)

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="2.0.0" />
  </ItemGroup>

</Project>
```

**Comment by ErikEJ** [comment]
Build number is 0.1.306 (or higher) and now there is an About dialog in the menu as well 😄

**Comment by julielerman** [comment]
since last night and continuing with the new VSIX, I'm not just getting dbcontext can't be found. Although if I switch SDK to netcoreapp, I have no problems running migrations. This is still on the VM. Obviously SOMETHING is funny on my VM. I've tried this with project in shared folders \\Mac\etc\Documnets and direct paths e.g. C:\Users\Julie ...

**Comment by ErikEJ** [comment]
Can you share a zip file with the project, and I can verify if it is just your PC?

**Comment by julielerman** [comment]
[EFCore2LibraryJulie.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1292603/EFCore2LibraryJulie.zip)

**Comment by julielerman** [comment]
i wonder if it is related to the fact that I can't use the EF Core reverse engineer feature  from sql extensions. I guess I have to stop wasting so much time on this vm and spend it on my real windows machine.

**Comment by ErikEJ** [comment]
.NET Core 1.1 SDK stuff interfering? Check your path and system path

**Comment by ErikEJ** [comment]
EFCore2LibraryJulie.zip works on my PC - are you using the latest build? 0.1.308 (Check the About menu item)

**Comment by ErikEJ** [comment]
>> i wonder if it is related to the fact that I can't use the EF Core reverse engineer feature from sql extensions. 

How does that manifest itself?

**Comment by julielerman** [comment]
oh it gets better...on my big machine, I'm getting an error that is the same as the one I was getting from SQLCEToolbox on the VM:

![image](https://user-images.githubusercontent.com/5007120/30283761-f7c74a94-96e6-11e7-9d05-cfaaf69d8052.png)

**Comment by julielerman** [comment]
yes 308 ...from the NEW about button :)

**Comment by ErikEJ** [comment]
Could you test with a .NET Standard lib? (Not .NET Core App)  - as I said before, everything works fine on both my machines

**Comment by julielerman** [comment]
i'll do that again (standard). I've done that about 20 times but I don't think on this machine

**Comment by ErikEJ** [comment]
The tool works fine for me with: NET 4.6.1 app (lib or console etc) and .NET Standard Lib - but not ASP.NET Core for some reason (most likely due to DI)

**Comment by julielerman** [comment]
no difference. I'm gong to have to stop messing around with this for the time being. Gotta get ready for my 2 week , 3 conference trip. I wlll use your screenshot in my workshop to say "it's in progress" but just won't demo it.

**Comment by ErikEJ** [comment]
Well, I will close this for now, as I have no clue what I am supposed to fix !

**Comment by ErikEJ** [comment]
One last Q: You are running VS 15.3 on your "big machine" ?

**Comment by julielerman** [comment]
yes 
and I've uninstalled all of the old .net core sdks

**Comment by julielerman** [comment]
also same (no dbcontext found) with .net 4.61 console app

**Comment by julielerman** [comment]
i've notice that it's a default error message when an unknown problem prevents this from working. So this may not really be the problem anyway.

**Comment by ErikEJ** [comment]
Thanks for your patience, Julie. Based on your experience, I have decided to provide an alternative approach - a DbContext extenion method, that I will publish as a NuGet package.

This will allow you to install the package, and then do this:

```csharp
            using (var myContext = new MyDbContext())
            {
                var dgml = myContext.AsDgmlView();
                var path = Path.GetTempFileName() + ".dgml";
                File.WriteAllText(path, dgml, Encoding.UTF8);
                Process.Start(path);
            }
 
```

**Comment by ErikEJ** [comment]
NUget package published: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools#view-dbcontext-model-as-graph

**Comment by ErikEJ** [comment]
Just a FYI, I was finally able to repro your issue, and has changed the DGFML feature to just add the NuGet package in the current project

**Comment by ErikEJ** [comment]
I have now added a feature to add DbContext Model diagram(s) to the current project, available in the latest release version on VS Marketplace - currently only works for .NET Framework projects.

**Comment by julielerman** [comment]
that is awesome. Sorry I couldn't help you figure it out. Going to go try it

**Comment by julielerman** [comment]
![image](https://user-images.githubusercontent.com/5007120/31060165-d7879d5a-a6dc-11e7-8d21-a6711d90db1c.png)
