### ISSUE TITLE
exportsqlce31.zip empty

### ISSUE THREAD

**Issue by AndyEW** [ErikEJ/SqlCeToolbox#502]
Erik,
Just went to download the zip file from here https://github.com/ErikEJ/SqlCeToolbox/releases and the zip is only 22K in size and is empty on download.

regards
Andrew

**Comment by ErikEJ** [comment]
It is for SQL Compact 3.1 - do you really need that?

**Comment by AndyEW** [comment]
Thanks for the quick reply Erik.

Believe it or not yes. 

We have a legacy application bad on 3.1 with about 20 users. 

The server failed and the sdfs were orphaned. 

We're going to batch out the data from the tables and do a delta and manually insert the records. 

I'd rather not have to upgrade all the sdfs to V3.5 before scripting but if that's what I have to do then so be it. 

Regards
Andrew.

**Comment by ErikEJ** [comment]
Let me see if I can provide a build - hang in there...

**Comment by AndyEW** [comment]
Thanks Erik. 

Appreciated. 

Regards
Andrew

**Comment by ErikEJ** [comment]
Should be there now, let me know if it works for you

**Comment by ErikEJ** [comment]
Did you get it?

**Comment by AndyEW** [comment]
Erik,

Thanks for the effort but I'm hitting a runtime error.

It has all the hall marks of this issue.

https://blogs.msdn.microsoft.com/smartclientdata/2005/07/14/the-little-database-that-could-deploying-sql-mobile-as-a-local-single-user-database-across-microsoft-mobile-devices/

Specifically

Error: System.DllNotFoundException: Unable to load DLL 'sqlceme30.dll': 
The specified module could not be found. (Exception from HRESULT: 
0x8007007E)
    at System.Data.SqlServerCe.NativeMethods.DllAddRef()
    at System.Data.SqlServerCe.SqlCeConnection..ctor(String 
connectionString)
    at ErikEJ.SqlCeScripting.DBRepository..ctor(String connectionString)
    at ErikEJ.SqlCeScripting.Helper.CreateRepository(String 
connectionString)
    at ExportSqlCE.Program.Main(String[] args)

I tried copying the DLLs in the same directory as the executable and got 
the following

Error: System.BadImageFormatException: An attempt was made to load a 
program with an incorrect format. (Exception from HRESULT: 0x8007000B)
    at System.Data.SqlServerCe.NativeMethods.DllAddRef()
    at System.Data.SqlServerCe.SqlCeConnection..ctor(String 
connectionString)
    at ErikEJ.SqlCeScripting.DBRepository..ctor(String connectionString)
    at ErikEJ.SqlCeScripting.Helper.CreateRepository(String 
connectionString)
    at ExportSqlCE.Program.Main(String[] args)

However I worked around this by upgrading the SDFs to 3.5 and using the 
ExportSQLce.exe. It took longer but in an emergency you do what you have to.

If you know the answer to this issue I'd be happy to test the result. 
However this portion of the emergency has been dealt with. We're now 
doing the delta queries. Fortunately it looks like very little data has 
been orphaned.

Thanks again for the effort.

regards

Andrew

**Comment by ErikEJ** [comment]
I have fixed the build issue, would be grateful if you could give it a try! (I was building for AnyCPU by mistake)

**Comment by AndyEW** [comment]
Worked perfectly Erik. Thankyou.

That's gone into the emergency toolbox.

regards

Andrew
