### ISSUE TITLE
SQLite/SQL Server Compact Toolbox UI: Match VS2017 colour scheme

### ISSUE THREAD

**Issue by GlynP** [ErikEJ/SqlCeToolbox#505]
A tiny UI suggestion for SQLite/SQL Server Compact Toolbox pane in VS2017. 

Match the UI colour scheme to whatever is being used in VS2017. 

Also, the tab icon is invisible if the VS2017 dark theme has been selected.

![sqlite_sql server compact toolbox ui](https://user-images.githubusercontent.com/7911874/30605986-07e82862-9d68-11e7-9ee6-ba0856fe746e.PNG)

**Comment by ErikEJ** [comment]
Thanks, have made many attempts at this, but I am just not smart enough - PRs accepted!
