### ISSUE TITLE
Addition of columns drops at run time

### ISSUE THREAD

**Issue by JobGetabu** [ErikEJ/SqlCeToolbox#509]
The tool box adds columns initially well.
It drops the generated column when you run the program.
You hit a EntityException not a valid column inner exception.
Later the entities complain of an invalid entry pointing to the missing column.

**Comment by ErikEJ** [comment]
It is unclear to me how this relates to the Toolbox, so please provider more details about the workflow and Toolbox features involved.

**Comment by JobGetabu** [comment]
Found out a fix. I was using two different databases.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=getabujob@gmail.com&idSignature=22>

Thanks,
             Job

**Comment by JobGetabu** [comment]
When using this ToolBox using(Microsoft.SqlServer.Compact 4.0.8876.1) it compiles fine, until when i add the latest nuget EntityFramework.SqlServerCompact.6.1.3'
I get an exception on build
**

_Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "
    if not exist "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\ConsoleApp\bin\Debug\x86" md "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\ConsoleApp\bin\Debug\x86"
    xcopy /s /y "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\x86\*.*" "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\ConsoleApp\bin\Debug\x86"
    if not exist "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\ConsoleApp\bin\Debug\amd64" md "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\ConsoleApp\bin\Debug\amd64"
    xcopy /s /y "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\amd64\*.*" "C:\Users\JOB\Desktop\Projects\school finance\Database prototypes\CompactDemo\ConsoleApp\bin\Debug\amd64"" exited with code 9009.	ConsoleApp_

**	
		
Have gone through all your blogpost too.
Am not sure what to do. 

Have gone through all your blogpost too
Have gone through all your blogpost too

**Comment by ErikEJ** [comment]
Avoid spaces in your path ("school finance")

**Comment by JobGetabu** [comment]
Still getting same error on a fresh project.
1. I created the project
2. Made a sdf database with few fields
3.Added EntityFramework.SqlServerCompact.6.1.3' nuget
4. Build now fails with  the error below

**_Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "
    if not exist "C:\Users\JOB\Desktop\Projects\CompactDemo\CompactDemo\bin\Debug\x86" md "C:\Users\JOB\Desktop\Projects\CompactDemo\CompactDemo\bin\Debug\x86"
    xcopy /s /y "C:\Users\JOB\Desktop\Projects\CompactDemo\packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\x86\*.*" "C:\Users\JOB\Desktop\Projects\CompactDemo\CompactDemo\bin\Debug\x86"
    if not exist "C:\Users\JOB\Desktop\Projects\CompactDemo\CompactDemo\bin\Debug\amd64" md "C:\Users\JOB\Desktop\Projects\CompactDemo\CompactDemo\bin\Debug\amd64"
    xcopy /s /y "C:\Users\JOB\Desktop\Projects\CompactDemo\packages\Microsoft.SqlServer.Compact.4.0.8876.1\NativeBinaries\amd64\*.*" "C:\Users\JOB\Desktop\Projects\CompactDemo\CompactDemo\bin\Debug\amd64"" exited with code 9009.	CompactDemo_**

**Comment by ErikEJ** [comment]
Feel free to zip up a repro project for me

**Comment by ErikEJ** [comment]
Closing as no repro received
