### ISSUE TITLE
revoke deletion right

### ISSUE THREAD

**Issue by quentinw** [ErikEJ/SqlCeToolbox#51]
I would like to protect the sdf file from users who could copy and replace by an older sdf such that transactions recorded could be removed. Howeve , it seems that full access right should be granted to everyone. Any hints?

Windows 7 and sql server compact 3.5

Thais

**Comment by ErikEJ** [comment]
Could you clarify why you think full access is required?

Do you specify temp paths in your connection string?

**Comment by quentinw** [comment]
I've tried revoke full access for everyone  then failed to connect , then grant read and write, failed, grant delete and fail . Finally grant full then ok.  

I'm using icacls command

**Comment by ErikEJ** [comment]
Fail??? What does it mean? Also, you can control access to the folder..

**Comment by quentinw** [comment]
Yes, fail. Using the sqlceconnect and fail.

I could control access to folder, but as the user should access to the file, i can't forbid his access right. 

The only solution now is to audit the delete action and to perform regular checking.

However, could i only allow user to read/write/update the sdf but not delete? Of course, user could still read/write/update/delete record in the sdf.

**Comment by ErikEJ** [comment]
I am trying to help you - but "fail" can mean 1000 different things - could you provide the exact SqlCeException error you are getting, please!

What error do you get if you revoke delete?

**Comment by quentinw** [comment]
The code is not beside me and will revert to you tomorrow. Thanks for your help

**Comment by alexng513** [comment]
Hi ErikEJ, this is quentinw's colleague. 

The SqlCeException is captured and below are number of attributes of the Exception object

**Message**
Access to the database file is not allowed. [ File name = _`SDF File Path`_ ]

**NativeError**
25039

**StackTrace**
at System.Data.SqlServerCe.SqlCeConnection.ProcessResults(Int32 hr)
at System.Data.SqlServerCe.SqlCeConnection.Open(Boolean silent)
at System.Data.SqlServerCe.SqlCeConnection.Open()

Besides, the connection string is as below:-
Data Source=|DataDirectory|_`SDF File Path`_;Password = _`File Password`_

We are opening the connection as below:-
SqlCeConnection conn = new SqlCeConnection(_ConnectionString_)
conn.Open();

then we encountered the above message. Please help to advise. Thanks for your help.

**Comment by ErikEJ** [comment]
Do you set the location of DataDirectory in code? 

Did you try a full path iso DataDirectory

Did you try to specfiy temp path? https://msdn.microsoft.com/da-dk/library/system.data.sqlserverce.sqlceconnection.connectionstring%28v=vs.100%29.aspx

**Comment by alexng513** [comment]
We didn't set the location of DataDirectory or specify the temp path. The sdf file is placed at a different directory as the program.

**Comment by ErikEJ** [comment]
What I am suggesting is that you try to do that!

If you use DataDirectory you have no control over the location of the file... Set DataDirectory value in code, or use a full path in your connection string.

**Comment by alexng513** [comment]
We tried taking away the DataDirectory away and also adding temp path to the connection string but it still fails. Below is the string we used.

DBConnectionString = "Data Source=C:\\TESTDB1\\TESTDB.sdf;Password = password;temp path=C:\\TESTDB2\\";

This string will work if the delete privilege is not revoked.

**Comment by ErikEJ** [comment]
OK, I guess it is not possible then...
