### ISSUE TITLE
How to choose guid for package id

### ISSUE THREAD

**Issue by alexsorokoletov** [ErikEJ/SqlCeToolbox#513]
I've tried to develop my own SSMS 17 plugin and it never got loaded into SSMS. I've tried registry skip loading and other tricks, did not help.

Then I cloned your project (amazing work, especially how targeting to multiple VS/SSMS is done) and it was loaded right away. Looking for differences, I dissected it until I found the key difference.

Guid used here https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SSMSToolbox/Package/ExplorerToolWindowPackage.vsct#L78 (GuidSymbol for the package) and here https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SSMSToolbox/Package/SqlCeToolboxPackage.cs#L25 (Guid for the package) is some kind of magical.

If you change it to any other value (even 1 digit), it stops loading.

### Steps to reproduce
1. 
Change guid value from `9b80f327-181a-496f-93d9-dcf03d56a792` to any other in those two places (both should have same new value).

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SSMSToolbox/Package/ExplorerToolWindowPackage.vsct#L78 (GuidSymbol for the package) and here https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SSMSToolbox/Package/SqlCeToolboxPackage.cs#L25 (Guid for the package) 

2. Run the SSMSToolbox in Debug|x86 configuration and see that package is not loading, menu item Views -> Other Windows -> SQL Ce Toolbox is missing.

3. Change value back to `9b80f327-181a-496f-93d9-dcf03d56a792` and run again. Check that menu is back.

### Further technical details
Toolbox version: latest master, `26f12de2a14d58fb8b8776338b1aae22ad8adc53`

Database engine: SQL Server

Visual Studio or SSMS version: SSMS 17.1

**Comment by ErikEJ** [comment]
Thanks for the detailed issue report! SSMS 16 and 17 contains a white list on know package GUIDs, and only packages with those "magical" ie whitelisted GUIDs will be loaded (according to the product manager to avoid SSMS being flodded with irrelevant extensions).

You can contact the product manager by email to request a whitelisted package id - Ppease email me at ejlskov at hotmail dot com, and I can give you his contact info.
