### ISSUE TITLE
UI does not work well with Color Theme Editor extension

### ISSUE THREAD

**Issue by luedi** [ErikEJ/SqlCeToolbox#519]
If you use the [Color Theme Editor](https://marketplace.visualstudio.com/items?itemName=VisualStudioProductTeam.VisualStudio2017ColorThemeEditorl) extension and choose a non standard color theme (dark with light editor in my case) the UI for the generator options (context name, namespace...) is partially not readable.

**Comment by ErikEJ** [comment]
Can you provide a scfeenshot?

**Comment by luedi** [comment]
I tried to attach a screenshot, but Github told me that it is not possible because something went wrong. So i uploaded a screenshot to my OneDrive. Here is the link: [screenshot](https://1drv.ms/i/s!AkmFlcC-2WFChwtRZMXQK8-qn9Oc)

**Comment by ErikEJ** [comment]
Thanks, I am simply using standard WPF controls, so not sure what I can do about this??

**Comment by ErikEJ** [comment]
https://stackoverflow.com/questions/18913208/colors-in-visual-studio-extension

**Comment by ErikEJ** [comment]
Fixed in latest daily build (of EF Core Power Tools) - please let me know if it works for you.

**Comment by luedi** [comment]
Hi Erik,

it works now. Doesn't look so nice because of the black background of the input fields, but it's readable now and this is the most important thing :-))).
