### ISSUE TITLE
Problem with installing EF in Windows Phone/Windows Store project

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#52]
Transferred from: https://visualstudiogallery.msdn.microsoft.com/0e313dfd-be80-4afb-b5e9-6e74d369f7a1/view/Discussions 

Thank You for this usefull tool. I'm writting because I have problem which I can't resolve. I have VS Community 2015. Let me describe step by step, how I install Your tool:

1. I didn't have EnityFramework and EntityFramework.SqlServerCompat so I installed it from Nuget.
2. I installed Your tool
3. I created new database. Connection is fine but then I have this red error: http://oi68.tinypic.com/2hd2l3b.jpg
4. When I want to add entity model to project I get error:
"Please add the EntityFramework.SqlServerCompact NuGet package to the project"

I have 2 question too. 
1.Do I have to EnityFramework and EntityFramework.SqlServerCompat referenced in solution? Because I don't see any of these in References in project.

2. May I install 3.5 version of Your tool and have option "Add Windows Phone DataContext to current Project".

Thank You,
Wojtek

**Comment by ErikEJ** [comment]
Re 3: Restart Visual Studio.
re 4: Install EntityFramework.SqlServerCompact in the project where you want to generate the code
>> Do I have to EnityFramework and EntityFramework.SqlServerCompat referenced in solution? Because I don't see any of these in References in project.

Yes, you do. What type of project are you building?

>> May I install 3.5 version of Your tool and have option "Add Windows Phone DataContext to current Project".

You just need to install SQL Server Compact 3.5 SP2 to enable that option, there is no "3.5 version" of my tool.

**Comment by woywie87** [comment]
Thank You, I'm building Windows 8 app project, also Windows Phone 8:
[](http://oi65.tinypic.com/hrabd3.jpg)

I've installed EntityFramework.SqlServerCompat but  I don't see it in References in project.

**Comment by ErikEJ** [comment]
EntityFramework is not supported in Windows 8 applications - you must use SQLite: 
http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html and
http://erikej.blogspot.dk/2012/08/getting-started-with-sqlite-in-windows.html

**Comment by woywie87** [comment]
Oh, thank You for explanation:) But I can use sql compact database in Win8 apps? I choosed this database because before I had frustrating errors with SQLite :) (I didn't use Sql Lite toolbox yet).
In several situation I get an error "Unable to active Windows Store app".

**Comment by ErikEJ** [comment]
No, you cannot use SQL Server Compact in Windows Store apps, you can only use it indirectly via COM for Enterprise Windows Apps.
You can only use SQL Server Compact with the full .NET Framework.
