### ISSUE TITLE
Link to gist of using EF Core Power Tools to automatically generate a dgml when you visit a web page. 

### ISSUE THREAD

**Issue by redwards510** [ErikEJ/SqlCeToolbox#523]
[Created an example of using AsDGML to autogenerate a dgml of the context when you visit a controller](https://gist.github.com/redwards510/a26276218be2b9d104e5e590ebed5b92). Feel free to add a link to it if you like. I feel the more examples the better .

**Comment by ErikEJ** [comment]
This is great! In the meantime I have updated the Power Tools to be able to create a diagram at design time.

**Comment by ErikEJ** [comment]
I have added it to the wiki page! Thanks a lot!
