### ISSUE TITLE
Opening database from sdf file show no connection

### ISSUE THREAD

**Issue by MarbleDaemon** [ErikEJ/SqlCeToolbox#524]
Opening database from sdf file show no connection

### Steps to reproduce
1. Open SSMS
2. Open View > SQL Lite / SQL Server Compact Toolbox
3. Add SQL CE 4.0 Connection
4. Browse to the sdf file
5. Test Connection -> OK
6. Data Connections is empty

### Further technical details
Toolbox version: 4.7.361.0

Database engine: (SQlite, SQL Compact or SQL Server) SQL Compact 4.0

Visual Studio or SSMS version: (e.g. Visual Studio 2015, SSMS 16.5.3) SSMS 17.3

**Comment by ErikEJ** [comment]
Thanks for reporting this, it is fixed on the latest version in Marketplace (4.7.390)
