### ISSUE TITLE
EF Core Power Tools ".NET Standard 2.0 not supported"

### ISSUE THREAD

**Issue by hafeefshaik** [ErikEJ/SqlCeToolbox#531]
Not able to generate the model diagram when project type is .Net Standard.

### Steps to reproduce
Have attached Gif image please refer to it. 
![error](https://user-images.githubusercontent.com/32909535/31864922-9131790e-b783-11e7-87e2-40546cc16601.gif)

### Further technical details
Toolbox version: (found in About dialog - blue questionmark icon)

Database engine: SQL Server

Visual Studio or SSMS version: Visual Studio 2017

**Comment by ErikEJ** [comment]
That is correct, that project type is not supported, as .NET Standard projects do not produce any build output. I describe a couple of possible workarounds on the wiki page here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools#view-dbcontext-model-ddl-sql

**Comment by hafeefshaik** [comment]
Thanks for the quick response.

**Comment by ErikEJ** [comment]
Leaving open for increased visibility

**Comment by TheMrAnderson** [comment]
The link is not working anymore

**Comment by ErikEJ** [comment]
@TheMrAnderson  New link: https://github.com/ErikEJ/EFCorePowerTools/wiki/Inspect-your-DbContext-model
