### ISSUE TITLE
How to browse to a Sqlite database created by entity framework on UWP

### ISSUE THREAD

**Issue by jmagaram** [ErikEJ/SqlCeToolbox#533]
I really want to use this tool to browse the SQLite database in my UWP app but I don't know how to do it. The database is managed by Entity Framework with a connection string like "Filename=MyData.db"; This gets created somewhere private/secure by UWP. How do I connect to it with your toolbox? What is the recommended workflow here? Do I need to include an actual SQLite file in my solution?

**Comment by ErikEJ** [comment]
The file is somewhere on your hard disk, locate it and connect.

**Comment by jmagaram** [comment]
I was surprised to find out I could browse to the actual file. It is located in a path like...

C:\Users\justi\AppData\Local\Packages\38c64765-5fb3-4757-bfad-73551093b492_eeb1y6kfp8qqa\LocalState
