### ISSUE TITLE
Additional options needed?

### ISSUE THREAD

**Issue by dfarrNTST** [ErikEJ/SqlCeToolbox#535]
In order for this tool to adhere to more company specific standards, will you add the following options?  (Or allow us the ability to edit the template used to create the generated files so we can add any options we need?)

-  Allow for pluralizing the collection names.
    - Ex:  For table name [Language], the tool creates a Context propert of Language.  This should be allowed to be Languages in the generated code for the DbSet<Language> property name.
- Make the class and property names exactly match the Table and Column names, even the casing.  It is currently making everything Pascal Case, which messes up our ID values.  We prefer for a table with a column named LanguageID that the property in c# be LanguageID...not LanguageId.
- Make all the generated file partial.  We always extend our entities to provide helper read-only properties.  Ex:  For a Person table, we add a property named LastFirstMiddle that is readonly and returns the 3 properties of FirstName, LastName, and MiddleName in a format we often use.  Making all the files partial by default allows for this without us having to break what is generated.

Thanks

**Comment by ErikEJ** [comment]
"this tool" - do you mean EF Core Power Tools Reverse Engineer?

For 1, I have logged: https://github.com/ErikEJ/SqlCeToolbox/issues/536 

For 2, this is a EF Core bug, a fix coming in 2.1: https://github.com/aspnet/EntityFrameworkCore/issues/9820 

For 3 - are they not partial already?

**Comment by ErikEJ** [comment]
Closing this, as there seems to be nothing to fix for this particular issue - feel free to re-open if you disagree 😄

**Comment by dfarrNTST** [comment]
Hi, yes..."this tool" = EF Core Power Tools Reverse Engineer.

2. This is not a EF Core issue, this is an issue with this tool.  The code that the tool generates takes my column name of LanguageID and makes a property name of LangaugeId.  (Lower case d is wrong.)  I would think the same logic is being applied to table --> class names.  So, its a bug in this tool.

3. No, they are not partial...I ran this 5 minutes ago and they are all "public class {TableName}".  They should all be "public partial class {TableName}".  If this is supposed to be in the tool, then its a bug, otherwise and enhancement.

I don't know how to reopen this issue.

**Comment by ErikEJ** [comment]
2: This tool is a wrapper over the EF Core code generation feature, so any bug in that relation need to be fixed in EF Core - sorry...

3: I am unable to repro this, could you provide a detailed repro or share exact version information ?
