### ISSUE TITLE
EFPT: Add optional pluralization using Inflector

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#536]
https://github.com/aspnet/EntityFrameworkCore/commit/dda3f43c046c2464f4813fdbb4261a6146aa4432
Label: "Pluralize or singularize generated object names"

**Comment by dfarrNTST** [comment]
Hey Erik, how long do you think until this enhancement is in the tool?  Once this is in it it, we can begin using it.

Thanks!

**Comment by ErikEJ** [comment]
Not too long, I would imagine

**Comment by ErikEJ** [comment]
This is now in the latest daily build - please let me know if it  works for you - and thanks for helping improve EF Core Power Tools!

**Comment by dfarrNTST** [comment]
Excellent, thanks Erik!  I know this might be a silly question...but how do I use the daily build inside my Visual Studio since this is a VS 2017 Extension?  I don't see a "Pre-Release" option for Extensions...which would be nice!  ;)

**Comment by ErikEJ** [comment]
Sorry, forgot to link to the daily build - see the link on this page: https://github.com/ErikEJ/SqlCeToolbox/wiki - download and install

**Comment by ErikEJ** [comment]
@dfarrNTST  Did you manage to get this tested?

**Comment by dfarrNTST** [comment]
Hey Erik, yes...I just installed it.  Checking the new checkbox pluralized the properties in each model that were ICollection, but the properties in the Context object are still singular...can you update it so those are pluralized as well?

Also, the checkbox label is confusing.  It currently says "Pluralize or singularize generated object names (English)".  I would think it should just says "Pluralize generated Collection Property names (English)".  That ways its clear that if you check it, you have chosen to Pluralize generated Collection Property names in both the context object and the model objects.

Also note that in the new "Choose Database Connection" popup, there is no margin to the left of the combo box, so it looks funny.  Add a matching margin on that side and it should look better.

**Comment by ErikEJ** [comment]
The EF6 feature pluralized DbSet names and singularized Entity / POCO class names.
That is what is currently implemented, I think 

      DbSet<User> Users

Can you provide a sample database schema and expected code result if you see a different result?

Thanks for the UI comment, I will fix that asap in the latest daily

**Comment by dfarrNTST** [comment]
See the 3 attached screenshots.

Note that the class Application has the correct pluralization for the ICollection property.

The issue is the ToolsContext class…all the DbSet properties are singular.  That doesn’t make any sense…they are essentially representing a set/enumerable/list of data.  Application should be Applications.

Table names should be singular in the database.  Properties which represent a collection of data from those tables should be pluralized.

This feature is in Reverser POCO Generator but it hasn’t been updated to work with .NET Core.

**Comment by ErikEJ** [comment]
You need to attach the screenshots on the Github web site

**Comment by dfarrNTST** [comment]
Done

**Comment by ErikEJ** [comment]
It looks like you have generated code without the option selected, on "my PC" the tool generates:

    DbSet<Application> Applications

For the ICollection naming, that is not implemented.

**Comment by dfarrNTST** [comment]
I just reran it with the settings in the screenshot attached and got the same results.  This is from the tools installed earlier this morning.  Application is still Application in the ToolsContext class.

![ef powertools settings](https://user-images.githubusercontent.com/20890311/32176489-2cfbc864-bd5e-11e7-8586-0a8f7a8b2201.png)

**Comment by dfarrNTST** [comment]
Is there any possible way you could put an option to override "Id" to "ID" in generated property names?  We unfortunately have to break the generated code every time by doing that update so our existing code will work.

**Comment by ErikEJ** [comment]
I am unable to repro, sorry. (I know the database connection form still has "issues")
Can you share a CREATE TABLE script for the Application table?

**Comment by dfarrNTST** [comment]
Here is the whole database so you get the same schema with all the constraints we have.

[script.sql.txt](https://github.com/ErikEJ/SqlCeToolbox/files/1427585/script.sql.txt)

**Comment by ErikEJ** [comment]
Thanks, I figured it out after taking a second look at your screen shot! 
Selecting "Use table and column names directly from the database" disables any pluralization!
I will try make them mutually exclusive in the UI!

**Comment by ErikEJ** [comment]
Made exclusive in latest daily!

**Comment by ErikEJ** [comment]
>> Is there any possible way you could put an option to override "Id" to "ID" in generated property names and just manually make that update in the tool? We unfortunately have to break the generated code every time by doing that update so our existing code will work.

I am sure there is, just to be clear before I go ahead - anything ending in Id should be ending in ID instead?

**Comment by dfarrNTST** [comment]
For property names within a model, yes.  A checkbox on the Generate window to enable this would be great.

**Comment by ErikEJ** [comment]
OK, I have  logged: https://github.com/ErikEJ/SqlCeToolbox/issues/540

**Comment by ErikEJ** [comment]
ID replace added to latest daily build, pls let me know if it works for you!

**Comment by dfarrNTST** [comment]
Everything works as expected now...thanks Erik!

**Comment by ErikEJ** [comment]
You are welcome, and thanks for your help in making this tool even better!

**Comment by ErikEJ** [comment]
![efreveng1](https://user-images.githubusercontent.com/4169187/32213556-02ba918e-be1c-11e7-905e-bc0235483c64.png)
![efreveng2](https://user-images.githubusercontent.com/4169187/32213557-02d39756-be1c-11e7-89ac-2cb82fe812c5.png)
