### ISSUE TITLE
MissingMethodException during View Database Schema as Graph

### ISSUE THREAD

**Issue by fmorriso** [ErikEJ/SqlCeToolbox#543]
Right-Clicking on project in Solution Explorer, choosing EF Core Power Tools / View Database Schema as Graph produces the following error:

System.MissingMethodException: Method not found: 'Void ErikEJ.SqlCeScripting.Generator..ctor(ErikEJ.SqlCeScripting.IRepository, System.String, Boolean, Boolean, Boolean)'.
   at ErikEJ.SqlCeToolbox.Helpers.RepositoryHelper.CreateGenerator(IRepository repository, String outFile, DatabaseType databaseType)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.GenerateServerDgmlFiles() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 25

### Steps to reproduce
1. Open Solution (mine happens to be called BethanysPieShop) which uses EF.Core 2.0.0.
2. Right click on the project (in my solution, BethanysPieShop is the only project).
3. Choose EF Power Tools, then View Database Schema as Graph.
4. Add connection to Azure SQL Server Database, which in my case, uses the following connection string (minus the password, which I will understandably not expose as clear text):
Server=fpmbethanyspieshop.database.windows.net,1433;Initial Catalog=BethanysPieShop;Persist Security Info=False;User ID=DevAdmin;Password=*******;MultipleActiveResultSets=True;Encrypt=True;TrustServerCertificate=False;Connection Timeout=40;

### Further technical details
Toolbox version: 4.7.406.0

Database engine: SQL Server

Visual Studio or SSMS version: Visual Studio 2017 Enterprise (15.4.1)

**Comment by ErikEJ** [comment]
Hmm... Could you try the latest daily build: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools 

Do you also have the SQLite Toolbox installed and in use?

**Comment by ErikEJ** [comment]
I was able to repro - I had created a breaking change, so a new release of the SQLite Toolbox is required. Publish to Marketplace very soon!

**Comment by ErikEJ** [comment]
Yep, fixed with latest release of SQLite Toolbox (build .406)
