### ISSUE TITLE
How do I make a context for a SQL View?

### ISSUE THREAD

**Issue by Ofer-Gal** [ErikEJ/SqlCeToolbox#545]
Describe what is not working as expected.
You only have options for Tables
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Please provide more details, thanks!

**Comment by ErikEJ** [comment]
Closing as requested details not provided
