### ISSUE TITLE
Writing from SQL Compact to SQL Server throws 'The handle is invalid'

### ISSUE THREAD

**Issue by Yelnik** [ErikEJ/SqlCeToolbox#547]
string dbAccess = @"Data Source=" + srcFile;
                using (IRepository ceRepository = new DB4Repository(dbAccess)) {
                    string fileName = System.IO.Path.GetTempFileName();
                    var generator = new Generator4(ceRepository, fileName);
                    generator.ScriptDatabaseToFile(Scope.SchemaData);
                    using (IRepository serverRepository = new ServerDBRepository4(conString)) {
                        serverRepository.ExecuteSqlFile(fileName);
                    }

                    return true;
                }

Using the above block, on the call to `ExecuteSqlFile`, I get System.IO.IOException: The handle is invalid.
Stack trace:  "   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)\r\n   at ErikEJ.SqlCeScripting.ServerDBRepository4.RunCommands(String scriptPath)\r\n   at ErikEJ.SqlCeScripting.ServerDBRepository4.ExecuteSqlFile(String scriptPath)\r\n "

### Steps to reproduce
Attempt to write SQL Compact database to SQL Server

### Further technical details
Toolbox/Power Tools version: 4.7.406.0

Database engine: SQL Compact and SQL Server 2014

Visual Studio or SSMS version: Visual Studio 2017 15.4.2

**Comment by ErikEJ** [comment]
Are you using the Nuget package? And which version?

**Comment by Yelnik** [comment]
Yes I am using the Nuget package, version: 3.5.2.70

**Comment by ErikEJ** [comment]
Ah, it needs an update, try to use the Toolbox gui as a workaround, I will update the Nuget package on Sunday or Monday

**Comment by Yelnik** [comment]
Ok great, thanks Erik

**Comment by ErikEJ** [comment]
Nuget package updated
