### ISSUE TITLE
EF6 workflow with SQLite DDEX provider Needs update

### ISSUE THREAD

**Issue by bruceburge** [ErikEJ/SqlCeToolbox#548]
Specifically 
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider#install-sqlite-in-gac

"Once per machine. Download **sqlite-netFx46-setup-bundle-x86-2015-1.0.105.2.exe** (from https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki)"

That version is no longer present on the site, it seems to have been replaced with **sqlite-netFx20-setup-bundle-x86-2015-1.0.106.0.exe**
[edit] 
typo **sqlite-netFx20-setup-bundle-x86-2005-1.0.106.0.exe** changed to **sqlite-netFx20-setup-bundle-x86-2015-1.0.106.0.exe**
[/edit]

**Comment by ErikEJ** [comment]
Thanks, I will get that updated

**Comment by bruceburge** [comment]
I know this is a bit off topic, but the process doesn't seem to work for visual studio 2017, I know there are issues with the design time components from the sqlite.data group, but in the sqlceToolbox it also doesn't show its in the GAC, I've confirmed that it does not appear to be installed in the gac, with gacutil. Any thoughts?

(if you'd rather I bring this up elsewhere let me know) 

Also, great tools, thanks for all you do!

![image](https://user-images.githubusercontent.com/6773890/32402557-a7c0fc7e-c0f4-11e7-8324-28d22f2b62f2.png)

**Comment by ErikEJ** [comment]
Install the package named -2015- - it must be in GAC for the workflow to work.

**Comment by bruceburge** [comment]
I've installed sqlite-netFx46-setup-bundle-x86-2015-1.0.106.0.exe making sure to check the "install in GAC" option.

Gacutil -l shows 

  System.Data.SQLite, Version=1.0.106.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=x86
  System.Data.SQLite, Version=1.0.105.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=MSIL
  System.Data.SQLite.EF6, Version=1.0.106.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=MSIL
  System.Data.SQLite.Linq, Version=1.0.106.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=MSIL

Toolbox results same as above
Version 4.7.413.0 - 903,153 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No


Sync Framework 2.1 SqlCe 3.5 provider - No


SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by ErikEJ** [comment]
Need to check dbproviders section in x86 mschine.config, most likely it is corrupted/wrong

**Comment by bruceburge** [comment]
Spot On sir, It had an old reference to sqlite, not sqlite ef provider.

**Comment by ErikEJ** [comment]
Could you share the crrect section, then I will add that to the wiki page

**Comment by ErikEJ** [comment]
Could you share the crrect section, then I will add that to the wiki page

**Comment by ErikEJ** [comment]
Pls leave open to remind me to update wiki page

**Comment by bruceburge** [comment]
On a machine that I had a previous version of sqlite installed, after using the uninstaller, and then using a new installer my machine config contained.

`<system.data> 
	 <dbproviderfactories> 
         <add name="sqlite data provider" invariant="system.data.sqlite" description=".net framework data provider for sqlite" type="system.data.sqlite.sqlitefactory, system.data.sqlite, version=1.0.99.0, culture=neutral, publickeytoken=db937bc2d44ff139"/> 
		 </dbproviderfactories> 
     </system.data> `

After a fresh install on a machine that never had sqlite installed. my machine config contained.

`	 <system.data>
		 <DbProviderFactories>
			<add name="SQLite Data Provider" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6, Version=1.0.106.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139" />
		 </DbProviderFactories>
	 </system.data>	 `

Replacing the first entry with the second on the machine with the previous unistall resolved the issue.

**Comment by ErikEJ** [comment]
wiki updated, thank for the help!

**Comment by EinsteinRepository** [comment]
i hv windows 10 x64bit visual studio 2022 how to install it from scratch, cause i`m trying i get same issue ?!

**Comment by ErikEJ** [comment]
@EinsteinRepository see https://github.com/ErikEJ/SqlCeToolbox/issues/924#issuecomment-1006812169

**Comment by EinsteinRepository** [comment]
can u give me download link for best version of VS to use the tool plz ?!

**Comment by ErikEJ** [comment]
VS 2019 - https://my.visualstudio.com/

**Comment by EinsteinRepository** [comment]
in visual studio installer i have vs community 2019 v16.11.9 it`s good ?!

**Comment by ErikEJ** [comment]
yes it is

**Comment by EinsteinRepository** [comment]
i`m sry @ErikEJ  i can`not understand > Installing the SSMS 17 extension & SSMS 18 step cause i`v not the location for (Microsoft Visual Studio 14.0)  & location for (Microsoft SQL Server Management Studio 18) but i hv folder for folder for (Microsoft Visual Studio 8) & folder for (Microsoft Visual Studio) there is folder named (2019 then community) & (Microsoft SQL Server) but when go to this folder there is not (Common7\IDE\Extensions\) folder

**Comment by ErikEJ** [comment]
The SSMS extension has nothing to do with VS  - just install via Tools, Extension menu in VS

**Comment by EinsteinRepository** [comment]
still get  > gac no
