### ISSUE TITLE
Hi, very interested in using this with VS 2017 express. It seems to have installed fine but not seeing the toolbox icon and features in server explorer.  I am getting my work done using the standalone program hower.  Thanks, Alan

### ISSUE THREAD

**Issue by atweisman** [ErikEJ/SqlCeToolbox#549]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
You cannot install any extensions in Express editions. You can however install with the free VS Community Edition
