### ISSUE TITLE
VS 2017 15.4.2 Missing most of the options

### ISSUE THREAD

**Issue by rauntska** [ErikEJ/SqlCeToolbox#550]
Hi,

I recently update VS 2017 from 15.3.x -> 15.4.2 
Running also the latest version from 
https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools

This however seems to have broken something, since i dont have anymore the ''Add EF Core model to current project..' option.

The only options are :
![image](https://user-images.githubusercontent.com/16056798/32484014-0db4e0fe-c3a7-11e7-8c01-0ad56e84a2b4.png)

Any idea what seems to be missing here ? - tried also the disable/enable tool, but that did not help
Thanks!

**Comment by ErikEJ** [comment]
The SQLite Toolbox context menu for a SQL Server database contains the menu items above. The "EF Core Model" feature has been removed, and is now available in "EF Core Power Tools" - available from the  context menu on a project in Solution Explorer.

Please let me know if that solves your issue?

**Comment by rauntska** [comment]
Thanks,

Yes i found it now :) That solved it.
