### ISSUE TITLE
LINQ to SQL, supported project types?

### ISSUE THREAD

**Issue by hultqvist** [ErikEJ/SqlCeToolbox#551]
I've made changes to a SQL Server Compact 4.0 database and now I want to update the generated DataContext.

I get this dialog:
![image](https://user-images.githubusercontent.com/505330/32486077-d9fdc5ec-c3a5-11e7-8324-a346135d78a8.png)

The project is a .NET Framework 4.6.1 and it is working fine with the previously generated code.
Although I do have other project types in the same solution, most of them are .NET 4.6.1.

I've tried to "select" the project I want to target by opening other files, setting it as the start project(although it's a library)

I also tried to download the latest release from this repo but generating a LINQ to SQL DataContext gives this error.
![image](https://user-images.githubusercontent.com/505330/32487033-bbfb9ddc-c3a8-11e7-86dd-6cda8faf8718.png)

### Steps to reproduce

Next I created a new .NET 4.6.1 Console application in a new solution.
Tried to generate the DataContext:
![image](https://user-images.githubusercontent.com/505330/32487150-1d9c0d6a-c3a9-11e7-8112-e65c2ff4f8bc.png)
![image](https://user-images.githubusercontent.com/505330/32487162-274e9062-c3a9-11e7-92fa-315887231d8d.png)

### Further technical details
Toolbox/Power Tools version: 4.7.406.0
Version 4.7.406.0 - 908 638 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider - Yes

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQL Compact

Visual Studio or SSMS version: Visual Studio 2017 15.4.2

**Comment by reza-hm89** [comment]
I have same problem

**Comment by ErikEJ** [comment]
@hultqvist Pls share your csproj file! 
I will get the SQLMetal issue fixed asap - where is it located on your machine?

**Comment by hultqvist** [comment]
Here is the .csproj file of the newly created project.

How do I know where SQL Metal is, should I install it separately?

```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <ProjectGuid>{5088F829-E5BA-46FE-9CE4-EE0A9500BB3A}</ProjectGuid>
    <OutputType>Exe</OutputType>
    <RootNamespace>ConsoleApp3</RootNamespace>
    <AssemblyName>ConsoleApp3</AssemblyName>
    <TargetFrameworkVersion>v4.6.1</TargetFrameworkVersion>
    <FileAlignment>512</FileAlignment>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>bin\Debug\</OutputPath>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>bin\Release\</OutputPath>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Xml.Linq" />
    <Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Data" />
    <Reference Include="System.Net.Http" />
    <Reference Include="System.Xml" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Properties\AssemblyInfo.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Include="App.config" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
```

**Comment by ErikEJ** [comment]
sqlmetal.exe is installed - look for it on your disk using file search!

I have attempted a fix in the latest daily build, could you please try that out: 

https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by hultqvist** [comment]
This is the path:

`C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6.2 Tools`

Using the test csproj I posted earlier it works.

However using my real project it still complains with with error:

![image](https://user-images.githubusercontent.com/505330/32491817-649c37e4-c3b8-11e7-8e61-77101ca9b522.png)

That project looks like it's using the newer, less verbose, project format:

```
<Project Sdk="Microsoft.NET.Sdk">
...
```

**Comment by ErikEJ** [comment]
Aaaah! Fixed in latest daily build

**Comment by hultqvist** [comment]
Any plans on supporting the new .csproj format?

**Comment by ErikEJ** [comment]
Does the latest daily build not work for you? 4.7.421

**Comment by hultqvist** [comment]
I'm now testing 4.7.422 and it's working.

I noted that I no longer get the dialog where I choose tables to include. Now I get all tables. This includes __ExtendedProperties which gives a warning about missing Primary Keys.
For me that's not a problem.

**Comment by ErikEJ** [comment]
@hultqvist  I have logged: #552 - that should be fixed, thanks for noticing

**Comment by ErikEJ** [comment]
@hultqvist I do not think that this feature ever supported selecting tables...

**Comment by hultqvist** [comment]
You're right, I was thinking of the "Script Schema..." which still works.

![image](https://user-images.githubusercontent.com/505330/32657533-67083dce-c616-11e7-9642-03ff0229a6f0.png)
