### ISSUE TITLE
How to uninstall SqlCeToolbox?

### ISSUE THREAD

**Issue by Oleg26Dev** [ErikEJ/SqlCeToolbox#553]
My SSMS 17.3 does not work after SqlCeToolbox installed.
How to uninstall/remove the  SqlCeToolbox?

**Comment by Oleg26Dev** [comment]
That is the error when I try to connecto to SQL Server database engine in SSMS 17.3


SetSite failed for package [SqlCeToolboxPackage][The DocumentSite on a WindowFrame may only be set once]:{   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.set_DocumentSite(DocumentObjectSite value)   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(FrameMoniker frameMoniker, Boolean isDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Guid rguidCmdUI, ViewGroup parent, IVsWindowFrame& ppWindowFrame)   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateContentPane(String pszName, Int32 fDockViewOn, Int32 fDocument, String lpstrMkDoc, UInt32 eCreateWindowFlags, UInt32 dwToolWinId, Object punkView, Object punkData, IServiceProvider pServiceProvider, IVsUIHierarchy pUIHierarchy, UInt32 vsid, Int32& pfDefaultPosition, Guid& rguidCmdUI, IVsWindowFrame& ppWindowFrame)   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, UInt32 flags)   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Type toolWindowType, Int32 id, ProvideToolWindowAttribute tool)   at Microsoft.VisualStudio.Shell.Package.FindToolWindow(Type toolWindowType, Int32 id, Boolean create, ProvideToolWindowAttribute tool)   at Microsoft.VisualStudio.Shell.Package.CreateToolWindow(Guid& toolWindowType, Int32 id)   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsToolWindowFactory.CreateToolWindow(Guid& toolWindowType, UInt32 id)   at Microsoft.VisualStudio.Platform.WindowManagement.WindowManagerService.CreateFrame(String moniker, UInt32 instanceID, IVsWindowFrame& frame)   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHRInternal(Int32 errorCode, IntPtr errorInfo)   at Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService.GetObjectExplorerWindowFrame()   at Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService.get_Tree()   at Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService.GetSelectedNodes(Int32& arraySize, INodeInformation[]& selNodes)   at ErikEJ.SqlCeToolbox.SSMSEngine.ObjectExplorerManager.SetObjectExplorerEventProvider() in C:\projects\sqlcetoolbox\src\GUI\SSMSToolbox\SSMSEngine\ObjectExplorerManager.cs:line 102   at ErikEJ.SqlCeToolbox.SqlCeToolboxPackage.Initialize() in C:\projects\sqlcetoolbox\src\GUI\SSMSToolbox\Package\SqlCeToolboxPackage.cs:line 226   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)}
--

**Comment by ErikEJ** [comment]
Hmmm... 

Remove the folder with the SQLite Toolbox extension files from this top level folder:

C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions

**Comment by Oleg26Dev** [comment]
Thanx, 
I am not sure that SqlCEToolbox is a reason of problem because today I have installed some software (SQL Assistant) and immediately after it SSMS could not to display connection window and to start the Sql CE toolbox.
I removed some software, restarted computer and now SSMS+Sql CE Toolbox work fine,

But it seems it may be useful to have quick way to uninstall Sql CE Toolbox add-in -for example  in CP or somehow else

**Comment by ErikEJ** [comment]
Thanks, I have made some improvements to the SSMS Toolbox start process to fail better in the latest build. 

Agree that an uninstall would be nice to have - what is "CP" - "Control Panel" ?

**Comment by Oleg26Dev** [comment]
yes, sure, it is "Control Panel" or some another way :-)

**Comment by ethouin** [comment]
Hi Erik,
Did Microsoft gave you any business reason *why* they're not supporting SSMS extensions yet? Seems to me that the market is demanding for it...
Thanks!

**Comment by ErikEJ** [comment]
No SSMS extension Marketplace…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
