### ISSUE TITLE
SQL Server connections do not expand

### ISSUE THREAD

**Issue by Oleg26Dev** [ErikEJ/SqlCeToolbox#554]
Describe what is not working as expected.
Any of stored SQL Server connections cannot be expanded.

### Steps to reproduce
May it is a side effect after case described here:
https://github.com/ErikEJ/SqlCeToolbox/issues/553

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.390.0
SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - No
SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No
SQL Server Compact 3.5 DDEX provider - No
Sync Framework 2.1 SqlCe 3.5 provider - No
SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No
------------

Database engine:SQL Server 2014

Visual Studio or SSMS version:  SSMS 17.3

**Comment by Oleg26Dev** [comment]
Also, these are connections "From Server Explorer", on one side they do not work: cannot be expanded etc
On other side I cannot remove them: no "Remove connection" in Right-Click menu.

**Comment by ErikEJ** [comment]
Pls share a screenshot - if you are referring to SQL Server connections in SQLite Toolbox, it is by design, they only have a context menu.

**Comment by Oleg26Dev** [comment]
This kind of connections have menu:
Script database
Migrate to SQLite
Migrate to SQL Server Compact

If it is ok then sorry. it is my mistake
But I think probably do not need to add all databases from the Server Explorer to the Sql CE Toolbox and have no possibility to remove a db from this list.
Sometimes there may be many dbs.

**Comment by ErikEJ** [comment]
I have logged: https://github.com/ErikEJ/SqlCeToolbox/issues/556

**Comment by ErikEJ** [comment]
I have added a setting to disable this feature - thanks for the feedback!
