### ISSUE TITLE
Generate mvc page, when running an error

### ISSUE THREAD

**Issue by caojinqin** [ErikEJ/SqlCeToolbox#559]
The following is the error message: How do I operate correctly? Thks！

An unhandled exception occurred while processing the request.

InvalidOperationException: Unable to resolve service for type 'MyCore.Model.TestrwContext' while attempting to activate 'MyCore.Web.Controllers.TestTablesController'.
Microsoft.Extensions.Internal.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, bool isDefaultParameterRequired)

**Comment by caojinqin** [comment]
Error screen capture！
![error](https://user-images.githubusercontent.com/2507925/32816704-1afc3dbc-c9f5-11e7-9478-ae8e88b6400f.png)

**Comment by caojinqin** [comment]
Error screen capture！
![error](https://user-images.githubusercontent.com/2507925/32816755-62245710-c9f5-11e7-8db6-dda6c13cc4c0.png)

**Comment by caojinqin** [comment]
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MyCore.Model;

namespace MyCore.Web.Controllers
{
    public class TestTablesController : Controller
    {
        private readonly TestrwContext _context;

        public TestTablesController(TestrwContext context)
        {
            _context = context;
        }

        // GET: TestTables
        public async Task<IActionResult> Index()
        {
            return View(await _context.TestTable.ToListAsync());
        }

        // GET: TestTables/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testTable = await _context.TestTable
                .SingleOrDefaultAsync(m => m.Id == id);
            if (testTable == null)
            {
                return NotFound();
            }

            return View(testTable);
        }

        // GET: TestTables/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TestTables/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,CreateTime")] TestTable testTable)
        {
            if (ModelState.IsValid)
            {
                _context.Add(testTable);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(testTable);
        }

        // GET: TestTables/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testTable = await _context.TestTable.SingleOrDefaultAsync(m => m.Id == id);
            if (testTable == null)
            {
                return NotFound();
            }
            return View(testTable);
        }

        // POST: TestTables/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Name,CreateTime")] TestTable testTable)
        {
            if (id != testTable.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(testTable);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TestTableExists(testTable.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(testTable);
        }

        // GET: TestTables/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var testTable = await _context.TestTable
                .SingleOrDefaultAsync(m => m.Id == id);
            if (testTable == null)
            {
                return NotFound();
            }

            return View(testTable);
        }

        // POST: TestTables/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var testTable = await _context.TestTable.SingleOrDefaultAsync(m => m.Id == id);
            _context.TestTable.Remove(testTable);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TestTableExists(long id)
        {
            return _context.TestTable.Any(e => e.Id == id);
        }
    }
}

**Comment by ErikEJ** [comment]
Hi, thanks for the review! 
I do not really see how this is related to the "EF Core Power Tools", suggest you post on the Stackoverflow

**Comment by caojinqin** [comment]
@ErikEJ thanks you.
