### ISSUE TITLE
[EF Core Power Tools] Display relationship types on DGML

### ISSUE THREAD

**Issue by julielerman** [ErikEJ/SqlCeToolbox#560]
I don't know if the DGML tool makes this possible but would love to see the navigation properties and relationship types quickly the way the EDMX designer was able to show us.

In the current view for example,
![image](https://user-images.githubusercontent.com/5007120/32909742-528d1f9a-cad5-11e7-9f64-8146308bceae.png)
 it's not obvious that Samurai has a property that is a collection of quotes or a property called SecretIdentity that is of type Identity.

In addition to displaying the properties, knowning the relationships without having to read the tooltips one at a time would also be really useful.
![image](https://user-images.githubusercontent.com/5007120/32909982-13b38cc2-cad6-11e7-8ce6-ec70f6201ce5.png)
I imagine that you must have looked for a way to make this diagram familiar to what EDMX displays, so I don't presume that you haven't wanted these things either. I'm just curious if this is even possible, or on your To-do list

Thanks!

**Comment by ErikEJ** [comment]
Great suggestions, let me see what I can do.. Can you share you DbContext and classes?

**Comment by ErikEJ** [comment]
Can you help me - how can I determine the relationships (1:* or 1:1) from the DebugView information?

**Comment by julielerman** [comment]
do you want to do a skype session in a little while to look at it together? I have to go walk the doggy first :)

**Comment by ErikEJ** [comment]
Let's do one on Monday - have a busy afternoon! At 14:00 CET perhaps - or is that too early for you?

**Comment by ErikEJ** [comment]
Made some small improvements in the latest daily build: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools

**Comment by ErikEJ** [comment]
In relation to Navigation, I already have this:
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ErikEJ.EntityFrameworkCore.DgmlBuilder/DebugViewParser.cs#L88

**Comment by julielerman** [comment]
Getting nightly build, yes, this is a step in the right direction because it shows me it is possible to display text along the arrows.
![image](https://user-images.githubusercontent.com/5007120/32954941-873810d0-cb82-11e7-94d1-e12e255f1a35.png)
But if we can figure out what the relationships are, I'd prefer just the 1:*, *:* (well not possible yet :) ), 1:1, *:1, 1:0..1 descriptions rather than the text of the entity names. That's (IMHO) too cluttered looking.

**Comment by julielerman** [comment]
Should I split the request for navigation properties displayed within an entity and the request for relationship types displayed by the arrows into two issues?

**Comment by ErikEJ** [comment]
Yes, that would probably makes sense, thanks!

**Comment by ErikEJ** [comment]
I will add a feature to get the DebugView from a model, then we can look at that together on Monday and I can do testing based on that!

**Comment by julielerman** [comment]
done, the navigation properties issue is now at https://github.com/ErikEJ/SqlCeToolbox/issues/565

**Comment by ErikEJ** [comment]
Are you able to share the model as code or a debugview text file?

**Comment by julielerman** [comment]
which do you prefer?

**Comment by julielerman** [comment]
here is debug view as text:
[debugviewforEEJ.txt](https://github.com/ErikEJ/SqlCeToolbox/files/1483081/debugviewforEEJ.txt)

**Comment by julielerman** [comment]
This is great. I'll try it out later on a more complex model. Thanks for doing it so quickly. I'll use it in my Pluralsight course!
![image](https://user-images.githubusercontent.com/5007120/32983241-7809ba5e-cc5f-11e7-87f6-f9adc8b5a87d.png)

**Comment by ErikEJ** [comment]
Thanks for your feedback to make the tool better.

**Comment by julielerman** [comment]
I'm glad that the ideas are sufficient. Because I am plowing forward, I'm not creating PRs to support your work. That's what I've done with EF Core and other tools like mssql extension and SQLOpsStudio. Really appreciate your quick implementation.
