### ISSUE TITLE
Exception on connection

### ISSUE THREAD

**Issue by bgvsan** [ErikEJ/SqlCeToolbox#561]
Got exception on connecting
![17-11-2017 10-05-11](https://user-images.githubusercontent.com/4590043/32942295-86679542-cb80-11e7-8123-1895055225ac.png)

### Steps to reproduce
Trying to connect to the database after loading the DB file

### Further technical details
Version 4.7.427.0 - 942,635 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Try to reinstall the SQLite package...
