### ISSUE TITLE
Remove connection not working

### ISSUE THREAD

**Issue by gmansi** [ErikEJ/SqlCeToolbox#562]
Visual Studio Community 2015 - Version 14.0.25123.00 Update 2 + SQLite / SQL Server Compact Toolbox 4.7.427.0 - Working with SQLite databases.

Right clic over a connection and clic on "Remove connection" and nothing happens.

Checked on 2 computers

**Comment by ErikEJ** [comment]
Have you tried removing the connection in Server Explorer?

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build. https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by gmansi** [comment]
"Have you tried removing the connection in Server Explorer?"

Right! Using Server explorer I can delete the connection and then I can also remove the connection from QLite / SQL Server Compact Toolbox 

Solved! Thanks for the quick answer

**Comment by ErikEJ** [comment]
thanks for reporting this - did the latest daily build work for you?

**Comment by gmansi** [comment]
No, even installing http://vsixgallery.com/extensions/41521019-e4c7-480c-8ea8-fc4a2c6f50aa/extension.vsix the problem remains the same.
