### ISSUE TITLE
Register DDEX Providers button missing

### ISSUE THREAD

**Issue by MartinRobins** [ErikEJ/SqlCeToolbox#563]
The "Register DDEX Providers" button is not being displayed.

### Steps to reproduce
Open the tool window, click on the About Icon. "Register DDEX Providers" button is not displayed (see image).

![about](https://user-images.githubusercontent.com/2203265/32946692-7737e544-cb90-11e7-8df4-4ff429a07d4c.png)

### Further technical details
Visual Studio 2017 15.4.4
Windows 10 (1709, 16299.64)

**Comment by ErikEJ** [comment]
This is on purpose, as you can see the DDEX providers are registered...

**Comment by MartinRobins** [comment]
Only the provider for 4.0 is registered. The 3.5 provider is not registered and this is the one that I need to use. This worked in previous versions but no longer appears to.

**Comment by ErikEJ** [comment]
Sorry, only the provider for 4.0 is available now, I gave up on the 3.5 provider.

**Comment by ErikEJ** [comment]
As a workaround, use a 4.0 database during design time
