### ISSUE TITLE
[EF Core Power Tools] Display navigation properties in entities on DGML

### ISSUE THREAD

**Issue by julielerman** [ErikEJ/SqlCeToolbox#565]
I don't know if the DGML tool makes this possible but would love to see the navigation properties and relationship types quickly the way the EDMX designer was able to show us.

In the current view for example,

![image](https://user-images.githubusercontent.com/5007120/32957062-a249ecbc-cb88-11e7-8a0c-d1e448fd2c76.png)
it's not obvious that Samurai has a property that is a collection of quotes or a property called SecretIdentity that is of type Identity.
Perhaps to make it obvious that they are navigation properties you can tag them e.g. for Samurai Quotes: 
Navigation *: Quotes
Quotes (Navigation)
Quotes (1:*)

just some ideas.

**Comment by ErikEJ** [comment]
Could it be:

Secretidentity (*:)

And

Quotes (1:)

**Comment by ErikEJ** [comment]
Could it be:
Secretidentity (1)
And
Quotes (*)
(and of course special color)
