### ISSUE TITLE
Error with tables "WITHOUT ROWID"

### ISSUE THREAD

**Issue by q1o1p** [ErikEJ/SqlCeToolbox#567]
![image](https://user-images.githubusercontent.com/22458230/32989747-865613e0-cd2d-11e7-98d3-a50c86f5e270.png)

Version 4.7.427.0
Database engine: SQlite
Visual Studio version: 2017 15.4.0

Db like this:

CREATE TABLE AllTypes (
    Id   INTEGER PRIMARY KEY ASC AUTOINCREMENT,
    Type INTEGER
);

CREATE TABLE Classes (
    Id      INTEGER REFERENCES AllTypes (Id) 
                    PRIMARY KEY,
    Name    STRING
)WITHOUT ROWID;

**Comment by ErikEJ** [comment]
Thanks for reporting this - fixed in latest daily build: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes
