### ISSUE TITLE
The option 'use table and columns names directly from database' dont work with fields with underscore

### ISSUE THREAD

**Issue by JuanIrigoyen** [ErikEJ/SqlCeToolbox#576]
My tables and fields names use underscore as char in their names, I set the option 'use table and columns names directly from database', buy when the entity is generated the name of field with underscore disappear.

### Steps to reproduce
Generate a entity with a field called 'Invoice_date' and generate the entity.
The tool generated a name called 'InvoiceDate'

### Further technical details
Toolbox/Power Tools version: EF Core Power Tools Version 4.7.437.0
Database engine: (SQL Server 2016)
Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
This is a know bug, and will be fixed in EF Core 2.1: https://github.com/aspnet/EntityFrameworkCore/issues/9820

**Comment by ErikEJ** [comment]
Add info to wiki page here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools
