### ISSUE TITLE
Not CaseSensitive

### ISSUE THREAD

**Issue by MESalar** [ErikEJ/SqlCeToolbox#578]
In the name of God

Hello

I have Problem with generated model from SQL table
for example
column Name : FoodStuffID
generated as : FoodStuffId

I Want exactly: FoodStuffID

**Comment by ErikEJ** [comment]
Assume you are referring to EF Core Power Tools - have you tried the option: "Replace Id with ID" ?

**Comment by MESalar** [comment]
Thanks for reply.
Obviously I do not want this.
for example:
I expect your model generator,  generate  "FoodStuffID" when my column name  in sql database is exactly  "FoodStuffID" . While what this tool produces is "FoodStuffId".
Why your tool change "ID" to "Id"? 
Is This EF code First Standard Convention?
Thanks.

**Comment by ErikEJ** [comment]
have you tried the option: "Replace Id with ID" ? ??
