### ISSUE TITLE
System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by aspramsh** [ErikEJ/SqlCeToolbox#580]
Hi ErikEj,

When trying to generate entities and DB Context with reverse Engineer, I get the following error:

System.IO.FileNotFoundException: Could not load file or assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Diagnostics.DiagnosticSource, Version=4.0.2.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Microsoft.EntityFrameworkCore.Scaffolding.Internal.ScaffoldingServiceCollectionExtensions.AddScaffolding(IServiceCollection serviceCollection, IOperationReporter reporter)
   at ReverseEngineer20.EfCoreReverseEngineer.GenerateFiles(ReverseEngineerOptions reverseEngineerOptions)
   at EFCorePowerTools.Handlers.ReverseEngineerHandler.<ReverseEngineerCodeFirst>d__2.MoveNext() in C:\projects\sqlcetoolbox\src\GUI\EFCorePowerTools\Handlers\ReverseEngineerHandler.cs:line 110

I am using Visual Studio Enterprise 2017 Version 15.4.4 and SSMS 17.3. Could you please help me to fix this?

**Comment by ErikEJ** [comment]
Can you build and run your project? 

If yes, can you share your packages.config and .csproj files.

**Comment by ErikEJ** [comment]
Which version of EF Core Power Tools?

**Comment by aspramsh** [comment]
I've downloaded the last version of EF Core Power Tools. I can build my project, now I will share the files you mentioned.

**Comment by aspramsh** [comment]
EF Core Power Tools version is 1.0.451.

**Comment by ErikEJ** [comment]
No need to share anything, I was able to reproduce!

**Comment by aspramsh** [comment]
ok :)

**Comment by aspramsh** [comment]
Thanks a lot, everything now is working just fine :)

**Comment by ErikEJ** [comment]
What happended?

**Comment by aspramsh** [comment]
I've just updated the package after your last commit, and everything worked.

**Comment by ErikEJ** [comment]
Which version are you running now?

**Comment by aspramsh** [comment]
1.0.455.

**Comment by ErikEJ** [comment]
Thanks for your bug report and help with testing the fix!

**Comment by ErikEJ** [comment]
And thanks for the review 😄

**Comment by aspramsh** [comment]
You are welcome! 😄

**Comment by shadowfoxish** [comment]
I was having the same issue as well. The daily build solved it. (1.0.458)

**Comment by ErikEJ** [comment]
Thanks, I will update the official build soon

**Comment by shadowfoxish** [comment]
This might be a theme thing (I have pretty heavily customized theme in VS), but in the daily version (458) the labels aren't visible on the screen that asks for the context name, namespace, and folder.

![image](https://user-images.githubusercontent.com/12143535/33284785-3c387e86-d37e-11e7-86c6-0001c24232e9.png)

**Comment by ErikEJ** [comment]
Hi, I think I have done all I can, but please file a new issue and I will investigate
