### ISSUE TITLE
Support for project initially created using VS Code

### ISSUE THREAD

**Issue by fmorriso** [ErikEJ/SqlCeToolbox#587]
Right-click on a .csproj file does not reveal any reverse engineering capability, perhaps by design?

### Steps to reproduce
1. Create a project using Visual Studio Code (1.18.1) and add an Angular 5.x piece, following the instructions at https://www.codeproject.com/Articles/1206306/Integrating-ASP-Net-Core-and-Angular-project.

2. Use Visual Studio 2017's "Open Folder" capability to open the folder containing the project (e.g., c:\projects\hello-world\). (Yes, I know this seems a bit absurd, since the project was initially created using Visual Studio Code and dotnet command-line entries).

3. In Solution Explorer, right-click on the .csproj file.

4. No Reverse Engineer option appears.

### Further technical details
Toolbox/Power Tools version:  4.7.427.0

Database engine: Azure SQL Server

Visual Studio or SSMS version: Visual Studio 2017 Enterprise (15.4.5)

Copy/Paste from the About icon screen:
Version 4.7.427.0 - 960,353 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.105.1
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by ErikEJ** [comment]
The tool requires a project system in order to create build output, as it relies on inpsection of build out (dll files) not source code, so this is not supported. Just open the project file in VS
