### ISSUE TITLE
Time representation

### ISSUE THREAD

**Issue by skaa** [ErikEJ/SqlCeToolbox#588]
Different time representation on different Result view type.

### Steps to reproduce
Show Result in Grid = **true**, Use classic (plain) grid = false
record Id=d9e3c545-2644-4339-8214-c6712034cb47, Created=12/8/2017 12:00:03 AM
![1](https://user-images.githubusercontent.com/494532/33753792-fd1d4df4-dc0a-11e7-9864-222142c01ce8.png)
Show Result in Grid = **false**, Use classic (plain) grid = false
record Id=d9e3c545-2644-4339-8214-c6712034cb47, Created=2017-12-08T00:00:03.9970000
![2](https://user-images.githubusercontent.com/494532/33753793-fd3f1bfa-dc0a-11e7-9dc2-b631b3c48e4a.png)
Second is the right one. When copying with Ctrl+C value is ok:
```
Created
--
08.12.2017 0:00:03
```
My timezone is UTC+05:00.
### Further technical details
Toolbox/Power Tools version: extension SQLite / SQL Server Compact Toolbox 4.7.427 (23.11.2017)

Database engine: SQL Compact

Visual Studio or SSMS version: Visual Studio 2017 15.4.4

**Comment by ErikEJ** [comment]
Thanks for suggesting this, it is fixed in the latest daily build: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes
