### ISSUE TITLE
EFPT: templates with .NET Core / .NET Standard

### ISSUE THREAD

**Issue by OmiCron07** [ErikEJ/SqlCeToolbox#597]
Is there an easy way to update the database definition instead to go all through the wizard?

Also, I can't get the templates working. I changed the DbContext template, re-run the wizard and it was not used at all. 

For information, my project is a .Net Standard 2.0.

**Comment by ErikEJ** [comment]
Which feature are you refering to?

**Comment by OmiCron07** [comment]
Reverse engineer to generate my database definitions.

**Comment by ErikEJ** [comment]
>> Is there an easy way to update the database definition instead to go all through the wizard?

You can save the Connection and the table definition.. Or are you referring to something else?

>> Also, I can't get the templates working. I changed the DbContext template, re-run the wizard and it was not used at all.

Did you set the checkmark to use the template both runs?

**Comment by OmiCron07** [comment]
Yes, the connection and table list are saved. But, how to add tables or columns to existing tables without going through the wizard and manually defining the same context name and the same path, checking the same options? Because for me, when I re-run the wizard, I get back to default values.

Yes, I checked the use of the templates, I get the template files, but my modifications are not taken in account. Or I don't understand how to use the templates?

**Comment by ErikEJ** [comment]
Are you proposing an option to save the selections on the options dialog?

Could you try to test the templates with a .NET Core or .NET Framework project?

**Comment by OmiCron07** [comment]
Ideally, I want the same experience than with EDMX. Once the EDMX is created, I can open it, right-click, update, choose my tables and save. Or at least, like our custom database provider with T4, once created, right-click on the T4 file, run custom tool.

Same results with a .Net Core project. How am I suppose to use the templates? You don't have documentation for that and maybe I don't use them adequately?

**Comment by ErikEJ** [comment]
OK, I have logged https://github.com/ErikEJ/SqlCeToolbox/issues/598 - I cannot give you the EDMX experience exactly, as no EDMX exists in EF Core.

I will do some testing with the template feature, did you read this: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools ?

**Comment by OmiCron07** [comment]
Ok thank you. I know you can't give the same experience, but just the ease of use with a few click, because with multiple people, I guaranteed there will be many DbContext!

Yes I read, but I don't know this new type of template and when I re-run the wizard, my modifications in the template are not taken in account.

**Comment by ErikEJ** [comment]
Re template: I was able to repro, and have attempted a fix in the latest daily build.

**Comment by ErikEJ** [comment]
Please let me know if the fix worked for you!

**Comment by OmiCron07** [comment]
1. Installed 1.0.481 from the daily build link
2. Make some modifications to DbContext.hbs template
3. Run reverse engineer wizard
4. Specify my current context name
5. Specify my current Data
6. Check pluralize option
7. Check customize code
8. Click Ok
9. Successful message, but default DbContext generated

It doesn't work. Am I using the template the good way?

**Comment by OmiCron07** [comment]
Finally, it has worked. I had to reload the solution to see the changes.

**Comment by ErikEJ** [comment]
I have found another bug, working on a fix.. It should not be required to reload the solution :smile:

**Comment by ErikEJ** [comment]
Basically, VS does not register if the file has changes with .NET Core projects...

**Comment by ErikEJ** [comment]
Try the latest build...

**Comment by OmiCron07** [comment]
Tried the new version (still 1.0.481?) and I don't have to reload the solution, but to close and re-open the file if already opened (in .Net standard class library).

**Comment by ErikEJ** [comment]
Corect - I have no good solution for that... Latest build is 1.0.482 (maybe I posted my message too early)
