### ISSUE TITLE
Converting from MDF to SDF

### ISSUE THREAD

**Issue by simonjeffs** [ErikEJ/SqlCeToolbox#60]
I created a new SDF file using the Right Click | Add Compact 4.0 connection. I then used the script database and schema feature to generate a file I could then use to add the tables and data from my MDF file. I creates the tables  but then errors:

Error Code: 80040E14
 Message   : A quotation mark delimiter is missing from the end of the query.
 Minor Err.: 25511
 Source    : SQL Server Compact ADO.NET Data Provider

It appears I have tables, no primary keys created and no data added. Have I missed something

**Comment by ErikEJ** [comment]
Maybe you foudn a bug - but I think you need to share the offending script

**Comment by simonjeffs** [comment]
Can I email directly rather than share?

**Comment by ErikEJ** [comment]
Feel free to email!

**Comment by simonjeffs** [comment]
I forgot I have encrypted a column during testing. I decrypted it and the script worked.

**Comment by ErikEJ** [comment]
Great news - If you use my tools, I would be very grateful for a rating or review here:

https://visualstudiogallery.msdn.microsoft.com/0e313dfd-be80-4afb-b5e9-6e74d369f7a1/view/Reviews
