### ISSUE TITLE
Reveng: Generates nullable bool

### ISSUE THREAD

**Issue by enriko-riba** [ErikEJ/SqlCeToolbox#603]
This is more a question (EF Core scope)...
Why is the configuration for NOT NULL fields with default values using constructs like:
```
entity.Property(e => e.Created).HasDefaultValueSql("(getutcdate())");
entity.Property(e => e.IsActive).HasDefaultValueSql("((1))");
```
With CLI scaffolding I used to override OnModelCreating and add a:
```
foreach (var type in tableTypes)
{
    modelBuilder.Entity(type).Property("Created").ValueGeneratedOnAdd();
}
```
This is working well even for non nullable value types where during inserts EF simply ignores the supplied value. 

Also noticed that the NOT NULL bit fields get reverse engineered as nullable types:
`public bool? IsActive { get; set; }`

This breaks the existing code base as all predicates containing IsActive in the expression now produce syntax errors.

**Comment by ErikEJ** [comment]
This was introduced in EF Core 2, sadly. Are you using the latest EF Core Power Tools?

**Comment by enriko-riba** [comment]
I guess I am, just installed today (v 1.0.491).
Any chance the nullable value types generation for NOT NULL fields with default values gets an on/off switch on the GUI or in the configuration json? 
I like the power tools tools much better than the scaffolding process bit this is a showstopper for folks with existing large code bases.

**Comment by ErikEJ** [comment]
I am simply using the existing EF Core scaffolding bits, so not able to change this until 2.1 arrives.

Pls share the CREATE TABLE script for the table with NOT NULL bit fields...

**Comment by enriko-riba** [comment]
```
CREATE TABLE [dbo].[NewTable](
	[Id] [int] IDENTITY(1,1) NOT NULL,	
	[IsActive] [bit] NOT NULL,
	[Created] [datetime2](7) NOT NULL
 ) ON [PRIMARY]
GO
ALTER TABLE [dbo].[NewTable] ADD  CONSTRAINT [DF_NewTable_IsActive]  DEFAULT ((1)) FOR [IsActive]
```
If I scaffold the IsActive field is mapped into a non nullable property as opposed to the generated `bool? IsActive` I get by using the power tools

**Comment by ErikEJ** [comment]
>> If I scaffold the IsActive field is mapped into a non nullable property 

What EF Core version are you using?

**Comment by enriko-riba** [comment]
dotnet --version
2.1.2

**Comment by ErikEJ** [comment]
That is also the version used by EF Core power tools, so I do not understand this statement:

>> If I scaffold the IsActive field is mapped into a non nullable property

What do you mean by that?

**Comment by enriko-riba** [comment]
I scaffolded my db hundred of times by using:
`"dotnet ef dbcontext scaffold "Data Source=sql01.xxx.xxx;...etc" Microsoft.EntityFrameworkCore.SqlServer -o DAL -c XXXContext -f --no-build"`
Always with same results: tables containing a NOT NULL BIT field with a default value get scaffolded into types with non nullable properties like this one: `public bool IsActive { get; set; }`
If I use EF Power Tools such properties turn into nullable types e.g. `public bool? IsActive { get; set; }`

I hear what you are saying .... but the end result is differs. :-(

**Comment by enriko-riba** [comment]
Not sure if this helps but my EF CLI version is:
```
dotnet ef --version
Entity Framework Core .NET Command Line Tools
2.0.0-rtm-26452

**Comment by ErikEJ** [comment]
Maybe you are using the 2.0.0 bits from command line iso 2.0.1 bits

**Comment by ErikEJ** [comment]
I will consider using 2.1 preview bits, they contain a fix for this

**Comment by ErikEJ** [comment]
Related bug fix: https://github.com/aspnet/EntityFrameworkCore/issues/10305

**Comment by ErikEJ** [comment]
2.1 bits now in latest daily build, pls let me know if it works for you
