### ISSUE TITLE
Mappings in separate file

### ISSUE THREAD

**Issue by mtugnoli** [ErikEJ/SqlCeToolbox#605]
All work fine !!
But I think is better to make a single file for each mapping

**Comment by ErikEJ** [comment]
Could you share a example of how this should be done.

**Comment by mtugnoli** [comment]
EfCorePowerTools.cs is actualy file created by "Reverse Engineer" function,
on OnModelCreating you can see there are ALL configurations (mappings)
in my sample ("EfCorePowerToolsContextWithConfigs.cs") the configurations are
each in a single external file
[EFModels.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1603004/EFModels.zip)
![project](https://user-images.githubusercontent.com/459399/34558780-bb2538a4-f13f-11e7-9260-dd456503b03b.png)

**Comment by ErikEJ** [comment]
Moving to backlog, will require many changes in the EF Core code gen
