### ISSUE TITLE
Bug on bit fields

### ISSUE THREAD

**Issue by mtugnoli** [ErikEJ/SqlCeToolbox#607]
Reverse Engineering :

I've found a little bug.
bit fields : the corresponding property in the class is always nullable

es.
  public bool? IsDeleted { get; set; }     <- im my db this field is not nullable

have to be :
  public bool IsDeleted { get; set; }

**Comment by ErikEJ** [comment]
Duplicate of #603 - I will investigate upgrading to 2.1 preview
