### ISSUE TITLE
Something is missing

### ISSUE THREAD

**Issue by mtugnoli** [ErikEJ/SqlCeToolbox#608]
PS: sorry for many post, but your tool is very helpful !!

this is sql for a sample table :

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [Security].[Roles](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Description] [nvarchar](50) NOT NULL,
	[Name] [nvarchar](20) NOT NULL,
	[IsDeleted] [bit] NOT NULL,
	[CreatedOnUtc] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [Security].[Roles] ADD  CONSTRAINT [DF_Roles_IsDeleted]  DEFAULT ('false') FOR [IsDeleted]
GO

this is actual reverse engineer config :

modelBuilder.Entity<Role>(entity =>
{
	entity.ToTable("Roles", "Security");
	entity.Property(e => e.Description).IsRequired().HasMaxLength(50);
        entity.Property(e => e.IsDeleted).HasDefaultValueSql("('false')");
	entity.Property(e => e.Name).IsRequired().HasMaxLength(20);
});

but I think have to be this :

modelBuilder.Entity<Role>(entity =>
{
	entity.ToTable("Roles", "Security");
	entity.HasKey(e => e.Id);
	entity.Property(e => e.Name).HasMaxLength(20).IsRequired();
	entity.Property(e => e.Description).HasMaxLength(50).IsRequired();
	entity.Property(e => e.CreatedOnUtc).IsRequired();
	entity.Property(e => e.IsDeleted).IsRequired().HasDefaultValueSql("('false')");
});

**Comment by ErikEJ** [comment]
Please keep the feedback coming, it is what makes this tool better for all users!

Please keep in mind, that Rev Eng is just a GUI wrapper over the scaffolding tooling that EF Core provides, so I have limited control over the generated code.

The Ef Core scaffoling configuration tries to limit the amount of code generated, so default values / properties set by convention are not scaffolded. So the scaffolding is correct
