### ISSUE TITLE
SQLite Provider not available even updated app.config  and machine.config

### ISSUE THREAD

**Issue by Sarathir1** [ErikEJ/SqlCeToolbox#609]
I followed the steps which you provided, but still the provider is now available at ADO.NET Entity Data Model (EF designer from database)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio 2017 15.3.4

![image](https://user-images.githubusercontent.com/35233326/34684130-28add18c-f4ca-11e7-886e-4d36bbf4fe73.png)
### App config
![image](https://user-images.githubusercontent.com/35233326/34684215-63046846-f4ca-11e7-92ab-4e9e188531e0.png)

Even updated the machine.config file at C:\WINDOWS\Microsoft.NET\Framework\v4.0.30319\Config
### SQLite tool help
![image](https://user-images.githubusercontent.com/35233326/34684402-fef9e0e6-f4ca-11e7-8e8e-107e0570f467.png)

**Comment by ErikEJ** [comment]
Does the System.data.sqlite version in GAC and machine.config match?

**Comment by Sarathir1** [comment]
Yes, it's in GAC and matching with machine.config, even provider option is not available.

**Comment by ErikEJ** [comment]
No clue...

**Comment by ErikEJ** [comment]
Can you share a repro project, and your machine.config file? (from the C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config folder)

**Comment by Sarathir1** [comment]
I attached the sample project which exploring sqlite . The zip also contains machine.config.txt in it

[ExploreSQLite.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1628188/ExploreSQLite.zip)

Thanks 
Sarathi.R

**Comment by ErikEJ** [comment]
Thanks, I am able to repro, what providers do you see in Server Explorer ? (Data Connections, Add Connection) ?

**Comment by Sarathir1** [comment]
it is available there.
![image](https://user-images.githubusercontent.com/35233326/34905994-cf866f92-f889-11e7-94f1-41da262bf92e.png)

How to add using Entity framework model

**Comment by ErikEJ** [comment]
Could you try the latest daily build, I have upgraded the included SQLite ADO.NET provider to the latest release.

**Comment by ErikEJ** [comment]
You have not installed the System.Data.SQLite NuGet package in your project! (so you did not follow all steps in my guide properly)
