### ISSUE TITLE
Comment in view causes problem

### ISSUE THREAD

**Issue by heckl** [ErikEJ/SqlCeToolbox#611]
There is problem is with "SQLite-SQL Server Compact Toolbox". If the definition of the Views has comments then you can not add entity framework based on your database using Visual Studio. Though the database is ok, the select * from myTable works. Rider has no problem with comments in View. The toolbox has no problem with comment in table just in the view.

**Comment by ErikEJ** [comment]
Please share a database that demonstrates this issue.

And please which exact Toolbox feature are you referring to?

**Comment by heckl** [comment]
see the original problem at: https://stackoverflow.com/questions/48174277/visual-studio-2017-does-not-handle-properly-sqlite-db?noredirect=1#comment83364710_48174277

or in Visual Stuio 2017, using "SQLite-SQL Server Compact Toolbox" create a table, create a view which has some comment in it; 

create view MyView as
-- this comment will cause an error
Select * from MyTable;

now if you select "edit top 200 rows" in "SQLite-SQL Server Compact Toolbox" there will be an error
if you "add new item / data / ado.net entity data model" based on this db there will be an error

**Comment by ErikEJ** [comment]
>> now if you select "edit top 200 rows" in "SQLite-SQL Server Compact Toolbox" there will be an error

"an error" ?? Which error?

>> if you "add new item / data / ado.net entity data model" based on this db there will be an error

"an error" ?? Which error?

**Comment by heckl** [comment]
![image](https://user-images.githubusercontent.com/16515220/34813096-e5ef91c4-f6a8-11e7-854a-bb643bf4f767.png)
after you create the view with the comment, and select the first option, there will be a dialog box with an errror message. The message is something like "missing database or sql logic error near: -- this comment will cause an error Select * from MyTable;" 
I am working at this moment so I can not make screenshot from the actual error message.

**Comment by ErikEJ** [comment]
Thanks, and how about: 

>> if you "add new item / data / ado.net entity data model" based on this db there will be an error

"an error" ?? Which error?

Can you share a database that demonstrates the issue?

**Comment by heckl** [comment]
the db contains some sensitive data, so I can not send it
but both errors is caused by the comment in view; if I recreated the view without the comment then both error was gone

![image](https://user-images.githubusercontent.com/16515220/34813886-f22d679c-f6ab-11e7-8fad-eba7fdd86315.png)
the second error occured after this step (a dialog window with an error message)

**Comment by ErikEJ** [comment]
I am not asking for your production database file, just a file that demonstrates the issue...

**Comment by heckl** [comment]
![image](https://user-images.githubusercontent.com/16515220/34830721-0b64b088-f6e5-11e7-96d4-882561fc8d40.png)
after you want to edit the table

![image](https://user-images.githubusercontent.com/16515220/34830734-14e1756a-f6e5-11e7-8b85-cd63243e410a.png)
you get this error message because there is a comment in the view

the database is this: 
https://www.dropbox.com/s/2nqq7sz8rjotgik/new3.db?dl=0

**Comment by ErikEJ** [comment]
Thanks for the info, it is a bug in the ado.net provider I use (System.data.sqlite) - but I think I can implement a workaround

**Comment by ErikEJ** [comment]
This is fixed in the latest daily build, pls let me know if it fixes your issue

**Comment by sajanmittal** [comment]
I am inserting new data into a table in my DB. When I query from cmd i am getting my updated data, but when I query from SQLite toolbox is it not giving me refreshed data.

**Comment by ErikEJ** [comment]
@sajanmittal Please submit a new issue with a repro database, thanks
