### ISSUE TITLE
SQlCeToolbox does not handle the names of the calculated columns

### ISSUE THREAD

**Issue by heckl** [ErikEJ/SqlCeToolbox#612]
I have a table and a corresponding view. In VS2017 I try "Script Select" for the view. 

![image](https://user-images.githubusercontent.com/16515220/34832765-1298b15c-f6ee-11e7-84cc-163637bbb7fd.png)

The calculated columns appear without name in the select. 
-- Script Date: 2018.01.11. 16:37  - ErikEJ.SqlCeScripting version 3.5.2.74
SELECT [Id]
      ,[weight]
      ,[]
  FROM [MyView];

The DB is good, because if you insert the missing name the script works. 

I strongly suspect that the same prolbem appears in a different format. If Entity framework is used based on the db then there will be no error message but the generated file for the view do not contain properties for the caluclated columns. The example db can be downloaded from:
https://www.dropbox.com/s/nxetdei1w7aemgk/New4.db?dl=0

**Comment by heckl** [comment]
Hi, is the problem well demonstrated? Do you need any additional info?

**Comment by ErikEJ** [comment]
I have all I need for now, just have not had time to look into this issue

**Comment by heckl** [comment]
One more piece of info: Not all the calculated columns are missing: 
SELECT [AccountName]
      ,[Date1]
      ,[Date2]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[]
      ,[PeriodType]
      ,[]
      ,[LiqudityCategory]
      ,[]
      ,[]
      ,[]
      ,[HistoryExtension]
      ,[BalanceExtension]
      ,[StatementExtension]
  FROM [AccountPeriodView];

Where [HistoryExtension], [BalanceExtension], [StatementExtension] are calculated columns. 
Now it is sure that the missing fields are not appear in the generated ADO object corresponding to the EntityFramework.

**Comment by heckl** [comment]
Hi! Do you need any additional information about this bug which can help to fix it? So you might have a schedule?

**Comment by ErikEJ** [comment]
As the other issue you reported, I suspect this is a bug in system.data.sqlite. I will investigate if a workaround is possible

**Comment by ErikEJ** [comment]
As suspected, this is a bug deep down in System.Data.SQLite, that I have no means or resources to fix. All I can suggest for now is to exclude the column if it is unnamed, thus generating a proper SQL SELECT statement - what do you think?

**Comment by ErikEJ** [comment]
Fixed in latest build

**Comment by heckl** [comment]
Hi! 
I am not sure from your comments if the bug is supposed to be fixed or not. The last two comments contradicts.

I have updated the sqlite toolbox.  

The  "script as select" now omits the calculated column. For the test file it gives:
https://www.dropbox.com/s/nxetdei1w7aemgk/New4.db?dl=0

-- Script Date: 2018.02.12. 17:25  - ErikEJ.SqlCeScripting version 3.5.2.75
SELECT [Id]
      ,[weight]
  FROM [MyView];

The calculated column DoubleWeight is missing.

I tried "script as select" on a more complicated view like: 

CREATE VIEW AccountView as
  WITH Date1Cte AS (
      SELECT  *,
        (SELECT Parameter.Value
         FROM Parameter
         WHERE Parameter.Name = 'Date1')
          AS Date1,
        (SELECT Parameter.Value
         FROM Parameter
         WHERE Parameter.Name = 'Date2')
          AS Date2
      FROM Account AS TOut
  )
  SELECT
    Name,
    LiquidityCategory,
    HistoryExtension,
    BalanceExtension,
    StatementExtension,
    CASE WHEN Date2 < OpeningDate
      THEN 0
    WHEN ClosingDate < Date1
      THEN 0
    ELSE 1
    END
      AS Active,
    OpeningDate,
    ClosingDate,
    Id
  FROM Date1Cte
;

Here I got a  SQLite/SQL server compact toolbox
Error code: 1
Message:  SQL logic error near "(" syntax error
Result: Error

**Comment by ErikEJ** [comment]
I have "fixed" the bug by excluding the unnamed, calculated column from the column list. For the second, more complex view, I will do no further work, as the implementation of schema information from sqlite is too limited.

**Comment by heckl** [comment]
Hi! One last thing. You said "As suspected, this is a bug deep down in System.Data.SQLite" It would be nice if you could report this bug to SQlite. You know the details this bug much better than me.

**Comment by ErikEJ** [comment]
@heckl YOu can report the issue here: http://system.data.sqlite.org//index.html/ticket
