### ISSUE TITLE
Failed importing entites without primary keys

### ISSUE THREAD

**Issue by JipingWang** [ErikEJ/SqlCeToolbox#613]
I was importing entities but kept being failed.  Tried many times with different options, finally found that my table needs a primary key definition.

Suggestion: is it possible to give clear error or warning messages for this situation? It wasted me some time without any clue.

**Comment by ErikEJ** [comment]
Did you look in the VS output window? 

How do you suggest I could improve this - showing the tables in the list, but grayed out and labelled 

    TableName (No primary key) 

perhaps?

**Comment by ErikEJ** [comment]
Lastes build does not list table with no primary key
