### ISSUE TITLE
Reverse Engineer - 4.7.497 version 

### ISSUE THREAD

**Issue by mtugnoli** [ErikEJ/SqlCeToolbox#615]
I just testing on SQL Server 2017,
all seem run but primarykey definitions are missing

es.
           entity.HasKey(t => t.Id);

**Comment by ErikEJ** [comment]
Is that different from previous release? 

(If the key is named Id, it will be by convention, and no fluent code is needed)

**Comment by mtugnoli** [comment]
thank you, I did not know it.
also
.IsRequired() is missing for same reason ?

**Comment by ErikEJ** [comment]
Yes (it is not used for nu-nullable values)
