### ISSUE TITLE
Empty screen on "Choose Your Data Connection"

### ISSUE THREAD

**Issue by gmansi** [ErikEJ/SqlCeToolbox#616]
Empty screen on "Choose Your Data Connection"

My configuration is:

Microsoft Visual Studio Community 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Community

Visual C# 2015   00322-20000-00000-AA175
Microsoft Visual C# 2015

SQLite & SQL Server Compact Toolbox   4.7
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

I create a new WPF proyect, create the SQLite Data base with SQLite & SQL Server Compact Toolbox  and populate some data.

Then I add the "ADO.NET Entity Data Model" - EF Designer from database and I'm get the empty screen on "Wich data connection should your application use to connect to the database"?

I installed SQLite / EFM from the NuGet Package Manager and also manually from the console. The same result

Maybe the same problem on https://github.com/ErikEJ/SqlCeToolbox/issues/609 ??

**Comment by ErikEJ** [comment]
Did you try the latest daily build?

Did you follow this guide: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider ?

**Comment by gmansi** [comment]
First part solved installing again sqlite-netFx46-setup-bundle-x86-2015-1.0.106.0.exe with "Install the assemblies into the global assembly cache" option.

Now I have the connection and the Model Diagram is fine.

Still I have a error when I type

using (var db = new MyEntity())

the name MyEntity (or anyother) is not listed.

I will uninstall and reinstall all over again and report if I have another trouble.

Thanks!

**Comment by gmansi** [comment]
Just for your info, following the guide on https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider I solved all the troubles.

I was using individual commands like:
install-package System.Data.Sqlite.Core -version 1.0.105.2
install-package System.Data.Sqlite.EF6 -version 1.0.105.2
install-package System.Data.Sqlite.Linq -version 1.0.105.2

Now using only
Install-Package System.Data.SQLite

All works ! Thanks

**Comment by ErikEJ** [comment]
Great news, and thanks for the update! Let me know if the guide can be made clearer!
