### ISSUE TITLE
[EF Core Power Tools] Support for MySQL, Oracle and others

### ISSUE THREAD

**Issue by AllanTee** [ErikEJ/SqlCeToolbox#617]
See PR https://github.com/ErikEJ/SqlCeToolbox/pull/645 for an example of  how this could be done.

Requires: 
- DDEX provider + full .NET Framework ADO.NET provider.
- EF Core 2.x provider that implements IDesignTimeServices

**Comment by ErikEJ** [comment]
Looks like the building blocks are present, let me know if you would be able to help test this?

https://dev.mysql.com/downloads/windows/visualstudio/
https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql

**Comment by AllanTee** [comment]
Hi Erik,

The Pomelo thing works. At least it connected to external MySQL database and did the "Scaffold-DbContext" miracle, which I needed. Thank You very much!!!
Consider to develop MySQL support to your tool as well. :-)

**Comment by AllanTee** [comment]
Thank you!

**Comment by Pangamma** [comment]
I would love this to become a feature.

**Comment by ErikEJ** [comment]
@Pangamma PRs accepted 😁

**Comment by ErikEJ** [comment]
@Pangamma  Which provider are you looking for?

**Comment by Pangamma** [comment]
@ErikEJ  MySQL.

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#17
