### ISSUE TITLE
Is this working on non-default scheme (dbo)?

### ISSUE THREAD

**Issue by JipingWang** [ErikEJ/SqlCeToolbox#618]
I imported 3 tables, one in default dbo scheme, ther other 2 in "tmp" scheme. But it just imported dbo tables.

Does this work on custom scheme tables? Or, I was doing something wrong?

**Comment by ErikEJ** [comment]
Are you talking about reverse engineer in EF Core Power Tools?

Does your tables in tmp schema have primary keys?

**Comment by ErikEJ** [comment]
Closing as requested additional info was not provided

**Comment by JipingWang** [comment]
(Sorry, didn't notice the mail message).
You are right, my tables don't have primary keys, I found that and fixed the issue. 

Is this open source, I want to contribute a little.

**Comment by ErikEJ** [comment]
Yes, it is open source, and contributions are most welcome!
