### ISSUE TITLE
Blob field always assumed as "image" datatype

### ISSUE THREAD

**Issue by RoySalisbury** [ErikEJ/SqlCeToolbox#619]
My tables have a "blob" field that I store a Guid in.  However, the VS addin always thinks its an "image" data type.  At the least, it should show the data as binary (hex) and not assume a data type.

Adding a way to display blob types as guid/uniqueidentifier would be helpful.

**Comment by ErikEJ** [comment]
Have you tried a SELECT in the query window?

**Comment by RoySalisbury** [comment]
Yes, in that case it shows “Byte[] Array”.  I was specifically talking about the “Edit top 200 Rows” view.  Sorry if I did not mention that.

Roy

**Comment by ErikEJ** [comment]
You can enable the option: "Show binary values in result" then (in the editor)
