### ISSUE TITLE
Custom type mapping

### ISSUE THREAD

**Issue by mbeckenbach** [ErikEJ/SqlCeToolbox#621]
This project is awesome! It feels just like the db first workflow is coming back. But there is one feature that I am really missing.

In EF6 DB First, there is this amazing feature of mapping external types to properties.
This can be perfectly be used for transforming an integer culumn into a C# enum.

EF Core supports enum properties and maps those to integer columns in the database.

When doing a reverse engineer, all integer columns get generated as integer properties as it should be. Then one can simply change a properties type to some enum type, which exists in the project. Works great.

But when repeating the reverse engineer process to update the generated model from database, the file will be overwritten, which removes the modification of the properties type.

So I was thinking about how it would be possible to preserve this modification.

One way of doing this could be to create a code template for a specific class file. I had a look at EntityFrameworkCore.Scaffolding.Handlebars by @tonysneed but I dont see a way for doing this.

Another idea was to extend the efpt.config.json with an array of type mappings, that could be applied after code generation. Could something like that be implemented in your tool?

```json
{
  "ContextClassName": "EfcoretestContext",
  "DatabaseType": 2,
  "IdReplace": false,
  "IncludeConnectionString": true,
  "OutputPath": "Models",
  "ProjectRootNamespace": "EFCoreTest",
  "SelectedToBeGenerated": 0,
  "Tables": [ "dbo.Posts", "dbo.Users" ],
  "UseDatabaseNames": false,
  "UseFluentApiOnly": true,
  "UseHandleBars": true,
  "UseInflector": true,
  "TypeMappings": [
    { "Column": "dbo.Posts.Category", "Type": "Enums.Categories" }
  ]
}
```

**Comment by ErikEJ** [comment]
Anything goes, and the tool is open source and welcomes contributions!

Could you show an example of what a class with a Enum would look like before and after this?

**Comment by mbeckenbach** [comment]
Hi @ErikEJ, good to hear that.

A typical example for my use case would be like this. You have a custom enum in some folder/namespace and a generated class like the ones below.

```c#
namespace EFCoreTest.Enums
{
    public enum Categories
    {
        SomeCategory = 0,
        AnotherCategory = 1,
        MoreCategories = 2
    }
}
```

```c#
namespace EFCoreTest.Models
{
    public partial class Post
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int Category { get; set; }
    }
}
```

After transformation the class would simply look like this:

```c#
public partial class Post
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Enums.Categories Category { get; set; }
    }
```

**Comment by ErikEJ** [comment]
OK. since I just get the generated files, maybe it would be better with

```
 "TypeMappings": [
    { "Class:"Post" "Property":"Category", "Type": "Enums.Categories" }
  ]
```
Do a PR, perhaps?

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L130

**Comment by mbeckenbach** [comment]
I have never edited a vs extension. But i'll try at weekend. :-)
Thanks for the hint on the line.

**Comment by ErikEJ** [comment]
Great, let me know if you hit any stumbling blocks! (It is a bit more involved than a standard Nuget library)

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#16
