### ISSUE TITLE
Exclude sysdiagrams

### ISSUE THREAD

**Issue by mbeckenbach** [ErikEJ/SqlCeToolbox#623]
Describe what is not working as expected.

### Steps to reproduce
Create a database in ssms, add a diagram and start a reverse engineer.
I dont see any reason why one should import the sysdiagrams table, so it could be excluded by default.

![image](https://user-images.githubusercontent.com/6654388/35775602-1b40a0ac-098c-11e8-899a-6fcc86f56f98.png)

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
4.7.497.0

Database engine: (SQlite, SQL Compact or SQL Server)
SQL-Server 2017

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS 2017

**Comment by ErikEJ** [comment]
Fixed in latest "daily" build: https://github.com/ErikEJ/SqlCeToolbox/commit/49fac57b7096c0292b0fc76c9eded65cbe35b330
