### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by caojinqin** [ErikEJ/SqlCeToolbox#625]
This is a very great tool, and he should be integrated into VS2017 by Microsoft. There are some personal suggestions for improvement on this tool for reference:
1, increase in the interface settings options automatically generate column comments; such as:
/// <summary>
/// Automatically generate column descriptions
/// </ summary>
2, whether to automatically generate Display attributes such as:
  [Display (Name = "MyName")]
3, whether the name of the class file automatically renamed (default is not automatic) Such as
W_Article -> WArticle

Looking forward to these features can be further improved at some time, it will be more to enhance the coding efficiency, I am very grateful.

**Comment by ErikEJ** [comment]
Thanks for the review and your suggestions!

re 1: Where would the descriptions come from?

re 2: Where would the displayname come from? (and using your EF POCO classes for display is not recommended)

**Comment by caojinqin** [comment]
@ErikEJ 
1、Description It is best to read the column comments in the database.
2、Generated code can display properties on properties [Display (Name = "Name")]
3、I use the db first reverse engineering generated code.
Thanks again for your tools to greatly enhance our efficiency.

**Comment by Athuruga** [comment]
Proposal how to get the Information for each field from the SQL Database:

Change in:
private static SqlMetaData[] GetMetaData(int metaCount, string tableName, OleDbConnection conn)

Change the Command Text from:

cmd.CommandText = "SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @p1 ORDER BY ORDINAL_POSITION";

To:

cmd.CommandText = "SELECT COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, NUMERIC_PRECISION, NUMERIC_SCALE, (select Value from fn_listextendedproperty (NULL, 'schema', TABLE_SCHEMA, 'table', TABLE_NAME, 'column', COLUMN_NAME)  Where Name = 'MS_Description') AS [DESCRIPTION] FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME = @p1 ORDER BY ORDINAL_POSITION";

This provides the extended Property MS_Description of each field, which could then be used to get added as summary.

**Comment by ErikEJ** [comment]
Where is GetMetsData method??

**Comment by Athuruga** [comment]
GetMetsData  is in 

Project SqlCeCLR

file SqlCeCLR.cs

namespace ErikEJ.SqlCe

**Comment by ErikEJ** [comment]
Ok, but that has no relation to EF Core Power Tools !?

**Comment by ErikEJ** [comment]
Closing, and leaving in Backlog
