### ISSUE TITLE
After uninstalling the DataProviders are not removed !

### ISSUE THREAD

**Issue by ymg2006** [ErikEJ/SqlCeToolbox#630]
after uninstalling this extention from visual studio 2017 ,the "SQL Server Compact 4.0 Provider (Simple by ErikEJ)" and "SQLite Provider (Simple for EF6 by ErikEJ)" are still present in the visual studio DataProviders , please describe how to remove them !

### Steps to reproduce
install and uninstall from visual studio.

### Further technical details
Visual Studio 2017 15.3
![screenshot_1](https://user-images.githubusercontent.com/844238/36043478-b4108e4e-0de4-11e8-944e-451a50080e95.jpg)

**Comment by ErikEJ** [comment]
Are you sure "SQLite & SQL Server Compact Toolbox" is not still installed?

**Comment by ymg2006** [comment]
Yes is do , here is the screen shot with search keyword : "SQLite"
![screenshot_1](https://user-images.githubusercontent.com/844238/36044440-f260f53c-0de7-11e8-9baf-4f620c50bde5.jpg)

**Comment by ErikEJ** [comment]
Do you have EF Core Power Tools installed?

**Comment by ymg2006** [comment]
yes that's my bad, i uninstalled this and they are gone.
thanks for your fast reply,
