### ISSUE TITLE
Update Modal with DB changes

### ISSUE THREAD

**Issue by pethumishara** [ErikEJ/SqlCeToolbox#631]
How to update Models with newly added tables.
My database changes are done only in SQL server not in the Code.

**Comment by ErikEJ** [comment]
Just re-run the Reverse Engineer process, make sure the new tables are selected ??

**Comment by pethumishara** [comment]
Thanks.
Is there anyway to add stored procedures?

**Comment by ErikEJ** [comment]
No, EF Core does not support stored procedure mapping ATM

**Comment by pethumishara** [comment]
Thanks.
My existing database has already stored procedures.
So, i have to use manual ODBC connection for that?

**Comment by ErikEJ** [comment]
No, you can use EF Core, if they return shapes like your entities: FromSQL - https://docs.microsoft.com/en-us/ef/core/querying/raw-sql
