### ISSUE TITLE
Use column names from table 

### ISSUE THREAD

**Issue by dgxhubbard** [ErikEJ/SqlCeToolbox#632]
Just downloaded EF core power tools and it is great. There is an option to 
"Pluralize or singularize object names" and 
"Use table and column names from database".

What I really need is an option to use column names from database, and to singularize object names.
Is that possible?

**Comment by ErikEJ** [comment]
No, it is either/or, sorry

**Comment by ErikEJ** [comment]
The "column names from database" feature is also kind of broken

**Comment by dgxhubbard** [comment]
That's what I thought. Is it possible to do some of this through code generation?

**Comment by ErikEJ** [comment]
Please share an example of exactly what you want to acheive

**Comment by ErikEJ** [comment]
I am considering making this happen in my Dacpac based model factory

**Comment by dgxhubbard** [comment]
I would appreciate it. We have a lot of code that uses our current column names so it would help us.
Thanks

**Comment by ErikEJ** [comment]
But do you have a dacpac involved?

**Comment by ErikEJ** [comment]
Actually, what is not working with the default behaviour?

**Comment by ErikEJ** [comment]
Possible dupe of #640
