### ISSUE TITLE
Use Database Annotation

### ISSUE THREAD

**Issue by SgTS2020** [ErikEJ/SqlCeToolbox#635]
reverse Engineer  with "use Database Annontation" generate à InverseProperty tag on the two part of all "unique" one to many relation and add redondant informations in the context in fluent API for the same relation. 

```
public partial class TMember
{
         ...
         [ForeignKey("Acsid")]
         [InverseProperty("TMembers")]
          public TActivitySector Acs { get; set; }
}
```

  ```
 public partial class TActivitySector 
{
         ...
        [Key]
        [Column("ACSId")]
        [StringLength(3)]
        public string Acsid { get; set; }
 
        [InverseProperty("Acs")]
        public ICollection<TMember> TMembers { get; set; }
    }

```
In the DbContext :

```
 modelBuilder.Entity<TMember>(entity =>
 {
... 
entity.HasOne(d => d.Acs)
                    .WithMany(p => p.TMembers)
                    .HasForeignKey(d => d.Acsid)
                    .HasConstraintName("FK_Member_Ref_ActivitySector");
...
}

```
Seems me that, in this case, InverseProperty is not required on the relation and the fluent API declaration or the tag version must be used but not the two on the same generation.

Best regards,

### Steps to reproduce

use Database Annontation option

### Further technical details
Toolbox/Power Tools version: 4.7.525.0
Database engine: SQL Server

Visual Studio or SSMS version: Visual Studio 2017 15.5.6

**Comment by ErikEJ** [comment]
Wonder if it is because the fk name does not follow convention ?

**Comment by SgTS2020** [comment]
I agree fk name does follow EF convention. This is the problems with existing DB. 
But generated a proper code is another thing.

In this case, the ForeignKey tag is correct but, why generate a declaration of the foreingKey in the Dbcontext  + in the entity class with a tag ? Tag **or** dbContext declaration is suffisent, no needs to rewrite it twice.

 Why generate [InverseProperty] tag on each part of single relation when [InverseProperty] is only needed then more than one pair of navigation properties between two entity types. No need to generate it. 

(https://docs.microsoft.com/en-us/ef/core/modeling/relationships#data-annotations) 

Regards,

**Comment by ErikEJ** [comment]
Since I am simply using the built-in EF Core scaffolding, maybe you should report an issue in the EF Core repo?

**Comment by SgTS2020** [comment]
Great, thanks you for the information and your help.
