### ISSUE TITLE
Rename class with Handlebars template

### ISSUE THREAD

**Issue by SgTS2020** [ErikEJ/SqlCeToolbox#636]
It's more a question than an issue : 
How can i rename a class  "TMember " into "Member" with the  Handlebars Template ?

thanks in advance for your help.

Further technical details
Toolbox/Power Tools version: 4.7.525.0
Database engine: SQL Server
Visual Studio or SSMS version: Visual Studio 2017 15.5.6

**Comment by ErikEJ** [comment]
I don't think you can really. @tonysneed ?

**Comment by tonysneed** [comment]
Can you please provide an example of what you're trying to do?

**Comment by Athuruga** [comment]
I guess it is a feature like table name is tblCustomer should be named as class Customer, but would then need a mapping to get the data out of tblCustomer like Simon Hughes is doing it in his Reverse POCO Generator for EF6?

**Comment by ErikEJ** [comment]
Yes. And it does not look like it is currently possible.

**Comment by SgTS2020** [comment]
Hi All,

thanks for your replys.  

@Athuruga  : Yes, I would like the same level of customisation that we have with T4 Templates on EF6. and yes, i need a feature like table name is tblCustomer should be named as class Customer.
The mapping with the table is generared by @ErikEJ  tool, no problems on that.

I'll see if  Simon Hughes Reverse POCO Generator for EF6 and .NET Core 2 cover all my needs.
 
@ErikEJ :  thanks a lot, for your help and your  great tool.

**Comment by tonysneed** [comment]
@SgTS2020 I invite you to open an issue on the handlebars template repo: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars.  There are extensibility points which allow you provide custom logic, and handlebars also has the concept of helpers, which you might find useful.

**Comment by tonysneed** [comment]
@SgTS2020 Not sure if Simon's tool supports EF Core yet. See https://github.com/sjh37/EntityFramework-Reverse-POCO-Code-First-Generator/issues/5

**Comment by SgTS2020** [comment]
@tonysneed : Yes Simon's tool don't supports EF Core yet.  Dommage...

I'll open an issue on the handlebars Template repo. I've see the concept of helper on the Handlebars documentation and have the possibility to use it could be great feature.
