### ISSUE TITLE
Select Tables to Script is not showing all Tables in DB

### ISSUE THREAD

**Issue by Athuruga** [ErikEJ/SqlCeToolbox#638]
Describe what is not working as expected.

When I choose "Reverse Engineer" and select my SQL DB in which I have about 400 Tables I get only 107 tables shown in the "Select Tables to Script" Dialog. When I choose "View Database Schema as Graph" all tables of the DB are visible in the "Select Tables to Script" Dialog.

Because of this I'm not able to choose the tables I'm really interested in.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Take a DB with lots of tables and choose  "Reverse Engineer"

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
4.7.525.0

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2017 15.5.7 (was also not working with 15.5.4-15.5.6

**Comment by ErikEJ** [comment]
A primary key is required on the table in order for it to be listed.
