### ISSUE TITLE
EFPT: investigate possibility for custom naming of dbset, classes and properties

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#640]
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs 

https://github.com/aspnet/EntityFrameworkCore/issues/11056#issuecomment-368256127

- [x] Get PR for ICandidateNamingService accepted
- [ ] Add support for efpt.renaming.json (drop empty, commented out sample in project, in there is none)
- [ ] add class for renames ColumnRenamer: Table, Old, New & TableRenamer: Old, New
- [ ] Override ICandiadteNamingService, and rename based on json file

**Comment by jonreis** [comment]
Erik, I really like your Reverse Engineering tool with Handlebars. Great work. Adding these items will be fantastic.

Do think you could add to the list specifying the datatype of the property also? As you know the generated code for Sqlite does not always reflect the ones the user wants to use.

**Comment by ErikEJ** [comment]
@jonreis I can, but it is outside the scope of this particular feature, due to the way EF Core reverse engineering is designed.

**Comment by ErikEJ** [comment]
No, I just thin you should log this as a seperate issue, the fix for that will no be possible via this feature/fix.

**Comment by statler** [comment]
Erik

I have never worked on a VSIX before, but would it be fair to say that the remaining steps on this issue are relatively straight forward? E.g. as each table name / column name is extracted, check if it matches an in-memory lookup table created from a JSON, and then substitute if found?

If so, I could have a crack at it if you can give me a couple of pointers to the relevant methods/overrides as I kind of need to be able to do this. If however it is more complex than it appears - I will just slowly back away... with reversing beeper on.

Cheers
D

**Comment by statler** [comment]
Hi Erik

Any thoughts on when this may be available?

**Comment by ErikEJ** [comment]
@statler  Around the release of 2.1 (was waiting for changes in EF Core, which are now available in in preview-2) - what database provider do you use?

**Comment by statler** [comment]
Oh cool - do you have a commit with this in it?

I use full SQL server

**Comment by ErikEJ** [comment]
Not yet, I need preview2, which was just released...

**Comment by OmiCron07** [comment]
Do you have a build now with this feature?

**Comment by ErikEJ** [comment]
Not yet, have been to busy with EF Core provider and my day job

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#14
