### ISSUE TITLE
SQLite error with special view due to bug - fix coming in System.Data.SqLite 109

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#641]
When opening my SQLite DB I get:

![grafik](https://user-images.githubusercontent.com/7541399/36834479-4bb4ed3c-1d33-11e8-9eed-820108819937.png)

I think this has to do with our special view definition (perfectly valid in SQLite):

```
CREATE VIEW [vwBibs] AS
WITH RECURSIVE
    [tab] AS(
        SELECT 1 AS [BibFrom],
               10 AS [BibTo]
        UNION ALL
        SELECT [BibFrom] + 1,
               [BibTo]
        FROM   [tab]
        WHERE  [BibFrom] < [BibTo]
    )
SELECT [BibFrom]
FROM   [tab];
```

### Steps to reproduce
Opening an SQLite DB

### Further technical details
Toolbox/Power Tools version: 4.7.534.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Could you share the DB (or is it any db??)

**Comment by mwallnoefer** [comment]
[test.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1771189/test.zip)

**Comment by ErikEJ** [comment]
This could be fixed in the latest daily build

**Comment by mwallnoefer** [comment]
Is this the latest build or do I have to wait till tomorrow? Since this one does not fix it yet...
![grafik](https://user-images.githubusercontent.com/7541399/37958414-c320fd52-31b0-11e8-85b2-1478bfd8f006.png)

**Comment by ErikEJ** [comment]
Exact same error?

**Comment by ErikEJ** [comment]
It is a bug in System.Data.SQLite - that I am not in a position to fix - maybe you can work around it by surrounding AS by spaces:

```
CREATE VIEW [vwBibs] AS
WITH RECURSIVE
    [tab] AS (
        SELECT 1 AS [BibFrom],
               10 AS [BibTo]
        UNION ALL
        SELECT [BibFrom] + 1,
               [BibTo]
        FROM   [tab]
        WHERE  [BibFrom] < [BibTo]
    )
SELECT [BibFrom]
FROM   [tab];
```

**Comment by mwallnoefer** [comment]
Glad to hear this, I will try your workaround. Thanks for your support Erik!

**Comment by ErikEJ** [comment]
Running this query in the Toolbox query window also fails with the same error, so I have no ideas...

WITH RECURSIVE       [tab] 
AS (           
SELECT [BibFrom],                   [BibTo],                   [idGroup]           FROM   [GroupBibs]           UNION ALL           SELECT [BibFrom] + 1,                   [BibTo],                   [idGroup]           FROM   [tab]           WHERE  [BibFrom] < [BibTo]       )   SELECT DISTINCT [idGroup] AS [idGroup],           [BibFrom] AS [BibNumber]   FROM   [tab];

**Comment by ErikEJ** [comment]
I suggest you raise an issue here: https://system.data.sqlite.org/index.html/login?g=/index.html/tktnew&anon

**Comment by ErikEJ** [comment]
Re-opening to remind me to verify that this is fixed in System.Data.SQLite 109
