### ISSUE TITLE
EFPT - Primary key not defined

### ISSUE THREAD

**Issue by OmiCron07** [ErikEJ/SqlCeToolbox#642]
I need to set the primary key in an abstract manner and the first thing I'm blocked is the generation of the definitions never defines the primary key, as indicated here: https://docs.microsoft.com/en-us/ef/core/modeling/keys

With that, I should retrieve the primary key field and set it. I need it to create a generic Attach method.

And how can I use Handlebars to get the type of the primary key? I need to inherit a generic interface like `EfCoreEntity : IPrimaryKey<T>.`

Is there any documentation for Handlebars and the usable variables?

This what I achieved with EF and I want to replicate for EF Core:
```
public partial class UserSetting : IPrimaryKey<Guid>
{
        [NotMapped]
        public System.Guid Id { get => UserSettingId; set => UserSettingId = value; }

        public Guid UserSettingId { get; set; }

        public Guid ApplicationSettingId { get; set; }

        public Guid UserId { get; set; }

        public string Value { get; set; }
}
```

**Comment by ErikEJ** [comment]
Did you read the wiki article? 

You can move the Id property to a partial class

**Comment by OmiCron07** [comment]
I want to generate all that, no hand codes, exactly what I did in EF with standard EDMX T4. I need a way to identify the primary key property and its type.

Two things, first I don't have in the method OnModelCreating the meta data to identify the primary key as indicated in MSDN, and secondly, I don't know how to generate my extra property with Handlebars, which seems pretty limited vs old T4.

**Comment by ErikEJ** [comment]
None of this is currently possible, sorry.

**Comment by OmiCron07** [comment]
You can at least add the .HasKey/[Key] part of EF Core as mentioned in MSDN?

**Comment by ErikEJ** [comment]
It will be added if the key name does not follow convention, otherwise not. (I am simply wrapping the existing EF Core reverse engineer implementation)

**Comment by OmiCron07** [comment]
Ok, I didn't test it, but if you are right, then I can get the primary key fields even without the .HasKey/[Key] in the generated code?

**Comment by ErikEJ** [comment]
Abseloutely
