### ISSUE TITLE
EFPT: Publish Dacpac scaffolding package for EF Core 2.1

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#648]
ErikEJ.EntityFrameworkCore.Dacpac ??

Use https://www.nuget.org/packages/Microsoft.SqlServer.DacFx.x86/ 

https://github.com/bricelam/EFCore.VisualBasic/blob/master/EFCore.VisualBasic/EFCoreVisualBasicServices.vb

**Comment by bricelam** [comment]
Oh, did you see this, too? https://github.com/bricelam/EFCore.Pluralizer/blob/master/EFCore.Pluralizer/build/netstandard2.0/Bricelam.EntityFrameworkCore.Pluralizer.targets

**Comment by ErikEJ** [comment]
Thanks, nooo idea what it means, though. It is assembly attributes?? And they are required for the "magic" to work??

**Comment by ErikEJ** [comment]
And thanks so much for keeping an eye over here - pretty active, as you can see! 😄

**Comment by ErikEJ** [comment]
Rettet 😊

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by bricelam** [comment]
Yes, that's the language-agnostic way to add the assembly-level `[DesignTimeServicesReferenceAttribute("MyDesignTimeServices")]` attribute to the user's project.
