### ISSUE TITLE
EFPT: Add Migrations UI

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#649]
https://github.com/bricelam/EFCore.VisualStudio/issues/3

**Comment by ErikEJ** [comment]
@bricelam - I think I can now make GetMigrationStatus and ApplyMigrations work, but how do I create migrations and get them added to the project.

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/EFCorePowerTools/Handlers/MigrationsHandler.cs

https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/EFCoreModelBuilder.cs#L62

**Comment by bricelam** [comment]
Scaffold:
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Design/Design/Internal/MigrationsOperations.cs#L92-L94

Add to project:
https://github.com/aspnet/EntityFrameworkCore/blob/dev/src/EFCore.Tools/tools/EntityFrameworkCore.psm1#L70-L76

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#13
