### ISSUE TITLE
Visual Studio Dark Theme Compatibility

### ISSUE THREAD

**Issue by feinstein** [ErikEJ/SqlCeToolbox#65]
When in Visual Studio 2015 Dark Theme the search bar is barely readable:

![captura_de_tela_051816_093205_pm](https://cloud.githubusercontent.com/assets/8120472/15379095/fa3c31da-1d3f-11e6-877b-f7e34c8f9445.jpg)

**Comment by zspitz** [comment]
The query editor is dark text on white background, which is incompatible with the dark theme.
(Also, the main toolbox window's butons have a light background.)
