### ISSUE TITLE
Not Getting Navigation Properties as Virtual.

### ISSUE THREAD

**Issue by arifjmamun** [ErikEJ/SqlCeToolbox#650]
Generating entities with **virtual** is required for **lazy loading** which is supported by EnitityFrameworkCore.

Also naming the navigation property is not always right as .Net EntityFramework does. 

If a property don't have **suffix ID/Id** the generated navigation property name contain suffix as **Navigation**

**Comment by ErikEJ** [comment]
>> Generating entities with virtual is required for lazy loading which is supported by EnitityFrameworkCore.

The tool does not support 2.1 (it is not released yet) and this is  2.1 feature. It is the navigations, not the entities that must be virtual: https://docs.microsoft.com/en-us/ef/core/querying/related-data#lazy-loading 

>> Also naming the navigation property is not always right as .Net EntityFramework does.

EF Core does things differently, yes. Can you give a example of what you are seeing?

**Comment by arifjmamun** [comment]
As an example,
public long DealTicketNo {get; set;}
// Navigation Property which is generated
public DealTicketGeneration DealTicketNo**Navigation** {get;set;}

**Comment by ErikEJ** [comment]
Thanks for the example, currently this is by design
