### ISSUE TITLE
Nice to have a past into option in the new query window.

### ISSUE THREAD

**Issue by GeorgeKenyon-GreatWebs** [ErikEJ/SqlCeToolbox#655]
Describe what is not working as expected.

Would be great if it was possible to paste into the New Query Window

### Steps to reproduce

Try past into the window.  

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Version 4.7.534.0 

Database engine: SQLite

Visual Studio Community 2017 15.5.2

**Comment by ErikEJ** [comment]
I think this is a good suggestion, but could you describe in more detail what you are asking for in a step-by-step way, thanks?

**Comment by GeorgeKenyon-GreatWebs** [comment]
Hi Erik,

 

Thanks for your quick response.

 

There will be many reasons that someone would like to copy and paste a SQLite Script into your New Query Window but my suggestion came from this:

 

Was having trouble with a complex SQLiteCommand I was building in C# code containing multiple string parts and passed parameters rendered as a single interpreted command string.

 

I was Debugging this and wanted to test the constructed command in your New Query window.

 

In Debug I copied the SQLiteCoomand string built in my code after it was constructed and then tried to paste it into the New Query window but it doesn’t have paste capability so I needed to either key the script manually or use another SQL tool I use DB Browser for SQLite which does allow pasting.

 

The reason I was doing this was to test if my script ran and gave the expected result.

 

I think allowing paste capability would make your already handy Toolbox even more powerful.

 

Thanks for allowing us to use your work it is appreciated.

 

Regards

 

George Kenyon.

 

Great Webs Pty. Ltd.

**Comment by ErikEJ** [comment]
Ctrl+V works fine for me !?

**Comment by GeorgeKenyon-GreatWebs** [comment]
Hi Erik,

 

Thanks for your reply. 

 

I tend not to use shortcuts because I have Arthritis in my left thumb so I didn’t think to try it.

 

But now I do  it works fine for me too, so please disregard my suggestion.

 

Regards,

 

George
