### ISSUE TITLE
EFPT: Navigation named xxxNavigation

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#656]
Another difference between EF6 reverse engineering is that I have a table named Segment, and another one called Field. A field has a navigation property to Segment. Instead of the name being Field.Segment as it was in EF6, it called is Field.SegmentNameNavigation

        private Segment m_SegmentNameNavigation;
        public Segment SegmentNameNavigation
        {
           get { return m_SegmentNameNavigation; }
           set
           {
             if(m_SegmentNameNavigation != value)
             {
                m_SegmentNameNavigation = value;
                OnPropertyChanged();
             }
           }
        }

This is the only navigation property that seems to get named differently than EF6.

The modelbuilder code generated for this entity is:

            modelBuilder.Entity<Segment>(entity =>
            {
                entity.HasKey(e => e.Name);

                entity.ToTable("Segment");

                entity.Property(e => e.Name)
                    .HasColumnType("nvarchar(3)")
                    .ValueGeneratedNever();

                entity.Property(e => e.Description).HasColumnType("nvarchar(1024)");
            });
This is the only navigation property that seems to get named differently than EF6.

The modelbuilder code generated for this entity is:

            modelBuilder.Entity<Segment>(entity =>
            {
                entity.HasKey(e => e.Name);

                entity.ToTable("Segment");

                entity.Property(e => e.Name)
                    .HasColumnType("nvarchar(3)")
                    .ValueGeneratedNever();

                entity.Property(e => e.Description).HasColumnType("nvarchar(1024)");
            });
@jonreis

**Comment by ErikEJ** [comment]
I believ this is "by design"

**Comment by jonreis** [comment]
Sounds like #604 will provide a work-around for this.
