### ISSUE TITLE
SQl Logic Data Type error when having a bit datatype in a table

### ISSUE THREAD

**Issue by mksaiprasad** [ErikEJ/SqlCeToolbox#658]
![dg](https://user-images.githubusercontent.com/9022636/37307124-e0b62946-2607-11e8-9fe9-bc4697ece0b9.jpg)
![edittop100](https://user-images.githubusercontent.com/9022636/37307125-e0c7cf3e-2607-11e8-9544-36f2b136b74a.JPG)

Describe what is not working as expected.
Hi Erik, This tool is great. Off late I started to use a bit datatype and do not see any error while creating the table. I see errors while using Select top 100 menu or even creating the database diagram. I am on the latest version 4.7.534.0. Not sure if you ever come across this type. I can write a select statement and it works fine.
Can you please let me know if I missing something.
I have also attached error images.
Thanks Sai 

### Steps to reproduce
Create a table with Bit Data type and try to get Top 100.

### Further technical details
Toolbox/Power Tools version: (4.7.534.0)

Database engine: (SQlite, SQL Compact or SQL Server) SQLite

Visual Studio or SSMS version: (Visual Studio 2015)

**Comment by ErikEJ** [comment]
Can you share a repro database file with me?

**Comment by mksaiprasad** [comment]
Hi Eric,
After doing some more work. I came to know that this issue is causing due to the view I had created. Its very simple view. If I drop the View then everything works Correctly.
I have attached a sample DB.
Please do let me know if anything that I'm doing wrong or missing something.
Thanks
Sai
[SampleToEric.zip](https://github.com/ErikEJ/SqlCeToolbox/files/1807829/SampleToEric.zip)

**Comment by ErikEJ** [comment]
Thanks for reporting, this is fixed in the latest daily build

**Comment by mksaiprasad** [comment]
Thanks Eric. I really appreciate all your help on this.
Sai

**Comment by ErikEJ** [comment]
Thanks, If you use my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
