### ISSUE TITLE
EFPT: Feature request to allow changing the datatype that is used on a property during database reverse engineering

### ISSUE THREAD

**Issue by jonreis** [ErikEJ/SqlCeToolbox#659]
To give some context to our overall goals I will explain the workflow that we follow. The subject of this feature request is only (3).

We currently use a database first approach for managing our entity objects. We keep our database up-to-date using Roundhouse as a migration tool and we use EF6 and t4 templates to generate our entity objects. When we add new properties or functions that are outside of the data model we add them in a separate file that is a partial class of the entity we are adding them to. Replicating this workflow under EF Core 2.1 has been challenging for the following reasons.

1) There is no control over the entity and property names that are generated. Using edmx model, it is easy to change the name of an entity, property, or relationship. It sounds like #640 will fix this.

2) Extra properties in the partial classes are automatically considered to be part of the data model unless they are decorated with [NotMapped]. I logged an issue (#11231) with the EF Core folks to have an opt-in mode, where if you fully specify model as is done during the reverse engineering of an existing data model, that additional properties would be ignored, however; it was rejected.

3) The datatypes being generated by EF Core do not always match those that are being used in the entity model. EF Core seams to want to an entity model that exactly matches the underlying storage model, which isn't what you always want. For example, if I define a bit in Sqlite, EF Core
generates me a string for the property type, same with the datetime. These can manually be edited after the entities are generated, however; in a database first approach you do not want to have to go back and fix up the entities each time. It would be nice to be able to define datatype overrides that would
be applied each time the entities are generated.

**Comment by ErikEJ** [comment]
Closing and moving to backlog, only relevant due to the limitations of the chosen database engine (SQLite)
