### ISSUE TITLE
Unable to Install on Visual Studio 2015 Shell (Integrated)

### ISSUE THREAD

**Issue by iabmatos** [ErikEJ/SqlCeToolbox#66]
Hi,

I've tried to install the add-on but did not work.  I'm not sure whether this is a limitation to particular versions of VS or some sort of configuration bug. Please help ou suggest a better approach.
Many thanks.

Here is the installation log:

27/05/2016 01:37:17 - Microsoft VSIX Installer
27/05/2016 01:37:17 - -------------------------------------------
27/05/2016 01:37:19 - Initializing Install...
27/05/2016 01:37:20 - Extension Details...
27/05/2016 01:37:20 - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
27/05/2016 01:37:20 - 	Name               : SQL Server Compact/SQLite Toolbox
27/05/2016 01:37:20 - 	Author             : ErikEJ
27/05/2016 01:37:20 - 	Version            : 4.5.0.2
27/05/2016 01:37:20 - 	Description        : SQL Server Compact/SQLite Toolbox add-in for Visual Studio. This add-in adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
27/05/2016 01:37:20 - 	Locale             : en-US
27/05/2016 01:37:20 - 	MoreInfoURL        : http://sqlcetoolbox.codeplex.com/
27/05/2016 01:37:20 - 	InstalledByMSI     : False
27/05/2016 01:37:20 - 	SupportedFrameworkVersionRange : [4.0,4.9]
27/05/2016 01:37:20 - 
27/05/2016 01:37:20 - 	SignatureState     : Unsigned
27/05/2016 01:37:20 - 	Supported Products : 
27/05/2016 01:37:20 - 		Microsoft.VisualStudio.Pro
27/05/2016 01:37:20 - 			Version : [10.0]
27/05/2016 01:37:20 - 		Microsoft.VisualStudio.Pro
27/05/2016 01:37:20 - 			Version : [11.0]
27/05/2016 01:37:20 - 		Microsoft.VisualStudio.Pro
27/05/2016 01:37:20 - 			Version : [12.0]
27/05/2016 01:37:20 - 		Microsoft.VisualStudio.Pro
27/05/2016 01:37:20 - 			Version : [14.0]
27/05/2016 01:37:20 - 		Microsoft.VisualStudio.Pro
27/05/2016 01:37:20 - 			Version : [15.0]
27/05/2016 01:37:20 - 
27/05/2016 01:37:20 - 	References         : 
27/05/2016 01:37:20 - 		-------------------------------------------------------
27/05/2016 01:37:20 - 		Identifier   : Microsoft.VisualStudio.MPF
27/05/2016 01:37:20 - 		Name         : Visual Studio MPF
27/05/2016 01:37:20 - 		Version      : [10.0,)
27/05/2016 01:37:20 - 		MoreInfoURL  : 
27/05/2016 01:37:20 - 		Nested       : No
27/05/2016 01:37:20 - 
27/05/2016 01:37:20 - Signature Details...
27/05/2016 01:37:20 - 	Extension is not signed.
27/05/2016 01:37:20 - 
27/05/2016 01:37:20 - Searching for applicable products...
27/05/2016 01:37:20 - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
27/05/2016 01:37:20 - Found installed product - Global Location
27/05/2016 01:37:20 - Found installed product - ssms
27/05/2016 01:37:20 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   em VSIXInstaller.App.InitializeInstall(Boolean isRepairSupported)
   em VSIXInstaller.App.InitializeInstall()
   em System.Threading.Tasks.Task.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()

**Comment by ErikEJ** [comment]
You need VS Community (which is free) or higher (pro, Enterprise etc) - what do you have?

**Comment by iabmatos** [comment]
Thanks Erik, I had intalled only the SQL Server Management Studio.  I'm installing Visual Studio right now.

**Comment by ErikEJ** [comment]
I am investigating enabling support for SQL Server Management Studio 2016 or later
