### ISSUE TITLE
gen poco for views of database

### ISSUE THREAD

**Issue by chrvip** [ErikEJ/SqlCeToolbox#660]
Can you gen poco for views of database?

### Steps to reproduce
In my db, there are some views. I was told to access some data from these views.

### Further technical details
Toolbox/Power Tools version:4.7.539.0

Database engine: SQL Server

Visual Studio or SSMS version:Visual Studio 2017 15.3, SSMS 17.3

**Comment by ErikEJ** [comment]
No, it is currently not supported, and there is limited support for views in EF Core 2.0. This will improve in 2.1 with DbQuery and View Types
