### ISSUE TITLE
 ADO.NET provider with invariant name 'System.Data.SQLite' is either not registered

### ISSUE THREAD

**Issue by hongil14** [ErikEJ/SqlCeToolbox#661]
Hello,

I'm getting the following error below:
An unhandled exception of type 'System.ArgumentException' occurred in EntityFramework.dll
The ADO.NET provider with invariant name 'System.Data.SQLite' is either not registered in the machine or application config file, or could not be loaded. See the inner exception for details.

I'm wondering if I have missed something to set up further.
Thank you.

### Steps to reproduce
I have installed the followings below:
  - sqlite-netFx46-setup-bundle-x86-2015-1.0.108.0.exe
  - EntityFramework v6.2
  - System.Data.SQLite v1.0.108
  - System.Data.SQLite.Core v1.0.108
  - System.Data.SQLite.EF6 v1.0.108
  - System.Data.SQLite.Linq v1.0.108

[packages.config]
`<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="EntityFramework" version="6.2.0" targetFramework="net462" />
  <package id="System.Data.SQLite" version="1.0.108.0" targetFramework="net462" />
  <package id="System.Data.SQLite.Core" version="1.0.108.0" targetFramework="net462" />
  <package id="System.Data.SQLite.EF6" version="1.0.108.0" targetFramework="net462" />
  <package id="System.Data.SQLite.Linq" version="1.0.108.0" targetFramework="net462" />
</packages>`

[App.config]
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
    
  </configSections>
  <startup>
    <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.6.2" />
  </startup>
  <entityFramework>
    <defaultConnectionFactory type="System.Data.Entity.Infrastructure.LocalDbConnectionFactory, EntityFramework">
      <parameters>
        <parameter value="v13.0" />
      </parameters>
    </defaultConnectionFactory>
    <providers>
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      <remove invariant="System.Data.SQLite" />
    </DbProviderFactories>
  </system.data>
  <connectionStrings>
    <add name="ProjectDBEntities" connectionString="metadata=res://*/ProjectDBModel.csdl|res://*/ProjectDBModel.ssdl|res://*/ProjectDBModel.msl;provider=System.Data.SQLite.EF6;provider connection string=&quot;data source=D:\C_Sharp\DB\example\ProjectDB.db&quot;" providerName="System.Data.SQLite" />
  </connectionStrings>
</configuration>`

### Further technical details
Toolbox/Power Tools version: 4.7.534.0

Database engine: SQLite

Visual Studio or SSMS version: Visual Studio 2017 15.6.3

=======copy from about info====================
Version 4.7.534.0 - 1,042,058 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by ErikEJ** [comment]
What is the Inner exception?

Did you check this guide: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider ?

**Comment by ErikEJ** [comment]
Closing as additional  information not received - feel free to re-open
