### ISSUE TITLE
SSMS Toolbox database context menu items not appearing (without toolbox open)

### ISSUE THREAD

**Issue by anthonyrodriguez** [ErikEJ/SqlCeToolbox#664]
Database context menu items do not appear in the Object Explorer until the SQLite / SQL Server Compact Toolbox is opened. Right-clicking on a database in the Object Explorer doesn't show the extra menu items unless I first manually open the toolbox window.

### Steps to reproduce
Open SSMS without the Compact Toolbox open. If the toolbox window is open, close it and restart SSMS. Right-click on a database in the object explorer.

### Further technical details
Toolbox/Power Tools version: 4.7.210.0

Database engine: SQL Server

SSMS version:  17.4 and 17.5

**Comment by ErikEJ** [comment]
Since extensibility is basically not supported by SSMS, I have not bee able to find a workaround for this - any ideas much appreciated

**Comment by anthonyrodriguez** [comment]
Thanks for the quick response. Have you been able to debug the SSMS extension in visual studio the way one would a VS extension? I've been trying to track this problem down but I haven't found a reliable way to debug yet.

**Comment by ErikEJ** [comment]
I have updated the wiki page here with debug instruction for the SSMSToolbox project: https://github.com/ErikEJ/SqlCeToolbox/wiki - please let me know if that helps?
