### ISSUE TITLE
EFPT: Update Handlebars for 2.1 preview1

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#666]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by OmiCron07** [comment]
When will the templates come back?

**Comment by ErikEJ** [comment]
Only @tonysneed knows ??

**Comment by tonysneed** [comment]
I finally have some bandwidth to tackle this. Stay tuned.

**Comment by tonysneed** [comment]
Now that EF 2.1 is RC, I plan to update my extensions.  I should have time to get started this week, but I'll definitely get it done within the next two weeks.

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#12
