### ISSUE TITLE
Not generating POCO for table

### ISSUE THREAD

**Issue by viveknuna** [ErikEJ/SqlCeToolbox#667]
I'm trying to generate a POCO for a table, but its failing with the following error.

**Script to generate the table:**

```
GO

/****** Object:  Table [dbo].[SampleTable]    Script Date: 3/27/2018 9:25:53 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SampleTable](
	[Col1] [varchar](255) NULL,
	[Col2] [int] NOT NULL,
	[Col3] [int] NOT NULL,
	[Col4] [datetime] NULL,
	[Col5] [int] NOT NULL,
	[Col6] [int] NOT NULL,
	[Col7] [int] NOT NULL
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[SampleTable] ADD  DEFAULT ((0)) FOR [Col2]
GO

ALTER TABLE [dbo].[SampleTable] ADD  DEFAULT ((0)) FOR [Col3]
GO

ALTER TABLE [dbo].[SampleTable] ADD  DEFAULT (getdate()) FOR [Col4]
GO

ALTER TABLE [dbo].[SampleTable] ADD  DEFAULT ((0)) FOR [Col5]
GO

ALTER TABLE [dbo].[SampleTable] ADD  DEFAULT ((0)) FOR [Col6]
GO

ALTER TABLE [dbo].[SampleTable] ADD  DEFAULT ((0)) FOR [Col7]
GO
```

**Error in the Output window:**

> Index column dbo.TaskOrdDeliver belongs to index IdcCol2 on table Col2 which is not included in the selection set. Skipping.
> Index column dbo.TaskOrdDeliver belongs to index IdxCol3 on table Col3 which is not included in the selection set. Skipping.
> Index column dbo.TaskOrdDeliver belongs to index IdxCol3 on table Col2 which is not included in the selection set. Skipping.
> Index column dbo.TaskOrdDeliver belongs to index IdxCol4 on table Col4 which is not included in the selection set. Skipping.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: 4.7.539.0

Database engine: SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.6, SSMS 17.4)

**Comment by ErikEJ** [comment]
A table must have a primary key...

**Comment by viveknuna** [comment]
@ErikEJ Yes, I agree, But this is the limitation of this tool. because there can be tables without PK.

**Comment by ErikEJ** [comment]
Yes, but EF Core must know what the key of your table is... It cannot work with POCO classes without a key
