### ISSUE TITLE
Reverse Engineer from DacPac omits SQL default value when zero

### ISSUE THREAD

**Issue by Steffen-M** [ErikEJ/SqlCeToolbox#669]
Describe what is not working as expected.

### Steps to reproduce
```` SQL
CREATE TABLE [dbo].[Table1] (
	[Id] INT NOT NULL PRIMARY KEY,
    [Value1] SMALLINT NOT NULL DEFAULT ((0)), 
    [Value2] SMALLINT NOT NULL DEFAULT ((1)) )
````

### Expected (as with "from Database")
````
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Table1>(entity =>
    {
        entity.Property(e => e.Id).ValueGeneratedNever();

        entity.Property(e => e.Value1).HasDefaultValueSql("((0))");

        entity.Property(e => e.Value2).HasDefaultValueSql("((1))");
    });
}
````

### generated from DacPac
````
protected override void OnModelCreating(ModelBuilder modelBuilder)
{
    modelBuilder.Entity<Table1>(entity =>
    {
        entity.Property(e => e.Id).ValueGeneratedNever();

        entity.Property(e => e.Value2).HasDefaultValueSql("((1))");
    });
}
````

### Further technical details
Toolbox/Power Tools versions:
Version 4.7.539.0
Version 4.7.548.0

**Comment by ErikEJ** [comment]
This is by design, but I am not sure this change is in 2.1-preview1 (coming in 2.1 rtm) 
(The "from database" codepath is 2.1-preview1, the dacpac codepath is mine, so newer)
https://github.com/aspnet/EntityFrameworkCore/pull/10880

**Comment by Steffen-M** [comment]
In general I would agree with not scaffolding unneeded defaults. But isn’t HasDefaultValueSql used in migrations to build the SQL column? There a default value matters, because there is none by default.

**Comment by ErikEJ** [comment]
The default value of CLR type short is always 0!

**Comment by Steffen-M** [comment]
Sorry for the late replay. 
I surely agree regarding CLR types. 
The ```` HasDefaultValueSql ```` information targets the SQL database not the CLR code. Let me continue the previous example. When using ```` context.Database.EnsureCreated() ```` to create the database, the generated SQL statement would like this:
````SQL
CREATE TABLE [Table1] (
    [Id] int NOT NULL,
    [Value1] smallint NOT NULL,
    [Value2] smallint NOT NULL DEFAULT (((1))) )
````
where column ```` [Value1] ```` does not have a default constraint, as it did in the original statement, that created the table.
Trying to execute the SQL statement
````SQL
INSERT INTO Table1 (Id) VALUES (1)
````
will fail with the error message
````
Cannot insert the value NULL into column 'Value1', table 'Database1.dbo.Table1'; column does not allow nulls. INSERT fails.
````
This is because there is no default value defined.
It does not fail on the original database.

We do not plan to rely on that EF feature, so this is not a real issue. I justed stepped over it, and wanted to inform you.

Best regards,
Steffen

**Comment by ErikEJ** [comment]
I suggest you raise an issue in the EF Core repository
