### ISSUE TITLE
Scripting SQL Compact Schema DateTime Issue

### ISSUE THREAD

**Issue by Tronald** [ErikEJ/SqlCeToolbox#670]
I am currently experimenting with converting an SQL CE database into an SQLite. I have scripted my schema and data from successfully from the toolbox, but when I import the sql file into an SQLite datebase, any table that contains a DateTime column fails to import and it fails silently (using sqlite3).

### Steps to reproduce
It appears the problem may lie in my default DateTime settings in the SQL CE database. The default date time is 1/1/1900 and the sql script has the default listed as such. Will I need to go into the sql file and manually change the format to 1900-01-01 00:00:00.000 or is there a way for the script to convert the date format when exporting the schema?

### Further technical details
VS Toolbox 4.7.534.0
Database engine: (SQL Compact)
Visual Studio or SSMS version: Visual Studio 2017 15.5.6

**Comment by ErikEJ** [comment]
Could you please show me a sample from the script, I do not understand, datatime columns should be scripted i a roundtrippable format always.

**Comment by Tronald** [comment]
Sure. This portion is the script that is generated from my "PAX" table out the the Compact database. It could be another issue causing failure, but the only common denominator is the datetime between the failing tables. The one the generate successfully do not have datetime columns. 

`CREATE TABLE [PAX] (
  [ID] INTEGER  NOT NULL
, [MissionID] int  NOT NULL
, [UnitName] nvarchar(100)  NULL
, [POCName] nvarchar(100)  NULL
, [POCPhone] nvarchar(100)  NULL
, [POCEmail] nvarchar(100)  NULL
, [Cargo] nvarchar(100)  NULL
, [PAX] nvarchar(100)  NULL
, [Hazards] nvarchar(100)  NULL
, [PreCoord] datetime DEFAULT 1/1/1900 NOT NULL
, [FM111] datetime DEFAULT 1/1/1900 NOT NULL
, [PickUpLocs] nvarchar(100)  NULL
, [DropLocs] nvarchar(100)  NULL
, [Remarks] nvarchar(500)  NULL
, [CallSign] nvarchar(100)  NULL
, CONSTRAINT [PK_PAX] PRIMARY KEY ([ID])
, FOREIGN KEY ([MissionID]) REFERENCES [Missions] ([ID]) ON DELETE CASCADE ON UPDATE CASCADE
);`

**Comment by ErikEJ** [comment]
Ah, the default values, not INSERT script - I think you will just have to manually remove them by hand..

**Comment by Tronald** [comment]
Ok no problem! Just wasn’t sure if I was doing something wrong. Thanks!
