### ISSUE TITLE
Could you please provide a sample for EF Core 2?

### ISSUE THREAD

**Issue by viveknuna** [ErikEJ/SqlCeToolbox#672]
Could you please provide a sample for adding a trigger, Condition is given it that I can't change your DbContext inheritance chain. If not possible then at least provide steps to create/alter/delete trigger, add migration and update database.

### Further technical details
Toolbox/Power Tools version: 6.1.1

Database engine:  SQL Server

Visual Studio or SSMS version: Visual Studio 2017 15.5, SSMS 17.4

**Comment by ErikEJ** [comment]
Are you posing this in the correct repository?

**Comment by ErikEJ** [comment]
I suggest you post a question on StackOverflow, describe what you have tried and what you would like to get/do.

**Comment by viveknuna** [comment]
@ErikEJ  I'm really sorry, It was my mistake. I was posting it to a different repository.

**Comment by ErikEJ** [comment]
No worries 😄
