### ISSUE TITLE
Add equivalent of -force option in reverse engineer?

### ISSUE THREAD

**Issue by BrandonPotter** [ErikEJ/SqlCeToolbox#673]
Is there a way, or can a way be added, to overwrite everything in the model folder when reverse engineer is run again? Similar to the `-force` parameter of DbContext-Scaffold.

Describe what is not working as expected.

### Steps to reproduce
1. Reverse engineer model, but leave out some tables.
2. Now, reverse engineer the model again, but select the tables.

DbContext class does not get updated with the newly selected table(s).

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Version 4.7.539.0

Database engine: (SQlite, SQL Compact or SQL Server)

SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

VS2017 15.6.4

**Comment by ErikEJ** [comment]
I always overwrite: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/ReverseEngineer20/EFCoreReverseEngineer.cs#L105 

I have noticed that sometimes you must re-open the file in VS in order to see the change in the VS editor. 

What source control system do you use?

**Comment by BrandonPotter** [comment]
Hmm... github. Will test again today..

**Comment by ErikEJ** [comment]
Any progress?
