### ISSUE TITLE
Performance improvments on Migrate to Sqlite

### ISSUE THREAD

**Issue by mehmetilker** [ErikEJ/SqlCeToolbox#674]
I am trying to create a sqlite db using "Migrate to Sqlite" option. Selecting a table with 10.000 rows in it and after start migration import takes hours.
I assume main reason taking so long of importing is that sqlite insert performance problem.

Is it possible to improve performance with utilizing method described here ?
https://blogs.msdn.microsoft.com/andy_wigley/2013/11/21/how-to-massively-improve-sqlite-performance-using-sqlwinrt/

I wanted to try by myself but I guess asking first would be more easier for this kind of test.

### Further technical details
Toolbox/Power Tools version: 
Version 4.7.534.0 - 1,047,047 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: Sqlite, Sql Server 2017

Visual Studio or SSMS version: Visual Studio 2017 15.6.4

**Comment by ErikEJ** [comment]
You could try generating script files, and run them with sqlite3.exe - otherwise the approach above should work, yes

**Comment by ErikEJ** [comment]
Closing as there is not really anything for me to do here...
