### ISSUE TITLE
Use database names isn't quite using database names

### ISSUE THREAD

**Issue by BrandonPotter** [ErikEJ/SqlCeToolbox#675]
Describe what is not working as expected.

### Steps to reproduce
1. Generate a model with a database using sequential caps in columns, i.e. `CRMStatus`
2. Model generates property as `Crmstatus`

Expected behavior is `CRMStatus` when "use database names" is enabled.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Version 4.7.539.0

Database engine: (SQlite, SQL Compact or SQL Server)

SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

VS2017 15.6.4

**Comment by ErikEJ** [comment]
This is a known issue, I think it may be fixed in the latest daily EF Core Power Tools build, version 1.0.552 (the version you site above is from SQLite Toolbox, which is not related to this feature) - download link: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools
