### ISSUE TITLE
SQLite View Problem #2

### ISSUE THREAD

**Issue by mwallnoefer** [ErikEJ/SqlCeToolbox#676]
I define a view in SQLite, e.g.
```
create view [vwTest]
as select 1;
```

Now when I want to have it scripted using the context menu options, the `create view [vwTest]
as` part is missing.

This means _Script as DROP and Create_ just yields:
```
DROP VIEW [vwTest];
select 1;
```

### Steps to reproduce
![grafik](https://user-images.githubusercontent.com/7541399/38134929-94928d86-3415-11e8-89de-0811551dbbfb.png)

### Further technical details
Toolbox/Power Tools version: 4.7.545.0
Database engine: SQLite
Visual Studio or SSMS version: Visual Studio 2013

**Comment by ErikEJ** [comment]
Fixed in latest build, but this gave me some ideas for fixing some of the crazy view parsing bugs you have been throwing at me!
