### ISSUE TITLE
Fix SQLite view / view column parsing issues 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#677]
Parse first AS statement better:
Replace \r and \n with space 
Replace ( and ) with " ( " and " ) "

@mwallnoefer

**Comment by ErikEJ** [comment]
strSql = rdViews.GetString(4).Replace('\r', ' ').Replace('\n', ' ').Replace('\t', ' ');
              n = CultureInfo.InvariantCulture.CompareInfo.IndexOf(strSql, " AS ", CompareOptions.IgnoreCase);
              if (n < 0)
                continue;

              strSql = strSql.Substring(n + 4);

**Comment by mwallnoefer** [comment]
Did this work with my test DB?

**Comment by ErikEJ** [comment]
Not tested/implemented yet 😁

**Comment by ErikEJ** [comment]
I did not 😞 - System.data.Sqlite bug/issue when getting list of columns in the database file (not even sure it is related to your view)

**Comment by ErikEJ** [comment]
But views with comments and "WITH" now work
