### ISSUE TITLE
EFPT: Support stored procedures

### ISSUE THREAD

**Issue by OmiCron07** [ErikEJ/SqlCeToolbox#680]

**Comment by ErikEJ** [comment]
As EF Core does not support stored procedures (to a large extent) - could you give an exmaple of what type of support you are looking for?

**Comment by OmiCron07** [comment]
I don't know exactly what you can currently do, but in the meantime, I think I will use this NuGet : https://github.com/verdie-g/StoredProcedureEFCore

Can you list the stored procedures in the database and create some classes or constants with their parameters, because, I don't want to use magic string. 

That would be nice to import the stored procedure with its list of parameters and using these with the other library.

**Comment by ErikEJ** [comment]
Moving to backlog - PRs accepted!

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#18
