### ISSUE TITLE
EFPT: Add a search box when selecting tables

### ISSUE THREAD

**Issue by OmiCron07** [ErikEJ/SqlCeToolbox#681]
Would be nice to filter the list of tables with a simple search by name when we have a lot of tables in the database.

**Comment by ErikEJ** [comment]
OK - what should happen when you start typing? Only list relevant tables? or something else?

**Comment by OmiCron07** [comment]
Yes, only list the relevant tables which contain the searched keyword.

**Comment by ErikEJ** [comment]
How about tables that have already been selected? Should they remain visible, or become unselected?

**Comment by OmiCron07** [comment]
Just a simple filter by name (contains), nothing more, just a quick way to find a table. After the filter is applied, I think we could simply select or unselect a table, change the filter, select or unselect a table and going to the next step.

Because the table selections are saved, we should not add any other logic than only showing filtered results. That way, we should not unselect tables by mistake.

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#11
