### ISSUE TITLE
EFPT - RevEng - How remove a connection in "Choose Database Connection" list

### ISSUE THREAD

**Issue by OmiCron07** [ErikEJ/SqlCeToolbox#684]
I moved my database to another server and each time I RevEng, I have to choose the second server of the list and click OK. I would like to just click OK because the first server is the right one.

Where do you stock/get that list of servers? Can I delete a connection or reorder the list?

![image](https://user-images.githubusercontent.com/31325575/38377102-23c1d74e-38c8-11e8-8b52-9ec3d62d73d8.png)

**Comment by ErikEJ** [comment]
They are stored in Server Explorer
