### ISSUE TITLE
Database password - Saved for ever - Security Risk

### ISSUE THREAD

**Issue by WaldoDJ** [ErikEJ/SqlCeToolbox#686]
Hi, i user SQlCeToolbox for 3.5, open a database with password, SqlToolbox prompt for password, entry the password, and save it for ever

### Steps to reproduce
Open a database with password, entry the password, now everytime you open database its open, without prompt again the password.
This is a security risk

### Further technical details
SQL Server Compact Toolbox, v 3.7.2.0.

Database engine: SQL Compact  3.5

**Comment by ErikEJ** [comment]
I do not consider the weak password protection of SQL CE databases a security feature, but an obfuscation feature. 

Given this, it is not something I plan to change, but I will of course accept a pull request for this.

**Comment by WaldoDJ** [comment]
Hi Erik
Maybe I did not express correctly.

I say...simply add a checkbox, save password?
And you keep, or not, the password for future use.

**Comment by ErikEJ** [comment]
I am not sure it is that simply - but as I said, the project is open for pull requests! 😁

**Comment by ErikEJ** [comment]
Moving to backlog - a PR for this will be welcome
