### ISSUE TITLE
unspecified error [sqlcese40.dll] 

### ISSUE THREAD

**Issue by baj9032** [ErikEJ/SqlCeToolbox#689]
I have **visual studio 2013** on my system and I have installed this plugin from NuGet package manager but When I tried to do new connection its give me error. See below screen shot for more detail.

![sqlliteceerror](https://user-images.githubusercontent.com/16740406/38484637-e2047dd6-3bf4-11e8-88d6-a5c533a8006e.PNG)

**Comment by ErikEJ** [comment]
Re-install/repair SQL Server Compact 4.0

**Comment by baj9032** [comment]
@ErikEJ : I have reinstall compact edition 4.0 but still it is not working.

**Comment by ErikEJ** [comment]
Pls share info from about screen...

**Comment by baj9032** [comment]
@ErikEJ : I have installed compact edition 3.5 now it's working.
