### ISSUE TITLE
Tools don't know how to singularize People

### ISSUE THREAD

**Issue by 82dsoldier** [ErikEJ/SqlCeToolbox#691]
When performing a reverse engineer of a database with a table named People, power tools (with pluralize/singularize option turned on) named the model People and the DbSet Peoples.

### Steps to reproduce
See above

### Further technical details
Toolbox/Power Tools version: 1.0.539

Database engine: Sql Server Standard 2016

Visual Studio or SSMS version: Visual Studio 2017 v 15.6.2

**Comment by ErikEJ** [comment]
As I said, no pluralizer is perfect...

**Comment by ErikEJ** [comment]
What did you actually expect her?

**Comment by ErikEJ** [comment]
https://www.wordhippo.com/what-is/the-plural-of/people.html

**Comment by 82dsoldier** [comment]
Singular of of People should be Person.

**Comment by ErikEJ** [comment]
The DbSet names are allways plural, so your table name should be Person, I think.

https://github.com/ErikEJ/EntityFramework/blob/05bc59711c11ee25b5ff483513d4fa389a3ddb24/src/EFCore.Design/Scaffolding/Internal/RelationalScaffoldingModelFactory.cs#L95
