### ISSUE TITLE
Options for partial and virtual?

### ISSUE THREAD

**Issue by 82dsoldier** [ErikEJ/SqlCeToolbox#692]
Would it be possible to add in options to disable partial classes?  I hardly ever need them and when they're there, VS complains about them.

Also, it would be nice to be able to turn on the virtual keyword for navigation properties.  I realize that EF Core doesn't fully support navigation properties yet, but I have a framework that I use for all of my data models to emulate navigation properties and it depends on finding them by having them marked as virtual.

**Comment by ErikEJ** [comment]
You should be able to do both with  modified handlebars templates
