### ISSUE TITLE
Updated database doesn't reflect during reverse engineering

### ISSUE THREAD

**Issue by madhav5589** [ErikEJ/SqlCeToolbox#693]
Thanks for the nice tool for reverse engineering. I could generate the model from existing database hosted on SQL server. But when I added new table in the database, I wanted to update the mode to include that table but I don't see the new table listed when I tried to do reverse engineering. 

In order to refresh, I tried to remove that "remembered " database but couldn't find any option to remove.

**Database engine**: SQL Server

**Visual Studio/SSMS version**: Visual Studio 2017 15.6.6, SSMS 17.6

**Comment by ErikEJ** [comment]
Does your new table have a primary key? - this is required

**Comment by madhav5589** [comment]
Got it. It was missing the PK. Now, I can see the new table listed.
Thank you.
