### ISSUE TITLE
EFPT: Create folder for table schemas or a way to distinguish generated entities

### ISSUE THREAD

**Issue by OmiCron07** [ErikEJ/SqlCeToolbox#694]
First, it would be nice to have the tables in their respective schema folder.

Second, it should help for when we have the same table name in many schemas. Actually, I imported three tables with the same name, but in the different schemas, and I got Company, Company1, Company2. It is impossible to distinguish which one is.

What do you think? A nice solution would be to put each table in the folder named after the schema. Or at least, have the schema as the prefix when table name clashes.

**Comment by ErikEJ** [comment]
Would #640 not fix this?

**Comment by OmiCron07** [comment]
Will I be able to know there are other tables named "Company" and have the schema name?

**Comment by ErikEJ** [comment]
I do not understand your question?

**Comment by OmiCron07** [comment]
First, do you have the name of the schema when generating the entity of the table?

Second, if I want to add, as a prefix, the schema of the table to avoid name clashes, can I detect that will clash or I need to add the prefix for all the tables no matter what?

**Comment by ErikEJ** [comment]
For the rename feature, specify the table with schema: dbo.Mytable

**Comment by ErikEJ** [comment]
The rename feature will fix this, 
TableRename: 
Table: dbo.Customer => Customer
Table: Discount.Customer => DiscountCustomer
