### ISSUE TITLE
EF Core PowerTools

### ISSUE THREAD

**Issue by TheDarkBoz** [ErikEJ/SqlCeToolbox#697]
Hello

Thanks for this very useful tool. 
I have a little issue.. I dont know how add a helper I tried to add in Propreties.hbs the following line before then after the call

```
Handlebars.registerHelper('ifEquals', function(arg1, arg2, options) {
    return (arg1 == arg2) ? options.fn(this) : options.inverse(this);
});
```

I have issue : 

> HandlebarsDotNet.HandlebarsRuntimeException: Template references a helper that is not registered. Could not find helper '#ifEquals'

I have need a helper for filter the list of proprieties.

Thank you.
Best Regards

EF Core PowerTool Version 4.7.539.0

**Comment by ErikEJ** [comment]
I know very liitle about handlebars - maybe @tonysneed can help?

**Comment by tonysneed** [comment]
Open an issue on my repo, and if I can’t answer I’ll provide the Handlebars.net repo where you can post your question.

**Comment by ErikEJ** [comment]
Repo here: https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars

**Comment by TheDarkBoz** [comment]
Thanks you I will post.

**Comment by MarcusMcKibben** [comment]
So should we use https://github.com/TrackableEntities/EntityFrameworkCore.Scaffolding.Handlebars if we need custom helpers or is there a way to setup our project to use custom helpers with the Reverse Engineer feature of EF Core Power Tools?

**Comment by tonysneed** [comment]
For advanced features of Handlebars scaffolding, such as custom helpers, you need to use the dotnet ef CLI rather than the EF Core Power Tools, which do not currently support IDesignTimeServices implementation you would need.
