### ISSUE TITLE
Feature Request: pre-generated views for EF Core 2

### ISSUE THREAD

**Issue by gtrbarbarian** [ErikEJ/SqlCeToolbox#698]
Hi, I'm wondering if pre-generated view creation is going to be added to this tool in the future as it exists in the EF6 version of these tools? I can't find anything on the web about this topic. 

Database engine: SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.5.7)

**Comment by ErikEJ** [comment]
That feature does not exist in EF Core - are you having performance issues?

**Comment by gtrbarbarian** [comment]
Just upon first query, per usual with EF with large schemas. I guess I need to delve into the EF core source to see how it is performing initial loading. So this feature is not part of EF core due to the way initial DBContext loading is done? (i.e. initial context loading is done differently than EF6 and hence is _not needed,_ or it just hasn't been created yet for EF Core 2). I appreciate your tutelage !

**Comment by ErikEJ** [comment]
have you tried the latest preview -I know some performance effort was done there (2.1 preview2)

**Comment by ErikEJ** [comment]
@smbolt  I already did: https://github.com/ErikEJ/SqlCeToolbox/issues/698#issuecomment-381704978 - it does not exist

**Comment by smbolt** [comment]
Thanks so much for your response.  Can you tell me if there is a parallel concern with EF Core with "startup costs" that are concerning enough that a mechanism such as the EF6 pre-compiled views might be warranted?

**Comment by ErikEJ** [comment]
There are discussions here: https://github.com/aspnet/EntityFrameworkCore/issues/1906 and here: https://github.com/aspnet/EntityFrameworkCore/issues/9347
