### ISSUE TITLE
SQLite - DateTime Format seems to be ignored

### ISSUE THREAD

**Issue by kellyelton** [ErikEJ/SqlCeToolbox#70]
I'm opening a database that uses DateTime.Ticks in the datetime fields. Reguardless of what I set the `DateTime Format` or `DateTime Format String` to, the results I see are `1698789-19947451-15 -19:-12:-55`

If I take the raw integer out of that field(using a different sqlite browser) and just run new DateTime(ticks) on it, it works fine.

**Comment by ErikEJ** [comment]
The Toolbox has many ways to "Open" a database - could you share a screenshot, perhaps?

**Comment by kellyelton** [comment]
![animation](https://cloud.githubusercontent.com/assets/1356163/15936141/e0546694-2e37-11e6-8e33-6fd91971236e.gif)

**Comment by kellyelton** [comment]
Does this work for you?

**Comment by ErikEJ** [comment]
Thanks, very nice! I am simply using the System.Data.SQLIte ADO.NET provider, and it has numeorus issues with datetime.

Could you try the adavanced Toolbox option: "Make SQLite datetime read only"

**Comment by kellyelton** [comment]
Should I leave the rest of the options I set the same as I set them?

**Comment by kellyelton** [comment]
I'm actually not seeing that anywhere

**Comment by kellyelton** [comment]
Alright, I downloaded the latest nightly, and that didn't change anything.

**Comment by ErikEJ** [comment]
Tools, Options, SQLite Toolbox, Advanced

**Comment by kellyelton** [comment]
Yeah I already tried it and it didn't work

**Comment by ErikEJ** [comment]
Not sure there is any solution, then. Can you share a database file?

**Comment by kellyelton** [comment]
Well the gif shows the data. It's just an integer. Is there an instance
where setting ticks in a field like that works?

**Comment by ErikEJ** [comment]
I have not done extensive testing of this, as I rely on the ADO.NET provider...

**Comment by kellyelton** [comment]
This actually appears to be working now.

**Comment by ErikEJ** [comment]
Thanks for the heads up!

**Comment by kellyelton** [comment]
Alright so this problem came back, only instead of just showing incorrect dates it gives me an exception whenever I open a table with DateTime fields in it

![image](https://cloud.githubusercontent.com/assets/1356163/23037068/1441ba1a-f453-11e6-8d22-2fa34a022949.png)

Followed by another exception

![image](https://cloud.githubusercontent.com/assets/1356163/23037085/205e21da-f453-11e6-9b3b-97be9197ac06.png)

I'm using the same settings as before.

I'll see if I can't give you a truncated sample of the database I have.

**Comment by kellyelton** [comment]
```
CREATE TABLE "TestTable" (
	`ID`	INTEGER PRIMARY KEY AUTOINCREMENT,
	`Date`	DATETIME NOT NULL
);
INSERT INTO `TestTable` (ID,Date) VALUES (1,636214953107300000);
```

This is all it takes to cause the problem.

**Comment by kellyelton** [comment]
[baddb.sqlite](https://github.com/ErikEJ/SqlCeToolbox/files/781325/baddb.zip)

**Comment by ErikEJ** [comment]
@kellyelton There is no SQLite data type called DATETIME - please see https://www.sqlite.org/datatype3.html - so what date does 1,6 represent?

**Comment by kellyelton** [comment]
1 is just the primary key, and the 636214953107300000 is the date in .net ticks

**Comment by ErikEJ** [comment]
Ok, but according to the data type docs, ticks are not a valid date time value..

**Comment by kellyelton** [comment]
Fair enough. I've inherited this database, so I didn't really think to check the validity of the data types.

The interface though has a checkbox that allows the selection of 'Ticks' for DateTime.

**Comment by ErikEJ** [comment]
Yes, that is built into the System.Data.Sqlite ado.net provider I use, not sure what it means.,.

**Comment by kellyelton** [comment]
While when working with ado.net through EF these values seem to translate properly to and from the database, it's been working for years.

**Comment by kellyelton** [comment]
I have values like this in the edmx
`<Property Name="CreatedDate" Type="datetime" Nullable="false" />`

**Comment by ErikEJ** [comment]
Yes, I use raw sql, EF uses parameters that have DbTypes, that is most likely the difference

**Comment by kellyelton** [comment]
So is this more of a feature request at this point and not a bug?

**Comment by ErikEJ** [comment]
Not sure, have not investigated the SQLite ado.net source enough to be sure. Leaving open until some SQLite expert chimes in....

**Comment by luckydragon76** [comment]
First, like to say. This is a great extension for Visual Studio!! Hats off man!

I too ran into this error while developing a mobile app that would copy data from server to run in a disconnected mode. So the database schema needed to match. I notice that even though the datatype is DATETIME, the values inserted successfully. Trying to run a SELECT * statement failed, but the my application loaded the DATETIME value and displayed it as expected. Just out of curiosity, I thought a would SQLStudio Management tool, and the date display fine.

After reviewing your comment about SQLite DataTypes, changed my Date fields to TEXT or NUMERIC fixed the issue and now able to query the table within the toolbox.

In-short, SQLite documentation doesn't support DATETIME, but able to work naively. Very weird. Since now I understand it, will just convert to TEXT for consistency.

Thanks again!
