### ISSUE TITLE
Export2SQLCE Command Line including data for SQLite despite setting schemaonly

### ISSUE THREAD

**Issue by jhogle** [ErikEJ/SqlCeToolbox#700]
Using the Export2SQLCe command line tool to generate an SQLite .sql file that only contains the schema instead ends up containing schema and data.

### Steps to reproduce
Run the following command:
`Export2SqlCe.exe "Connection String" "Output.sql" "sqlite" "schemaonly"`

Notice that data is also included in the .sql file.

Database engine: SQLite

**Comment by ErikEJ** [comment]
Fixed in latest source..
