### ISSUE TITLE
EF 6 provider not supporting composite primary keys

### ISSUE THREAD

**Issue by pcampion1** [ErikEJ/SqlCeToolbox#704]
Describe what is not working as expected.

After I migrated a working SQL server database to Sqlite using your toolbox according to your instructions I tried to add an edmx model of the new Sqlite db file to my project as per your instructions and I found that all my foreign keys that reference composite primary keys have been rejected with error E6035. Foreign keys that reference non-composite primary keys are unaffected. I have confirmed that all foreign keys are present with SqliteStudio.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
1. Migrate a SQL server database with tables that have foreign keys referencing composite primary keys.
2. Add the new Sqlite database as an edmx into a C# project.
3. Confirm E6035 for all composite foreign keys.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon) 4.7.534.0

Database engine: (SQlite, SQL Compact or SQL Server)  Where do I find this?

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3) VS2017 15.6.6

**Comment by ErikEJ** [comment]
Thanks for reporting this,

This seems like an issue with the SQLite EF6 support, the site for that is here: http://system.data.sqlite.org/
