### ISSUE TITLE
Not able to generate objectContext and use poco classes with SQLite DDEX provider and using Legacy format = true while generatinf TT templates from the DDEX provider.

### ISSUE THREAD

**Issue by ramkris06** [ErikEJ/SqlCeToolbox#705]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
This sounds like a limitation in the System.Data.SQlite EF6 provider, not something I can assist with, sadly.
