### ISSUE TITLE
Reverse Engineer Errors

### ISSUE THREAD

**Issue by YINZHU2016** [ErikEJ/SqlCeToolbox#707]
I used the structure of the reflection database configuration screenshot, but the reflection of the table object, its namespace has a problem
![02e42ef168109b48abb7e77c605c7a29](https://user-images.githubusercontent.com/18044751/39806910-9bfba050-53ad-11e8-98e0-536d28fb740c.png)

The namespace of the entity class file becomes the following structure

namespace xxx.xxx.**UserData/Models**

**Comment by ErikEJ** [comment]
This should be fixed in the latest daily build https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools
