### ISSUE TITLE
This extension is not installable on any currently installed products.

### ISSUE THREAD

**Issue by tfsmag** [ErikEJ/SqlCeToolbox#708]
Having problems installing using the downloadable VSIX file on the marketplace. I've attached the install log.

log below
---------------------------------------------------------------------------------------------
5/9/2018 10:12:47 AM - Microsoft VSIX Installer
5/9/2018 10:12:47 AM - -------------------------------------------
5/9/2018 10:12:47 AM - vsixinstaller.exe version:
5/9/2018 10:12:47 AM - 15.0.26430.16 built by: D15SVC
5/9/2018 10:12:47 AM - -------------------------------------------
5/9/2018 10:12:47 AM - Command line parameters:
5/9/2018 10:12:47 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VSIXInstaller.exe,C:\Users\jeffturner\Documents\EFCorePowerTools1.0.568.vsix
5/9/2018 10:12:47 AM - -------------------------------------------
5/9/2018 10:12:47 AM - Microsoft VSIX Installer
5/9/2018 10:12:47 AM - -------------------------------------------
5/9/2018 10:12:47 AM - Failed to initialize settings for Isolated Shell C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\ssms.exe: Unable to find an entry point named '?' in DLL 'PkgdefMgmt.dll'.
5/9/2018 10:12:47 AM - Initializing Install...
5/9/2018 10:12:47 AM - Extension Details...
5/9/2018 10:12:47 AM - 	Identifier         : f4c4712c-ceae-4803-8e52-0e2049d5de9f
5/9/2018 10:12:47 AM - 	Name               : EF Core Power Tools
5/9/2018 10:12:47 AM - 	Author             : ErikEJ
5/9/2018 10:12:47 AM - 	Version            : 1.0.568
5/9/2018 10:12:47 AM - 	Description        : Useful design-time DbContext features, added to the Visual Studio Solution Explorer context menu.

When right-clicking on a C# project, the following context menu functions are available:
Reverse Engineer - Generates POCO classes, derived DbContext and Code First mapping for an existing database.
Add DbContext Model Diagram - Adds a DGML graph from your DbContext Model.
View DbContext Model SQL DDL - View a SQL DDL script from your DbContext Model.
View Database Schema as Graph - Generates a DGML graph of your database schema, viewable in Visual Studio.
About - Displays version and other diagnostic information about your Visual Studio instance. 
        
5/9/2018 10:12:47 AM - 	Locale             : en-US
5/9/2018 10:12:47 AM - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools
5/9/2018 10:12:47 AM - 	InstalledByMSI     : False
5/9/2018 10:12:47 AM - 	SupportedFrameworkVersionRange : [4.5,)
5/9/2018 10:12:47 AM - 
5/9/2018 10:12:47 AM - 	SignatureState     : Unsigned
5/9/2018 10:12:47 AM - 	Supported Products : 
5/9/2018 10:12:47 AM - 		Microsoft.VisualStudio.Community
5/9/2018 10:12:47 AM - 			Version : [15.0.26730.3,16.0)
5/9/2018 10:12:47 AM - 
5/9/2018 10:12:47 AM - 	References         : 
5/9/2018 10:12:47 AM - 		-------------------------------------------------------
5/9/2018 10:12:47 AM - 		Identifier   : Microsoft.VisualStudio.MPF.15.0
5/9/2018 10:12:47 AM - 		Name         : Visual Studio MPF 15.0
5/9/2018 10:12:47 AM - 		Version      : [15.0]
5/9/2018 10:12:47 AM - 		MoreInfoURL  : 
5/9/2018 10:12:47 AM - 		Nested       : No
5/9/2018 10:12:47 AM - 
5/9/2018 10:12:47 AM - 	Prerequisites      : 
5/9/2018 10:12:47 AM - 		-------------------------------------------------------
5/9/2018 10:12:47 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
5/9/2018 10:12:47 AM - 		Name         : Visual Studio core editor
5/9/2018 10:12:47 AM - 		Version      : [15.0,16.0)
5/9/2018 10:12:47 AM - 
5/9/2018 10:12:47 AM - Signature Details...
5/9/2018 10:12:47 AM - 	Extension is not signed.
5/9/2018 10:12:47 AM - 
5/9/2018 10:12:47 AM - Searching for applicable products...
5/9/2018 10:12:47 AM - Found installed product - Microsoft Visual Web Developer Express 2010
5/9/2018 10:12:47 AM - Found installed product - Microsoft Visual Studio Professional 2015
5/9/2018 10:12:47 AM - Found installed product - Microsoft Visual Studio Community 2015
5/9/2018 10:12:47 AM - Found installed product - Microsoft Visual Studio 2015 Shell (Integrated)
5/9/2018 10:12:47 AM - Found installed product - Global Location
5/9/2018 10:12:47 AM - Found installed product - Visual Studio Professional 2017
5/9/2018 10:12:47 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by ErikEJ** [comment]
It look like you are running VS 15.2.2 and you need a least 1.53 or newer.

5/9/2018 10:12:47 AM - vsixinstaller.exe version:
5/9/2018 10:12:47 AM - **15.0.26430.16** built by: D15SVC

5/9/2018 10:12:47 AM - Microsoft.VisualStudio.Community
5/9/2018 10:12:47 AM - Version : [**15.0.26730.3**,16.0)

https://docs.microsoft.com/en-us/visualstudio/install/visual-studio-build-numbers-and-release-dates

**Comment by tfsmag** [comment]
awesome, thanks. Looks like it's installing now.

**Comment by ErikEJ** [comment]
You are welcome, hope you will update your review...
