### ISSUE TITLE
missing constructor for DbContextOptions

### ISSUE THREAD

**Issue by jonmeyerson** [ErikEJ/SqlCeToolbox#711]
Describe what is not working as expected.
The generated context does not generate a constructor that accepts DbContextOptions to pass to the base class. Example 
`public MyDbContext(DbContextOptions<MyDbContext> options) : base(options) {}`
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
1. right click the project, click reverse engineer then select tables and generate.
### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
1.0.568
Database engine: (SQlite, SQL Compact or SQL Server)
Sql Server
Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2017

**Comment by ErikEJ** [comment]
The generated classes are partial, so just a a MyDataContext.Custom.cs:

    public partial class MyDataContext
    {
        public MyDataContext(DbContextOptions<MyDataContext> options) : base(options) { }
    }

**Comment by ErikEJ** [comment]
Yes, I noticed - included in EF Core 2.1!
