### ISSUE TITLE
Files do not regenerate on their own

### ISSUE THREAD

**Issue by jonmeyerson** [ErikEJ/SqlCeToolbox#712]
Describe what is not working as expected.
After having inititially generated a model through reverse engineer which works the following does not work.
The generated context does not update and the .cs file with the model is not removed after removing a table through the reverse engineer dialog.
The generated context does not update after adding a item through the reverse engineer dialog. 
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
1. right click the project, click reverse engineer, select the database and click ok,  select tables and click ok, Click ok on the last page.
2. right click the project, click reverse engineer, select the database and click ok,  remove a table from the items and click ok, click okay on the last page (item is not removed from dbcontext or removed from project)
2. right click the project, click reverse engineer, select the database and click ok,  add a table from the items and click ok, click okay on the last page (item is not updated in DbContext)
### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
1.0.568
Database engine: (SQlite, SQL Compact or SQL Server)
Sql Server
Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2017

**Comment by ErikEJ** [comment]
Re-open the DbContext file (a VS issue)

For the deleted file, remove manually (I assume you use the new SDK project type?)
