### ISSUE TITLE
Error Code: 80004005

### ISSUE THREAD

**Issue by nasheayahu** [ErikEJ/SqlCeToolbox#714]
Hi ErikEJ,

Using Compact 3.5: After added more tables to DbContext I now get this error from your Toolbox:
Error Code: 80004005
Message: The specified buffer size is not valid.. [Buffer size specified = 0]
Minor Err: 25002
Source : SQL Server Compact ADO.NET Data Provider

Note: Compact works normal in the application

## Steps to reproduce
Tried to refresh the Tables to see the new Tables I added.

### Further technical details
Version 4.7.534.0 - 1,070,461 downloads
SQL Server Compact 4.0 in GAC – No
SQL Server Compact 4.0 DbProvider – No
SQL Server Compact 4.0 DDEX provider – No
SQL Server Compact 4.0 Simple DDEX provider – Yes
SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider – Yes
SQL Server Compact 3.5 DDEX provider – No
Sync Framework 2.1 SqlCe 3.5 provider – No
SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC – No
System.Data.SQLite DDEX provider – No
SQLite Simple DDEX provider – Yes
Database engine: (SQlite, SQL Compact or SQL Server)

Microsoft Visual Studio Community 2017 
Version 15.7.2
VisualStudio.15.Release/15.7.2+27703.2018
Microsoft .NET Framework
Version 4.7.03056
Installed Version: Community

What adjustments I need to do for this to work?

**Comment by nasheayahu** [comment]
I separated the additional Tables to another database, so what could cause this error for the Tool?

**Comment by ErikEJ** [comment]
Please share the SQLCE 3.5 version that you use - are you using the latest update?

And share the database file with me - ejlskov @ hotmail . com

**Comment by ErikEJ** [comment]
Closing as no additional information available, fell free to reopen if you can supply more info
