### ISSUE TITLE
Error with SQLite when script conext menu options are selected

### ISSUE THREAD

**Issue by asiergonzalezgorordo** [ErikEJ/SqlCeToolbox#717]
Describe what is not working as expected.

### Steps to reproduce
If I click in any of Script context menu options, it happens with all.
![imagen](https://user-images.githubusercontent.com/10169840/40829566-1c66a554-6584-11e8-8429-1b185cccb09a.png)
Following error is thrown.
![imagen](https://user-images.githubusercontent.com/10169840/40829607-3fea6042-6584-11e8-8eae-126481e55421.png)

### Further technical details
Toolbox/Power Tools version: 4.7.534.0

Database engine: SQlite

Visual Studio or SSMS version: Visual Studio 2017

**Comment by ErikEJ** [comment]
I am unable to reproduce, so I assume it is database specific, please share the database with me, you can email me privately at  ejlskov @ hotmail.com

**Comment by asiergonzalezgorordo** [comment]
Hi! I have tried now with **the latest build** and now its working fine.

Thanks!
