### ISSUE TITLE
Can't generate model from database. SQlite EF6 VS 2017 15.7

### ISSUE THREAD

**Issue by kevindaizj** [ErikEJ/SqlCeToolbox#722]
none of tables is displayed in "Entity Data Model Wizard". But i am surely confirmed that the connecting db has tables.  see the screenshot below:
![qq 20180626181711](https://user-images.githubusercontent.com/12622531/41905572-338ec646-796e-11e8-8d2f-666916e95cee.png)

**Comment by ErikEJ** [comment]
Your tables must have a primary key...

**Comment by kevindaizj** [comment]
Problem Solved. Thx
