### ISSUE TITLE
default keyword missing for datetime column with default value.

### ISSUE THREAD

**Issue by pnoiboi77** [ErikEJ/SqlCeToolbox#723]
Scripting schema for SQLite does not include "default" keyword for DateTime columns with a default value.

### Steps to reproduce
First, create a table in sql server with a DateTime column that has a default value (for example getdate()) and not null. Under Data Connections, right click on a Sql Server connection and select Script Database ->Script Schema for SQLite. 

Notice how [DateCreated] datetime current_timestamp NOT NULL line is created. The correct syntax should be  [DateCreated] datetime default current_timestamp NOT NULL

### Further technical details
ErikEJ.SqlCeScripting version 3.5.2.75

Database engine: (SQlite, SQL Compact or SQL Server)
SQLite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2017 Community

**Comment by ErikEJ** [comment]
It does not work without the "default" keyword, or?

**Comment by pnoiboi77** [comment]
Correct. I figured it was a bug because I also have a bit field with a default value of 0 and your scripts are applying the "default" keyword when the script is generated for those columns. I have to manually add "default" for the date columns in the script to get sqlite to autogenerate the date.

**Comment by ErikEJ** [comment]
Are you using the Toolbox - just looking at your odd version number...

**Comment by pnoiboi77** [comment]
Yes. I searched and installed your toolbox through visual studio Extension and Updates last week. So the latest one you have available from the  Visual Studio Gallery is the version I'm using.

**Comment by ErikEJ** [comment]
Fixed in latest daily build
