### ISSUE TITLE
SSMS Extension about dialog links to the VS version

### ISSUE THREAD

**Issue by Mertsch** [ErikEJ/SqlCeToolbox#725]
### Steps to reproduce
1. Click the link in about dialog, and arrive at https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details

Should be: https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolboxforSSMS#overview

### Further technical details
Toolbox for SSMS 4.7.460
Database engine: SQlite
SSMS version: 17.8.1

**Comment by ErikEJ** [comment]
Fixed in latest daily build
