### ISSUE TITLE
Error on connectionString 

### ISSUE THREAD

**Issue by PaulBression** [ErikEJ/SqlCeToolbox#727]
Hi ! 

I'm starting SQLite for first time and i tried to connect my SQLite file but i don't succed...

When i create my data connection, i set my connectionString but when i submit, i'have an error.

![capture](https://user-images.githubusercontent.com/42279233/43972640-55cf066e-9cd5-11e8-80ac-cad75634f3bc.PNG)

I'm not sure if it's the path to paste in connectionString.

I think my error is stupid but i have no idea

Thank you for your help !

my package.config contain :

  <package id="EntityFramework" version="6.2.0" targetFramework="net461" />
  <package id="System.Data.SQLite" version="1.0.108.0" targetFramework="net461" />
  <package id="System.Data.SQLite.Core" version="1.0.108.0" targetFramework="net461" />
  <package id="System.Data.SQLite.EF6" version="1.0.108.0" targetFramework="net461" />
  <package id="System.Data.SQLite.Linq" version="1.0.108.0" targetFramework="net461" />

Database engine: SQLite 

IDE : Visual Studio 2017

**Comment by ErikEJ** [comment]
I think you  should have a look at the guide here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by PaulBression** [comment]
The probleme is that i tried it, but it doesn't work. 
I will create a new project and restart your tutorial ...

On connection string, it's the path of the file to enter in input ?

Sorry if my English is bad

Paul B.
