### ISSUE TITLE
Investigate support for SSMS 2016

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#73]
[VSIXProject1.zip](https://github.com/ErikEJ/SqlCeToolbox/files/345644/VSIXProject1.zip)
Initially enable SQL Server Compact and SQLite features (without VS integration).

Enable re-use of existing code (may require some refactoring)

https://www.nuget.org/packages/SQLConnectionStringUI/ 

Add new folder SSMSToolbox, with initial loadable ExplorerToolWindow, that adds button to Tools and other Windows menu

"C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Ssms.exe"

https://blogs.msdn.microsoft.com/visualstudio/2013/08/08/update-for-extension-authors-vsix-manifest-version-range-attribute/

http://www.sqlservercentral.com/Forums/Topic1536227-2799-1.aspx 

https://social.msdn.microsoft.com/Forums/sqlserver/en-US/595faee8-d718-4363-a272-978dbc71a3b8/how-to-register-vspackage-into-sql-server-management-studio?forum=sqltools

https://social.msdn.microsoft.com/Forums/vstudio/en-US/b1952c59-2b40-4972-b502-49b187060ca4/how-to-deploy-an-extension-to-an-isolated-shell-app-for-debugging?forum=vsx

http://stackoverflow.com/questions/26659852/vspackage-did-not-load-correctly-how-to-revert-continue-to-show-this-error-mes

https://visualstudiogallery.msdn.microsoft.com/f1cc3f3e-c300-40a7-8797-c509fb8933b9 installer project

**Comment by ErikEJ** [comment]
{9b80f327-181a-496f-93d9-dcf03d56a792}

**Comment by ErikEJ** [comment]
- [ ] Add new folder SSMSToolbox, with initial loadable ExplorerToolWindow, that adds button to Tools and other Windows menu
- [ ] Implement ExplorerControl (link) - initiall without context menus
- [ ] Implement ExplorerControl context menus
- [ ] 
- [ ]

**Comment by devvcat** [comment]
Hi @ErikEJ, 

how did you choose the `PackageGuidString` of your SSMS extension?

I am developing an extension of my own, however am stuck on error 'Package did not load correctly'. The workaround is to set 'SkipLoading=1' in registry, but this is not a clean solution. Then searched the internet and found your source code. You extension does not give this error and I've found out that when I take you `PackageGuid` the error is NOT displayed. If I take a random GUID, the error is shown.
I guess the Guid is validated by SSMS somehow, how did you choose it.

Thank you,
Stanislav

**Comment by ErikEJ** [comment]
You need to contact SSMS PM directly, SSMS has a "whitelist" of package GUIDs that he hands out on a case by case basis. Please email me, and I will share his contact info with you
