### ISSUE TITLE
Impossible to configure data set after creating new table

### ISSUE THREAD

**Issue by peterzarzour** [ErikEJ/SqlCeToolbox#730]
Hi
Thanks for you tool
In new visual studio express for desktop 2015, when I installed your tool, I can now see my local database and I can add tables an manage it

the problem is that, in vb studio express, after doing that, you need to configure the dataset before slide it to the form you want it. In configuration wizard, you check the litte box left to your new table and so... your table is ready to be used (slide) to the form you need it

1.Can you tell me how to do this please.. I really need to work in my projects 2015 and before and I cannot anymore

2.Also, do you have the old iso of visual studio 2015 express for desktop that was made to work with local database?

**Comment by ErikEJ** [comment]
1: DataSets are not supported and not recommended, use SqlCeResultSet og LINQ to SQL

2: No, I do not, sorry

**Comment by peterzarzour** [comment]
Hi

thanks for your answer

I need to figure something out please

I copy paste the visual studio 2015 folder from an windows 8 computer that uses old fashion dataset wizard and paste it to windows 10 new computer... knowing that some bugs will occur but when i will run it...

when I run the exe file from this copy paste  visual studio 2015 folder on the new windows 10 computer.. i still see the new way for dataset wizard impossible to configure the new table added with your tool but impossible to slide it on the form

my question is.. if this new way of managing database in visual community  appears when I run visual studio 2015 copy pasted on the windows 10 computer... it means that this portion of the software do not take this managment in the visual studio 14.0 folders/files ... 

1.so where are those source of dataset wizard managment...
where does an old version of studio 2015 copy pasted takes this new datataset managment way else where from his folders

If I can't change it to old style...
2.do you have a tutorial to replace the dataset wizard meaning that I will not slide the dataset table anymore on my form but I will programme it or something else that you know 

thanks

**Comment by ErikEJ** [comment]
I am not sure I understand what you are asking - I have a guide for LINQ to SQL here:

http://erikej.blogspot.com/2013/10/sql-server-compact-4-desktop-app-with.html

**Comment by peterzarzour** [comment]
thanks for your answer

I'll make it simple

before.. we had to configure the dataset in the Data source after creating a new table so that the dataset in data source is updated with the new table and then we slide it on the chosen form

1.i understand I cannot do that anymore so do you have a tutorial to do instead of that after creating a new table

2.  do I have to recode all my projects with local databases? It would be incredable... hours and hours of recoding passing from : 

 ```
 For x = 0 To Form1.Database1DataSet1.datbase.Rows.Count - 1

next
```


to that :

 ```
 Dim cn As New SqlConnection()
        Dim DS As New DataSet()
        Dim da As SqlDataAdapter
        Dim dr As DataRow
        Dim cmdBuilder As SqlCommandBuilder



       
            cn.ConnectionString = "Data Source=xxxxxx;User Id=xxxxxx;Password=xxxxxxxx;"
           
 cn.Open()



            'Initialize the SqlDataAdapter object by specifying a Select command 
            'that retrieves data from the sample table.

            da = New SqlDataAdapter("SELECT * FROM database order by no", cn)


            'Initialize the SqlCommandBuilder object to automatically generate and initialize
            'the UpdateCommand, InsertCommand and DeleteCommand properties of the SqlDataAdapter.

            cmdBuilder = New SqlCommandBuilder(da)

            'Populate the dataset by running the Fill method of the SqlDataAdapter.
            da.Fill(DS, "database")

     
            Dim dateX As String = Today.Month.ToString + Today.Year.ToString
            Dim nom As String = "Home"
            Dim verificateur As Boolean = False

            For x = 0 To DS.Tables("database").Rows.Count - 1

next

```
