### ISSUE TITLE
Command line tools wiki page has missing hyperlink

### ISSUE THREAD

**Issue by icnocop** [ErikEJ/SqlCeToolbox#731]
There's a missing hyperlink on the `Command line tools` wiki page:
https://github.com/ErikEJ/SqlCeToolbox/wiki/Command-line-tools

>     this will generate a .sql script in SQLite3 dump file format, for more information see my blog post here

I expected `here` to be hyperlinked.

Thank you.

**Comment by ErikEJ** [comment]
Fixed
