### ISSUE TITLE
"index already exists" error when trying to migrate from Microsoft SQL Server to SQLite

### ISSUE THREAD

**Issue by icnocop** [ErikEJ/SqlCeToolbox#732]
Hi.

When I try to migrate from a Microsoft SQL Server database to SQLite, I get the following error:

> ErrorCode : 1
> Message   : SQL logic error
> index MyIndex already exists

### Steps to reproduce
1. Create a new Microsoft SQL Server database
2. Create two tables
3. Create an index on each table with the same name
4. Try to migrate the database to SQLite

I expected the name of the index to contain the table name so that the migration succeeds.

### Further technical details
SQLite & SQL Server Compact Toolbox 4.7
Microsoft SQL Server Enterprise (64-bit) 2014 (12.0.5214.6)
Visual Studio Enterprise 2015 Update 3 (14.0.25431.01)

Issue https://github.com/ErikEJ/SqlCeToolbox/issues/424 seems to be related.

Thank you.

**Comment by ErikEJ** [comment]
Fixed in latest daily build
