### ISSUE TITLE
ASP.NET Core 2.1 Error EF Power Tools - Migrations Tool

### ISSUE THREAD

**Issue by rehaddad** [ErikEJ/SqlCeToolbox#735]
Hi, I created a new ASP.NET Core 2.1.0 project, add a class and the Context:

public class Produto
{
    public int ProdutoID { get; set; }
    public string Descricao { get; set; }
    public decimal Preco { get; set; }
    public decimal Qtde { get; set; }
    public decimal ValorEstoque => Preco * Qtde;
}

public class DBContexto : DbContext
{
    public DBContexto (DbContextOptions<DBContexto> options)
        : base(options)
    {
    }

    public DbSet<Produto> Produto { get; set; }
}

---------
appsettings.json - declare database
"ConnectionStrings": {
    "DBContexto": "Server=local;Database=PBIBanco;Trusted_Connection=True;MultipleActiveResultSets=true"
  }

---------
Package:
<PackageReference Include="Microsoft.AspNetCore.App" />

When I build the Project it's OK. But when I try to use Migrations Tool (preview), right click into the Project / EF Core Power Tools / Migrations Tool (preview), show me the messagebox:
could not load file or assembly 'microsoft.aspnetcore.hosting.abstractions, version=2.1.0.0

My goal is use EF Power Tools to generate migrations scripts. Can you help me, please?
Best.

Versions: 
EF Power Tools - Version 1.0.643.0
SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Visual Studio Enterprise 15.7.6

**Comment by ErikEJ** [comment]
What if you move the context and migrations to a .net Core class library?

**Comment by rehaddad** [comment]
I tried to move to a DLL. And then, when I click at Add Migration button, shows me: System.IndexOutOfRangeException: Index was outside the bounds of the array. 
in https://1drv.ms/f/s!Aiq_G0V2u7eXg0UNCCkYOvH2vzvl I put the Picture error (F1) and the zip Project (ASPCore_PBI.ZIP)
Best.

**Comment by ErikEJ** [comment]
I will have a look

**Comment by ErikEJ** [comment]
This issue was moved to ErikEJ/EFCorePowerTools#85
