### ISSUE TITLE
Publish "daily" NuGet package builds to NuGet

### ISSUE THREAD

**Issue by icnocop** [ErikEJ/SqlCeToolbox#743]
I would like to see the "ErikEJ.SqlCeScripting" NuGet package updated with the latest code from the master branch.

Currently, the latest "ErikEJ.SqlCeScripting" NuGet package was published to nuget.org on November 5th, 2017 (v3.5.2.74).

I would like to see continuous deployment/delivery like the vsix file.

For daily builds, the NuGet package may be marked as "prerelease".

Thank you.

**Comment by ErikEJ** [comment]
I have just published build 79 to NuGet.org
