### ISSUE TITLE
Export Table Schema

### ISSUE THREAD

**Issue by tlcoder** [ErikEJ/SqlCeToolbox#744]
Trying to export a tables schema, but the exported script does not have any create statements.

Always shows "insert statements":
![image](https://user-images.githubusercontent.com/20194391/45764515-7db38280-bbf8-11e8-83d1-b7e46dfcfc8f.png)

### Steps to reproduce
![image](https://user-images.githubusercontent.com/20194391/45763857-0b8e6e00-bbf7-11e8-9432-b2bf6e09a047.png)

### Further technical details
ErikEJ.SqlCeScripting version 3.5.2.77

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server 2017 - 14.0.1000.169

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
![image](https://user-images.githubusercontent.com/20194391/45764399-3e853180-bbf8-11e8-9bc1-c95b21dc72b2.png)

Please let me know if this is an issue or if I'm doing something wrong.

Thanks,
Tony

**Comment by ErikEJ** [comment]
Is this in the SSMS extension?

**Comment by tlcoder** [comment]
Correct

**Comment by ErikEJ** [comment]
Sounds like a bug, looking into it

**Comment by ErikEJ** [comment]
Fixed in latest daily build, let me know if it works for you
