### ISSUE TITLE
"Rename Connection..." broken?

### ISSUE THREAD

**Issue by sdfir3** [ErikEJ/SqlCeToolbox#747]
When trying to "Rename Connection...", the connection isn't renamed.

### Steps to reproduce
"Rename Connection..." -> type "NewName" -> the connection still has it's old name.

### Further technical details
Toolbox/Power Tools version: 4.7

Database engine: SQL Compact 4.0

Visual Studio or SSMS version: Visual Studio Community 2015 (14.0.25431.01 Update 3)

**Comment by ErikEJ** [comment]
I cannot see that feature anywhere in the recent release - exactly which version of the Toolbox are you running?

**Comment by ErikEJ** [comment]
Sorry, found it now - and yes, it appears to be broken

**Comment by ErikEJ** [comment]
I have decided to remove this feature for now
