### ISSUE TITLE
A path problem in DB4Repository

### ISSUE THREAD

**Issue by challaloussama** [ErikEJ/SqlCeToolbox#749]
hello , I'm using a VB Code , i want to generate a sqlite Script programmatically from my SDF 
but i get this error ("The given path's format is not supported")

this is my code : 

![sans titre](https://user-images.githubusercontent.com/44205606/47029155-c06a6b00-d162-11e8-960c-86a2fcaaff3d.png)

**Comment by icnocop** [comment]
Can you provide the complete stack trace please?

**Comment by ErikEJ** [comment]
Maybe try "Data Source" iso "DataSource" ?

**Comment by ErikEJ** [comment]
Closing as the requested feedback was not provided
