### ISSUE TITLE
Migrate SQL Server to SQLite : InteropServices.COMException

### ISSUE THREAD

**Issue by Garrin07** [ErikEJ/SqlCeToolbox#752]
When trying to migrate SQL Server to SQLite :

![capture081118](https://user-images.githubusercontent.com/17246611/48191463-76316f80-e345-11e8-94fc-ad420022babb.PNG)

### Steps to reproduce
"Migrate to SQLite..." > "Ok" > "Save"

### Further technical details
Toolbox/Power Tools version: 4.7.534.0

Database engine: SQLite, SQL Server 14.0.1000.169

Visual Studio : Visual Studio Pro 2017 15.8.9

SMSS : 17.6

**Comment by ErikEJ** [comment]
Reboot VS?

**Comment by Garrin07** [comment]
I've already tried to reboot VS, and to reinstall the SQLite Toolbox.
I believe that the error appeared when I updated visual studio. Before that worked with this same SQL database.

**Comment by zdomokos** [comment]
Tried to do the same thing, got the same error message.

**Comment by ErikEJ** [comment]
@zdomokos  Same VS version?

**Comment by ErikEJ** [comment]
Could you both please try the latest daily build?

**Comment by Garrin07** [comment]
I'v the same problem with daily build ( v4.7.609 )

**Comment by ErikEJ** [comment]
Can you share a db file that reproduces the issue?

**Comment by Garrin07** [comment]
This simple database is enough to reproduce the problem :

[Test.zip](https://github.com/ErikEJ/SqlCeToolbox/files/2576468/Test.zip)

Thank you for your time.

**Comment by Garrin07** [comment]
I've the same problem with 15.9.1 ...

**Comment by YannPenven** [comment]
Same here,

Toolbox/Power Tools version: 4.7.560.0

Database engine: SQLite, SQL Server 14.0.2002.14

Visual Studio : Visual Studio Pro 2017 15.8.9

SMSS : 17.9

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No


Sync Framework 2.1 SqlCe 3.5 provider - No


SQLite ADO.NET Provider included: 1.0.107.0
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

I have SQLite for windows runtime and SQLite for Universal Windows Platform extension installed as well (i don't know if it changes anything)

I'm on windows 10 Professionnal version 1803

**Comment by ErikEJ** [comment]
Upgraded to VS 15.9.2 - unable to repro ???

**Comment by Garrin07** [comment]
Same problem with 15.9.2

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build https://github.com/ErikEJ/SqlCeToolbox/commit/63e80301504cb13d585f9d2f0e8fa65fe02228b1

**Comment by Garrin07** [comment]
This build fix my problem, but i believe that outputs don't work anymore.

**Comment by Garrin07** [comment]
I use french version

**Comment by ErikEJ** [comment]
Well, that explains it - it has never worked on non-Englsh VS!

**Comment by YannPenven** [comment]
it's was working a few weeks ago :)

**Comment by Garrin07** [comment]
Thank you for your time, i will use your daily build.

**Comment by ErikEJ** [comment]
I will close this, status messages are shown in the VS Status bar
