### ISSUE TITLE
I can't view table's records

### ISSUE THREAD

**Issue by regismus** [ErikEJ/SqlCeToolbox#754]
Describe what is not working as expected.

### Steps to reproduce
In a table, option "Edit top 200 rows"

### Further technical details
Versión 4.7.534.0

SQL compact

Visual Studio 2017 versión 15.9.2
.NET Framework 4.7.0.3056
![image](https://user-images.githubusercontent.com/45361965/49019874-47155d80-f18f-11e8-83f2-9d8804586872.png)

**Comment by ErikEJ** [comment]
Have you tried re-booting computer and/or VS?

**Comment by regismus** [comment]
Yes, of course. I so compact, shrink and repair the database with VS 2010

**Comment by regismus** [comment]
Sometimes I also have this other error
![image](https://user-images.githubusercontent.com/45361965/49150285-a5b41600-f30c-11e8-8933-c3eac81e60c8.png)

**Comment by icnocop** [comment]
> El procesamiento del distribuidor se ha suspendido, pero aún se están procesando mensajes.
Dispatcher processing has been suspended, but messages are still being processed.

> Hay una infracción de uso compartido de archivos. Puede que otro proceso esté usando el archivo.
There is a file sharing violation. A different proccess might be using the file.

Make sure no other process has the sdf file open.

**Comment by regismus** [comment]
Hello everyone and thanks for your help. After spending several days trying everything, uninstalling applications, reinstalling visual studio and its accessories, ... and not getting anything. Finally we have managed to locate the failure, the hard disk has failed and that was affected to the proper functioning of the databases.

**Comment by ErikEJ** [comment]
Thanks for the update!
