### ISSUE TITLE
Unable to login with AD MFA Support

### ISSUE THREAD

**Issue by nick5454** [ErikEJ/SqlCeToolbox#756]
Describe what is not working as expected.
Using my Azure AD account ( MFA Support in SSMS ) I cannot log in.

### Steps to reproduce
Try logging in with an AzureAD account

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon) Not sure, Not listed

Database engine: SQL Compact or SQL Server

Visual Studio or SSMS version: SSMS 17.9 VS 15.9.3

**Comment by ErikEJ** [comment]
Ping?

**Comment by nick5454** [comment]
Sorry was on vacation.

![image](https://user-images.githubusercontent.com/5711577/50113767-7fe1a900-0208-11e9-8724-c5320b52b492.png)
 That picture is a screen shot from SSMS. I need to login with my AAD(Azure AD account )

**Comment by nick5454** [comment]
Let me know if you need more information.

**Comment by ErikEJ** [comment]
I do need more info - how does this relate to SQLite/SQL Server Compact Toolbox ?

**Comment by ErikEJ** [comment]
Ping? I dont think the Toolbox shows this dialog !?

**Comment by nick5454** [comment]
The issue I had was I have 10 tables and I want to Scaffold them, but googling I came across your tool and I needed to login, so I could choose the tables. However your tool didn't allow me to login. My company switch from AD to AzureAD in the cloud integrated with Office365. My user does not have a traditional windows account, but an AAD. So I can't login with my user in your tool. But, I can through SSMS using MFA support. I'll do a screenshot document and upload it, so you can see the whole process.

**Comment by nick5454** [comment]
Unless your tool was not meant to connect to a SQL database in the Azure ecosystem. So I right click as new Sql Connection.

![image](https://user-images.githubusercontent.com/5711577/50347862-b49d7b00-04fc-11e9-8e2b-25ed2d27c770.png)

Now I want to login, but all of these types in the drop down don't support my user located in the cloud. 

![image](https://user-images.githubusercontent.com/5711577/50348118-7bb1d600-04fd-11e9-9c16-e4b017bda830.png)

And on this  link it's looks like I need "Interactive" options

![image](https://user-images.githubusercontent.com/5711577/50348175-98e6a480-04fd-11e9-80a1-97446c4b4a54.png)

https://docs.microsoft.com/en-us/sql/ssdt/azure-active-directory?view=azuresqldb-current 

Which is MFA support.

**Comment by nick5454** [comment]
This weekend I can download your code and see how to add this. See if I can help.

**Comment by nick5454** [comment]
And  here is the experience I was expecting: ( This is the Sql Object Explorer in VS2017 )

![image](https://user-images.githubusercontent.com/5711577/50348912-c6cce880-04ff-11e9-95ea-313eb935a42d.png)

I log in with my AAD account ( Using Windows with Interactive 

![image](https://user-images.githubusercontent.com/5711577/50348944-dcdaa900-04ff-11e9-8632-db90a2db7cf4.png)

 And I see it listed

**Comment by ErikEJ** [comment]
I am using the VS Server Explorer APIs to save the connection, and it appears that it does not support AAD auth with MFA. Maybe in VS 2019 preview?

**Comment by nick5454** [comment]
Visual Studio.

**Comment by nick5454** [comment]
> I am using the VS Server Explorer APIs to save the connection, and it appears that it does not support AAD auth with MFA. Maybe in VS 2019 preview?

Ok. I saw this [AAD in WPF](https://azure.microsoft.com/en-us/resources/samples/active-directory-dotnet-native-desktop/) but, i'm not sure if it's possible with an extension. 

I'm going to close this since it may not be possible at the moment. I think think AAD isn't quite mature yet. ( We've had a lot of little issues here and there ) If I find a way, I'll create a sample extension and share it in a new ticket, so you can focus on more important things. 

Thanks for trying to help.
