### ISSUE TITLE
Migrating MS SQL database to SQL Compact fails when the server and database collations differ

### ISSUE THREAD

**Issue by ivaylomi** [ErikEJ/SqlCeToolbox#767]
I have a database with Cyrillic_General_CI_AS collation on LocalDB (with SQL_Latin1_General_CP1_CI_AS collation). After upgrading to the latest version of the Toolbox the attempt to migrate this database to SQL CE fails with the error dialog below. Before this upgrade the migration was working without any errors.

![collationerror](https://user-images.githubusercontent.com/46621272/51071855-9ab90900-1660-11e9-83e3-8a76c79ac1e7.jpg)

The problem seems to be not my database, because the error is the same with a new, very simple database as described.

### Steps to reproduce
1. Create a database with Cyrillic_General_CI_AS collation on MS SQL with Latin collation
2. Create a database table with one column (the column type seems to do not matter; I used INTEGER)
3. Try to migrate the database to SQL CE

### Further technical details

Toolbox/Power Tools version: 4.7.630.0

Database engine: SQL Server 2017 LocalDB => SQL CE

Visual Studio or SSMS version: Visual Studio Community 2017 15.9.5

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know it is resolves your issue

**Comment by ivaylomi** [comment]
Yes, the version from the daily build works correctly as before.

Thank you!
