### ISSUE TITLE
export2sqlce : exporting table with computed colums to SQLite

### ISSUE THREAD

**Issue by roya12** [ErikEJ/SqlCeToolbox#770]
I have been using export2sqlce for awhile to export from mssql server to sqlite, recently I added several computed column to mssql server, however, the computed columns are not exported while using the tool.

Does export2sqlce support exporting of computed columns in mssql to sqlite?

**Comment by ErikEJ** [comment]
Not currently - not sure it is feasible/possible.

**Comment by roya12** [comment]
Ok, no worries. Thank you for the info!
