### ISSUE TITLE
Delay unresponsiveness

### ISSUE THREAD

**Issue by mbolanosd** [ErikEJ/SqlCeToolbox#772]
Just installed and trying to use extension.

Extension SQLLite/SQL server compact toolbox 4.7.634 likely cause X seconds of unresponsiveness... and indicates that I should disable the extension. While the unresponsiveness seems to freeze VS2017 it also freezes all other applications and Windows 10, for X seconds that varies and usually for minutes, until VS2017 is done with processing any part of SQLLite/SQL selected option. Once finished processing the results are fine.
 
### Steps to reproduce
Cannot really reproduce steps as it happens with any option to process from SQLLite/SQL toolbox. When loading VS2017, it loads normally.

### Further technical details
Version 4.7.634.0 - 1.239.151 downloads
SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider - Yes
SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Microsoft Visual Studio Enterprise 2017 version 15.9.6 & Microsoft .NET Framework version 4.7.03056 full installation.

Please help!

**Comment by ErikEJ** [comment]
Not much to go by, and never seen this or heard reports from others. Virus scanner?

**Comment by ErikEJ** [comment]
Ping?

**Comment by ErikEJ** [comment]
Closing as the requested info was never supplied, feel free to re-open if you can provide more detailed repo steps an other info.
