### ISSUE TITLE
"Execution Timeout expired" when script schema and Data

### ISSUE THREAD

**Issue by penielx** [ErikEJ/SqlCeToolbox#774]
I still use it last week and worked perfectly. buy now is no longer working due to updates. please, can I get the previous build/version?

![step 1](https://user-images.githubusercontent.com/45533861/52921027-21719d80-3313-11e9-9943-c6e8febef8f5.png)

![step2](https://user-images.githubusercontent.com/45533861/52921028-21719d80-3313-11e9-9d33-6ecefcd7cab3.png)

![step3](https://user-images.githubusercontent.com/45533861/52921026-20d90700-3313-11e9-8112-cbd420d74d79.png)

**Comment by ErikEJ** [comment]
Please try the latest daily build https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes and let me know if that fixes your issue

**Comment by penielx** [comment]
Thanks Is working fine now.
