### ISSUE TITLE
Create Table script

### ISSUE THREAD

**Issue by ttrujillo99** [ErikEJ/SqlCeToolbox#776]
[MY_TimeStamp] datetime DEFAULT strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime') NOT NULL

I have a datetime field that defaults to the date and time.   The above line gets created when I use the "Script as CREATE" for the table.  It will not work unless I add parenthesis around the strftime function.

[MY_TimeStamp] datetime DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now', 'localtime')) NOT NULL

version 3.5.2.80

**Comment by ErikEJ** [comment]
Fixed in the latest daily build, please let me know if that solves your issue

**Comment by ttrujillo99** [comment]
It appears to be fixed.   I like tool. It makes it real easy to work with SQLite.

**Comment by ErikEJ** [comment]
Thanks - If you like my tools, I would be very grateful for a rating or review here:
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox#review-details
