### ISSUE TITLE
Installer succeeds but nothing showing in VS or SSMS

### ISSUE THREAD

**Issue by erik-sunderware** [ErikEJ/SqlCeToolbox#778]
Hi there,

I just tried installing the SSMSToolbox, and the installation seems to have completed successfully.
Re-installing leads to a pop-up with "This extension is already installed to all applicable products"
(tried both normal and command-line installation).

However, I can't seem to find any trace of it in VS or SSMS:
_ SSMS: no "SQL Server Compact Edition" option under Connect to Server > Server Type
_ SSMS: error message when trying to open a .SDF file ("There is no editor available for ...")
_ VS: no "SQL Server Compact Toolbox" icon displayed in Server Explorer (as per Getting Started page)

I checked prereqs, and I seem to have both Microsoft SQL Server Compact 3.5 SP2 and 4.0 installed.
FYI: SSMS is version 17.9.1, VS is version 15.9.1

Anything I am missing?

Thx,

(another) Erik

**Comment by ErikEJ** [comment]
Have you looked here: https://github.com/ErikEJ/SqlCeToolbox/wiki

To start using it in Visual Studio, launch the Toolbox from the button in Server Explorer, or from the Tools menu **(View menu in SSMS)**:

**Comment by erik-sunderware** [comment]
Yes, I looked at that page.
But the button isn't there (in Server Explorer)...
![image](https://user-images.githubusercontent.com/40926926/53559442-f73f9b80-3bae-11e9-8bbe-a987d64df6d0.png)

**Comment by ErikEJ** [comment]
I am confused - there is no "Server Explorer" in SSMS?? In SSMS, look under the "View" menu...

**Comment by erik-sunderware** [comment]
OK!!!! I just realized that the VS extension and the SSMS extension are 2 separate packages!!!
Sorry about that, I thought it was one single package. My bad, seems really obvious now... :-(
The command line installer using an executable in a Visual Studio path probably confused me.

**Comment by ErikEJ** [comment]
Then I will close this...
