### ISSUE TITLE
Migrate to SQL Server report object named 'PrimaryKey' Exists Error.

### ISSUE THREAD

**Issue by superbug8848** [ErikEJ/SqlCeToolbox#781]
When I want to migrate a CE database into SQL SERVER, when multi tables has primary key, all the key name will be 'PrimaryKey', When I scipte the database to SQL SERVER, can also see these names.
But when I run the script on SQL SERVER， will report the ERROR : object named PrimaryKey alread exists.
all the struct and data be import to SQL SERVER, but not include the primary key.
I Think you can change the PrimaryKey name to PrimaryKey_[TableName]。

### Steps to reproduce
Migrate a CE database file to SQL SERVER with multi tables have Primary Key.

### Further technical details
Toolbox/Power Tools version: 4.7.634.0

Database engine: (SQlite, SQL Compact or SQL Server)
SQL CE: 4.0 ,  SQL SERVER: 2017 Localdb

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
vs 2017  15.9.8

**Comment by ErikEJ** [comment]
Can you share a repro schema or database?

**Comment by ErikEJ** [comment]
ping?

**Comment by ErikEJ** [comment]
Closing as the requested additional info has not been supplied - feel free to re-open
