### ISSUE TITLE
GetSelectedNodes throws exception on start up

### ISSUE THREAD

**Issue by MrMonotone** [ErikEJ/SqlCeToolbox#782]
I try to run build the and run the SSMSToolbox project on master and when the ObjectExplorer calls GetSelectedNodes (ObjectExplorerManager, L105) the program errors with:
``
Exception thrown: 'System.Runtime.InteropServices.COMException' in Microsoft.SqlServer.Management.SqlStudio.Explorer.dll
An exception of type 'System.Runtime.InteropServices.COMException' occurred in Microsoft.SqlServer.Management.SqlStudio.Explorer.dll but was not handled in user code
Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
``
### Steps to reproduce
1. Build Shared Projects
2. Set SSMSToolbox as Startup Project and hit start.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Unknown
Database engine: (SQlite, SQL Compact or SQL Server)
SQLServer
Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2017 15.9.8, SSMS 17.9.1

**Comment by ErikEJ** [comment]
Hmmm - it can be brittle. Are you running VS as Admin?

**Comment by MrMonotone** [comment]
Yes any other ideas what it might be?

**Comment by ErikEJ** [comment]
No, you are simply entering an unsupported world of pain 😈

**Comment by MrMonotone** [comment]
Closing this for now. It seemed to be a weird caching issue with VS. I solved it by downloading the project and compiling again. Deleting the existing addin before doing this.
