### ISSUE TITLE
What is the problem?

### ISSUE THREAD

**Issue by gaoconggit** [ErikEJ/SqlCeToolbox#784]
![image](https://user-images.githubusercontent.com/10905068/54996688-eb57c580-5004-11e9-976c-4c05489fd480.png)

**Comment by ErikEJ** [comment]
Hi, I do not know this language, can you provide a translation in English (or Danish, Norwegian Swedish, German or French) Thanks.

**Comment by gaoconggit** [comment]
Sorry, ConnectString I entered path but did not join Data Source=

**Comment by ErikEJ** [comment]
So it is working now?

**Comment by gaoconggit** [comment]
Thank you very much, work well.
