### ISSUE TITLE
SQL Server migration - Same Table Name, different Schema not handled well

### ISSUE THREAD

**Issue by mikeytinks** [ErikEJ/SqlCeToolbox#787]
When migrating 2 tables of the same name in different SQL Server DB Schema Names, the fields are merged into a single create table statement. Any duplicated field names will cause the create statement to fail.

### Steps to reproduce
E.g.
If in SQL Server you have 2 tables:
CREATE TABLE SchemaA.MyTable (ID INT, Name VarChar(100) )
CREATE TABLE SchemaB.MyTable (ID INT, Name VarChar(100) )
The SQLite migration will generate:
CREATE TABLE MyTable (ID INT, ID INT, Name VarChar(100), Name VarChar(100) )
Clearly this will raise an error when run against SQLITE

It would be useful to get a warning when there are duplicate tables names selected in SQL Server during the migration to prevent this. Otherwise a duplicate column error occurs which is difficult to track down.
Whats more as the table fields are merged, this may not be expected behaviour.

**Comment by ErikEJ** [comment]
You can use the advanced option: Use Server schema names
