### ISSUE TITLE
Creating SQLite DB from SQLServer gives exception

### ISSUE THREAD

**Issue by rocket452** [ErikEJ/SqlCeToolbox#788]
![image](https://user-images.githubusercontent.com/21027113/55811933-ffe19680-5ab7-11e9-8a84-5baa1c50ac4b.png)

Getting "System.Data.SqlClient.SqlException: Invalid column name 'is_computed'.

**Comment by ErikEJ** [comment]
Which SQL Server version?

**Comment by ErikEJ** [comment]
ping?

**Comment by ErikEJ** [comment]
Closing as additional info not supplied - feel free to re-open
