### ISSUE TITLE
SqlCE Toolbox menu

### ISSUE THREAD

**Issue by IoTFier** [ErikEJ/SqlCeToolbox#790]
Describe what is not working as expected.
The context menu shown after the right clicking of the database name doesn't show all menu items.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Install SQLCE/SqlServer Compact Toolbox Extension in VS 2019 community edition (16.0.2)
create a SQL CE database; connect to that database using Add SqlLite connecting from existing solution. Right click the database name after it is connected, it will show following menu -

![image](https://user-images.githubusercontent.com/26844611/56854944-4c283580-6904-11e9-8d0b-cc62be40e7a6.png)

![image](https://user-images.githubusercontent.com/26844611/56854950-6b26c780-6904-11e9-9bad-c209b21754cb.png)

which is limited unlike one below shown in the GitHub page of this extension
![image](https://user-images.githubusercontent.com/26844611/56854954-77ab2000-6904-11e9-8fd5-b1d9c6f8f6ea.png)

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
![image](https://user-images.githubusercontent.com/26844611/56854962-a4f7ce00-6904-11e9-963f-8084762d3f9e.png)

Database engine: (SQlite, SQL Compact or SQL Server)
SQLite 

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Yes, the number of options are limited for SQLite compared to SQL Server Compact

**Comment by IoTFier** [comment]
Hi @ErikEJ , thank you. A kind request to leave the issue open until we get a fair chance to finish our communication on the issue. 

Agreed with your comment, but SQLite do support data types BLOB. It will be nice to have at least that as an option. Creating DBContext file with the model classes , especially in the Xamarin Forms App building effort will be extremely valuable and helpful.

I am using your extension against the database created via https://sqlitebrowser.org/ tool. 
Thank you for creating the toolbox .. it helps see all the schema inside VS.
Apparently, using EFCore tool has been a bit difficult to generate scaffolding of model classes from the database (first approach). I wished it had encapsulated work to be done using EF PMC tool https://docs.microsoft.com/en-us/ef/core/miscellaneous/cli/dotnet by using dotnet ef dbcontext scaffold command.

I have generated those assets in a separate .net core console project , and will be copying generated types and dbcontext manually in my Xamarin Forms app project. Unfortunately, I will won't be able to make use of your EF Core utility within the Xamarin  forms solution.

Thanks

**Comment by ErikEJ** [comment]
Sounds like your comments should be split out in two feature requests
