### ISSUE TITLE
Migrate to SQL Server failing

### ISSUE THREAD

**Issue by marcond05** [ErikEJ/SqlCeToolbox#791]
Greetings, 

I have a rather large SQL Compact database, approximately 2.3 GB. We're having some performance issues, and I thought I would migrate this over to our production SQL Server (2016). 

I have confirmed that the Schema made its way over, but no data is transferring that I can tell. There does not seem to be any Log files or Progress indicator anywhere within the Visual Studio 2017 window. Long story short, I can't tell if it's doing anything or not.

Are there log files? Is there any other suggested way to monitor the progress of the "Migrate to SQL Server" functionality? 

Thanks and no rush! 
-Marc

**Comment by ErikEJ** [comment]
For a large database like that, I would suggest using the command line approach as described here: http://erikej.blogspot.com/2012/02/migrating-databases-between-sql-server.html 
(and handling of multiple script files here: http://erikej.blogspot.com/2010/02/how-to-use-exportsqlce-to-migrate-from.html )

**Comment by ErikEJ** [comment]
And there should be progress indication in the VS status bar

**Comment by marcond05** [comment]
Hi Erik, 

Many thanks for your response. I somehow stumbled onto one of the other tickets regarding SSMS 2017, and decided to give that shot off your nightly build, and voila. Much success. This thread - https://github.com/ErikEJ/SqlCeToolbox/issues/768  resolved my issue! 

Thanks again for your response, and for creating this fine set of tools. 

Cheers,
-Marc

**Comment by ErikEJ** [comment]
Hmmm… Maybe it is time for e new release?

**Comment by marcond05** [comment]
Well for what it's worth I did try the current production release first for kicks, which did yield the exact exception outlined in #768 . I've used your tool for years without any issues, this was a pretty edge case situation. I'll go ahead and close the ticket, thanks again Erik!
