### ISSUE TITLE
Dark Theme in VS2019

### ISSUE THREAD

**Issue by normanarmas** [ErikEJ/SqlCeToolbox#792]
### Steps to reproduce
If you select Color Theme "Dark" in VS2019
(in VS2017 work fine)
see the attached image

### Further technical details
Toolbox/Power Tools version: (Version 4.7.6340)
Database engine: (SQlite)
Visual Studio version: (Visual Studio 2019 16.0.3)

![image](https://user-images.githubusercontent.com/17601197/57531936-a19f1200-7308-11e9-8f45-43011e11c11c.png)

**Comment by ErikEJ** [comment]
I am  unable to reproduce, please show me this screen from your VS installation:

![image](https://user-images.githubusercontent.com/4169187/59563264-c4bf8e80-9037-11e9-8918-4e3e4f3d6803.png)

**Comment by normanarmas** [comment]
Erik

With the new update is no happening any more.

Thanks

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
