### ISSUE TITLE
SSMS 17 Installer installs VS 15 extension

### ISSUE THREAD

**Issue by CasperBoye** [ErikEJ/SqlCeToolbox#793]
When trying to use the installer from the markedplace as well as VSIX gallery, both installs the visual studio 15 extension, and succesfully does so. 
But problem is that it is the SSMS installers I use, and both install vs 15 extension not the SSMS 17 extension.

![InstallingWrongProduct](https://user-images.githubusercontent.com/50825131/58008877-9a88b880-7aed-11e9-9432-e137b8e0299f.png)

**Comment by ErikEJ** [comment]
Have you installed and checked if it is actually installed in SSMS?
Are you using the command line "fix" ?

Have you looked in C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions ?

**Comment by CasperBoye** [comment]
I have looked in the program, it is not installed in SSMS17, but it appears in VS15 after installation.

It does not exist in the specified folder either.

I will try with the command line now

**Comment by CasperBoye** [comment]
The command line install works.
Thank you

**Comment by ErikEJ** [comment]
Great, Casper. It is due to the fact that basically SSMS extensions are not supported in any way by Microsoft.
