### ISSUE TITLE
Scripting schema of sql tables for Sqlite failing timeout

### ISSUE THREAD

**Issue by erkdobey** [ErikEJ/SqlCeToolbox#795]
When attempting to script schema in Azure or local sql servers, after selecting a table to script and providing a script name an error occurs "The wait operation timed out".  This is a very mature database w/100's of tables.

I've profiled the call and the sql is using a UNION and either side's sql seems to run quick but with the union it takes 90+ seconds to run in SSMS.  We've attempted to power up the Azure database without success.

Compact Toolbox version 4.7.634

Database engine: SQL Server

Visual Studio 2017 15.9.7

**Comment by ErikEJ** [comment]
This should be fixed in the latest daily build: https://github.com/ErikEJ/SqlCeToolbox/commit/daff25d1787ed8aa1c909362048f2d7391c383a8

**Comment by ErikEJ** [comment]
Also see this: https://github.com/ErikEJ/SqlCeToolbox/wiki/Release-notes

**Comment by ErikEJ** [comment]
Ping?

**Comment by erkdobey** [comment]
The daily build version successfully resolved the issue for us, thank you for your information and time.

**Comment by ErikEJ** [comment]
Leaving this open to remind me to release the latest daily to MarketPlace
