### ISSUE TITLE
I could not be able to create .edmx file in c# sqlite  project

### ISSUE THREAD

**Issue by turkalpjr** [ErikEJ/SqlCeToolbox#796]
Describe what is not working as expected.

I want to add .edmx file to sqlite c# project.

### Steps to reproduce
 https://www.youtube.com/watch?v=o4Ug1e3TzNM&feature=youtu.be

Database engine: (SQlite)

Visual Studio or SSMS version: (Visual Studio 2017 )

**Comment by ErikEJ** [comment]
Thanks for the video, next you could:

1: Confirm that your system is configured according to my wiki post here:https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

2: Share the error message text

3: Share a project that reproduces the error

**Comment by turkalpjr** [comment]
1) confirmed ok
2) there is no error message, window is disappearing without any error messages.

https://www.youtube.com/watch?v=EONLFHby00k&feature=youtu.be
3) proje link:
http://angular5.turkalpkucur.com/testproje.rar

**Comment by ErikEJ** [comment]
Which exact VS version do you use?

**Comment by turkalpjr** [comment]
VS2017 15.9.12

**Comment by ErikEJ** [comment]
I cannot open the rar file, why not use .zip, and also remove the bin and obj folders before you create the zip.

**Comment by turkalpjr** [comment]
http://angular5.turkalpkucur.com/testproje.zip

**Comment by ErikEJ** [comment]
I have now had a look at your sample project.

Apparently your were unable to follow the instructions in the wiki post, in particular this section:
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider#install-systemdatasqlite-nuget-package

So please go through the guide carefully step by step.

(I have updated the guide to refer to version 110 instead of 108)

After updating all elements to version 1.0.110 I had no issues creating an EDMX.

**Comment by turkalpjr** [comment]
Hi,
I implied exactly step by step, including updating system.data.sqlite to 1.0.110 then , an error message,again. I think one step behind from victory. I prepared video:  https://www.youtube.com/watch?v=vVkdMxSlk-4&feature=youtu.be

**Comment by turkalpjr** [comment]
errormessage:  an error occured while connectiong to the database. the database might be unavaiable….

**Comment by ErikEJ** [comment]
Please share the detailed error message and stack trace

**Comment by turkalpjr** [comment]
well, the complete error message is 

An error occured while connecting to the database. the database might be unavaiable. an exception of type system.data.entity.core.providerIncompatibleexception occured. the error message is : the provide r did not return a providermanifest instance. the inner exception caught was of type system.methodaccessexception with this error message: system.data.sqlite.ef6.sqliteprovidermanifest.getprovidermanifesttoken[system.string] metodunun system.data.sqlite.unsafenativemethods.getstringvalue[system.string, system.string] metoduna erişim girişimi başarısız oldu.

**Comment by ErikEJ** [comment]
Please check your machine.config file as described in the wiki post

**Comment by ErikEJ** [comment]
Or share a project that reproduces the error.

**Comment by turkalpjr** [comment]
proje link:  http://angular5.turkalpkucur.com/testproje.zip
machineconfigfile :  http://angular5.turkalpkucur.com/machine.zip

**Comment by ErikEJ** [comment]
Remove this from your machine.config file!

		
```
		 <add name="SQLite Data Provider" 
           invariant="System.Data.SQLite" 
           description=".NET Framework Data Provider for SQLite" 
           type="System.Data.SQLite.SQLiteFactory, System.Data.SQLite" />

```

**Comment by turkalpjr** [comment]
I removed this part of code, restarted pc, tried but same error. nothing changed.

**Comment by ErikEJ** [comment]
Please share a repro project that causes this error.

**Comment by turkalpjr** [comment]
http://angular5.turkalpkucur.com/testproje.zip

**Comment by ErikEJ** [comment]
The app.config file in the project you shared does not follow the guidelines from the wiki post

**Comment by turkalpjr** [comment]
I Tried
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      
    <remove invariant="System.Data.SQLite" />
   </DbProviderFactories>
  </system.data>
</configuration>

then tried

<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <configSections>
    <section name="entityFramework" type="System.Data.Entity.Internal.ConfigFile.EntityFrameworkSection, EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" requirePermission="false" />
  </configSections>
  <entityFramework>
    <providers>
      <provider invariantName="System.Data.SQLite.EF6" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6" />
    </providers>
  </entityFramework>
  <system.data>
    <DbProviderFactories>
      <remove invariant="System.Data.SQLite.EF6" />
      <add name="SQLite Data Provider (Entity Framework 6)" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite (Entity Framework 6)" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6" />
      
    <remove invariant="System.Data.SQLite" />
   </DbProviderFactories>
  </system.data>
</configuration>



same error. I updated  project link
http://angular5.turkalpkucur.com/testproje.zip

**Comment by turkalpjr** [comment]
hello, coud you be able to add edmx to the project which I send?

**Comment by ErikEJ** [comment]
Yes

**Comment by turkalpjr** [comment]
Could you send me this project which you added the edmx ?

**Comment by ErikEJ** [comment]
I have cleaned the .csproj and app.config files, and updated my system to version 1.0.111 (released 2 days ago) - and added the EDMX file by following the wiki inscructions!

[cannotaddedmx.zip](https://github.com/ErikEJ/SqlCeToolbox/files/3280819/cannotaddedmx.zip)

**Comment by turkalpjr** [comment]
Ok, let me ask you, what exact parameter(s) did you entered to this popup?

http://angular5.turkalpkucur.com/connstringenter.png

**Comment by ErikEJ** [comment]
In "Data Source" I put the full path and filename to the db file

**Comment by turkalpjr** [comment]
I put    dataSource field to  --->   C:\Users\HP\Downloads\cannotaddedmx\testdb.db
not worked.

**Comment by turkalpjr** [comment]
could you provide  exact path which you entered?

**Comment by ErikEJ** [comment]
What does "not worked" mean?

**Comment by turkalpjr** [comment]
same error code. I need youtube video of complete process.

**Comment by turkalpjr** [comment]
I could not make changes  my computer's machine.config file. It is not professional.

**Comment by turkalpjr** [comment]
well, I realize that, you ,Erik, blocked my linkedin profile. Accept it, your solution does not works!!! and, I am afraid, you are the member of people who wants to make carrier with scratchs and shits!. your garbage wasted lots of time of mine! you owe that. and people, please, stay away and do not try this solution.
