### ISSUE TITLE
Extension not installing on VS 2019

### ISSUE THREAD

**Issue by lavanyadeepak** [ErikEJ/SqlCeToolbox#797]
My Visual Studio Version is 2019

![image](https://user-images.githubusercontent.com/2217926/59764131-bfbd4200-92b8-11e9-9c55-6273f5b07c75.png)

Install Log:

6/19/2019 5:36:20 PM - Microsoft VSIX Installer
6/19/2019 5:36:20 PM - -------------------------------------------
6/19/2019 5:36:20 PM - vsixinstaller.exe version:
6/19/2019 5:36:20 PM - 16.2.1045
6/19/2019 5:36:20 PM - -------------------------------------------
6/19/2019 5:36:20 PM - Command line parameters:
6/19/2019 5:36:20 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Deepak kumar\Desktop\SqlCeVsToolbox.4.7.644.vsix
6/19/2019 5:36:20 PM - -------------------------------------------
6/19/2019 5:36:20 PM - Microsoft VSIX Installer
6/19/2019 5:36:20 PM - -------------------------------------------
6/19/2019 5:36:21 PM - Initializing Install...
6/19/2019 5:36:21 PM - Extension Details...
6/19/2019 5:36:21 PM - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
6/19/2019 5:36:21 PM - 	Name               : SQLite/SQL Server Compact Toolbox
6/19/2019 5:36:21 PM - 	Author             : ErikEJ
6/19/2019 5:36:21 PM - 	Version            : 4.7.644
6/19/2019 5:36:21 PM - 	Description        : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
6/19/2019 5:36:21 PM - 	Locale             : en-US
6/19/2019 5:36:21 PM - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
6/19/2019 5:36:21 PM - 	InstalledByMSI     : False
6/19/2019 5:36:21 PM - 	SupportedFrameworkVersionRange : [4.5,)
6/19/2019 5:36:21 PM - 
6/19/2019 5:36:21 PM - 	SignatureState     : Unsigned
6/19/2019 5:36:21 PM - 	Supported Products : 
6/19/2019 5:36:21 PM - 		Microsoft.VisualStudio.Pro
6/19/2019 5:36:21 PM - 			Version : [11.0,17.0)
6/19/2019 5:36:21 PM - 		Microsoft.VisualStudio.Community
6/19/2019 5:36:21 PM - 			Version : [12.0,17.0)
6/19/2019 5:36:21 PM - 		Microsoft.VisualStudio.IntegratedShell
6/19/2019 5:36:21 PM - 			Version : [12.0,17.0)
6/19/2019 5:36:21 PM - 
6/19/2019 5:36:21 PM - 	References         : 
6/19/2019 5:36:21 PM - 	Prerequisites      : 
6/19/2019 5:36:21 PM - 		-------------------------------------------------------
6/19/2019 5:36:21 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/19/2019 5:36:21 PM - 		Name         : Visual Studio core editor
6/19/2019 5:36:21 PM - 		Version      : [11.0,)
6/19/2019 5:36:21 PM - 
6/19/2019 5:36:21 PM - Signature Details...
6/19/2019 5:36:21 PM - 	Extension is not signed.
6/19/2019 5:36:21 PM - 
6/19/2019 5:36:21 PM - Searching for applicable products...
6/19/2019 5:36:21 PM - Found installed product - Global Location
6/19/2019 5:36:21 PM - Found installed product - Visual Studio Community 2019
6/19/2019 5:36:22 PM - System.InvalidOperationException: VSHiveStub.exe failed: PkgdefManagement failed to create application: "0x80070005".
   at VSIXInstaller.LocationBasedSKU.get_RegRootHiveOverride()
   at VSIXInstaller.SupportedVSSKU.InitializeSettingsManager()
   at VSIXInstaller.SupportedVSSKU.get_Host()
   at VSIXInstaller.SupportedVSSKU.CreateExtensionEngine()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at VSIXInstaller.ExtensionService.GetExtensionEngineForApplicableSKU(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension installableExtension, List`1 applicableSKUs, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionService.TryAddSkuToValidSkuList(ICommandLineData cmdLineData, SupportedVSSKU supportedSKU, IInstallableExtension extension, List`1 validSKUs, Boolean isRepairSupported)
6/19/2019 5:36:22 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by ErikEJ** [comment]
No idea, maybe perform a repair of your installation

**Comment by lavanyadeepak** [comment]
Thanks Erik. Will retry this over the weekend and keep you posted with my observations ...

Deepak Kumar Vasudevan
Software Architect
www.lavanyadeepak.tk<http://www.lavanyadeepak.tk/>
[twitter icon]<https://twitter.com/lavanyadeepak> [facebook icon] <https://www.facebook.com/ld.lavanyadeepak>  [linkedin icon] <https://www.linkedin.com/in/lavanyadeepak>


________________________________

**Comment by IoTFier** [comment]
same here. It gave me that option only to install in SSMS and not for VS 2017, VS 2019

**Comment by ErikEJ** [comment]
@IoTFier  @lavanyadeepak  Are you installing the correct extension VSIX? 
The one for VS is at: https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox

**Comment by lavanyadeepak** [comment]
Looks like some magic going on. Today it says

[cid:568904a4-ad14-44d3-bd81-f1e7880b887f]

and then after a few seconds...

[cid:7ab05f4f-4ba0-4ca5-bad5-1d1bb232c7f5]

**Comment by lavanyadeepak** [comment]
Yes. Interestingly it completed today  installing. I don't have any VS Update from the previous installation. 

![image](https://user-images.githubusercontent.com/2217926/59914193-819a5c80-9437-11e9-9346-267319ac5130.png)

**Comment by lavanyadeepak** [comment]
Uh Oh. Even though I managed to install it is not not use-able because of this error

![image](https://user-images.githubusercontent.com/2217926/60002562-81dc6700-9686-11e9-810f-ecd07186e830.png)

**Comment by ErikEJ** [comment]
@lavanyadeepak Suggest you create a new issue with more detailed information about when the error occurs.
