### ISSUE TITLE
How to add my command to the context menu?

### ISSUE THREAD

**Issue by win32nipuh** [ErikEJ/SqlCeToolbox#798]
May be it is off-topic, but anyway:

How I can add my command to right-click context menu in SSMS Object Explorer? 
I'd like to add my command to menu if user right-clicks on database, then get the connection string etc.
I did not find any documentation and VS2017 Extension for SSMS 18 is different from olde versions.

**Comment by ErikEJ** [comment]
This is what I can offer: https://github.com/ErikEJ/SqlCeToolbox/tree/master/src/GUI/SSMSToolbox

**Comment by win32nipuh** [comment]
Thank you.
Naturally, it is not about SqlCeToolbox, it works.

I mean: when I right click in SQL Server Object Explorer on SQL Server node I add one command to the context menu, if it is Database node the I add other command.
I have tried to re-define Extensibility2 interfaces OnConnection(), OnDisconnection() etc as I did for SSMS 2012 but these methods is never called.
