### ISSUE TITLE
not found is vs 2017

### ISSUE THREAD

**Issue by quliting** [ErikEJ/SqlCeToolbox#801]
![test](https://user-images.githubusercontent.com/14035957/62611809-e0a92780-b938-11e9-8232-5c5c554a2cbc.png)
![bug](https://user-images.githubusercontent.com/14035957/62611811-e141be00-b938-11e9-8bd9-6ca30dc68333.png)

my vs version is first picture and the extension is enable ;but in vs 2017 is is not found 
thanks;
it is related to the vs version?

**Comment by ErikEJ** [comment]
This first screenshot is the wrong window, it is SQL Server Object Explorer, and you should look in Server Explorer!

Your VS version is fine, you can also verify that the extension is installed by scrolling down on the list in the middle of the About dialog
