### ISSUE TITLE
UWP App and SQLite

### ISSUE THREAD

**Issue by msavazzi** [ErikEJ/SqlCeToolbox#802]
I'm using the simple Create cs classes for my DB: I've followed the instructions on the MS site to add SQLite to my app but I get an error the SQLite namespace is not available.
(the instructions here: https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases#prepare-the-data-access-class)
I tried to add the System.Data.SQLite but then the CreateTable does not exist.

I know should be something stupid but I'm a little lost.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: 
Version 4.7.644.0 - 1,379,677 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.110.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio or SSMS version: VS2019 Community

**Comment by ErikEJ** [comment]
Please explain how this relates to the toolbox?

**Comment by msavazzi** [comment]
Erik,
thank you for your answer. First of all the toolbox is Great!!
It is related to the toolbox because in the videos where you demo it as well as one of it’s wonderful components is to generate the Model code, or Data Access code as you define it even more correctly.
So what I would expect is that the code generated works in the app, compiles.
What instead happens is that the file is nice but has 1000 errors. Is for sure my issue not yours… but I was not able find the solution.

I think the possible solutions are 2:

  1.  The Toolbox checks which SQL Libraries are included in the solution and creates a code compatible with them
  2.  At the beginning of the file in the comments you specify which libraries are requested for the code to be compiled

I think the 1) is crazy to do 😊 while the second is easy and just a line of comment 😊
Or maybe more than one if there is a difference between UWP apps or others 😊


Thank you again,
M


Da: Erik Ejlskov Jensen <notifications@github.com>
Inviato: sabato 21 settembre 2019 09:31
A: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Cc: Massimo Savazzi <massimo@savazzi.eu>; Author <author@noreply.github.com>
Oggetto: Re: [ErikEJ/SqlCeToolbox] UWP App and SQLite (#802)


Please explain how this relates to the toolbox?

**Comment by ErikEJ** [comment]
Please provide the steps to get the error (as requested when you post an issue here)

**Comment by msavazzi** [comment]
Using instructions here:
https://docs.microsoft.com/en-us/windows/uwp/data-access/sqlite-databases
[cid:image001.png@01D5714D.E6C72910]
[cid:image002.png@01D5714D.E6C72910]
[cid:image003.png@01D5714E.4673CE40]

[cid:image004.png@01D5714E.B0507BB0]


[cid:image005.png@01D5714E.B0507BB0]

[cid:image006.png@01D5714E.B0507BB0]

[cid:image007.png@01D5714E.B0507BB0]
[cid:image008.png@01D5714F.05F40190]

[cid:image008.png@01D5714F.05F40190]
[cid:image009.png@01D5714F.05F40190]
[cid:image010.png@01D5714F.05F40190]
When I try to build:
[cid:image011.png@01D5714F.05F40190]



Da: Erik Ejlskov Jensen <notifications@github.com>
Inviato: domenica 22 settembre 2019 08:49
A: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Cc: Massimo Savazzi <massimo@savazzi.eu>; Author <author@noreply.github.com>
Oggetto: Re: [ErikEJ/SqlCeToolbox] UWP App and SQLite (#802)


Please provide the steps to get the error (as requested when you post an issue here)

**Comment by ErikEJ** [comment]
I see no mention of the Toolbox in the linked instructions!?

**Comment by msavazzi** [comment]
Erik,
look at the screenshots.
I already told you: you do not put ANY requirement of libraries etc for the toolbox to work
BUT the code it generates des not compile
This is what have to be fixed.
The cx structure it creates must compile…


M

Da: Erik Ejlskov Jensen <notifications@github.com>
Inviato: lunedì 23 settembre 2019 19:47
A: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Cc: Massimo Savazzi <massimo@savazzi.eu>; Author <author@noreply.github.com>
Oggetto: Re: [ErikEJ/SqlCeToolbox] UWP App and SQLite (#802)


I see no mention of the Toolbox in the linked instructions!?

**Comment by ErikEJ** [comment]
I do not see any screenshots! 

You must go to GitHub.com and upload them, not just include in an email

**Comment by msavazzi** [comment]
Haaa
Sorry 😊
Ok will do


Da: Erik Ejlskov Jensen <notifications@github.com>
Inviato: lunedì 23 settembre 2019 20:12
A: ErikEJ/SqlCeToolbox <SqlCeToolbox@noreply.github.com>
Cc: Massimo Savazzi <massimo@savazzi.eu>; Author <author@noreply.github.com>
Oggetto: Re: [ErikEJ/SqlCeToolbox] UWP App and SQLite (#802)


I do not see any screenshots!

You must go to GitHub.com and upload them, not just include in an email

**Comment by msavazzi** [comment]
[sql.pdf](https://github.com/ErikEJ/SqlCeToolbox/files/3643568/sql.pdf)
here all the screenshots and sequence. Sorry for not noticing the images were removed and thank you for your help!

**Comment by ErikEJ** [comment]
Thanks. DataAccess.cs does not work with Microsoft.Data.Sqlite and UWP
