### ISSUE TITLE
Suggestion: Naming in the Data Connections tree

### ISSUE THREAD

**Issue by Barina** [ErikEJ/SqlCeToolbox#804]
It would be great to have the ability to rename DB's in the tree
For example I have in the picture below two databases connected 
1. The DB I am working on
2. The DB when debugging 

I could have one another for release as well but the naming isn't ideal..
![Annotation 2019-10-15 195552](https://user-images.githubusercontent.com/370379/66852520-cf5a4800-ef85-11e9-9295-097e3fb99c43.png)

Maybe have the ability in the "Add server connection" dialog as well as renaming in the tree itself 
![image](https://user-images.githubusercontent.com/370379/66852839-8bb40e00-ef86-11e9-81fd-6b8e1eaabc8f.png)

**Comment by ErikEJ** [comment]
You can open "Server Explorer" and rename the connections
