### ISSUE TITLE
Suggestion: (Migration)Script to new window

### ISSUE THREAD

**Issue by Zilkode** [ErikEJ/SqlCeToolbox#806]
First of all, thank you for your tool and efforts.

It would be very helpful and more comfortable to use the "scripting" abilities without juggling between VS and filesystem.

The current way to convert MSSqlServer to SqlCE possesses the following scenario:
1. script MS table to a file
2. open the file and copy it's content (or opening it through the toolbox window).
3. run the script
4. erase the file

An helpful feature would be script to new window (like in SSMS).
This feature will drop the excess steps of finding the file, opening the file, erasing the file and just become more quick to operate functionality: script and execute.

Thank you.

**Comment by ErikEJ** [comment]
You can do it directly in the GUI:
1. Add a SQL Server connection to the Toolbox
2. Right click and select "Migrate to SQL Server Compact"

**Comment by Zilkode** [comment]
Using "Migrate to SQL..." requires interacting with the file system (when working on projects you rarely stay in the same directory).

This option also replaces the current SqlCE file:
1. If i made changes to the schema from VS they will be discarded.
2. If i have data in SqlCE file it will be lost.

**Comment by ErikEJ** [comment]
Please elaborate how you envision the workflow - it is important to continue to be able to script to a file like currently.

Maybe a new top level menu "Script database to file" and always script to editor from the current menu item?

**Comment by Zilkode** [comment]
I think this could be achieved with minor changes.
In the Script popup there can be tabs or checkbox.

As for tabs i think it's too gawky for a single button "script", however in the future you might want to add few more options.

as for checkbox or radio button, you change the current layout to invisible.
1st RB -> Script to new window
2nd RB -> Script to file.

when "Script to new window" is selected, it's content view will expand (nothing to show for now, maybe in the future)

when "Script to file" is selected, it's content view will show the current options.

![Capture](https://user-images.githubusercontent.com/43464815/67393579-5b362a80-f5ab-11e9-8c37-c308fb328f9b.PNG)

**Comment by Zilkode** [comment]
I think the most intuitive option and the easiest to implement would be:
1. rename "OK" to "Script to file..."
2. add new button "Script to new window"



![Capture](https://user-images.githubusercontent.com/43464815/67394336-a69d0880-f5ac-11e9-824a-144540ef5956.PNG)

**Comment by Zilkode** [comment]
If you want to stay with a single button, this could be achieved by renaming "OK" to "Script to" (with dropdown element).


Option 1: "File"
Option 2: "New Window"

**Comment by ErikEJ** [comment]
Thanks for the proposals, I will just go with 2 buttons for now!

**Comment by ErikEJ** [comment]
Fixed in latest daily build

**Comment by Zilkode** [comment]
Works as requested.
Thanks!
