### ISSUE TITLE
Script to window does not change DB context

### ISSUE THREAD

**Issue by Zilkode** [ErikEJ/SqlCeToolbox#810]
When using the "Script to Window" the output window is in SqlDB context instead changing to context to SqlCE.

Is it possible to add dropdown to change the connection of the new window query?

Current behavior requires to select all->copy-> open new query window (target db) ->paste ->execute

Thank you.

![image](https://user-images.githubusercontent.com/43464815/68122188-717ca880-ff12-11e9-8bab-f5821c809b9e.png)

![image](https://user-images.githubusercontent.com/43464815/68122303-b3a5ea00-ff12-11e9-9ecc-b06f4600f299.png)

**Comment by ErikEJ** [comment]
This is complicated - you may not event have a connection to a SQL CE file to refer to !?

**Comment by ErikEJ** [comment]
Must use workaround
