### ISSUE TITLE
Trouble getting it to work in VS2019

### ISSUE THREAD

**Issue by pmeems** [ErikEJ/SqlCeToolbox#811]
I'm having trouble getting it to work in VS2019.

The toolbox seems to work fine, but I can get my application properly configured.
I've posted about it at https://stackoverflow.com/questions/58767771/cant-get-sqlite-to-work-in-vs2019-with-ef6

Does anybody have experience with the SQLite configuration and VS2019?

**Comment by ErikEJ** [comment]
Did you check my wiki post here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by pmeems** [comment]
Thanks Erik, sorry for the noise. I was a little desperate ;)
I found the problem and posted it as an answer in my SO question.

In short. I had to alter my App.config and make sure I was using the correct version of it in my Test project.
