### ISSUE TITLE
does not install

### ISSUE THREAD

**Issue by alanjshort** [ErikEJ/SqlCeToolbox#812]
###Problem
trying to install, I  get "This App can't run on your PC"

### Steps to reproduce
download the file (to E:\very temp)
open command window as administrator
run the command  "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\vsixinstaller.exe" "E:\very temp\SSMSToolbox.xsix"

### Further technical details
MSSMS -- Version V 17.4
O/S -- Windows 10 V 10.0.17134 
CPU -- AMD Ryzen 7 1800X 8 core
RAM -- 16GBytes 
All windows updates installed (automatic)

**Comment by ErikEJ** [comment]
Are you downloading from VS Marketplace or using the daily build?

**Comment by alanjshort** [comment]
Hi Erik
I downloaded using the link on this page
https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolboxforSSMS#overview

**Comment by ErikEJ** [comment]
I have never seen this before - some local policy? 
Have you checked the Application event log for errors?
Can you run vsixinstaller with any parameters?

**Comment by alanjshort** [comment]
Hi Eric

Nothing is posted to the application log for this install attempt.
I just retried by selectively disabling  kasperskiy with no change

**Comment by alanjshort** [comment]
Correction:

I get following in Application Event Log

Log Name:      Application
Source:        MSOLAP$MSSQLSERVER2016
Date:          11/13/2019 10:04:22 AM
Event ID:      5
Task Category: None
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      DESKTOP-1B7RSIO
Description:
The description for Event ID 5 from source MSOLAP$MSSQLSERVER2016 cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 


The message resource is present but the message was not found in the message table

Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="MSOLAP$MSSQLSERVER2016" />
    <EventID Qualifiers="49431">5</EventID>
    <Level>2</Level>
    <Task>0</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2019-11-13T15:04:22.933948900Z" />
    <EventRecordID>310296</EventRecordID>
    <Channel>Application</Channel>
    <Computer>DESKTOP-1B7RSIO</Computer>
    <Security />
  </System>
  <EventData>
    <Binary>02000000</Binary>
  </EventData>
</Event>

**Comment by alanjshort** [comment]
And now I see this error when i run vsixinstaller with no parameters.
investigating this now - -

**Comment by ErikEJ** [comment]
Any update?
