### ISSUE TITLE
Please provide option to close connection

### ISSUE THREAD

**Issue by weitzhandler** [ErikEJ/SqlCeToolbox#813]
### Steps to reproduce
- Add a connection to a local SQLite _db_ file and maybe even open a table for edit.
- Try deleting that file, can't access.

### Proposed solution
1. Offer a _Close connection_ option in the DB context menu
2. In the _Delete connection_ context menu item, display a checkbox _Close connection_, like VS SQL tools.

### Further technical details
Toolbox/Power Tools version: 4.7.644.0.

Database engine: (SQlite, SQL Compact or SQL Server)
SQL ADO.NET Provider: 1.0.110.0.

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS Community 16.3.9.

**Comment by ErikEJ** [comment]
I have gone great lengths to prevent this. Please provide exact repro steps, from launching VS and on.

**Comment by weitzhandler** [comment]
Hi Erik and thanks for your quick response.
I think the issue only happens when you actually open a table for edit.

Here's my repro:
- Close [this] project and run it once.
- In solution explorer select the project and enable "Show all files"
- Right click the _App.db_ file, right click and select "Copy path"
- Navigate to the SQLite toolbox, and add SQLite connection, use browse, paste path and click "Close".
- Right click the _Models_ table and select _Edit Top 200 Rows_
- Right click the connection and select _Remove Connection_
- In Solution explorer, right click the _App.db_ file and select _Delete_
- An error message will show saying:
> Cannot remove project item "..path to file..\App.db" from disk. Error code 32.

![image](https://user-images.githubusercontent.com/2716316/69030225-96c3e900-09df-11ea-96db-6f282c0983f5.png)

Anyway, after closing the table editor, the file deletes properly. So it's the editor that keeps the connection active.
Gonna close this issue as I found the solution, but yesterday I've been working on a large project and didn't even realize there was an editor open, so it might be worth keeping the editor's connection idle time shorter.
