### ISSUE TITLE
Want to add an additional SQLite connection.

### ISSUE THREAD

**Issue by Kingtiger623** [ErikEJ/SqlCeToolbox#814]
Can't add another SQLight connection

SQLite/Open the SQL Server Compact Toolbox
Select the Add SQLite connection; the ADD SQLite Connection dialog comes up.
Find my SQLite database. (****.sqlite)
Add needed information.
Test the connection... Test Succeeded!
Click close.
**No new data connection is added to the toolbox.**

### Further technical details
4.7.663.0

SQLite

Visual Studio 2017 and 2019
I was only able to do this once. can not add another data connection!

**Comment by ErikEJ** [comment]
Do you see any errors in the output window?

**Comment by Kingtiger623** [comment]
I did not see any errors, the add connection dialog was presented to me, I closed the dialog for for it to add the new, tested database. It never appeared in the collection even after I refreshed the tab. I did this many times and got no new database added.

**Comment by ErikEJ** [comment]
Maybe you SQLite install is broken - check your config according to this: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by ErikEJ** [comment]
Ping?

**Comment by nunomcardoso** [comment]
I think I have the same problem and solved it.

I followed the guide on how to install in the Wiki **(EF6 workflow with SQLite DDEX provider)**
and then proceeded to connect to the database (SQLite file), I clicked the button _"Add SQLite Connection"_ then Browse... and selected the file. Clicked the Test Connection and everything was ok. Then I clicked Close, thinking it would add the connection to the Toolbox. Nothing happened. Did that 5 times with other db, same result.

After that, I solved the problem. What I did was the following:
- Opened Server Explorer
- Clicked Connect to database
- Data source: SQLite Provider (Simple for EF6 by ErikEJ)
- In the connection string field I wrote by hand: (change **c:\mydb.db** to your path)
`Data Source=c:\mydb.db;Version=3;`
- Clicked OK and it added the data connection.

**Comment by ErikEJ** [comment]
Closing as the requested info was not provided

**Comment by ErikEJ** [comment]
I attempted a fix for this in the latest daily build, would be very greateful if one of you could confirm the fix.

**Comment by ErikEJ** [comment]
Confirmed fixed and published to VS Marketplace
