### ISSUE TITLE
SQLite Schema DIFF?

### ISSUE THREAD

**Issue by Trekkan** [ErikEJ/SqlCeToolbox#817]
Toolbox v4.7.644.0
Visual Studio 2019
SQLite

Wasn't there a Schema DIFF at one point?  I recently went to use it again and can't seem to find it?  It was nice to be able to script DIFF and get the ALTER statements, etc.  Am I thinking of something else?  Just not seeing it? Thanks for such a great tool also!

**Comment by ErikEJ** [comment]
There is schema diff for SQL Server Compact, but not for SQLite, as it does not support ALTER statements
