### ISSUE TITLE
Cannot add another SQLite connection. 

### ISSUE THREAD

**Issue by Kingtiger623** [ErikEJ/SqlCeToolbox#818]
Describe what is not working as expected.
Please Reopen issue #814 

All previous specified problems still apply. 

### Further technical details
Did verify SQLite setup, no issues here. 
Could not reply on status of current issues when requested, because of being indisposed.this has not been resolved.  

Database engine: (SQlite, SQL Compact or SQL Server)
As indicated in issue #814 

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
As indicated in issue #814

**Comment by ErikEJ** [comment]
If you want help with this general, non- toolbox related issue, you must provide more info and proof of you configuration.
