### ISSUE TITLE
Cannot add a SQLite connection (VS Community 2019)

### ISSUE THREAD

**Issue by robytur** [ErikEJ/SqlCeToolbox#820]
Hi,

I installed the Toolbox through Extension Manager in Visual Studio (Community 2019, v16.4.1).
When I try to add a new connection and I select the DB through the "Browse" window and then close that, it isn't added to the "Data Connections" sections of the Toolbox.
I tried creating a new database (with "Create" button): it created correctly the file on hard disk, but it didn't add it to the "Data Connections". Then I tried opening a sample database file (https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip) with no result.

### Steps to reproduce
1. Install the "SQLite Toolbox" extension through Extension Manager
2. Launch "SQLite/SQL Server Compact Toolbox" (eg. from Tools menu)
3. Right-click on "Data Connections" and select "Add SQLite Connection..."
4. Click "Browse..." button, locate the DB file and click "Open" button
5. Click "Close" button

### Further technical details
Toolbox version: 4.7.665
Database engine: SQLite
Visual Studio version: Visual Studio Community 2019 v16.4.1

Thank you.
RT

**Comment by ErikEJ** [comment]
Have you verified your SQLite installation according to my wiki post?

**Comment by ShiJess** [comment]
I had the same problem! But it worked before.

**Comment by ErikEJ** [comment]
Let me check!

**Comment by robytur** [comment]
> 
> 
> Have you verified your SQLite installation according to my wiki post?

Hi,
sorry for the delay.

I've followed again the tutorial described here (https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider) and I noticed that I missed some points.
However, here's what I did:
1. Installed the Toolbox (through Extension Manager)
2. Installed SQlite in GAC (I downloaded the exact file you mentioned in the wiki: sqlite-netFx46-setup-bundle-x86-2015-1.0.110.0.exe) and restarted Visual Studio
3. Installed "System.Data.Sqlite" package (via Nuget)

Now, I can add a new EF Data Model (with the "EF Designer from Database" option): I can locate the database on the hard disk and the designer appears correctly. At this point, if I click on the "Refresh" icon of the Toolbox, the database previously connected through EF Data Model appears in the "Data Connections" section, and it seems that all works as expected (dropdown menus, queries, etc.).
But even after that, if I try to add a new connection through the Toolbox, after locating the file (or creating a new one) and clicking on the "Close" button, the database isn't added to the Data Connections.

**Comment by ErikEJ** [comment]
@robytur Thanks, I am able to repro, and will look into a fix very soon.

**Comment by ErikEJ** [comment]
I attempted a fix for this in the latest daily build, would be very greateful if one of you could confirm the fix.

**Comment by ShiJess** [comment]
@ErikEJ Thanks, it's fixed!

**Comment by ErikEJ** [comment]
Thanks for confirming, I have also published the latest build to marketplace
