### ISSUE TITLE
I only get a limited menu

### ISSUE THREAD

**Issue by wysisoft** [ErikEJ/SqlCeToolbox#821]
![image](https://user-images.githubusercontent.com/15177964/71013097-596d7c80-20ad-11ea-839c-dda827cb80e8.png)

**Comment by ErikEJ** [comment]
A SQLite database?

**Comment by wysisoft** [comment]
Yes, im looking specificallyfor the diff command in sqlite

**Comment by ErikEJ** [comment]
It's not there, as SQLite basically does not have ALTER statements

**Comment by wysisoft** [comment]
ok thanks, incredible product, would be nice if it were implemented using temp tables possibly?

**Comment by ErikEJ** [comment]
Yeah, you will have to discuss that with the SQLite maintainers
