### ISSUE TITLE
Clipboard Cut (CTRL + X) doesn't work in the "script" window

### ISSUE THREAD

**Issue by robytur** [ErikEJ/SqlCeToolbox#822]
Hi,

I used the "Build Table" feature, then I clicked on the "Script!" button to open up a new tab in the editor with the code generated by the toolbox (that I only have to "Execute" to create my table).
In that window I can make all the edits I need. The only thing that doesn't work is the "Cut" function (CTRL + X): if I press CTRL+X nothing happens. The other two clipboard-commands (copy and paste) works as expected.
I thought it was a problem caused by the files opened in the editor beeing read-only... but I noticed I can copy/paste and also edit text manually, so it's not the problem.

### Further technical details
Toolbox version: 4.7.666.0
Database engine: SQlite
Visual Studio or SSMS version: Visual Studio Community 2019 (16.4.2)

ps: thank you for this amazing project!!

**Comment by ErikEJ** [comment]
I am not able to reproduce, wonder if you have an extension or workload installed that causes it not to work?

**Comment by robytur** [comment]
Ok, that was caused by a wrong target Framework.
In Project Properties was set on "4.7.2": changing to "4.6" or "4.6.1" the issue was fixed.
Thank you.
