### ISSUE TITLE
AUTOINCREMENT keyword is added next to INTEGER PRIMARY KEY when I select "Script as CREATE"

### ISSUE THREAD

**Issue by Realgigabyte** [ErikEJ/SqlCeToolbox#823]
AUTOINCREMENT keyword is added next to INTEGER PRIMARY KEY when I select "Script as CREATE" 

### Steps to reproduce

Select a table without AUTOINCREMENT (with an INTEGER IDX) from the tree menu. Right click on Script as CREATE.
The script appear like this:
CREATE TABLE [Brands1] (
  [IDX] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, [Name] nvarchar(100) NULL COLLATE NOCASE
);
This table primary key is not autoincrement (checked with DB Browser for SQLite (sqlitebrowser.org))
If manually remove AUTOINCREMENT from the script the table will be generated properly without it (checked with DB Browser for SQLite (sqlitebrowser.org)).
If Right click on Script as CREATE again the AUTOINCREMENT keyword will reappear in the proposed script.

### Further technical details
Toolbox/Power Tools version: 4.7.666
Database engine: 3.27.2

Visual Studio or SSMS version: Visual Studio 2019 16.4.2

**Comment by ErikEJ** [comment]
https://www.sqlite.org/autoinc.html - maybe I should consider never generating AUTOINCREMENT - what do you think?

**Comment by Realgigabyte** [comment]
If the table's INTEGER PRIMARY KEY is AUTOINCREMENT then that should appear in the script. Vice versa if it is a simple INTEGER PRIMARY KEY then it should not be present in the script. I think is important that the SQL script reflect the table accurately. Never generating AUTOINCREMENT would be still wrong for tables that do have AUTOINCREMENT as that would be not shown in the SQL script.
p.s. thank you for developing this plug-in it has been fantastically useful when I migrated from MS-SQL localdb to SQLite.

**Comment by Realgigabyte** [comment]
Hi, just wanted to clarify that this is related to when a table is already from a SQLite database. It's the Script as Create when is applied to an already existing SQLite table.
When converting from MSSQL is another matter and agree that the 2 databases are slightly different in regard of the autoincrement as you pointed out on your link.

**Comment by ErikEJ** [comment]
Can you share a repro SQLIte DB and I will have a look

**Comment by Realgigabyte** [comment]
This is schema of a table created with DB Browser for SQLite:
CREATE TABLE "Table1" (
	"Index"	INTEGER NOT NULL,
	"Description"	TEXT,
	PRIMARY KEY("Index")
);

When I connect with SqlCeToolbox inside Visual Studio (2019) and I select the Table1, right click "Script as CREATE":
-- Script Date: 06/02/2022 10:25  - ErikEJ.SqlCeScripting version 3.5.2.90
CREATE TABLE [Table1] (
  [Index] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, [Description] text NULL
);

The key word AUTOINCREMENT is added but it shouldn't as per DB Browser for SQLite behaviour.
See link for SQLite documentation about Autoincrement [https://sqlite.org/autoinc.html](url) .
Example database used here: https://1drv.ms/u/s!AsY5BeiXqtval4pHL8dJ6F-NSqMkjw?e=TWPkQL

**Comment by ErikEJ** [comment]
Great, I will have a closer look and re-read the docs.

**Comment by ErikEJ** [comment]
@Realgigabyte Sorry for the long wait. I have finally located a bug relating to this, and attempted a fix in the latest daily build. Would be grateful if you could try it out.
