### ISSUE TITLE
'Migrate to SQL Server' and 'Script Database' features could be enhanced to include 'Create Database' functionality

### ISSUE THREAD

**Issue by shaktisinghr** [ErikEJ/SqlCeToolbox#824]
Currently 'Migrate to SQL Server' or 'Script Database' features include creating tables (and migrating data) functionality. The 'Create Database' feature isn't present.

### Steps to reproduce
'Migrate to SQL Server' results in tables and data being created in the 'master' DB by default since that is selected by Visual Studio Server Explorer on creating a connection.

Database engine: SQL Compact

**Comment by ErikEJ** [comment]
That is not correct, Server Explorer allows you to connect to any existing database, or even create a new one.

**Comment by shaktisinghr** [comment]
This feature was specifically about migrating from CE to SQL or generating schema scripts for SQL.
There migrate option creates tables in master DB (doesn't create a new database with the same name as CE database) and the schema scripts start with create table statements (not create database statements).

**Comment by ErikEJ** [comment]
>> There migrate option creates tables in master DB

I disagree! You can connect to any user database in Server Explorer

**Comment by shaktisinghr** [comment]
> > > There migrate option creates tables in master DB
> 
> I disagree! You can connect to any user database in Server Explorer

That is correct, however there's no option to create a new database.

**Comment by ErikEJ** [comment]
>> That is correct, however there's no option to create a new database.

Just type the name of the new database, and the dialog will offer to create it for you!
