### ISSUE TITLE
Error opening sdf

### ISSUE THREAD

**Issue by PRFerro** [ErikEJ/SqlCeToolbox#825]
![Untitled](https://user-images.githubusercontent.com/59301231/72291217-ac473f00-362d-11ea-96d9-bec1b0261f8f.png)
Toolbox/Power Tools version: 4.7.666
Database engine: SQL Compact
Visual Studio 2019

**Comment by ErikEJ** [comment]
Have you installed the SQL Compact runtime??

**Comment by PRFerro** [comment]
OMG, my bad, wrong runtime version installed. Sorry... and thanks for pointing me in the right direction
