### ISSUE TITLE
Migrate to SQLite is not working and throw Argument Null Exception

### ISSUE THREAD

**Issue by sahamainak89** [ErikEJ/SqlCeToolbox#826]
1. Right click on Server.
2. Click "Migrate to SQLite".
3. Select Tables.
4. Click "OK"
5. Select File Path to save.
![ToolBoxError](https://user-images.githubusercontent.com/42532203/72796994-4f1f3f00-3c66-11ea-824b-b204678e6646.JPG)

Version 4.7.666.0 - 14,90,146 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Visual Studio 2019, version : 16.4.2

**Comment by ErikEJ** [comment]
Could you share a repro database? I am guessing it is a quirky view

**Comment by sahamainak89** [comment]
Hi Erik,

Thank you for your replay but sorry I can't share the database due to some client NDA. However when I try to generate the script from C# code by using "ErikEJ.SqlCeScripting" namespace instead of UI, It is generating successfully.

While generating script via code, my road block is my database collation is "Latin1_General_CI_AI" where as per my understanding "ServerDBRepository4" class try to connect with "SQL_Latin1_General_CP1_CI_AS" collation. Can you please let me know can I set any property in "ServerDBRepository4" where I mentioned collation?

**Please Note :** I can't change collation of database as it is existing database and some feature of "Latin1_General_CI_AI" is using by the system. 

For your reference I just paste my code snippet below,

        private static void RestoreData()
        {
            string connStr = "Data Source=.,14330;User ID=sa;Password=pass;Initial Catalog=TestDatabase;";
            string backupfilepath = string.Format(@"{0}backUPData.sql", "E:\dbbackup\");
            using (IRepository serverRepository = new ServerDBRepository4(connStr))
            {
                IGenerator generator = new Generator4(serverRepository, backupfilepath);
                foreach (var tableName in serverRepository.GetAllTableNames())
                {
                    if (tableName.ToUpper().Contains("ABC_"))
                    {
                        generator.GenerateTableScript(tableName);
                        generator.GenerateTableContent(tableName, false);
                    }
                }
                generator.ScriptDatabaseToFile(Scope.SchemaDataSQLite);
            }
        }

**Additional Query** : Is there any method exposed by "ErikEJ.SqlCeScripting" by which we can execute the generated SQLite script?

Thank You

**Comment by sahamainak89** [comment]
Hi Erik,

Any update regarding my queries?

**Comment by ErikEJ** [comment]
>> While generating script via code, my road block is my database collation is "Latin1_General_CI_AI" where as per my understanding "ServerDBRepository4" class try to connect with "SQL_Latin1_General_CP1_CI_AS" collation. Can you please let me know can I set any property in "ServerDBRepository4" where I mentioned collation? 

I do not understand this? Do you see any error message realting to this, and if so, kindly share them!


Re Exclude: I think you also must add the schema, and maybe even use [dbo].[mytable], but you can check in the source.

**Comment by ErikEJ** [comment]
Ping?

**Comment by cbs-cbt** [comment]
Hello,
First of all, thank you for the great tool !
Same problem here, please find hereby a Microsoft SQL database backup that cannot be exported to SQLite due to the NullReferenceException
Please let me know if I can help solve the problem
[TestSQLiteExportNullReferenceException.zip](https://github.com/ErikEJ/SqlCeToolbox/files/4218234/TestSQLiteExportNullReferenceException.zip)

**Comment by ErikEJ** [comment]
Fixed in latest daily build, please let me know if it solves your issue

**Comment by cbs-cbt** [comment]
Hello @ErikEJ,
It works perfectly, thank you very much for the fast reaction !
