### ISSUE TITLE
Cant remove SQL Server connections in Visual Studio 2019 Enterprise Edition. 

### ISSUE THREAD

**Issue by pateljeel** [ErikEJ/SqlCeToolbox#827]
Describe what is not working as expected.
In Visual Studio 2019 Enterprise Edition, If you have a SQLServer connection, you wont be able to remove the connection by right clicking on the database because the 'Remove Connection' does not exist.
### Steps to reproduce
1) Using VS 2019, Add a connection to a SQL Server database.
2) Right click on the database and you will not see an option to 'Remove Connection' 
3) Right click on 'Data Connections' and click Remove broken connections. Nothing will happen.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.666.0

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server 

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio Enterprise 2019 Version 16.4.3
SSMS Version 18.1

**Comment by ErikEJ** [comment]
Open Server Explorer to remove the connection
