### ISSUE TITLE
Add EF 6 DbContext: ErrorGeneratingOutput

### ISSUE THREAD

**Issue by AaronV-NorthStar** [ErikEJ/SqlCeToolbox#828]
Hello Erik,
First, thank you for the great tool. I've used it now for several years and its been a great help.

Second my issue is that when attempting to generate a EF 6 DbContext for my existing SQLCE database file, I end up with a DataBase.cs file containing just: `ErrorGeneratingOutput`. The following two errors are what shows up after attempting to generate the output.

`Failed to resolve include text for file:C:\[path]\EF.Reverse.POCO.v3.ttinclude	App	C:\[path]\Database.tt	0`

`Loading the include file 'EF.Reverse.POCO.v3.ttinclude' returned a null or empty string. The transformation will not be run.	APP	C:\[Path]\Database.tt	1`

### Steps to reproduce
1. Install the required extensions and nuget packages into a VS2019 C# console application project.
2. Run the Add EF 6 DbContext on an existing SQLCE datbase.
3. See error.

### Further technical details
Toolbox/Power Tools version: 4.7.666.0

Database engine: SQL Compact

Visual Studio 2019

-- Script Date: 1/29/2020 10:22 AM  - ErikEJ.SqlCeScripting version 3.5.2.85
-- Database information:
-- Locale Identifier: 1033
-- Encryption Mode: Platform Default
-- Case Sensitive: False
-- Database: C:\[path]\database.sdf
-- ServerVersion: 4.0.8482.1
-- DatabaseSize: 583.543 MB
-- SpaceAvailable: 3.43 GB
-- Created: 1/24/2020 10:19 AM

Thank you for your time,
Aaron Viviano

**Comment by ErikEJ** [comment]
Hmmm… I thought I had removed that feature, You should simply be using the standard EF 6 Tools to do this.

**Comment by ErikEJ** [comment]
Sorry. this is the Reverse POCO Template - just refer to the wiki post, and contact the maintainer if you encounter any issues. (I will remove this option now)

**Comment by ErikEJ** [comment]
wiki potst: https://github.com/ErikEJ/SqlCeToolbox/wiki/EntityFramework-Reverse-POCO-Code-First-Generator

**Comment by AaronV-NorthStar** [comment]
Hello Erik,
Thank you, that is quite helpgul. I'll look into this.

Regards,
Aaron
