### ISSUE TITLE
SQL Compact Edition VS Toolbox

### ISSUE THREAD

**Issue by BGH-MXQ** [ErikEJ/SqlCeToolbox#829]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by BGH-MXQ** [comment]
Just want the VS 2010 version, plz. Link?

**Comment by ErikEJ** [comment]
http://vsixgallery.com/extensions/45521019-e4c7-480c-8ea8-fc4a2c6f50aa/extension.vsix
