### ISSUE TITLE
Unable to find requested .Net Framework Data Provider 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/SqlCeToolbox#830]
I am using VS2019 and I install your extension and install EF6 workflow with SQLite DDEX provider

I connected to the db please see image 
![image](https://user-images.githubusercontent.com/35128168/73535823-3284c300-442d-11ea-9d46-a01ef746dc38.png)

then following the follwoing steps

From the Tools menu select Connect to Database.
Right-click the Data Connections node in Server Explorer and click Add Connection.
Right-click the data connection you want to modify in Server Explorer and click Modify Connection.
The dialog consists of several controls where you supply information needed to connect to the database. The following list describes the most important controls.

Database
  The full path and filename of the database.
After you fill the controls with data click Test connection button to verify it or click OK button to apply changes and close the dialog.

I am getting an error ( its a now class library  with nothing in it ) 

![image](https://user-images.githubusercontent.com/35128168/73535964-82638a00-442d-11ea-8e51-c8c627ed096a.png)

![image](https://user-images.githubusercontent.com/35128168/73535988-8e4f4c00-442d-11ea-8824-8a81478de7f9.png)

**Comment by ErikEJ** [comment]
Are you using the exact same version of all SQLite components?

**Comment by smarteez17** [comment]
Hi there thank for replying 

here all the versions I using 

Version 4.7.666.0 - 1 490 146 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No


Sync Framework 2.1 SqlCe 3.5 provider - No


SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by smarteez17** [comment]
I install this ? is it correct ?
![image](https://user-images.githubusercontent.com/35128168/73536492-aecbd600-442e-11ea-96bc-9e3957930506.png)

**Comment by smarteez17** [comment]
![image](https://user-images.githubusercontent.com/35128168/73536732-44fffc00-442f-11ea-984e-1669e78c12e6.png)

**Comment by smarteez17** [comment]
@ErikEJ  what can i try ?

**Comment by ErikEJ** [comment]
Double check against the wiki post

**Comment by smarteez17** [comment]
I install 64 bit for .net framework 4.6 is the correct version i should used is the version for 4.7.2 or higher

**Comment by smarteez17** [comment]
I think I found the problem i am using vs 2019 to Install SQLite in GAC can you send me the link 

I have tried  Once per machine. Download sqlite-netFx46-setup-bundle-x86-2015-1.0.110.0.exe (from https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki)

 but it set to No 
SQLite EF6 DbProvider in GAC - No

what should I used

**Comment by ErikEJ** [comment]
As I stated rigth away: "Are you using the exact same version of all SQLite components?" !!!

You should use https://system.data.sqlite.org/downloads/1.0.112.0/sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0.exe of course!
