### ISSUE TITLE
SQLite DDEX provider size error 

### ISSUE THREAD

**Issue by smarteez17** [ErikEJ/SqlCeToolbox#831]
Hi there 

My database size is 2 785368 KB .
I would like to used the EF6 workflow with SQLite DDEX provider and I getting this error ( see image below) it the max size ? How can i change it 

![image](https://user-images.githubusercontent.com/35128168/73612584-94902480-45f5-11ea-87bf-8a7c71540413.png)

![image](https://user-images.githubusercontent.com/35128168/73612558-73c7cf00-45f5-11ea-827e-431d41002be1.png)

**Comment by ErikEJ** [comment]
You are using the SQL Server Compact provider to connect to a SQLIte database file - that wont work!
