### ISSUE TITLE
System.ArgumentNullException in AppendFormatHelper when migrating SQL Server to SQLite

### ISSUE THREAD

**Issue by clintp1969** [ErikEJ/SqlCeToolbox#836]
Describe what is not working as expected.

### Steps to reproduce
* Connect to SQL Database
* Migrate to SQLite
* Select any table (or tables)
* Click OK
* Select sqlite file (new or empty, does not matter)
* Error shown in attachment

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.666.0

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server 10.50.6000.34
Database compatibility level SQL Server 2008

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS 2015 version 14.0.25431.01 Update 3

![Error](https://user-images.githubusercontent.com/47461705/75363654-69ad8f00-5888-11ea-8f39-ba8908c9e632.png)

**Comment by ErikEJ** [comment]
Already fixed in latest daily build
