### ISSUE TITLE
Error when generate a SQLitle compatible script from SQL Server

### ISSUE THREAD

**Issue by rgrastur** [ErikEJ/SqlCeToolbox#839]
I have this error when I try to generate it by selecting only one table.

![image](https://user-images.githubusercontent.com/48772925/77199535-45407d80-6ae9-11ea-909a-c803e2229dce.png)

Any idea?

My table:

![image](https://user-images.githubusercontent.com/48772925/77200537-0ca1a380-6aeb-11ea-9bfd-c04d75c4ceef.png)

With other databases I have no problem.

**Comment by ErikEJ** [comment]
Did you try the latest daily build, I think it is fixed there?

**Comment by rgrastur** [comment]
I did't have the last SSMS build. Thank you for your time!

**Comment by ErikEJ** [comment]
I will publish the latest build on Marketplace
