### ISSUE TITLE
Error Code 80004005

### ISSUE THREAD

**Issue by dichaelen** [ErikEJ/SqlCeToolbox#840]
### Describe what is not working as expected.
I cannot import and inspect database

Pop-up:
Error Code: 80004005
Message: Unspecified error
Minor Err.: 0
Source: SQL Server Compact ADO.NET Data Provider

### Steps to reproduce
* Add SQL Server Compact 3.5 Connection
* Browse and add my Db.sdf (I can share if needed)

### Further technical details
SQL Server Compact Toolbox 4.7.670.0

### Database engine: 
https://www.microsoft.com/en-us/download/details.aspx?id=5783

### Visual Studio version (with extension too): 
Visual Studio 2017 15.1

**Comment by ErikEJ** [comment]
Would be great if you could share, yes. Feel free to email me privately

**Comment by dichaelen** [comment]
Done :-)

**Comment by dichaelen** [comment]
Quick and fast response - i will close this :-)
