### ISSUE TITLE
Migrate to SQLLite UnauthorizedAccessException

### ISSUE THREAD

**Issue by mjlabe** [ErikEJ/SqlCeToolbox#844]
Migrate to SQLLite UnauthorizedAccessException

![sql_toolbox](https://user-images.githubusercontent.com/28718113/81212222-907ff400-8fa2-11ea-8a53-2662118ec40e.jpg)

### Steps to reproduce
Connect to SQL Server database in Visual Studio Version 16.5.4. Open SQLite/SQL Server Compact Toolbox 4.7.670 from Server Explorer. Right click SQL Server database connection. Click "Migrate to SQLite..."

### Further technical details
Toolbox/Power Tools version: 4.7.670

Database engine: SQL Server to SQlite

Visual Studio or SSMS version: Microsoft Visual Studio Community 2019 16.5.4

**Comment by ErikEJ** [comment]
Virus scanner?

**Comment by mjlabe** [comment]
Only Windows Defender. Fresh install via Bootcamp yesterday. I will try disabling Defender.

**Comment by mjlabe** [comment]
Same thing. It's Windows, so let me try rebooting.

**Comment by ErikEJ** [comment]
Empty your temp folder, perhaps?

**Comment by mjlabe** [comment]
Ok, that solved the crashing issue, but now the resulting file is 0kb. Seems to have finished running (VS said "Importing Data" then "Ready" and it created 444 .sqlce files in the temp directory.

**Comment by ErikEJ** [comment]
With that amount of data, I would consider using the command line tools.

**Comment by mjlabe** [comment]
The command line tools don't seem to create a single sqlite file. So I have to script `sqlite3 chinook.db < chinook_xxxx.sql` to create the final result?

**Comment by mjlabe** [comment]
Script worked and was easy enough. Closing. Thanks!
