### ISSUE TITLE
Can't install toolbox on VS 2017

### ISSUE THREAD

**Issue by ArmorBearer** [ErikEJ/SqlCeToolbox#845]
Tried to install the toolbox on my system with Visual Studio 2017.  It failed (see attached log file).
[VSIXInstaller_933a3922-e52e-4433-a7de-621aa29b3235.log](https://github.com/ErikEJ/SqlCeToolbox/files/4638626/VSIXInstaller_933a3922-e52e-4433-a7de-621aa29b3235.log)

### Steps to reproduce
Downloaded the installer from Visual Studio Marketplace
Double-clicked the VSix file.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
N/A

Database engine: (SQlite, SQL Compact or SQL Server)
SQlite (SQL Server 2017 is also installed, but not my current focus)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Microsoft Visual Studio Community 2017  (VS2017)
Version 15.9.11
VisualStudio.15.Release/15.9.11+28307.586
Microsoft .NET Framework
Version 4.8.03752

Application Insights Tools for Visual Studio Package   8.14.20131.1

ASP.NET and Web Tools 2017   15.9.04012.0
ASP.NET and Web Tools 2017
ASP.NET Core Razor Language Services   15.8.31590

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a

Cookiecutter   15.9.18254.1

GitHub.VisualStudio   2.11.89.33912

JavaScript Language Service   2.0
JavaScript Project System   2.0
JavaScript UWP Project System   2.0

Azure App Service Tools v3.0.0   15.9.03024.0
Azure App Service Tools v3.0.0
Common Azure Tools   1.10
Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.0.0

Microsoft JVM Debugger   1.0
Microsoft MI-Based Debugger   1.0

Visual C++ 2017   00369-60000-00001-AA176
Microsoft Visual C++ 2017
Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards
Visual C++ for Cross Platform Mobile Development (Android)   15.0.28107.00
Visual C++ for Cross Platform Mobile Development (Android)

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

MLGen Package Extension   1.0

NuGet Package Manager   4.6.0

ProjectServicesPackage Extension   1.0

Python   15.9.18254.1
Python - Django support   15.9.18254.1
Python - IronPython support   15.9.18254.1
Python - Profiling support   15.9.18254.1

ResourcePackage Extension   1.0

SQL Server Data Tools   15.1.61903.01040

TypeScript Tools   15.9.20918.2001

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a

Visual Studio Code Debug Adapter Host Package   1.0

Visual Studio Tools for CMake   1.0

Visual Studio Tools for Universal Windows Apps   15.0.28307.556

WiX Toolset Visual Studio Extension   1.0.0.4

**Comment by ErikEJ** [comment]
Try to install from inside VS instead of downloading from Marketplace

**Comment by ArmorBearer** [comment]
I was able to install from within VS 2017 by finding it in the Extensions and Updates dialog (Tools > Extensions and Updates) and installing it from there.
