### ISSUE TITLE
Toolbox always switches to the Properties Pane when expanding a database

### ISSUE THREAD

**Issue by jmoleary** [ErikEJ/SqlCeToolbox#847]
### Steps to reproduce
1.Start Visual Studio
2. Open the SQLite/SQLServer Compact Toolbox ("SSCT" for short)
3. Locate a SQLite database within it (or add one)
4. Expand it (to reveal the "Tables" and "Views" nodes beneath it.
5. Expand the "Tables" node

At this point,. the Visual Studio "Properties" window gets activated, no matter where it was.  If the Properties windows wasn't showing before, it shows up.  If it was already showing before in the same docked-tool-pane as the SSCT, then it appears, thereby hiding the SSCT.

I keep my Properties and SSCT toolboxes in the same pane so it's annoying.  I have to click back on to the SSCT to see the tables node I just expanded.  The first few times it happened, I was really confused; I didn't realize the toolbox panes had changed and I wondered where my database went.

This only happens the very **_first_** time you expand a "Tables" node.  Every time thereafter it does not happen, at least not until you shut down and restart visual studio.

### Further technical details

Toolbox/Power Tools version: Version 4.7.670

Database engine: SQlite

Visual Studio or SSMS version: Visual Studio 2019 4.8.03752.  But this has been happening for  long time now.  I just never bothered to make a report about it.

**Comment by ErikEJ** [comment]
This "feature" has been in the tool for years, and you are the first person to bring this up.
Let me consider an option to disable the behaviour.

**Comment by jmoleary** [comment]
Admittedly it's pretty minor.    I've thought about posting this and decided not to for a long time.   I just hit it one too many times  Love the tool regardless

**Comment by ErikEJ** [comment]
I think I figured out why no one else have complained! :smile:

Have you tried to set the "Display Properties Window" option to false ?

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/SqlCeToolbox/blame/master/src/GUI/SqlCe35Toolbox/ToolWindows/ExplorerControl.xaml.cs#L886

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if the option does not work

**Comment by jmoleary** [comment]
If there is an option for this, then certainly I will feel appropriately stupid.  But I can't find one in the Options dialog that corresponds to what you are checking.  I tried searching on "properties" and "display" and cannot see it.  Can you give me a properties navigation path that would let me turn this off?   Like "Tools >> Options >> Database Tools >> ????" or whatever

**Comment by jmoleary** [comment]
Nevermind, Found it.  Now I do feel appropriately stupid
