### ISSUE TITLE
Problem when both SSMS 17 and 18 are installed

### ISSUE THREAD

**Issue by slear** [ErikEJ/SqlCeToolbox#848]
It seems that when both SSMS 17.9.1 and 18.5 are both installed on the same machine the tool installs itself only on SSMS 17.9.1. I am not even sure if the tool is compatible with 18.5 and I cannot (at the moment) disinstall the SSMS 17.9.1 to check if it works when there is only 18.5

### Steps to reproduce
Just install the SSMS 18.5 without disinstalling the previous version (mine happened to be 17.9.1), then install the tool.

### Further technical details
Tool Version 4.7.632.0

Database engine: (SQlite, SQL Compact or SQL Server)
SQLCompact 4.0

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2019, SSMS 17.9.1 && 18.5

**Comment by ErikEJ** [comment]
Assume you are aware that you must install manually for SSMS 18 - see the readme.

**Comment by slear** [comment]
I should have known that I have forgotten to read something. Thanks ErikEJ. Case closed.
