### ISSUE TITLE
No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SQLite.EF6'. 

### ISSUE THREAD

**Issue by hims889** [ErikEJ/SqlCeToolbox#849]
Hi,
I am trying to fetch data from sqlite database but getting following error when EF runs the query.

"System.Data.Entity.Core.MetadataException: 'Schema specified is not valid. Errors: 
Model1.ssdl(2,2) : error 0152: No Entity Framework provider found for the ADO.NET provider with invariant name 'System.Data.SQLite.EF6'. Make sure the provider is registered in the 'entityFramework' section of the application config file. See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.'

Following is the structure of my packages.config.

```
<packages>
  <package id="EntityFramework" version="6.4.4" targetFramework="net461" />
  <package id="System.Data.SQLite" version="1.0.113.1" targetFramework="net461" />
  <package id="System.Data.SQLite.Core" version="1.0.113.1" targetFramework="net461" />
  <package id="System.Data.SQLite.EF6" version="1.0.113.0" targetFramework="net461" />
  <package id="System.Data.SQLite.Linq" version="1.0.113.0" targetFramework="net461" />
</packages>
```

This is the entity framework tag of my app config.

```
<entityFramework>
    <providers>
      <provider invariantName="System.Data.SqlClient" type="System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer"/>
      <provider invariantName="System.Data.SQLite" type="System.Data.SQLite.EF6.SQLiteProviderServices, System.Data.SQLite.EF6"/>
    </providers>
  </entityFramework>
```

and last is the connection string generated by model class in app config.

```
 <add name="mainEntities"
connectionString="metadata=res://*/Model1.csdl|res://*/Model1.ssdl|res://*/Model1.msl;provider=System.Data.SQLite.EF6;provider connection string=&quot;data source=C:\test\test.db&quot;"
      providerName="System.Data.EntityClient"/>
```

can you please tell me where i am doing wrong?

Database engine: SQlite

Visual Studio version:  Visual Studio 2017

**Comment by ErikEJ** [comment]
Have you carefully followed the guide here? https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by hims889** [comment]
Yes, i followed the guide from mentioned link. But, still getting the issue.

Thanks

**Comment by ErikEJ** [comment]
I see version 113 - are you using same version everywhere, also in machine.config?

**Comment by hims889** [comment]
Yes, in machine.config i have the same version.

following is the machine.config file code

```
<system.data>
		<DbProviderFactories><add name="Microsoft SQL Server Compact Data Provider 4.0" invariant="System.Data.SqlServerCe.4.0" description=".NET Framework Data Provider for Microsoft SQL Server Compact" type="System.Data.SqlServerCe.SqlCeProviderFactory, System.Data.SqlServerCe, Version=4.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91" /><add name="SQLite Data Provider" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139" /></DbProviderFactories>
	</system.data>
```

**Comment by ErikEJ** [comment]
No idea then, maybe have a look at the many related (closed) issues here.

**Comment by hims889** [comment]
yes, i am looking into closed issues related to this. Until now, no luck.

**Comment by ErikEJ** [comment]
Did you install https://system.data.sqlite.org/downloads/1.0.113.0/sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0.exe ??

**Comment by ErikEJ** [comment]
In that case I am not able to assist, please raise an issue in the SQLite issue tracker.

**Comment by ErikEJ** [comment]
I have updated to system.data.sqlite build 113 in the latest daily build
