### ISSUE TITLE
Create SQLite standalone .exe GUI 

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#850]

**Comment by win32nipuh** [comment]
Ok, great!

**Comment by win32nipuh** [comment]
Hi, 
can we hope on standalone GUI app in the nearest time? ;-)

**Comment by ErikEJ** [comment]
Not high on my list, there are already other standalone SQLite tools on the market

**Comment by win32nipuh** [comment]
thnx
