### ISSUE TITLE
Cannot Generate SQLite Database from Model

### ISSUE THREAD

**Issue by Artoymyp** [ErikEJ/SqlCeToolbox#851]
I cannot Generate SQLite Database from Entity framework model.

### Steps to reproduce
1. Create a .NET Framework 4.7.2 project.
2. Follow instructions found at https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider to setup the Toolbox.
3. Add new item to the project: ADO.NET Entity Data Model -> Empty EF Designer model.
4. Open it and call the "Generate Database from Model..." command from the model's context menu.
5. Click "New connection" button in the "Generate Database Wizard"
6. Specify some new filename (e.g. "h:\work\db.sqlite") in the "Data Source" field in the "Connection Properties" dialog.
7. Click "OK". Click "Next"

Expected result: db-file "h:\work\db.sqlite" is filled with new schema, I suppose.
Actual result:
![image](https://user-images.githubusercontent.com/12625469/84603065-35d89280-ae94-11ea-9446-987e831a45c2.png)

### Further technical details
Toolbox/Power Tools version: 4.7.671.0

Database engine: SQlite

Visual Studio or SSMS version: Visual Studio 2017 15.9.10, Visual Studio 2019 16.6.0

PS: I think the problem may be connected to one sentence from your instruction: "Make sure to install the same version as the tools package above.". I'm not quite sure what it means, because phrasing is somewhat ambiguous, but I have installed System.Data.Sqlite 1.0.113.1 and your Toolbox seems to be built against System.Data.Sqlite 1.0.112.0. This may lead to some type conflicts mentioned in the error MessageBox. I cannot reference 1.0.112.0 version from NuGet because there is no such version on NuGet now at all.

**Comment by ErikEJ** [comment]
Restart Visual Studio?

**Comment by ErikEJ** [comment]
You can specify version 1.0.112.0 if you install from the PMC. 
Please try that, I very much doubt it is related.

**Comment by Artoymyp** [comment]
Visual Studio restart is not helping.
Sorry, could you please explain what PMC means? I cannot figure it out.

**Comment by ErikEJ** [comment]
PMC = Package Manager Console

**Comment by Artoymyp** [comment]
OK, I have downgraded System.Data.SQLite (and also Core, EF, Linq) to 1.0.112 version.
It didn't solve my issue. The error was still the same.

I have tried to go the other way around and tried to create a ADO.NET Entity Data Model from existing db (although it was 0 bytes in size). Luckily this attempt has yielded another, more verbose, error message:
![image](https://user-images.githubusercontent.com/12625469/84652258-079a9780-af14-11ea-8286-e9c6d5ab695c.png)
It says that the System.Data.SQLite v1.0.113.0 assembly from GAC_32 folder was used for some reason. 
I think it was because I installed incorrect version of sqlite-netFx46-setup-bundle-x86-2015-1.0.113.0.exe file to install SQLite into GAC.

After that I uninstalled sqlite and installed another version of the file: https://system.data.sqlite.org/downloads/1.0.112.0/sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0.exe.
It has solved original issue, but I still fail to fulfill the task because of a new error:
![image](https://user-images.githubusercontent.com/12625469/84663961-839ddb00-af26-11ea-892a-0352e83c3483.png)

So the issue was (as expected) on my side and I will go and triple check my setup.

**Comment by ErikEJ** [comment]
I will update to 113 soon!

**Comment by ErikEJ** [comment]
I have updated to system.data.sqlite build 113 in the latest daily build

**Comment by Artoymyp** [comment]
I have just installed the new Toolbox. Now I can create a model from a db successfully and that is great. Thank you! But I still have problems with generating db from a model. I'll investigate it at a later time.
