### ISSUE TITLE
link direct to Wiki

### ISSUE THREAD

**Issue by DickBaker** [ErikEJ/SqlCeToolbox#852]
on page https://github.com/ErikEJ/SqlCeToolbox/wiki there is a link (middle of 3)
"Entity Framework Core Database First (Reverse Engineering) with EF Core Power Tools"
that takes you to
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF-Core-Power-Tools
which states "This page has moved to https://github.com/ErikEJ/EFCorePowerTools/wiki"
which is tiresome since that first link should take you directly to
https://github.com/ErikEJ/EFCorePowerTools/wiki

By all means keep that intermediate page if you really believe anyone is likely to point to it (presumably logs would confirm/deny need), but my grumble is people visiting that first page. Small beer FWIW, and many thanks for providing this useful resource.

**Comment by ErikEJ** [comment]
Any feedback to make the user experience better is much appreciated. Link updated
