### ISSUE TITLE
Feature request: Allow formatting SQL similar to SSMS

### ISSUE THREAD

**Issue by mdell-seradex** [ErikEJ/SqlCeToolbox#854]
I often use the tool to examine data via the "Edit TOP X Rows" context menu.
Normally, I have to adjust the SQL to apply my filters and change the view of columns I want to see (remove some and move others around), however in many databases I access, I usually have to page through 20+ pages because the SQL has one column per line.
Please add the ability to format the SQL via a setting to that multiple columns can appear on a single line up to a line length of X.
I know many people are in love with the concept of a single column per row, but I can only fathom that this is because they typically deal with tables that have a small number of columns.  I am the exact opposite.  Many of the tables I access have a great number of columns, so viewing the entire SQL is impossible when only one column is on a line, and scrolling through to 20 to 100 pages is just causes migraines.

My main concern is the single row per column formatting, but I would not be adverse to you adding any other SSMS like SQL formatting behavior.

I would appreciate you adding this.

Thank you.

**Comment by ErikEJ** [comment]
I am not aware of the SSMS feature, could you share more sample SQL code and maybe a screenshot?

**Comment by mdell-seradex** [comment]
I wouldn't exactly call it a feature of SSMS, more standard built-in behaviour.
I forgot that when you right-click on a table and perform the "Select Top X Rows" is does produce an SQL Statement identical to yours, however, if you select that text and select "Design Query in Editor" from the context menu (Ctrl-Shift-Q in SSMS v18 and probably others), you will get an SQL Statement like I mentioned.
This is the same formatting that you get when viewing the SQL statement of a database View that was created or modified via the View designer (New View...).

**Comment by ErikEJ** [comment]
Sorry, I do not follow. Could you share screenshot(s) ?

**Comment by mdell-seradex** [comment]
I was trying to demo the text, but it won't keep the formatting.  Here are some images:

![image](https://user-images.githubusercontent.com/40300659/84695013-2a2eaf80-af18-11ea-9192-e3d1b2ceeb25.png)
![image](https://user-images.githubusercontent.com/40300659/84695105-50544f80-af18-11ea-858d-1108ccda69b0.png)
![image](https://user-images.githubusercontent.com/40300659/84695315-a6c18e00-af18-11ea-9f01-1c2739d67720.png)

**Comment by mdell-seradex** [comment]
I can demonstrate a more complex SQL statement if you wish with JOINs, a GROUP BY, HAVING, and ORDER BY.
I believe they tend to follow the same pattern as the SELECT statement.

**Comment by ErikEJ** [comment]
You can edit the text in the SQL pane in the Toolbox to be anything you want - why does that not solve your problem?

**Comment by mdell-seradex** [comment]
It does, and it is what I do now.  It would be simply more convenient to have it formatted in the condensed version to begin with.
This is why I marked it as a Feature Request, not a bug.

**Comment by ErikEJ** [comment]
Could you share a sample of uncondensed Vs condensed formatting??

**Comment by mdell-seradex** [comment]
Condensed:
![SQL 2020-06-15 152457](https://user-images.githubusercontent.com/40300659/84697657-885d9180-af1c-11ea-81d7-87dc15173754.png)

Uncondensed:
![image](https://user-images.githubusercontent.com/40300659/84697215-bf7f7300-af1b-11ea-8710-942f4e3fe24a.png)

**Comment by ErikEJ** [comment]
OMG - the columns!!!

**Comment by mdell-seradex** [comment]
Exactly. Note that I am less concerned about removing the unnecessary square brackets.

**Comment by mdell-seradex** [comment]
That is from a Microvellum database.  I don't know if you have heard of that product before.

**Comment by mdell-seradex** [comment]
To be honest, I am not thrilled about the excess amount of spaces (or tabs based on your settings) that SSMS injects at the start of each line, but I would prefer the ability to have the appearance of consistency across the two products (yours and Microsoft's), if no control is given over that.

**Comment by mdell-seradex** [comment]
Hi @ErikEJ 
I'm not sure I fully understand the check-in.   It looks like it could be different from the SSMS formatting, but it should definitely help.
Thank you.

**Comment by ErikEJ** [comment]
Have you tested the latest daily build?

**Comment by mdell-seradex** [comment]
I haven't tried.  Wasn't sure I could access that. :)

**Comment by ErikEJ** [comment]
Oh yes, just look at the readme in the repo..

**Comment by mdell-seradex** [comment]
I tested the nightly build by updating to it using your "Additional Extension Gallery" in Visual Studio and your modification works much better for me, however it is different from how SQL Server Management Studio does it.  Thank you very much.

SQL Server Management Studio has a specific line length that it adheres to and forces a wrap at a proper word boundary to prevent lines longer than that length.  Also, I think it treats characters between square brackets as if they were not white space.
Also, since it appears to be a permanent change for everyone, I wonder how many will dislike it.

I'd like to spend some times trying to put together a pull request to enhance this, but I've never done that before.  I also rarely have time for these things, but I will try. 🙂
