### ISSUE TITLE
Altering the SQL to re-arrange columns does not re-arrange them in the view.

### ISSUE THREAD

**Issue by mdell-seradex** [ErikEJ/SqlCeToolbox#856]
When editing data in a SQL Compact table (v4 in my tests), if I re-arrange the columns in the SQL statement, the output order does not change until I remove all of the columns after the new/old position (which ever is closer to the first column), run the SQL, and then add the removed columns back in.
e.g. changing:
`SELECT AdjustedCutPartLength, AdjustedCutPartWidth, FileName, LinkID, LinkIDMaterial, LinkIDProduct, LinkIDProject, MaterialName, Quantity, TotalQuantity 
FROM Parts`
to
`SELECT LinkID, LinkIDMaterial, LinkIDProduct, LinkIDProject, AdjustedCutPartLength, AdjustedCutPartWidth, FileName, MaterialName, Quantity, TotalQuantity 
FROM Parts`
does not move the Link columns to the start.  I have to remove LinkID to TotalQuantity from the SQL, and then add it back in after.

**Comment by ErikEJ** [comment]
I which context? Please provide some sample SQL so I can try to reproduce...

**Comment by mdell-seradex** [comment]
Sorry, I was trying to add the SQL to my original post and it accidentally submitted it.
Let me know if you need more information.

**Comment by ErikEJ** [comment]
Please show me the context (screenshot) of this, there are many features in the Toolbox

**Comment by ErikEJ** [comment]
I am not able to reproduce this based on the inforamtion provided.

**Comment by mdell-seradex** [comment]
I have provided a zip file that contains an mp4 that demos this.
[Columns not moving.zip](https://github.com/ErikEJ/SqlCeToolbox/files/4787904/Columns.not.moving.zip)

**Comment by ErikEJ** [comment]
How many columns do you have in that table? (I cannot repro with a table with a sane amount of columns)

**Comment by mdell-seradex** [comment]
It is not my table.
This is actually a Microvellum database (https://www.microvellum.com/), so I have no control over the data structure.
Also, the database was provided by a client, so I don't control the amount of data either, unfortunately.  Note that this is the same table I showed in the other post with the screenshot.  https://github.com/ErikEJ/SqlCeToolbox/issues/854#issuecomment-644332240

**Comment by mdell-seradex** [comment]
Note that I can reproduce this in a table with 13 columns.
Are you testing with a SQL Compact database, or something else?
I can also reproduce this with a SQLite database.

**Comment by ErikEJ** [comment]
Which Toobox version are you using the in repro demo?

**Comment by mdell-seradex** [comment]
I figured this was the easiest thing to provide you all the information you might need. 🙂
![image](https://user-images.githubusercontent.com/40300659/84862465-3bbfa680-b041-11ea-9950-185559428877.png)

**Comment by mdell-seradex** [comment]
This works for me in the nightly build.

**Comment by ErikEJ** [comment]
Thanks for confirming!
