### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by mdell-seradex** [ErikEJ/SqlCeToolbox#857]
I experience an out of memory error after opening and closing a large table for editing many times.  Note that it was over 10 times, possibly near 20, but I have had other times where it seemed to occur much sooner.

Note that I did try clicking on column headers to sort and minor re-arrangement of columns in the SQL editor to try to get it to occur sooner.

Also note that the SQL Compact database file I am using is 895MB in size.
![image](https://user-images.githubusercontent.com/40300659/84803243-be0f8280-afcf-11ea-9011-7267cab4e67e.png)

**Comment by mdell-seradex** [comment]
Note that if you would like me to try to diagnose this with some debug files, please let me know.
:simple_smile:

**Comment by ErikEJ** [comment]
Exclude your image column from the SELECT column list...

**Comment by mdell-seradex** [comment]
Also, When trying to close Visual Studio, it thinks a dialog is left open after the error occurs and prompts me, but allows me to ignore this and close anyway.

**Comment by ErikEJ** [comment]
Tried to dispose better in the latest daily build

**Comment by mdell-seradex** [comment]
They (Microvellum) have so many of those stupid things (image columns), it is just annoying.
I was surprised the first time I saw them that the tool displays the actual images instead of an address, or hex data.
It will not be easy to remove the image columns everytime, besides, they are always included when opening the table for edit.

**Comment by mdell-seradex** [comment]
I just saw your last comment.
Thank you.

**Comment by ErikEJ** [comment]
You can also set the grid to only show the last 20 rows by default instead of 200!

**Comment by ErikEJ** [comment]
Tried to dispose better in latest daily build, try that and feel free to re-open if the issue persists. (No guarantee for any fix, though)

**Comment by mdell-seradex** [comment]
I still get an out of memory error in some cases, but I am not getting the others related problems like the message when closing Visual Studio.

**Comment by ErikEJ** [comment]
Thanks for the update.
