### ISSUE TITLE
Views not transferred during migration from SQL Server 

### ISSUE THREAD

**Issue by karosc** [ErikEJ/SqlCeToolbox#858]
When I try to script my SQL Server Database for either SQL Server CE or SQLite, the views I have created are not added to the script. Only the tables and indexes are transferred. It's not clear to me whether or not this is expected.

### Steps to reproduce
Try to migrate an SQL Server with views into SQLite; the views are not migrated.

### Further technical details
Toolbox/Power Tools version: 4.7.679.0

Database engine: SQL Server/SQLite

Visual Studio or SSMS version: SSMS 18.5

**Comment by ErikEJ** [comment]
This is by design - SQL Compact does not support views, and I cannot reliably transfer SQL Server views to SQLite.
