### ISSUE TITLE
CLI for migration?

### ISSUE THREAD

**Issue by jesperordrup** [ErikEJ/SqlCeToolbox#859]
Hi @ErikEJ 

Is it possible to use the cmd line tool for migrating from SQL server to sdf?

Thank you
Jesper

**Comment by ErikEJ** [comment]
Absolutely - use Export2SqlCe https://github.com/ErikEJ/SqlCeToolbox/releases/tag/3.5.2 and then use SqlCeCmd to create the database file and run the script.

Have a look at this 10 year old blog post for help http://erikej.blogspot.com/2010/02/how-to-use-exportsqlce-to-migrate-from.html - and let me know if you need any additional info.

**Comment by jesperordrup** [comment]
Thank you. I'll give it a go!
