### ISSUE TITLE
Connection Names

### ISSUE THREAD

**Issue by mdell-seradex** [ErikEJ/SqlCeToolbox#860]
When adding a SQLite connection, if the database file name is the same as one that is already in the list, it is added so there are now 2 with the same name pointing to different files.
When adding a SQL Compact 4.0 connection, if the database file name is the same as one that is already in the list, an index is appended to it when it is added so that each has a unique name in the list.

1. Can these be made consistent?
2. Can we have the ability to change the displayed connection name as this could be helpful when looking at data from several similar files.

Note I have not tried any other connection types, nor have I looked at what occurs if one type has the same name as another type when it is added. (e.g. adding a poorly named SQL Compact db that matches a SQLite db in the list)

Thank you

**Comment by ErikEJ** [comment]
This is not something I have any plans to fix, but I accept pull requests

**Comment by mdell-seradex** [comment]
Ok, thank you.
I am really not familiar with how to do that.
I find the naming convention very confusing (Pull Requests). 🙂
