### ISSUE TITLE
How to save to disk/upload an image field?

### ISSUE THREAD

**Issue by win32nipuh** [ErikEJ/SqlCeToolbox#861]
I have a SQLite dabatase, one of tables contains field type IMAGE. I store some zipped data to the field.
How I can save the field data to disk as a file? and how to upload a file to the field?

**Comment by ErikEJ** [comment]
You should be able to use the Edit Top 200 rows, and right click the image column

**Comment by win32nipuh** [comment]
Thanx, it works!

**Comment by ErikEJ** [comment]
Excellent, was unsure about whether it worked with SQLite...
