### ISSUE TITLE
C# and WPF Open SqliteFile

### ISSUE THREAD

**Issue by ms1094392787** [ErikEJ/SqlCeToolbox#864]
I tried to use C# to open a Sqlite database file containing the encryption key (.sqlite).What should I do now?.And the path to the database needs to change as the program runs.So I have to switch data all the time.
The question now is.When I opened the database it was shown that the "SQLite.Interop. DLL "module could not be found

**Comment by ErikEJ** [comment]
How does that relate to the Toolbox ?

**Comment by ErikEJ** [comment]
Ping ?

**Comment by ErikEJ** [comment]
Closing, feel free to re-open if you can provide the requested info
