### ISSUE TITLE
Inconsistency in script file created from Visual Studio tool vs. Command Line tool (Export2SQLCE)

### ISSUE THREAD

**Issue by rsayeed** [ErikEJ/SqlCeToolbox#865]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Added a local SQL Server instance to the Data Connections using Visual Studio. Then created a script (schema and data) file. The resulting script successfully created a DDL file, which contains triggers to enforce constraints. I then decided to see whether the command line tool - Export2SQLCE.exe - would yield the same script file because I would like to automate the process.The main difference I have seen is that the triggers are not being included from the output of the command line tool. Is there a way to produce the script file from the tool to yield the same exact output as the visual studio plugin?

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.670.0 - more than 900,000 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server and SQL Lite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2019

**Comment by ErikEJ** [comment]
Thanks for reporting this, I have updated the Release files with a fix
