### ISSUE TITLE
Incomplete connection properties dialog.

### ISSUE THREAD

**Issue by iVoteSize** [ErikEJ/SqlCeToolbox#866]
Describe what is not working as expected.

### Steps to reproduce
I 'broke' my visual studio 2019 installation and reinstalled it; but now the connection dialog is missing some important parts (I think).

### Further technical details
![Incomplete connection properties dialog](https://user-images.githubusercontent.com/5899342/92440406-7174b700-f17a-11ea-8b6c-ff56c15126ec.JPG)

Version 4.7.670.0
SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No
SQL Server Compact 3.5 DDEX provider - No
Sync Framework 2.1 SqlCe 3.5 provider - No
SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

### Database engine: (SQlite, SQL Compact or SQL Server)
SQLite

### Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Microsoft Visual Studio Enterprise 2019
Version 16.7.2
VisualStudio.16.Release/16.7.2+30413.136
Microsoft .NET Framework
Version 4.8.04084
Installed Version: Enterprise

**Comment by ErikEJ** [comment]
You need to go through this: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by iVoteSize** [comment]
Thanks for the help - the missing link for me what to make sure to check the:

Install the assemblies into the global assembly cache. 
Install the designer components for Visual Studio 2015.

... checkboxes.
