### ISSUE TITLE
Add SQL CE latest runtime to Tools folder

### ISSUE THREAD

**Issue by BjornCanasta** [ErikEJ/SqlCeToolbox#867]
When using the ExportSqlCe40 comandline tool to export a sql server ce database to sqlite I get

Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlServerCe,

### Steps to reproduce

I´m using the following statement in windows powershell
.\ExportSqlCE40.exe "Data Source=small_test.sdf" "temp_sql_file.sql" sqlite

### Further technical details

I´m using the latest version of the command line tool downloaded off Github 13of september 2020

exporting sql server ce 4.0 to Sqlite

**Comment by ErikEJ** [comment]
Do you have the SQL Server Compact runtime installed?

**Comment by BjornCanasta** [comment]
I realized that this was a deployment issue, but it took me a while to find the private deployment files in 

SqlCeToolbox-master\NuGet\EntityFramework.SqlServerCompact.PrivateDeployment\lib\net40

it would great if the comand line tool exe were built stand alone. 

Thanks for a great tool

**Comment by ErikEJ** [comment]
You can also find the MSI installer in the Tools folder. 

It is not possible to use a single .exe due to the unmanaged dependencies.

**Comment by ErikEJ** [comment]
I see now that the 4.0 runtime is not included in the tools folder, I will get that added.

**Comment by ErikEJ** [comment]
Runtimes added to tools folder in repo
