### ISSUE TITLE
Crash occurs when column data type mis-matches

### ISSUE THREAD

**Issue by ManGupt** [ErikEJ/SqlCeToolbox#868]
Whenever the data type doesn't match the plugin crashes and takes down the VS with it.

### Steps to reproduce
1. Create a datetime field in sqlite.
2. Insert a string not in format of datetime.
3. Try opening the table in plugin for viewing table data.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.670.0
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQLite ADO.NET Provider included: 1.0.109.0
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS Community 2019, Version 16.6.0

![2](https://user-images.githubusercontent.com/25338257/93734255-1de07f80-fbf6-11ea-994e-35182c99cd88.jpg)
![1](https://user-images.githubusercontent.com/25338257/93734260-220c9d00-fbf6-11ea-80ad-a3b732bfacaa.jpg)

**Comment by ErikEJ** [comment]
This is a System.Data.SqLite issue. I will see if I can prevent VS crash, if you can provide exact repro steps.

**Comment by ManGupt** [comment]
Please use following sql commands to create table and insert data:
1. CREATE TABLE types ([id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, [code] nvarchar(50) NULL, [desc] nvarchar(250) NULL, [name] nvarchar(30) NOT NULL, [inactive] character DEFAULT ('n') NULL, [end_date] timestamp NULL);

2. INSERT INTO [types] ([id],[code],[desc],[name],[inactive],[end_date]) VALUES (1, 'c1', 'code 1', 'Dummy', 'n', '"NULL"');

Although the query was generated by my code is wrong, but the this should be handled gracefully.

**Comment by ErikEJ** [comment]
Could you please try the latest build?

**Comment by ErikEJ** [comment]
Fixed in latest daily build
