### ISSUE TITLE
Unique constraint not visible

### ISSUE THREAD

**Issue by ManGupt** [ErikEJ/SqlCeToolbox#872]
Whenever there is unique constraint on column. The window doesn't show that.
Shows PK and not null constraints.

### Steps to reproduce
1. CREATE TABLE [cat_mapping] ( [pid] integer primary key autoincrement, [id] bigint NOT NULL UNIQUE, [cat] nvarchar(250) NULL);
2. View table details in plugin window only "PK, null, not null" constraints are shown.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.685.0 

Database engine: (SQlite, SQL Compact or SQL Server)
SQLite ADO.NET Provider included: 1.0.109.0

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
VS 2019 Community Version 16.6.0

**Comment by ErikEJ** [comment]
SQL Server Management Studio does not display this, so it is not something I plan to implement
