### ISSUE TITLE
SQL Server - Alter Table Add Constraint - error for filtered constraints

### ISSUE THREAD

**Issue by rsayeed** [ErikEJ/SqlCeToolbox#876]
Describe what is not working as expected.

When generating a script for a SQL Server DB, tables that currently have filtered indexes on them defined, get translated 
as 
`ALTER TABLE [TableName] ADD CONSTRAINT [ConstraintName] UNIQUE ([FieldName]) WHERE ([FieldName] IS NOT NULL);`

However, running the above in SQL Server Management Studio throws a syntax error in SQL Server indicating that the "WHERE" is invalid. Should this code instead be as follows:
```
CREATE UNIQUE NONCLUSTERED INDEX ConstraintName
    ON TableName (FieldName)  
    WHERE FieldName IS NOT NULL ; 
```

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
1. Connect to a SQL Server Instance and create a Database
2. Create a table with a primary key field and a nullable field
3. Create a Unique Nonclustered Index on the nullable field. Set the filter to be: (fieldName] IS NOT NULL)
4. Go into Visual Studio and connect to the SQL Server instance
5. Right-click and click on Script Database -> Script Schema and Data and save to a .sql file
6. Verify that the Index is being translated the same way that I described above
7. Create another Database
8. Execute the .sql file from step 5 to applied against the new database created in step 6 
9. Notice that it will error on the Where clause as I indicated in the problem description

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.7.670.0 - more than 900,000 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider - Yes

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Server

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio Professional 2019 - 16.6.5
SSMS: 18.5.1

**Comment by ErikEJ** [comment]
What embedded database is involved in this?

**Comment by rsayeed** [comment]
I was actually doing a SQL Server to SQL Server data dump migration to see if I can fully replicate the schema and data from one database to another.

**Comment by ErikEJ** [comment]
This tool is not designed for that..

**Comment by rsayeed** [comment]
I see. Thank you.
