### ISSUE TITLE
Related to HTML document generation

### ISSUE THREAD

**Issue by gaurakshay** [ErikEJ/SqlCeToolbox#877]
Hi @ErikEJ! 

Not really an issue just a question. At the link : [SqlCeToolbox](https://erikej.github.io/SqlCeToolbox/), it is mentioned that we can generate HTML documentation of the DB. Is there documentation on how to access this feature of the toolbox? I apologize in case I missed it.

Thanks in advance!

**Comment by ErikEJ** [comment]
Right click on the Database Connection, and select Create Database Documentation

**Comment by ErikEJ** [comment]
I think so, yes. Why don't you try?

**Comment by gaurakshay** [comment]
Yes I tried it but wasn't sure if I was doing it right. In VS 2019, I was only able to see the option to generate DGML and didn't find the option to generate documentation. Please see the screenshot below:

![image](https://user-images.githubusercontent.com/17280428/101051355-00f7ef00-354b-11eb-8e74-cc836c675356.png)

**Comment by ErikEJ** [comment]
The feature only works for SQLite and SQL Server Compact databases!

**Comment by gaurakshay** [comment]
🤦‍♂️ sorry!

**Comment by ErikEJ** [comment]
There are multiple commercial and free tools for documenting SQL Server databases.

**Comment by gaurakshay** [comment]
Do you have any suggestions for free tools? I found some : [SchemaSpy](https://github.com/schemaspy/schemaspy), [SchemaCrawler](https://github.com/schemacrawler/SchemaCrawler) but would love to know if you were aware of any others or if any that used C# (and were more up to date unlike DB>Docs which hasn't been updated in years).

**Comment by ErikEJ** [comment]
No, I do not. 
I usually use database projects,with MS_Description added as needed.
