### ISSUE TITLE
Update model from database cannot find the ddex provider (vs2019)

### ISSUE THREAD

**Issue by bgvsan** [ErikEJ/SqlCeToolbox#880]
Describe what is not working as expected.

### Steps to reproduce
Right click into the edmx file -> Update Model From database.
![image](https://user-images.githubusercontent.com/4590043/103013545-a21c0900-453d-11eb-958f-964e05ba933d.png)

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
![image](https://user-images.githubusercontent.com/4590043/103013601-b9f38d00-453d-11eb-9e1d-f9af9e3bd9fb.png)

Database engine: (SQlite, SQL Compact or SQL Server)
im using .net 4.5.2 with sqlite 1.0.113 with VS 2019

After a day of pain i was able to install the sqlite version sqlite-netFx451-setup-bundle-x86-2013-1.0.113.0, and i successfully drop the old edmx and re createad another one. but if im trying it to update from the db again , it cannot find the DDEX.

this is my machine settings.

`<add name="SQLite Data Provider" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139" />`

This is the package section
![image](https://user-images.githubusercontent.com/4590043/103014281-d04e1880-453e-11eb-8db3-4c6f4da80ac8.png)

**Comment by ErikEJ** [comment]
Sorry it is so painful. It's out of my hands. 

Did you follow the guide in the wiki carefully?

**Comment by bgvsan** [comment]
NP.
i've followed that:
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider
but i can redo everything back again from the beginning.

**Comment by bgvsan** [comment]
no luck, still got the issue on generation

**Comment by bgvsan** [comment]
i manage to make it work - ish.. 
i've tried on a different project ( created a new edmx, and from there the updates called the edmx wizard).
So after that i was able to call it from my data project. my advice is to always create a brand new project,

i  said  work -ish because the updates is not generating corrrectly the Association. all the tables losts the FK connection.

![image](https://user-images.githubusercontent.com/4590043/103081646-a812f800-45d8-11eb-87c4-9303dc479bcc.png)

**Comment by ErikEJ** [comment]
Not really anything for me to here.
