### ISSUE TITLE
Generate database from Model gives errors:

### ISSUE THREAD

**Issue by t0b4cc0** [ErikEJ/SqlCeToolbox#881]
Describe what is not working as expected.

### Steps to reproduce

1. Add new item > ado.net data model
2. select "EFDesigner from database"
3. select sqlitedatabase with help from your totally awesome software (in my case an "empty" sqlite db file (no tables just created the db with python) / 
4. "create database from model" 
5. in entity designer brings up error

PS: selecting "empty model" on step 2 leads to same result but then step 3 and 4 are switched

### Further technical details
I did everything as described here:
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

Here my appconfig:
[App.config.txt](https://github.com/ErikEJ/SqlCeToolbox/files/5760965/App.config.txt)

And one with 2 added parts, a whole section and one line that was suggested could help
[App.config2.txt](https://github.com/ErikEJ/SqlCeToolbox/files/5760961/App.config.txt)

That doesnt change anything.

Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
```
Version 4.7.670.0

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes


SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No


Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider included: 1.0.109.0
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes
```

Database engine: 
SQlite

Visual Studio version:
Microsoft Visual Studio Community 2019 Version 16.8.3

![error1](https://user-images.githubusercontent.com/9497253/103467959-9659ef00-4d54-11eb-983d-862ecfe21024.jpg)
![Clipboard02](https://user-images.githubusercontent.com/9497253/103467963-96f28580-4d54-11eb-8935-dbe0ce2ef2ce.jpg)

**Comment by ErikEJ** [comment]
You are NOT using the same version of System.Data.Sqlite everywhere, as required.

**Comment by ErikEJ** [comment]
If you still encounter errors after fixing your version issues, feel free to re-open.
