### ISSUE TITLE
Close issue

### ISSUE THREAD

**Issue by ErikEJ** [ErikEJ/SqlCeToolbox#882]
In Visual Studio 2019 if the SQLLite toolbox is auto-hidden and Edit top X is selected, it opens in another tab (this is good). However, while the tool box is autohidden and I close out the record edit tab the Sqlite toolbox also closes out. I then have to go to View -> Other Windows -> Sqlite .... toolbox

**Comment by dzsoundnirvana** [comment]
To help you investigate this item, I have attached a small video showing the interaction.

https://user-images.githubusercontent.com/3346180/104125525-89209f80-5314-11eb-9521-be9adbd79362.mp4

**Comment by ErikEJ** [comment]
@dzsoundnirvana Which version of the Toolbox do you use?

**Comment by ErikEJ** [comment]
I am able to repro, also with latest build. 

It is most likely due to the code here, added to avoid memory issues when many edit grids are loaded:
https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/ToolWindows/DataGridViewWindow.cs

Notice that you can also launch the Toolbox from the Tools menu.

**Comment by dzsoundnirvana** [comment]
@ErikEJ I have ver. 4.7.670.0
![SQLiteToolboxVS19_Verinfos_11JAN20](https://user-images.githubusercontent.com/3346180/104220056-2f93a000-53fc-11eb-80f0-0e085dfce579.png)

**Comment by ErikEJ** [comment]
I prefer this over memory leaks, so closing for now - a PR to fix this would be welcome.
