### ISSUE TITLE
Cannot use "Password" connection string property 

### ISSUE THREAD

**Issue by arvin1121** [ErikEJ/SqlCeToolbox#883]
Describe what is not working as expected.
![image](https://user-images.githubusercontent.com/77423024/105158225-b527f600-5b48-11eb-8f2a-d3734b45698e.png)

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Please provide the requested information

**Comment by arvin1121** [comment]
When I use “password” for Sqlite, I will report an error. If I don't use “password”, everything is normal.

Toolbox/Power Tools version: 4.7.688.8 - 1679,096

Database engine: SQlite

Visual Studio 2017 15.9.24

**Comment by ErikEJ** [comment]
Please "Include a complete description that I can redo to reproduce the issue."

**Comment by duongnt0910** [comment]
I also have this problem.
-first, i creat sqlite file by SQLiteStudio: Type=System.Data.Sqlite, password=12345678
![image](https://user-images.githubusercontent.com/6957206/106096741-b2d92380-6168-11eb-8ca4-c3996761b4c2.png)
-And then, i connect this db file to Visual studio by your provider, press Test connection or OK then error appear:
![image](https://user-images.githubusercontent.com/6957206/106097139-59252900-6169-11eb-9f3c-486d9bf67a58.png)
Please check and help us.
Thanks ErikEJ.

**Comment by duongnt0910** [comment]
You can check by my db file:
https://1drv.ms/u/s!AqELdlvWv68xppoyQwwS1JfFFUWvkA?e=DeJitY
Thanks!

**Comment by ErikEJ** [comment]
Which version of System.Data.Sqlite does Sqlite Studio use - I think for the latest version, CryptoAPI is no longer supported.

**Comment by arvin1121** [comment]
> Which version of System.Data.Sqlite does Sqlite Studio use - I think for the latest version, CryptoAPI is no longer supported.

System.Data.SQLite Verson 1.0.113.2

**Comment by ErikEJ** [comment]
Looks like it is no loner supported, maybe SQLite Studio uses their own build? https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki

**Comment by duongnt0910** [comment]
So, now is there any way I use sqlite with password protected?

**Comment by ErikEJ** [comment]
I can actually open the file you shared without any issues, using this connection string: 

    data source=C:\Users\eej\Downloads\bd2.db;Password=12345678

**Comment by ErikEJ** [comment]
Sorry, I can open it in SQLite Toolbox - why do you want to open it in Server Explorer?

**Comment by ErikEJ** [comment]
Ah, with EF6! I think you will have to decrypt for use with the design time tooling.

**Comment by duongnt0910** [comment]
Khi tôi cài bản sqlite-netFx46-setup-bundle-x86-2015-1.0.113.0, tôi cũng mở được bằng SQLite Toolbox của bạn. nhưng kết nối dùng EF6 nó báo lỗi không chấp nhận password trong connection string như tôi mô tả ở trên.
Còn khi tôi cài lại bản sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0 thì lại có thể dùng EF6 mở với Password như bình thường.

**Comment by duongnt0910** [comment]
When I install sqlite-netFx46-setup-bundle-x86-2015-1.0.113.0, I can also open it with your SQLite Toolbox. But connecting using EF6 it error not accepting password in connection string as I described above.
And when I reinstalled the sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0 version, I could use EF6 to open with Password as usual.

**Comment by duongnt0910** [comment]
> I can actually open the file you shared without any issues, using this connection string:
> 
> ```
> data source=C:\Users\eej\Downloads\bd2.db;Password=12345678
> ```
When I install sqlite-netFx46-setup-bundle-x86-2015-1.0.113.0, With above connetion string, EF6 show error:
![image](https://user-images.githubusercontent.com/6957206/106219552-313ad180-620c-11eb-881a-6ea07e09e5f5.png)

**Comment by ErikEJ** [comment]
I meant, I can open the file use SQLite Toolbox, possibly not with the EF6 Tooling.

Looking here https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki I assume that this change could have broken this scenario: 

When using the (unsupported) legacy CryptoAPI based codec, skip encrypting page #1 because that can lead to database corruption and other malfunctions.

>> And when I reinstalled the sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0 version, I could use EF6 to open with Password as usual.

Sounds like you found a workaround then?

**Comment by duongnt0910** [comment]
Yes, temporarily I use the old version sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0 then OK. But from time to time when the versions update, I don't know if it can run.
Thanks for your support, ErikEJ.

**Comment by ErikEJ** [comment]
You are welcome, sorry I cannot really help with this.
