### ISSUE TITLE
Foreign Key triggers for Composite Foreign Keys

### ISSUE THREAD

**Issue by StephenDye1977** [ErikEJ/SqlCeToolbox#885]
When converting a table from SQL Server to SQLite, the Foreign Key integrity checking triggers are incorrectly created when there is a composite foreign key.  The subquery select has more than one column.  This causes the "2 Columns when 1 Expected" error.  

Could this be fixed please.  Being new to SQLite, would "SELECT 1 FROM..." be a workaround?

Thanks

Stephen

**Comment by ErikEJ** [comment]
Sounds like a bug, could you provide some scripts to reproduce?

**Comment by ErikEJ** [comment]
Closing as the requested information was not provided.
