### ISSUE TITLE
SQLite Provider is unavailable

### ISSUE THREAD

**Issue by ElGauchooooo** [ErikEJ/SqlCeToolbox#887]
I've installed the "SQLite Toolbox DDEX provider" for EF6 as described here https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

Unfortunatelly, the SQLite Provider does not show up in the "Choose Data Source" dialog:

![image](https://user-images.githubusercontent.com/55155202/111796388-6be5ef80-88c8-11eb-8ff1-743dab569ebd.png)

I've checked the about dialog of the SQLite toolbox, which shows that i've installed Version 4.7.689.0 (which should, according to the release notes, support SQLite 1.1.113. Yet it shows me, that the included SQLite ADO.NET Provider is 1.1.109 and therefore most probably won't show up in the "Choose Data Source" dialog

![image](https://user-images.githubusercontent.com/55155202/111796932-f7f81700-88c8-11eb-892b-4f07b8794831.png)

### Steps to reproduce
I've followed the steps here: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider
I've aswell uninstalled both the extension and SQLite and reinstalled afterwards, the issue seems to persist.

### Further technical details
Toolbox/Power Tools version: 4.7.689.0

Database engine: SQLite 1.1.113

Visual Studio or SSMS version: VS 2019 Pro 16.8.1

If theres anything else you might need to resolve this, please let me know. Thanks in advance!

**Comment by ErikEJ** [comment]
Maybe try to install .109?

**Comment by ElGauchooooo** [comment]
That might work, but how to get 113 up and running?

**Comment by ErikEJ** [comment]
Use the latest daily build?

**Comment by ElGauchooooo** [comment]
I _did_ try that aswell, yet with no success. i've taken the instructions from here: https://github.com/ErikEJ/SqlCeToolbox/wiki/Subscribing-to-latest-%22daily%22-build

**Comment by ErikEJ** [comment]
You can just download...

**Comment by ErikEJ** [comment]
>> yet with no success.

What does that mean exactly? you were unable to update or?

I will consider a new official release with support for .113

**Comment by ElGauchooooo** [comment]
Hi Erik, thanks for the reply and sorry for my late answer. 
I was able to update, but as you can see on the screenshot, SqlCeToolbox still reports 

**SQLite ADO.NET Provider included: 1.0.109.0** 

shouldn't that be:

**1.0.113.0** ?

I've just upgraded SqlCeToolbox to version 4.7.690.0, yet it still shows up as SQLite ADO.NET Provider included: **1.0.109.0**

Any ideas?

**Comment by ErikEJ** [comment]
It is because I am apparently loading the dll from GAC 🙁

**Comment by FerdieGithub** [comment]
I am having a similar issue... 

Using:
- Visual Studio Professional 2019 Version 16.9.2
- Windows 10
- SQLite 1.0.113.0
- PowerTools 4.7.670

![image](https://user-images.githubusercontent.com/30120308/112734222-0db2af80-8f4d-11eb-8736-bae76fc50094.png)

The MS SQL Compact provider appears, but not the SQLite provider, even though I can see them both in the machine.config...
![image](https://user-images.githubusercontent.com/30120308/112734302-9c273100-8f4d-11eb-8e0e-8932803d70e3.png)

I tried all sorts of reinstallation, installation of different versions, following the exact steps as per the tutorials here on the wiki... but I just cannot get the SQLite provider to come up...

I would really appreciate any assistance.

**Comment by ErikEJ** [comment]
I noticed that version 109 was loaded from here !!:

C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\PrivateAssemblies\System.Data.SQLite.dll

Maybe that is what is causing conflicts.

I tried to rename the file, and the .dll distributed by SQLite Toolbox was loaded instead (as it should be)

**Comment by ErikEJ** [comment]
@FerdieGithub If you are using .113, you should be using the latest daily build, .112 is supported by the current release on MarketPlace.

**Comment by ErikEJ** [comment]
I have released 4.7.691 with support for .113

**Comment by ElGauchooooo** [comment]
Hi Erik, 

Thanks a lot for your reply and the fast fix. I found the same issue this night when i was recompiling your extension with some logging, after i realized that it already showed up with version .109 on a fresh VS2019 install without ever SQLite being installed on that machine. My assembly was being loaded VS 2019 Professionals private assemblies folder aswell, it comes preinstalled with Visual Studio. I now can see that it loads the correct .113 Version:

![image](https://user-images.githubusercontent.com/55155202/112747787-d0cfd280-8fb7-11eb-934f-028768113be8.png)

Yet i still have no SQLite Data Provider:

![image](https://user-images.githubusercontent.com/55155202/112747836-315f0f80-8fb8-11eb-8415-6228c02d30bf.png)

Any ideas what is now still missing?

**Comment by ErikEJ** [comment]
@ElGauchooooo I assume you have missed some step in the provider/GAC install guide. The DDEX provider only appears if System.Dats.Sqlite is properly installed in GAC. So follow the install guide exact, and check your x86 machine.config or inspect the GAC.

**Comment by ElGauchooooo** [comment]
Hi Erik, thanks for the reply. I assumed i did this, but checked once more:

SQLite is installed in GAC:

```
> gacutil.exe -l System.Data.SQLite
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  System.Data.SQLite, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139, processorArchitecture=x86

Number of items = 1
```

The only SQLite related entry in my  `C:\Windows\Microsoft.NET\Framework\v4.0.30319\Config\machine.cfg` looks like:

```
<system.data>
		<DbProviderFactories>
			<add name="SQLite Data Provider" invariant="System.Data.SQLite.EF6" description=".NET Framework Data Provider for SQLite" type="System.Data.SQLite.EF6.SQLiteProviderFactory, System.Data.SQLite.EF6, Version=1.0.113.0, Culture=neutral, PublicKeyToken=db937bc2d44ff139" />
		</DbProviderFactories>
	</system.data>
```

I'll try to debug your extension , where it tries to load the SQLite ddex.

**Comment by ErikEJ** [comment]
@ElGauchooooo Make sure you are running the latest daily build!

**Comment by ElGauchooooo** [comment]
@ErikEJ i did install 4.7.691:

![image](https://user-images.githubusercontent.com/55155202/112811927-d6432080-907c-11eb-918a-7c3f44b5fdb8.png)

**Comment by ElGauchooooo** [comment]
@FerdieGithub Were you able to get the SQLite Provider showing up with version 4.7.691? I doublechecked everything, yet it does not appear there. SQLite is registered properly in the GAC and it is listed in the machine.config.

**Comment by ErikEJ** [comment]
@ElGauchooooo Why do you need the SQLite provider?

**Comment by FerdieGithub** [comment]
Hi Erik

I followed the exact steps as per this article...
[](https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider)
Not succeeding yet... Where I need to select the SQLite provider it is not in the list....

I need to get a EF6 model generated from the sqlite DB, not sure how else to do this if the SQLite provider does not come up in VS 2019...   

![image](https://user-images.githubusercontent.com/30120308/113377829-b8740500-9375-11eb-930b-c7e8fe1e1a48.png)

I did install 1.0.113....

![image](https://user-images.githubusercontent.com/30120308/113377988-23254080-9376-11eb-9941-426f51cb250f.png)

I uninstalled and reinstalled the latest daily build from the marketplace...

**Comment by ErikEJ** [comment]
@FerdieGithub the installation of the System.data.sqlite VS support package is the important part!

**Comment by ErikEJ** [comment]
Closing this, as in all other instances, following the guide and related tips, and ensuring the same version (in this case .113) is in use everywhere. May be worsened by the fact that VS now includes version .109 sadly.
