### ISSUE TITLE
Extension completely broken and crashes VS 2019

### ISSUE THREAD

**Issue by leo-stone** [ErikEJ/SqlCeToolbox#890]
Hi there,

today I got surprised by the toolbox not working anymore. It got probably updated automatically.
If I hit the add sqlite connection button, VS 2019 crashes. 

![image](https://user-images.githubusercontent.com/15155123/113024807-76856c00-9187-11eb-8812-e80e12ba0b2b.png)
Version 4.7.691.0 - 1.718.194 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider installed: 1.0.109.0
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

**Comment by ErikEJ** [comment]
Probably related to: https://github.com/ErikEJ/SqlCeToolbox/issues/887

In other words, try this: https://github.com/ErikEJ/SqlCeToolbox/issues/887#issuecomment-808858493 

If that is the case, my only option is to revert to System.Data.Sqlite 109!

**Comment by ErikEJ** [comment]
Sadly, as also mentioned in the related issue, it just means System.Data.SQLite is not installed in GAC on your machine.

But is it still broken now?

**Comment by leo-stone** [comment]
Yes still broken, System.Data.SQLite.dll is contained in the Package, but fails to load.... obviously

**Comment by ErikEJ** [comment]
>> Obviously

Why?

**Comment by ErikEJ** [comment]
The release works fine on my PC and reports 113 installed. I do not have System.Data.Sqlite in GAC.

**Comment by leo-stone** [comment]
I've now renamed your dll, e.g. 113, now I get following
![image](https://user-images.githubusercontent.com/15155123/113030231-a899cc80-918d-11eb-996f-a2fc2d233ebb.png)

**Comment by leo-stone** [comment]
> > > Obviously
> 
> Why?

because of the red error message?

**Comment by ErikEJ** [comment]
Restart VS / re-install extension?

Is the System.Data.SQLite.dll present in the %localappdata%\Microsoft\VisualStudio and which versions?

**Comment by ErikEJ** [comment]
You should not rename "my dll", rename the one on PrivateAssemblies !

**Comment by leo-stone** [comment]
I did both, first I renamed the one in Private Assemblies, and posted the result.
Only later I've checked your dll, if it is there, or not, and then renamed it, to check behaviour...

Please, wich dll are you redistributing??? Because

![image](https://user-images.githubusercontent.com/15155123/113031402-f2cf7d80-918e-11eb-96f2-035cbbd37856.png)

Is this the correct dll? Because in PrivateAssemblies is

![image](https://user-images.githubusercontent.com/15155123/113031531-201c2b80-918f-11eb-93f8-041d9afbcb47.png)

**Comment by ErikEJ** [comment]
I am distributing .113

**Comment by ErikEJ** [comment]
I have nothing to do with the PrivateAssemblies folder!

**Comment by leo-stone** [comment]
I know that, but you are redistributing SQLite.Interop.dll, can you maybe give me an previous release package, so i can compare?

**Comment by ErikEJ** [comment]
Previous versions contain the same dll (System.Data.SqLite.dll is the file name) - as you can see in source control history:
https://github.com/ErikEJ/SqlCeToolbox/commits/master/src/GUI/lib/System.Data.SQLite.dll

**Comment by ErikEJ** [comment]
Do you have SQLite installed in GAC?

**Comment by leo-stone** [comment]
> Do you have SQLite installed in GAC?

No

**Comment by leo-stone** [comment]
The dll you redistribute has dependencies, it needs System.Data.SQLite.Core.113 which I don't have
I have 
 System.Data.SQLite.Core.109 via PrivateAssemblies 
So somehow your package should reference this dependencies so they get installed, no?

**Comment by ErikEJ** [comment]
Correct, System.Data.SQLite.dll version .113 is included with the extension, and installed within the extension folder, together with  the other parts of the extensions in the folder: C:\Users\eej\AppData\Local\Microsoft\VisualStudio\16.0xxx

**Comment by leo-stone** [comment]
Yes, but it has a dependency that is not on my machine...., I suspect now  

![image](https://user-images.githubusercontent.com/15155123/113038652-0a126900-9197-11eb-9e48-1574a88978b7.png)

Anywaz, if I'm the only one with that issue, you should not think about it too much.....

**Comment by ErikEJ** [comment]
Ah, I see now - I take the file from:  sqlite-netFx40-static-binary-bundle-Win32-2010-1.0.113.0.zip

Maybe I should be using this:  sqlite-netFx451-static-binary-bundle-Win32-2013-1.0.113.0.zip (which depends on a newer C++ runtime)

**Comment by leo-stone** [comment]
> Yes, but it has a dependency that is not on my machine...., I suspect now
> 
> ![image](https://user-images.githubusercontent.com/15155123/113038652-0a126900-9197-11eb-9e48-1574a88978b7.png)
> 
> Anywaz, if I'm the only one with that issue, you should not think about it too much.....

Just, confirmed... installing https://www.microsoft.com/de-de/download/details.aspx?id=8328 fixes it.

**Comment by ErikEJ** [comment]
I will take a newer "build" onboard, thanks for your patience and debugging work.
