### ISSUE TITLE
Only a question

### ISSUE THREAD

**Issue by elenaaralla** [ErikEJ/SqlCeToolbox#891]
Hi,

I'm trying to set password to my sqlite db (migrated from sqlce with your toolbox)

How I can set password on db with toolbox?

For CE in Maintenance menu i can see "Set Password", but i can't find it on Lite (see attached images)

Can you hemp me?

Thank you, Elena.

![Schermata 2021-04-01 alle 10 33 14](https://user-images.githubusercontent.com/14870650/113266926-14874c80-92d6-11eb-8aaf-7464ababc111.jpg)
![Schermata 2021-04-01 alle 10 33 33](https://user-images.githubusercontent.com/14870650/113266975-1f41e180-92d6-11eb-9db1-43cd8cf36cb0.jpg)

**Comment by ErikEJ** [comment]
No currently implemented, maybe you can use this: https://stackoverflow.com/questions/57508126/setting-and-changing-sqlite-database-password-in-c-sharp
