### ISSUE TITLE
SQLite build .113 removes encryption codec, and some legacy customers depend on it

### ISSUE THREAD

**Issue by gambled** [ErikEJ/SqlCeToolbox#892]
After updating to 4.7.691.0 I lost the ability to connect to encrypted SQLite databases.  This is due to an update to System.Data.SQLite.dll being upgraded to 1.0.113.0 which dropped the supported for using a password in the connection string to access an encrypted SQLite database.  In order to support my end-users, I need still need this functionality until I can push out a new update.  I need to be able to rollback to an earlier version that has an earlier version of System.Data.SQLite.dll that still has that functionality.

Sorry for an information request entered as an issue, but I could not find this information on the Wiki.

### Steps to reproduce
N/A

### Further technical details
Toolbox/Power Tools version: 4.7.691.0

Database engine: SQLite

Visual Studio or SSMS version: Visual Studio 2019 16.3.6

**Comment by ErikEJ** [comment]
The previous version used 112.0, and I cannot see any breaking changes in the relation. 
Please point me to or demonstrate the breaking change.

**Comment by gambled** [comment]
Please see attached screen snippets.  Please let me know if these did not come across.  The answer in the following StackOverflow describes dropping support for the password in  113.0 (https://stackoverflow.com/questions/64382606/system-data-sqlite-core-cannot-use-password-connection-string-property).  Not looking for your newest version to handle it since it is dropped support  from SQLite.  Just trying to figure out how to get a previous version of your toolbox that is using 112.0 or below.

- ToolBox About Info.png - About from the plug-in
- SQLIte Connection Error.png - Error when press the Test Connection button in the toolbox reports 109.0.
- System.Data.SqLite.dll properties show the actual version of the DLL being used even though the about box reports

![System Data SqLite dll properties](https://user-images.githubusercontent.com/13751651/113337918-6fc93700-92f6-11eb-82c7-0f210cd2dd72.PNG)

![Toolbox about info](https://user-images.githubusercontent.com/13751651/113337659-14974480-92f6-11eb-881f-4f03e10789b7.PNG)


![SQLite Connection Error](https://user-images.githubusercontent.com/13751651/113337581-f598b280-92f5-11eb-801f-8811dbc99fa6.PNG)

**Comment by ErikEJ** [comment]
Yes, what the about box reports is misdleading, I will remove that info.

**Comment by ekarimBM** [comment]
I have the exact same issue. is there a way to revert to previous version of toolbox using 112.0

**Comment by ErikEJ** [comment]
Think I finally was able to find the evidence:

Community Support Policies
Effective May 1, 2017
Updated May 22, 2020
**Legacy CryptoAPI Codec**
It is unsupported.
It is disabled in all default build configurations.
It may not be possible to build binaries with it enabled. 

(from https://system.data.sqlite.org/index.html/doc/trunk/www/news.wiki ) 

I assume this means that binaries built after May 2020 no longer includes the codec!

So.... Let me revert to .112 in the latest daily build, so you can help your customers move away from this!

**Comment by ErikEJ** [comment]
More evidence: https://system.data.sqlite.org/index.html/tktview?name=9c330a3e03

**Comment by ErikEJ** [comment]
Latest daily now used .112, please let me know if that solves your issue.

**Comment by gambled** [comment]
That seems to be working.  Thank you very much.  I am working with the Product Managers to find an alternative to for protecting data-at-rest for our occasionally-connected-app and getting it deployed.

**Comment by korasoglu70** [comment]
I'm using visual studio 2013 before formatting the computer, but now I've installed it, but it doesn't work
sqlite-netFx451-setup-bundle-x86-2013-1.0.114.0.exe I need to add this
1-NDP462-DevPack-KB3151934-ENU.exe
2-SQLite_and_SQL_Server_Compact_Toolbox_v4.7.691.vsix
3-sqlite-netFx46-setup-bundle-x86-2015-1.0.114.0.exe
4-SQLite-1.0.66.0-setup.exe

**Comment by ErikEJ** [comment]
@korasoglu70 You should install .112, not .114!

**Comment by korasoglu70** [comment]
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider
I applied it according to the explanation in this link before, it worked. I don't know 114 or 112 but it doesn't work now. I would appreciate if you can help me how to download 112.

**Comment by ErikEJ** [comment]
https://system.data.sqlite.org/downloads/1.0.112.0/sqlite-netFx46-setup-bundle-x86-2015-1.0.112.0.exe

**Comment by korasoglu70** [comment]
![ToolBox](https://user-images.githubusercontent.com/85835088/121965540-d8607580-cd75-11eb-82a2-6101adeba1b2.jpg)

**Comment by korasoglu70** [comment]
Dear ErikEJ thank you problem solved. transactions made
![A1](https://user-images.githubusercontent.com/85835088/122290512-7da55600-cefc-11eb-93aa-d539aad363cc.jpg)
![A2](https://user-images.githubusercontent.com/85835088/122290521-81d17380-cefc-11eb-9c1d-03ab246c5553.jpg)
![A3](https://user-images.githubusercontent.com/85835088/122290530-84cc6400-cefc-11eb-8574-57918ad9b4a5.jpg)
![A4](https://user-images.githubusercontent.com/85835088/122290545-885feb00-cefc-11eb-8ed6-98ceea16d7f3.jpg)
for visual studio 2013
machine.config
<system.data>
    <DbProviderFactories> 
        <add name="SQLite Data Provider" 
             invariant="System.Data.SQLite.EF6" 
             description=".NET Framework Data Provider for SQLite" 
             type="System.Data.SQLite.EF6.SQLiteProviderFactory, 
                    System.Data.SQLite.EF6, 
                    Version=1.0.113.0, 
                    Culture=neutral, 
                    PublicKeyToken=db937bc2d44ff139" 
        />  
    </DbProviderFactories> 
</system.data>
