### ISSUE TITLE
Migration from sqlite to SQL Server fails with Id column as primarykey with autoincrement 

### ISSUE THREAD

**Issue by Econ808** [ErikEJ/SqlCeToolbox#893]
When I try to migrate to SQL Server the following error is raised.
![image](https://user-images.githubusercontent.com/36441764/113843198-ab02b480-9793-11eb-8e7c-d609e8f462fb.png)

### Steps to reproduce

- Create sqlite table containing a column named "Id" as primary key with autoincrement:
        
        CREATE TABLE [dannede_sager] (
          [Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
        , [cpr] nvarchar(10) NOT NULL COLLATE NOCASE
        , [sags_navn] nvarchar(50) NOT NULL COLLATE NOCASE
        , [sags_link] nvarchar(50) NOT NULL COLLATE NOCASE
        , [borger_navn] nvarchar(50) NOT NULL COLLATE NOCASE
        , [borger_link] nvarchar(50) NOT NULL COLLATE NOCASE
        , [borgerensplan_link] nvarchar(50) NOT NULL COLLATE NOCASE
        , [Timestamp] datetime NULL
        );
        
- Insert rows...

- Migrate to SQL Server:

![image](https://user-images.githubusercontent.com/36441764/113844689-0da88000-9795-11eb-8dc4-7764f6abf94c.png)

#### Toolbox/Power Tools version: 
Version 4.7.697.0 - 1.734.351 downloads

SQL Server Compact 4.0 in GAC - No
SQL Server Compact 4.0 DbProvider - No

SQL Server Compact 4.0 DDEX provider - No
SQL Server Compact 4.0 Simple DDEX provider - No

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

SQL Server Compact 3.5 DDEX provider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider used: 3.30.112
SQLite EF6 DbProvider in GAC - No

#### Database engine: SQlite/SQL Server

SSMS 18

**Comment by Econ808** [comment]
Is there someway that I can script the code to a file and then simply insert the following lines?

    SET IDENTITY_INSERT dannede_sager ON

    ...sql script...
    
    SET IDENTITY_INSERT dannede_sager OFF

**Comment by ErikEJ** [comment]
Have you tried the "Script Database" menu options?

**Comment by Econ808** [comment]
I have now tried the script Database option, and I have successfully created the table. It did, however, require numerous adjustments to the script, yet, using find-replace meant the adjustments were not too cumbersome.

Tak.

**Comment by ErikEJ** [comment]
Re-opening.

If you can privately share the db I can look into improvements.

**Comment by Econ808** [comment]
That is a generous offer. Is it okay if I simply share the output of "Script Schema and Database" as an  `.sql` file - Then I will just edit the urls. 

Not that it is sensitive data since I am working in an educational environment and cpr-numbers etc. are faked by myself (i.e. 10 random numbers that fit the criteria of a regular cpr...)

How can I share it with you?

**Comment by ErikEJ** [comment]
Thanks, it will be much more helpful to get a SQLite db, you can email me ejlskov at hotmail dot com.

**Comment by Econ808** [comment]
I have sent you the db.

**Comment by ErikEJ** [comment]
Wont fix!
