### ISSUE TITLE
Export from SQL CE 4.0 to .csv does not quote values with EOLs

### ISSUE THREAD

**Issue by fifonik** [ErikEJ/SqlCeToolbox#894]
I'm trying to export data from SQL CE 4.0 DB I have into CSV to process it.
Downloaded standalone SQL CE 40 toolbox, opened my cdf file, issued SELECT * FROM table query and clicked Export button to save. 
Tried SSMS version with the same outcome.

What I see in the csv file:
- Quotes in values are correctly escaped (" => "")
- Values with comma are correctly quoted (a,b => "a,b")
- Values with EOLs (0D 0A) are **not** quoted (a\r\nb must become "a\r\nb", where \r\n means chars with codes 0x0D 0x0A, not 4 chars '\\', 'r', '\\', 'n')

As a result, such csv could not be correctly opened.

I've also tried to Ctrl + A, Ctrl + C results and paste them in Excel directly -- no luck as well (results are slightly different when grid is ON and OFF).

So, is it possible to export data with EOLs?

Thanks.

### Further technical details
Toolbox/Power Tools version: 4.7.687

Database engine: SQL Compact 4.0

Visual Studio or SSMS version: SSMS 18

P.S. Right now I'm manually building SELECT queries that quote everything as required, something like this:
```
SELECT
       [id]
      ,'"' + REPLACE(LTRIM(RTRIM([name])), '"', '""') + '"' AS name
      ,'"' + REPLACE(LTRIM(RTRIM([comments])), '"', '""') + '"' AS comments
FROM [MyTable];
```

**Comment by ErikEJ** [comment]
>> So, is it possible to export data with EOLs?

Yes, with you workaround 😄 

I am using a very old version of an old CSV library: https://github.com/kentcb/KBCsv - a PR to update and fix this will be welcome.

Issue is that I currently support .NET Framework 4.5.1, and I think the current version is NET Standard 2.0, aka .NET FW 4.6.1

**Comment by fifonik** [comment]
I briefly looked at export code in SqlEditorControl.xaml.cs and have not found evidence of using the library you mentioned:
```
dataGrid.UnselectAllCells();
var result = (string) Clipboard.GetData(DataFormats.CommaSeparatedValue);
Clipboard.Clear();
File.WriteAllText(sfd.FileName, result);

```
If I understand correctly, the issue is in Clipboard.GetData and the only way to fix this (I can think of) is to build csv-string manually.

**Comment by fifonik** [comment]
I understand that my workaround works, but I need to export a number or tables so this is not the easiest approach.

I just dirty patched your program and building cvs manually:

```
        private string[] GetDataAsCSV(DataGrid dgrid, char separator = ',', char encloser = '"')
        {
            int columnCount = dgrid.Columns.Count;

            string[] lines = new string[dgrid.Items.Count + 1/*header*/];

            string[] header = new string[columnCount];
            for (int i = 0; i < columnCount; ++i) header[i] = enclose(dgrid.Columns[i].Header.ToString(), encloser, separator);

            lines[0] += string.Join(separator.ToString(), header);

            for (int j = 0; j < dgrid.Items.Count; ++j)
            {
                DataRowView row = dgrid.Items[j] as DataRowView;
                if (row == null) continue; // todo@ break?

                string[] line = new string[columnCount];
                for (int i = 0; i < columnCount; ++i)
                {
                    string s = enclose(row.Row.ItemArray[i].ToString(), encloser, separator);
                    line[i] = s;
                }

                lines[j + 1] = string.Join(separator.ToString(), line);
            }

            return lines;
        }


        private string enclose(string s, char encloser = '"', char separator = ',')
        {
            bool enclose = false;
            if(s.IndexOf(encloser) >= 0)
            {
                string escapedEncloser = encloser.ToString() + encloser.ToString();
                s = s.Replace(encloser.ToString(), escapedEncloser);
                enclose = true;
            }

            if (!enclose)
            {
                char[] chars = { separator, '\n', '\r' };
                enclose = s.IndexOfAny(chars) >= 0;
            }
            return enclose ? (encloser + s + encloser) : s;
        }
    } 
```
And then in grid's section of ExportButtonClick:
```
                        if (sfd.ShowDialog() == true)
                        {
+                            string[] lines = GetDataAsCSV(dataGrid, ',', '"');
+                            if (lines != null)
+                            {
+                                string csv = string.Join("\n", lines);
+                                File.WriteAllText(sfd.FileName, csv);
+                                return;
+                            }
                           ...
```

This solves my problem.
Sorry that I cannot provide proper patch. I'm just recently started with C#.

**Comment by ErikEJ** [comment]
Have you tried the dedicated "Export to CSV" feature?

**Comment by fifonik** [comment]
Nope. 
How can I find it?

**Comment by ErikEJ** [comment]
Sorry, I was mixing up with the Import feature.

You could try View as Report, and then export to Excel!

**Comment by ErikEJ** [comment]
If you can share a add file with content that does not export, I can investigate

**Comment by fifonik** [comment]
Thanks for suggestion. I will try to find out why View as Report does not work on my PC if I have time.
Unfortunately, I cannot share these files.

**Comment by ErikEJ** [comment]
You need to install the report viewer.

**Comment by ErikEJ** [comment]
Maybe you could share a CREATE and INSERT script, that reproduces the issue?

**Comment by ErikEJ** [comment]
I have added the Report Viewer installer to the tools folder in this repo

**Comment by ErikEJ** [comment]
I have tested via Report Viewer => .xls => .csv - works as expected.

**Comment by fifonik** [comment]
Confirming that export through Excel using Report Viewer works.
Thanks.
