### ISSUE TITLE
Stuck on installing into SSMS

### ISSUE THREAD

**Issue by bizinbarefeet** [ErikEJ/SqlCeToolbox#895]
Am trying to install SSMS with SQLCEToolbox for the first time (toolbox works fine in VS).  Am not a SSMS user.

Am following instructions here https://github.com/ErikEJ/SqlCeToolbox

Environment:
VS Community 16.9.3
SSMS 18.8 / SQL Server Management Studio 15.0.18369.0

ERROR: "Could not load ....Immutable.10..."

How do I do basic install???

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

SQL Compact 4

Microsoft Visual Studio Community 2019 Version 16.9.3

SSMS 18.8 / SQL Server Management Studio 15.0.18369.0

**Comment by ErikEJ** [comment]
You should follow the readme guide.

And maybe share the full error message!

Why do you need it in SSMS if it works for you in VS?

**Comment by bizinbarefeet** [comment]
> You should follow the readme guide.

Not sure what you mean here.  I've following the guide with latest daily build, manual install, etc.

> And maybe share the full error message!

Full Message: 
"Could not load file or assembly 'Microsoft.VisualStudio.Shell.Immutable.10.0, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependences.  The system cannot find the file specified.

> Why do you need it in SSMS if it works for you in VS?

So we can migrate them to Azure SQL.

**Comment by ErikEJ** [comment]
Depending on what exactly you mean by "migrate them (??) to Azure SQL" you should be able to do that in VS.

Basically extensions are not really supported in SSMS...

**Comment by bizinbarefeet** [comment]
OK.  I'll leave it.  Thanks for your VS tools too.
