### ISSUE TITLE
SQLMetal

### ISSUE THREAD

**Issue by eabtool** [ErikEJ/SqlCeToolbox#901]
Sorry to disturb you again. 

  When i right click on the database name and select 'Generate Code', 'Add LINQ to SQL DataContext.." i get the error Could not find SQLMetal file location.

  I downloads the latest Windows 10 SDK.  I added the path C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools.  I can see the program and even run it.  How do i get the toolkit to see/run the program ?

  I am using Visual Studio 2019 16.9.6

Thanks.

**Comment by ErikEJ** [comment]
There is some old code to locate the tool that probably needs to be updated...

But why do you use LINQ to SQL and not EF Core?

**Comment by ErikEJ** [comment]
This probably needs to be updated: https://github.com/ErikEJ/SqlCeToolbox/blob/master/src/GUI/SqlCe35Toolbox/Commands/SqlCeDatabaseMenuCommandsHandler.cs#L548

**Comment by eabtool** [comment]
I have always used that.  I’ll investigate usin EF core.

Thank you for you help.

On May 23, 2021, at 9:35 AM, Erik Ejlskov Jensen ***@***.***> wrote:

﻿

There is some old code to locate the tool that probably needs to be updated...

But why do you use LINQ to SQL and not EF Core?

**Comment by ErikEJ** [comment]
I will get that old code updated!

**Comment by ErikEJ** [comment]
Makes sense to use LINQ to SQL with SQL Compact.

**Comment by ErikEJ** [comment]
I have attempted a fix in the latest daily build

**Comment by ErikEJ** [comment]
@eabtool Did you try out the latest daily?

**Comment by eabtool** [comment]
Thank you.  It is working very well.

It is a great program,.

Thanks.

Alex
