### ISSUE TITLE
Could not load file or assembly 'System.Data.SQLite.dll' or one of its dependencies

### ISSUE THREAD

**Issue by eku1s** [ErikEJ/SqlCeToolbox#903]
After installing the latest version of the extension into Visual Studio 16.10.2, I receive the error:

'Could not load file or assembly 'System.Data.SQLite.dll' or one of its dependencies'

I have attempted to install this package into my project but this has no effect.

I also upgraded to Visual Studio 16.10.3 to no avail.

I have also uninstalled and reinstalled the plugin but this still does not work.

### Steps to reproduce
As above.

### Further technical details
Toolbox/Power Tools version: 4.7.691.0

Database engine: SQLite

Visual Studio or SSMS version: 16.10.2/16.10.3.

**Comment by ErikEJ** [comment]
Odd. Maybe try the latest daily? 4.8.728

**Comment by ErikEJ** [comment]
Ping?

**Comment by eku1s** [comment]
Thanks Erik, I installed the latest daily and this seemed to resolve the issue. The one I downloaded was from the Visual Studio Marketplace. When will this be updated with the latest version? This may help others avoid the issue.

**Comment by ErikEJ** [comment]
4.8.728 is already published to MarketPlace, but I have not heard any other users having this issue.
