### ISSUE TITLE
SQL Ce database size

### ISSUE THREAD

**Issue by ricl** [ErikEJ/SqlCeToolbox#905]
I have a 2.52 GB SQL Ce database but it reports  an error code of 80004005 saying the database size is too large.

How can I fix this?

![image](https://user-images.githubusercontent.com/7289122/126831345-97c299c7-4ce4-446d-8b68-19f99a20e1d5.png)

**Comment by ErikEJ** [comment]
Set the max database size connection string option to 4000?

**Comment by ErikEJ** [comment]
When you add the connection..

**Comment by ricl** [comment]
OK. Thanks
