### ISSUE TITLE
Can not connect to SQL server

### ISSUE THREAD

**Issue by Makeshet** [ErikEJ/SqlCeToolbox#910]
Hi Erik
You succeed to develop a great tool. 
I just install the new Version 4.8.735.0. Connecting to SQLite works just fine.
But I can not succeed to connect to my local SQL Server:
![image](https://user-images.githubusercontent.com/500151/132998069-0ebac7e8-4752-4230-bff5-c475edf00e1f.png)

When click on the "Add SQL Server connection" Icon I get form that tells me:
"Choose a database connection already connected in Server Explorer/Data connection"
and a combo box but with no items.

What I am missing here?
Eliezer Kaplansky PhD.
CTO
Makeshet Information Systems LTD.
___________________________________________

Version 4.8.735.0 - 1,881,285 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 Simple DDEX provider - No

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider used: 3.31.1
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - No

**Comment by ErikEJ** [comment]
Open Server Explorer window in VS, and add a SQL Server connection

**Comment by Makeshet** [comment]
Hi Erik
Your suggestion works for VS.
Thanks a lot.

Is it possible to connect to SQL Server with SSMS 18?
Eliezer

**Comment by ErikEJ** [comment]
I think so, connect a server in Object Explorer.

**Comment by Makeshet** [comment]
Hi Erik
Thanks for your answer.

My tests shows there is a link between the setting of VS 2019 to what happens on  SSMS 18.

I start with SSMS and can not make any SQL Server connection, even I have a server connected in  the SSMS object explorer
**as shown in the picture in my issue description**.,
With your advice I use VS 2019 and there the combo box have items and I can make the connection.  
I go back to SSMS 18 and the combo box is still empty, but using the "Add SQL Server connection" button I can connect to the database I connect in the VS 2019.
Any idea what goes worn here?

Eliezer

**Comment by ErikEJ** [comment]
Ping?
