### ISSUE TITLE
Encryption support missing

### ISSUE THREAD

**Issue by skydivider** [ErikEJ/SqlCeToolbox#911]
I have latest extension installed and Sqlite nuget package 1.0.114 together with bundle for design support (also 114 version)
Following #892 I tried to find  version 4.7.691.0 of this extension to enable encryption support , but with no success. The encryption support is vital for project I am currently working on. 

Does anyone has saved  version 4.7.691.0 of this extension?

As far as I can tell there is no repository of previous versions of this tollkit/extension

### Further technical details
Toolbox/Power Tools version: 4.8.735.0

Database engine: (SQlite 1.0.114)

Visual Studio or SSMS version: (Visual Studio 2017 15.9.39)

**Comment by ErikEJ** [comment]
Check the releases in this repo.

But you have to stop using this unsupported encryption!
