### ISSUE TITLE
Export2SqlCe fail with using with IIS

### ISSUE THREAD

**Issue by Cyril035** [ErikEJ/SqlCeToolbox#913]
Hi there,

I'm facing with a strange issue and I wasted so much time to understand without succes.

### Steps to reproduce
I'm using Export2SqlCe tool in c# wcf service hosted in IIS. The tool is launched by command line. When the process start, it create sql script but stop after a few second.
When the same args used and launched manually in a command prompt, the process terminate normally

Edit:
A begin of an answer:
The tool should generate about 1500 files. It fail at about 70 files. (many try, always same result). The server was 4Gb of RAM. We increase to 8GO and restart the process. It fails at about 550 files....
In the last generated file which is incomplete, the last line is truncated

it seems a memory pb...?

And no logs...
Can you help me please
Regards

**Comment by Cyril035** [comment]
Forget IIS, I have this trouble by launching the tool in cmd prompt. I clone the solution to see what happen witout success. The process stop randomly without any exception.

This tools works for me for a long time in desktop app without any trouble. For security reason (db access), I have to split it in client-service app to host all build process on a server side (wcf hosted in IIS)

Anyway, no exception occurs so quite difficult to debug.

**Comment by ErikEJ** [comment]
Virus scanner? Check the Windows event log?

**Comment by ErikEJ** [comment]
Do you have the SQL CE runtime installed on the machine?

**Comment by Cyril035** [comment]
nothing in windows event logs. I uninstall virus scanner too..
After a restart of the machine, it was better but after a few try, this issue still there...

**Comment by ErikEJ** [comment]
Check out the source and run a debugger?

**Comment by Cyril035** [comment]
This issue occurs on production server, and unfortunately I cannot reproduce it on different environnment. Maybe an environnemental bug...
Any way, I took the nuget scripting lib as you suggested. I found a bug on it as you can see on a PR that I push yesterday.

**Comment by ErikEJ** [comment]
Are you blocked on the PR, or do you just use the source code?

**Comment by Cyril035** [comment]
I 'll use the source code until the bug could be approved and release in a new version :)
