### ISSUE TITLE
SqlCeToolbox not shown in the SSMS toolbox

### ISSUE THREAD

**Issue by trisin** [ErikEJ/SqlCeToolbox#917]
Describe what is not working as expected.

I download the  SqlCeToolbox extension files（http://vsixgallery.com/extensions/d6c77c32-fe4b-4f6d-ad5d-f7b755212760/extension.vsix） for SSMS 18.9.2

i have manually "installed" it under the folder.
![image](https://user-images.githubusercontent.com/20191730/142382102-1228f0ae-e25b-4302-876b-ba013d5531a6.png)

but i can't find it in the toolbox of SSMS
![image](https://user-images.githubusercontent.com/20191730/142381915-0f75a8b0-808d-47b1-a068-c2aacf0c8b2d.png)

i don't know what went wrong.

**Comment by ErikEJ** [comment]
Have you looked under the "View" menu? (as documented here: https://github.com/ErikEJ/SqlCeToolbox#sql-server-management-studio-ssms-1718-extension )

**Comment by trisin** [comment]
![image](https://user-images.githubusercontent.com/20191730/142395096-26ede4a9-1813-4747-9d13-34aa7514e695.png)

**Comment by ErikEJ** [comment]
Top menu item in your screenshot!

**Comment by trisin** [comment]
i am a blind.  lol
