### ISSUE TITLE
SQL Lite - Database Information always returns -1 row for each table

### ISSUE THREAD

**Issue by acieslik** [ErikEJ/SqlCeToolbox#919]
When I open an SQL lite database and click on the "Database Information" option it will give this output.
But the numbers of rows for each table are not -1. There are actually records inside

-- Script Date: 12/3/2021 2:04 PM  - ErikEJ.SqlCeScripting version 3.5.2.90
-- Database information:
-- Database: C:\my.db
-- ServerVersion: 3.35.5
-- DatabaseSize: 816 KB
-- Created: 12/2/2021 1:38 PM

-- User Table information:
-- Number of tables: 19
-- __OBJECTSTORE: -1 row(s)
-- __VERSIONS: -1 row(s)
-- applicationmetadata: -1 row(s)
-- appModulesSyncInfo: -1 row(s)
-- attributemetadata: -1 row(s)
-- entitymetadata: -1 row(s)
-- entityrecord: -1 row(s)
-- lastCleanDateTime: -1 row(s)
-- list: -1 row(s)
-- metadataversionstamp: -1 row(s)
-- navigationdata: -1 row(s)
-- offlinedatabaseinformation: -1 row(s)
-- sessionstate: -1 row(s)
-- tempapplicationmetadata: -1 row(s)
-- tempattributemetadata: -1 row(s)
-- tempentitymetadata: -1 row(s)
-- tempmetadataversionstamp: -1 row(s)
-- usercontext: -1 row(s)
-- userpersonalization: -1 row(s)

### Steps to reproduce
See above

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.8.735.0 - 1,934,058 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - No
SQL Server Compact 3.5 DbProvider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider used: 3.31.1
SQLite EF6 DbProvider in GAC - No
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Database engine: SQlite

Visual Studio 2019

**Comment by ErikEJ** [comment]
Correct, I was able to do this without impact with SQL Server Compact, but not with SQLite
