### ISSUE TITLE
SQLite_and_SQL_Server_Compact_Toolbox_v4.8.735.vsix  for Microsoft Visual Studio Profesional 2013 Installation

### ISSUE THREAD

**Issue by pepegenio** [ErikEJ/SqlCeToolbox#920]
I have been using Microsoft Visual Studio Profesional 2013 with SQL Server Compact/SQLite toolbox version 4.1.0.0 for 5 or 6 years.

However I need it to use it a new computer, so I reinstalled Microsoft Visual Studio Profesional 2013.

I could not  find SQL Server Compact/SQLite toolbox version 4.1 because the link from http://sqlcetoolbox.codeplex.com is broken.

So I found the following from https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox:
 SQLite_and_SQL_Server_Compact_Toolbox_v4.8.735.vsix

But when I try to installed it, it gives me the following error log:

12/6/2021 11:12:05 AM - Microsoft VSIX Installer
12/6/2021 11:12:05 AM - -------------------------------------------
12/6/2021 11:12:10 AM - Initializing Install...
12/6/2021 11:12:10 AM - Extension Details...
12/6/2021 11:12:10 AM - 	Identifier      : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
12/6/2021 11:12:10 AM - 	Name            : SQLite and SQL Server Compact Toolbox
12/6/2021 11:12:10 AM - 	Author          : ErikEJ
12/6/2021 11:12:10 AM - 	Version         : 4.8.735
12/6/2021 11:12:10 AM - 	Description     : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
12/6/2021 11:12:10 AM - 	Locale          : en-US
12/6/2021 11:12:10 AM - 	MoreInfoURL     : https://github.com/ErikEJ/SqlCeToolbox
12/6/2021 11:12:10 AM - 	InstalledByMSI  : False
12/6/2021 11:12:10 AM - 	SupportedFrameworkVersionRange : [4.7.2,)
12/6/2021 11:12:10 AM - 
12/6/2021 11:12:10 AM - 	Supported Products : 
12/6/2021 11:12:10 AM - 		Microsoft.VisualStudio.Community
12/6/2021 11:12:10 AM - 			Version : [15.0,17.0)
12/6/2021 11:12:10 AM - 		Microsoft.VisualStudio.Community
12/6/2021 11:12:10 AM - 			Version : [17.0,18.0)
12/6/2021 11:12:10 AM - 
12/6/2021 11:12:10 AM - 	References      : 
12/6/2021 11:12:10 AM - 
12/6/2021 11:12:10 AM - Searching for applicable products...
12/6/2021 11:12:11 AM - Found installed product - Microsoft Visual Studio Professional 2013
12/6/2021 11:12:11 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
12/6/2021 11:12:11 AM - Found installed product - Global Location
12/6/2021 11:12:11 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.InitializeInstall()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Does this means that SQLite_and_SQL_Server_Compact_Toolbox_v4.8.735.vsix does not longer work for Visual Studio Professional 2013?
If that is the case, is there any way to SQL Server Compact/SQLite toolbox version 4.1.0 for Visual Studio Professional 2013?

Thanks,

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
You can download the archived build for 2013 from here: https://github.com/ErikEJ/SqlCeToolbox/releases/tag/vs2012 - but why are you not able to n´move to VS 2022?

**Comment by pepegenio** [comment]
Thanks Erick. It Worked!.

    On Monday, December 6, 2021, 11:35:12 PM PST, Erik Ejlskov Jensen ***@***.***> wrote:  
 
 


You can download the archived build for 2013 from here: https://github.com/ErikEJ/SqlCeToolbox/releases/tag/vs2012 - but why are you not able to n´move to VS 2022?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
