### ISSUE TITLE
Download link to 

### ISSUE THREAD

**Issue by Fruchtzwerg94** [ErikEJ/SqlCeToolbox#922]
The [wiki](https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider) describes:

> Once per machine. Download the latest sqlite-netFx46-setup-bundle-x86-2015-1.0.xxx.0.exe (from https://system.data.sqlite.org/index.html/doc/trunk/www/downloads.wiki)

The link does not support installers anymore. Instead, [this link](https://system.data.sqlite.org/index.html/doc/trunk/www/downloads-unsup.wiki) can be used.

**Comment by ErikEJ** [comment]
Thanks I will get the link updated

**Comment by ErikEJ** [comment]
Updated, thanks
