### ISSUE TITLE
I just installed the SqlCEToolbox but no script menus

### ISSUE THREAD

**Issue by soba-noodle** [ErikEJ/SqlCeToolbox#923]
Data Connections Context Menu does not show Script menus at all as you can see the attached image.   I need Export from SQL Server to SQL Server Compact database or I need to run SQL Server script created on SQL server to executed on CE. 

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Installed the vsix v4.8.735 on both VS 2017 and VS 2019.  

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
4.8.735

Database engine: (SQlite, SQL Compact or SQL Server)
SQL Compact 4.0 Sp1, SQL Server 14.0.3370.1

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Visual Studio 2019 16.11.5

![NoScriptMenus](https://user-images.githubusercontent.com/53722946/148010732-bc546ab5-3515-4fc4-b253-32abfa2e7c72.png)

**Comment by ErikEJ** [comment]
I think you just need to add a SQL Server Connection

**Comment by soba-noodle** [comment]
Strange.   I have the server Explorer showing the following:
![image](https://user-images.githubusercontent.com/53722946/148160169-9d8b58bd-becd-4262-90fd-9cc7ec02eabd.png)
and SQK Server Compact toolbox as
![image](https://user-images.githubusercontent.com/53722946/148160208-d9c8972d-1d01-4826-839f-85a04e77b2d2.png)
Still does not have script menus.
![image](https://user-images.githubusercontent.com/53722946/148160272-d50af1f5-32e5-4620-adc4-d48dc23fcd44.png)

**Comment by ErikEJ** [comment]
Right click the Server entry!
