### ISSUE TITLE
Connection error in Server Explorer

### ISSUE THREAD

**Issue by MrM40** [ErikEJ/SqlCeToolbox#925]
What am I missing?
![error](https://user-images.githubusercontent.com/16258063/152991358-0c96e774-036d-455e-944b-9364d5a2bacb.jpg)

Another thing, the button "Test Connection" will also show "Test connection succeeded" no matter what you write in the connection string

**Comment by MrM40** [comment]
I thought you could use the native Visual Studio Server Explorer?

The explorer from the Toolbox works:
![pic1](https://user-images.githubusercontent.com/16258063/152992580-62979b2b-09ef-4764-9a16-7ef24b60344c.jpg)
![pic2](https://user-images.githubusercontent.com/16258063/152992597-40baf086-1491-4a4d-a6c4-964be3b3af67.jpg)

**Comment by MrM40** [comment]
Where do I find the guide for 2022?

**Comment by ErikEJ** [comment]
The connections in the Toolbox are only partially releated to Server Explorer connections!

[This guide](https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider)

**Comment by MrM40** [comment]
That guide is not easy to find. I did look at the wiki but it never came to my mind that I should look at something called "DDEX" or "EF6" for that matter. But now I know :-)

**Comment by ErikEJ** [comment]
what would have been a good title given the content?

**Comment by MrM40** [comment]
Anything with "Visual Studio x64 support" and/or "Visual Studio 2022" that whould have caught my attention.

**Comment by ErikEJ** [comment]
OK, I have made some updates to this issue: https://github.com/ErikEJ/SqlCeToolbox/issues/924

**Comment by ErikEJ** [comment]
Duplicate of #924
