### ISSUE TITLE
Connection Error - duplicate value - unique index

### ISSUE THREAD

**Issue by tark3411** [ErikEJ/SqlCeToolbox#926]
### Describe what is not working as expected.
I cannot create a connection to SQL Server Compact 3.5 database

Error Dialog Box:
Error Code: 80004005
Message  : A duplicate value cannot be inserted into a unique index. [ Table name = Address,Constraint name = idxAddress]
Minor Err.: 25016
Source   : SQL Server Compact ADO.NET Data Provider
Err. Par. : Address
Err. Par. : idxAddress

### Steps to reproduce
1. Add SQL Server Compact 3.5 Connection
2. Browse and select .sdf file
3. Pop-up error displayed (see above)

### Further technical details
SQLite/SQL Server Compact Toolbox for Visual Studio Version: 4.8.735.0
SQL Server Compact: 3.5.8080.0
Microsoft Visual Studio 2017 Professional: 15.19.14

**Comment by ErikEJ** [comment]
Interesting. I think I need the database file if you want help - can you share - maybe privately?

**Comment by tark3411** [comment]
Unfortunately I can not share it due to its contents.  Can the contents of the tables be exported to .csv files without a connection?  Can the .sdf file be manually edited, via text editor, to remove the constraint or remove the duplicate(s)?  Any other suggestions?

**Comment by ErikEJ** [comment]
I would Ensure that the latest runtime is installed on my machine and then run Compact or repair againt a file copy using SqlCeCmd.

**Comment by tark3411** [comment]
I was able to repair the database with a C# application (repair command below) that I put together and the database is now queryable in the Compact Toolbox extension.  
``` .cs
mySqlCeEngine.Repair(null, RepairOption.DeleteCorruptedRows);
```
Thank you for your recommendations.

**Comment by ErikEJ** [comment]
You are welcome - SqlCeCmd tool could have done exsctly that for you, as I suggested.
