### ISSUE TITLE
Tool not working on my environment

### ISSUE THREAD

**Issue by carolijime** [ErikEJ/SqlCeToolbox#928]
Describe what is not working as expected.
I cannot make the tool work. 
I have an old SQL Compact connection in a VB Visual studio program (code made by someone else who already left the company)
I would like to be able to see the old DB and migrate it using the SQLite and SQL Server Compact Toolbox tool

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
- I have Windows 10 Pro (64-bit)
![image](https://user-images.githubusercontent.com/42026488/156656915-71494e7d-7987-47f4-8f0e-445cdcb96a2c.png)

- I have installed Microsoft® SQL Server® Compact 4.0 SP1 (64-bit) (https://www.microsoft.com/en-us/download/details.aspx?id=30709)
- I have also installed Microsoft SQL Server Compact 3.5 Service Pack 2 for Windows Desktop (the 32-bit and 64-bit installs)(https://www.microsoft.com/en-us/download/details.aspx?id=5783) the 32-bit and 64-bit (as recommended in the product' documentation) and I get the same result (tool not working)

![image](https://user-images.githubusercontent.com/42026488/156654616-d08a5705-f43a-4e82-96e4-dad7aa6b0040.png)

- I have installed "SQLite and SQL Server Compact Toolbox" tool using the Manage extension inside visual studio.

After installing all needed (as per my knowledge) programs, when trying to use the tool (SQLite and SQL Server Compact Toolbox) I get the 

![image](https://user-images.githubusercontent.com/42026488/156634878-971aa0a6-209e-40fa-a76d-668895a71a36.png)

It looks like the old database is a SQL Server Compact version 3.5 (image below of what it shows when using "Detect SQL Server Compact file version..." option, when clicking ok button I get an error message "
Could not load file or assembly 'Microsoft.ApplicationInsights, Version=2.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified."

![image](https://user-images.githubusercontent.com/42026488/156654134-b73486df-144a-4404-b29a-2923f81cba80.png)

![image](https://user-images.githubusercontent.com/42026488/156653901-8e9138da-6289-47fb-a0f0-f2ec2b935474.png)

![image](https://user-images.githubusercontent.com/42026488/156653936-c77b91ee-66af-4ee5-a07a-574f702a2ecc.png)

Getting below error message when trying "Add SQLite and SQL Compact connection from current solution" option

![image](https://user-images.githubusercontent.com/42026488/156654853-5907c418-050f-4fc6-be18-331079bd2945.png)

When trying the "Refresh", "Add SQLite connection", "Add SQL CE 4.0 Connection", "Add SQL Server Connection" or "Options" buttons, visual studio simply closes without visible error message

![image](https://user-images.githubusercontent.com/42026488/156656082-3a4b4c81-e82e-4660-9e1f-cbed9009ba21.png)

When Clicking "New Query" button, nothing happens

![image](https://user-images.githubusercontent.com/42026488/156656047-c1c7a180-6883-4c11-b39c-4928f90e569c.png)

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Sorry, no sure where should I find this

Database engine: (SQlite, SQL Compact or SQL Server)
Installed SQL Compact 4.0, SQL Compact 3.5 (as described above) 
Installed SQL Server Express 2019 LocalDB (installed as an individual component using Visual Studio Installer)

![image](https://user-images.githubusercontent.com/42026488/156656780-b706583f-fa6b-459d-b037-c740980db7a5.png)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

Visual Studio Community 2022

![image](https://user-images.githubusercontent.com/42026488/156656659-f445ec7b-87a7-4847-a7cf-92e32ca641a3.png)

Hope you can help me making this tool work because it is just what I need. Thanks

**Comment by ErikEJ** [comment]
Try to go to Tool/Options/SQLite Toolbox/Advanced and set participate in telemetry to false, then restart VS

**Comment by carolijime** [comment]
I did it (even restarting the computer after making the change) and still the same issue.

![image](https://user-images.githubusercontent.com/42026488/156819248-f5781807-795b-4bd8-8f13-292d952b8ebc.png)

**Comment by ErikEJ** [comment]
Try another computer?

**Comment by ErikEJ** [comment]
Or try removing and re-installing the extension?

**Comment by carolijime** [comment]
Hi @ErikEJ, thanks for your help and ideas. I was able to solve that issue. I had to install Microsoft.ApplicationInsights, Version=2.1.0.0 (then clean and rebuilt my solution). I am now able to see the SQL Server Compact 3.5 database (instead of the error message). 

But now, when trying to see the tables, I get the below sharing violation error message. I have tried to fix it (googled the error message) without success. By any chance, do you know what could be the issue?

![image](https://user-images.githubusercontent.com/42026488/157303167-b9db8be0-0ec0-4b9a-923a-df0164921aad.png)

Additionally, Does your toolbox automatically make the table adapters references?

![image](https://user-images.githubusercontent.com/42026488/157303420-793a6fcc-5b58-4dd0-83ea-01bb079f93d7.png)

For when the tool is working on my environment. I have tried to see the documentation about the tool (I would like to eventually migrate the Compact database to another database that is currently supported), but the videos on "How do I get started using the Toolbox?" page (https://github.com/ErikEJ/SqlCeToolbox/wiki) are not longer available, is there somewhere else where I could find documentation on how to use the toolbox?

**Comment by ErikEJ** [comment]
Accessing a SQL Compact file over the network is not supported. Copy it locally.

Table adapters are not supported. Use other means like EF or LINQ to SQL to access. 

I will try to restore the video links.

**Comment by ErikEJ** [comment]
https://walkingcat.github.io/ch9-index/index.html
