### ISSUE TITLE
Toolbox Crashing Visual Studio 2022 Community

### ISSUE THREAD

**Issue by errajeshsharma** [ErikEJ/SqlCeToolbox#930]
![Error](https://user-images.githubusercontent.com/101260470/157438448-6340ebc9-2764-4744-bb98-5dd91f2c4b90.jpg)
![VS Details](https://user-images.githubusercontent.com/101260470/157438468-43f54d07-2b93-4e36-9662-6c34c7e03ed1.jpg)

Describe what is not working as expected.
After VS 2022 Community update to Version 17.1.1.  Prior to update toolbox was working fine

### Steps to reproduce
When opening project and clicking on any toolbox option VS crashes

### Further technical details
Toolbox/Power Tools version: 4.8.740.0

Database engine: (SQL Compact 4.0)

Visual Studio or SSMS version: VS 2022 Community edition

**Comment by ErikEJ** [comment]
VS crashes or the Toolbox crashes?

**Comment by errajeshsharma** [comment]
Thanks for your response,
Visual Studio crashes when any of Toolbox option is clicked
#928 worked for me by installing Microsoft.ApplicationInsights Version=2.1.0.0. Latest version of Microsoft.ApplicationInsights 2.20.0 is not working.
So my concern is why after updating Visual Studio Toolbox is failing while it was working earlier

**Comment by ErikEJ** [comment]
>> worked for me by installing Microsoft.ApplicationInsights Version=2.1.0.0

Where did you install that? 

>> why after updating Visual Studio Toolbox is failing while it was working earlier

Sometimes things break when they are updated. I will see if I can reproduce and if I can provide a resolution.

**Comment by errajeshsharma** [comment]
> > > worked for me by installing Microsoft.ApplicationInsights Version=2.1.0.0
> 
> Where did you install that?
> 
> > > why after updating Visual Studio Toolbox is failing while it was working earlier
> 
> Sometimes things break when they are updated. I will see if I can reproduce and if I can provide a resolution.

I installed it into my Project solution from Nuget packages. So problem is I have to install Microsoft.ApplicationInsights Version=2.1.0.0 into every solution wherever I am using Toolbox. Prior to VS update no separate or exclusive installation of Microsoft.ApplicationInsights was required for those solutions wherever I have used SQL Server CE. After simple Toolbox installing , toolbox was working fine for every solution but VS update did something unusual

**Comment by ErikEJ** [comment]
>>  is I have to install Microsoft.ApplicationInsights Version=2.1.0.0 into every solution wherever I am using Toolbox

That should not be required at all. I will try to repro, and provide some sort of fix.

**Comment by errajeshsharma** [comment]
> > > is I have to install Microsoft.ApplicationInsights Version=2.1.0.0 into every solution wherever I am using Toolbox
> 
> That should not be required at all. I will try to repro, and provide some sort of fix.

Thank you, it would be really helpful

**Comment by ErikEJ** [comment]
I have tried updating App Insights lib in the latest daily. Please give it a try.

If that does not work, I will try to remove usage of it in the next daily build.

**Comment by errajeshsharma** [comment]
> I have tried updating App Insights lib in the latest daily. Please give it a try.
> 
> If that does not work, I will try to remove usage of it in the next daily build.

I am new user if you can guide me how to give try on daily

**Comment by ErikEJ** [comment]
Sure: https://github.com/ErikEJ/SqlCeToolbox#visual-studio-extension

**Comment by errajeshsharma** [comment]
Thanks a lot,
Toolbox V4.8.742 is working fine after installation without any extra fix
