### ISSUE TITLE
SQL CE 4.0 load error Could load file or assemble Microsft.Application

### ISSUE THREAD

**Issue by kwcoffee1** [ErikEJ/SqlCeToolbox#931]
Describe what is not working as expected.
The connection page does not show the connected databases for SQL CE 4.0 files.
It shows the error: Could load file or assembly Microsft.Application.

### Steps to reproduce
Occurs when attempting to open the extention.

### Further technical details
Latest download of SQLlite/SQL Compact or SQL Server)

Visual Studio or version: (Visual Studio 2022 17.1.1)
OS: Windows 11

**Comment by ErikEJ** [comment]
Duplicate. Have you tried the latest daily build?

**Comment by ErikEJ** [comment]
Ping?

**Comment by kwcoffee1** [comment]
I do not know how to find the latest daily build.
My current version is the Nuget version: 4.8.735

Thank you.

**Comment by ErikEJ** [comment]
I is described [in the readme](https://github.com/ErikEJ/SqlCeToolbox#visual-studio-extension)

**Comment by kwcoffee1** [comment]
I am running the most current release.
I removed it and reinstalled it to no avail.
However, it is working in VS 2022 17.2.0 Prev 2.

A fix may be appending in a future release of VS 2022.

**Comment by ErikEJ** [comment]
Which version?

**Comment by kwcoffee1** [comment]
It failed in Visual Studio or version: 2022 17.1.1
It worked in Visual Studio or version: 2022 17.2.0 Prev 2, and perhaps also in the prior release

**Comment by ErikEJ** [comment]
Which version of the extension?

**Comment by kwcoffee1** [comment]
Extension version is: 4.8.735

**Comment by ErikEJ** [comment]
Why was this closed?

**Comment by kwcoffee1** [comment]
Sorry, I assumed it to be a Microsoft fix in version 17.2.0 since it is currently working in the preview release.

**Comment by ErikEJ** [comment]
You are not using the latest daily version  - it is .743 or later.

**Comment by kwcoffee1** [comment]
Thank you very much, that fixed the issue.

Sincerely,
King
