### ISSUE TITLE
Toolbox is not using FK names set in SQLite database

### ISSUE THREAD

**Issue by TheKrowi** [ErikEJ/SqlCeToolbox#932]
Database used is SQLite.

Take the following table and notice the named FK FK_GeneralSettings_CommandBitType.

```
CREATE TABLE "GeneralSettingsCommandBitTypes" (
	"GeneralSettingId"	INTEGER NOT NULL,
	"BitTypeId"	INTEGER NOT NULL,
	FOREIGN KEY("GeneralSettingId") REFERENCES "GeneralSetting"("Id"),
	CONSTRAINT "FK_GeneralSettings_CommandBitType" FOREIGN KEY("BitTypeId") REFERENCES "BitType"("Id"),
	PRIMARY KEY("GeneralSettingId","BitTypeId")
);

```

When refreshing the table or adding the connection again in the toolbox, auto generated FK names are used (see image).

![image](https://user-images.githubusercontent.com/22818581/161042527-4e6074df-c869-491d-8415-c53f633c7213.png)

I would expect the toolbox to use the FK name instead of creating one itself.

**Comment by ErikEJ** [comment]
Please share a sample file

**Comment by TheKrowi** [comment]
[Drives.zip](https://github.com/ErikEJ/SqlCeToolbox/files/8388809/Drives.zip)

**Comment by ErikEJ** [comment]
No reliable way of extracting the names: https://stackoverflow.com/questions/41595152/how-to-get-the-names-of-foreign-key-constraints-in-sqlite
