### ISSUE TITLE
Error message instead of the list of connections

### ISSUE THREAD

**Issue by PeterAdam** [ErikEJ/SqlCeToolbox#934]
There is a red highlighted text in the SQLite/SQL Server Compact Toolbox after starting Visual Studio 2017 Community.
It says Due to high risk of deadlock you cannot call GetService from a background thread in an AsyncPackage derived class. You should ...

Right click -> add connections from solution makes all my connections to appear, not just from the current solution (including SSCE connections)

### Steps to reproduce
Start VS 2017 Community.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon): Version 4.8.743.0 - more than 900 000 downloads

Database engine: (SQlite, SQL Compact or SQL Server): SQLite

SQL Server Compact 4.0 in GAC - Yes - 4.0.8482.1
SQL Server Compact 4.0 DbProvider - Yes
SQL Server Compact 4.0 Simple DDEX provider - Yes
SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider - Yes
Sync Framework 2.1 SqlCe 3.5 provider - No
SQLite ADO.NET Provider used: 3.31.1
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3): 2017 Community 15.9.47

**Comment by ErikEJ** [comment]
Are you able to try VS 2022 Community?

**Comment by PeterAdam** [comment]
I have installed it to a VS 2022 Community on a W11 Insider Preview, the message is the same
![Képernyőkép 2022-04-21 221009](https://user-images.githubusercontent.com/8123097/164544883-83c7d2df-1ef2-4640-a631-94559c0e7ed2.png)

**Comment by ErikEJ** [comment]
It is not the same message.

Your SQL Compact install is broken- please remove and re-install.

**Comment by PeterAdam** [comment]
You are right. Do I have to install it? I would use Sqlite functionality only. SqlCE sadly out of support for more than a year.

Az Android Outlook<https://aka.ms/ghei36> letöltése

Üdvözlettel,
Ádám Péter
________________________________

**Comment by ErikEJ** [comment]
You can also just remove it.

But Toolbox breaks if you have a broken SQL CE install.

**Comment by PeterAdam** [comment]
I have installed SQLCE 4.0 but found out the problem was the missing 64 bit SQLCE 3.5 SP2:
![Névtelen](https://user-images.githubusercontent.com/8123097/164912238-a45cb018-01c1-4568-8e68-63df9c118d89.png)
![Képernyőkép 2022-04-23 165836](https://user-images.githubusercontent.com/8123097/164912242-ba233f12-624e-4ab2-b9fe-6468b6b13a95.png)

I don't know what installed the 32 bit SQLCE 3.5 SP2.

To answer the question, yes, the toolbox is working without error message on VS 2022 CE. I will try to open databases with it.

**Comment by ErikEJ** [comment]
Perfect!
