### ISSUE TITLE
VS 2022 Exception has been thrown by the target of an invocation

### ISSUE THREAD

**Issue by rmckay49** [ErikEJ/SqlCeToolbox#935]
Describe what is not working as expected.
When Visual Studio 2022 starts the error message 'Exception has been thrown by the target of an invocation' displays in the SQLite/SQL Server Compact Toolbox window.  I also have Visual Studio 2019 installed and the toolbox is operating normally.
### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.
Start Visual Studio 2022 and open the SQLite/SQL Server Compact Toolbox

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)
Version 4.8.743.0
Database engine: (SQlite, SQL Compact or SQL Server)
SQL Compact

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
Microsoft Visual Studio Community 2022 (64-bit) - Preview Version 17.2.0 Preview 6.

<img width="313" alt="2022-05-03 1
<img width="468" alt="2022-05-03 15_54_16-Microsoft Visual Studio Preview (Administrator)" src="https://user-images.githubusercontent.com/13072462/166574169-99ce98c1-ec42-41f6-99dc-c3f43baaf655.png">
5_56_16-" src="https://user-images.githubusercontent.com/13072462/166574162-9ac5dc1d-fb73-4e09-8397-21b15ed2f08c.png">
0

**Comment by rmckay49** [comment]
ErikEJ, Thanks.  I'll reinstall and let you know.  Some additional information is that left clicking on the refresh arrow loads the connected databases.  I hadn't tried tht before.

**Comment by ErikEJ** [comment]
I was able to repro with 17.3 - please try the latest daily build
