### ISSUE TITLE
'SQL logic error no such table: TEMP.SCHEMATABLES'

### ISSUE THREAD

**Issue by iVoteSize** [ErikEJ/SqlCeToolbox#936]
i had a bumpy update to my vs2022 and now this when trying to update model from db:

An error occurred while connecting to the database. The database might be unavailable. An exception of type "System.Data.Entity.Core.EntityCommandExecutionException" occurred. The error message is: "An error occurred while executing the command definition. See the inner exception for details.
The inner exception caught was of type 'System.Data.SQLite.SQLiteException', with this error message:
'SQL logic error no such table: TEMP.SCHEMATABLES'.'.

extension info:

Version 4.8.743.0 - more than 900,000 downloads

SQL Server Compact 4.0 in GAC - Yes - 4.0.8876.1
SQL Server Compact 4.0 DbProvider - No
SQL Server Compact 4.0 Simple DDEX provider - Yes

SQL Server Compact 3.5 in GAC - Yes - 3.5.8080.0
SQL Server Compact 3.5 DbProvider - No

Sync Framework 2.1 SqlCe 3.5 provider - No

SQLite ADO.NET Provider used: 3.31.1
SQLite EF6 DbProvider in GAC - Yes
System.Data.SQLite DDEX provider - No
SQLite Simple DDEX provider - Yes

vs info:

Microsoft Visual Studio Community 2022
Version 17.2.0
VisualStudio.17.Release/17.2.0+32505.173
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Community

ASP.NET and Web Tools 2019   17.2.388.21846
ASP.NET and Web Tools 2019

Auto Close Folders   1.0.2
A Visual Studio Extension that automatically closes a folder when no document in that folder is open.

Azure App Service Tools v3.0.0   17.2.388.21846
Azure App Service Tools v3.0.0

C# Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

CleanRun   1.5
CleanRun allows you to clean, build and run a project with 1 button

Close Tabs   1.0.8
Provides additional options to close tabs in the tab context menu, for instance to close all tabs to the right or left.

Code Cleanup On Save   1.0.12
Automatically run one of the Code Clean profiles when saving the document. This ensures your code is always formatted correctly and follows your coding style conventions.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Entity Framework Core Power Tools   2.5
Adds useful design-time EF Core DbContext features to the Visual Studio Solution Explorer context menu.

Menu Extension   1.0
Menu Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

PHP Tools for Visual Studio   1.64.15602.2022
PHP Tools extend Visual Studio with a set of features to build PHP applications more efficiently. It makes code more readable, easier to navigate, and clean.

Razor (ASP.NET Core)   17.0.0.2218101+885a343b00bcab620a90c1550c37dafd730ce984
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.0.62204.01010
Microsoft SQL Server Data Tools

SQLite & SQL Server Compact Toolbox   4.8
SQLite & SQL Server Compact Toolbox adds scripting, import, export, rename, query execution and much more to SQL Server Compact & SQLite Data Connections.

StylerPackage Extension   1.0
StylerPackage Visual Stuido Extension Detailed Info

Switch Startup Project   4.2.76
Provides a toolbar dropdown box  to switch between startup projects.

Syntax Visualizer   1.0
An extension for visualizing Roslyn SyntaxTrees.

TypeScript Tools   17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

VersionChanger Extension   1.0
VersionChanger Visual Studio Extension Detailed Info

Visual Basic Tools   4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

VSColorOutput64   2022.2
Color output for build and debug windows - https://mike-ward.net/vscoloroutput

Word Highlight With Margin Extension   1.0
Highlight all occurrences of a selected word and display carets on the enhanced vertical scrollbar at the right margin.

**Comment by ErikEJ** [comment]
This seems like a run time error and not related to SQLite Toolbox.

**Comment by iVoteSize** [comment]
update - 'reverting' (with professional edition as i can't find out how with community) to 17.1.7 fixed this issue.

**Comment by Flithor** [comment]
@ErikEJ 
I got same issue about this.
It happens after I update to VS 17.2.3.

Need a fix, not workaround(downgrade).

**Comment by ErikEJ** [comment]
@iVoteSize @Flithor As I said above, this has nothing at all to do with Sqlite Toolbox. But if one of you can provide a reproduction project and also let me know the exact version of System.Data.Sqlite in your 64 bit GAC, I will offer to take a closer look.
