### ISSUE TITLE
plugin error

### ISSUE THREAD

**Issue by luisarturoch** [ErikEJ/SqlCeToolbox#941]
The plugin is not up in VS 2017

Toolbox/Power Tools version: 4.8.756

Database engine: SQL Compact or SQL Server

Visual Studio or SSMS version: Visual Studio 2017 15.9.48
![image](https://user-images.githubusercontent.com/12836156/173446888-9dd92530-0694-4eed-935c-6439c9cf9dda.png)

**Comment by ErikEJ** [comment]
Could you try .755 pls? (From Marketplace)

**Comment by ErikEJ** [comment]
Maybe one of your Server Explorer connections are broken - try to remove them and then refresh

**Comment by luisarturoch** [comment]
When I try to remove broken connections it gives me the following error.

![image](https://user-images.githubusercontent.com/12836156/173618903-83a8ebbf-db1e-4945-b2f4-20e0c334fe89.png)

**Comment by ErikEJ** [comment]
I think I located a bug, please try the latest daily release, build .757 or later

**Comment by luisarturoch** [comment]
that version is not available (757)

**Comment by ErikEJ** [comment]
As a daily build, yes

**Comment by luisarturoch** [comment]
please send me the link

**Comment by ErikEJ** [comment]
Did you try changing the option as described above?

Link is in the readme.

**Comment by ErikEJ** [comment]
What made it work??

**Comment by luisarturoch** [comment]
install version 757 
![image](https://user-images.githubusercontent.com/12836156/173669769-7d5db705-d4ad-4c3b-a6a7-b6b9f699fee4.png)

**Comment by ErikEJ** [comment]
Thanks!
