### ISSUE TITLE
Add grouping to result grid

### ISSUE THREAD

**Issue by talley** [ErikEJ/SqlCeToolbox#944]
Add grouping columns to result grid

**Comment by talley** [comment]
![Screenshot 2022-08-20 110852](https://user-images.githubusercontent.com/6354720/185753431-3b1a7172-5424-4ebe-967f-fbfaeeef251e.jpg)

Sample below. I grouped the record by CustomerID

**Comment by ErikEJ** [comment]
You can already do it with the advanced grid.

**Comment by ErikEJ** [comment]
![image](https://user-images.githubusercontent.com/4169187/185803563-0f7fe119-2212-4104-82b7-d6e058bb1b7f.png)
