### ISSUE TITLE
Missing "View Top 1000 Rows"

### ISSUE THREAD

**Issue by SchreinerK** [ErikEJ/SqlCeToolbox#946]
How can I show data without to write a new query each time?

 A context menu entry "View Top 1000 Rows" could easily solve this problem by generating a new query automatically.

_BTW "View Data as Report" seems not to work. Microsoft Report Viewer 2010 ist not installed and I don't want to install it._

**Comment by ErikEJ** [comment]
@SchreinerK The "Edit Top x rows" shows the data immediately

>>  "View Data as Report" seems not to work. 

I cannot help you if you dont want it to work....

**Comment by SchreinerK** [comment]
> I cannot help you if you dont want it to work....

That's not what I'm talking about. I just don't want to have to install an may be outdated tool from 2010. From which I also do not know where exactly I get the right version. A link would be helpful.

**Comment by ErikEJ** [comment]
I have added a link to download to this page: https://github.com/ErikEJ/SqlCeToolbox/wiki
