### ISSUE TITLE
Questions about Visual Basic

### ISSUE THREAD

**Issue by TonyScarpelli** [ErikEJ/SqlCeToolbox#947]
I have a Visual Studio 2022 Visual Basic project, with a fully operational SQLite database already included.

When I clicked on "Generate Code", "Add sqlite-net DataAccess.cs to current Project..." it generated a C# file. I tried to convert it to Visual Basic but got too many errors.

It would be nice to have this done in Visual Basic for all of us who still use it.

One of the reasions I tried this was to get the path to the SQLite file. 
However this code didn't display the path to the file:

       string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }
 
Is this the wrong use of the DataAccess.cs file and the code above? To get the path?

I thought it would produce something like this:
Public dbPath As String = "C:\Users\Tony\Documents\Visual Studio 2022\My App\Data\MyData.db"

This doesn't appear to work, so I have to have the path to the data wherever it is installed:
Public dbName As String = "MyData.db"
Public dbPath As String = Application.StartupPath & "\" & dbName

Any ideas about any of this?
Thanks

Tony Scarpelli
tonyATS@maine.rr.com

**Comment by ErikEJ** [comment]
>> It would be nice to have this done in Visual Basic for all of us who still use it.

This is not something I plan to do. You could add just that file to a C# class library in you project, and use it from VB.

The full path you should be able to get with Path.GetFullPath() method.
