### ISSUE TITLE
Compact Toolbox Icon Does Nothing

### ISSUE THREAD

**Issue by PatrickRyder** [ErikEJ/SqlCeToolbox#949]
I have installed the Compact Toolbox. The installation appears to be successful and the icon appears in the menu (see screenshot) but clicking it does nothing.

### Steps to reproduce
1. Install the Compact Toolbox into VS2019.
2. Click icon in Tools menu.
3. Observe nothing happens; no error, nothing.

### Further technical details
I cannot see this anywhere.

Database engine: SQLite V3

Visual Studio version: 2019 4.8.04084

![VS Screenshot](https://user-images.githubusercontent.com/13526323/198260915-ce3c5e76-3a23-4d08-b64c-25b7063d30ed.png)

**Comment by ErikEJ** [comment]
Are you running the latest VS 2019 Update?

**Comment by ErikEJ** [comment]
Have you tried a VS repair? 

Ping?

**Comment by PatrickRyder** [comment]
Hi Eric,

Sorry for the delay getting back to you. Been away from my PC for a few days.

I have just tried uninstalling the extension, repairing VS and reinstalling. It does exactly the same thing - a click on the menu item shows a brief busy indicator but then nothing else that I can see anywhere.

I was using this extension about a year ago in the same installation of VS. I noticed it had vanished from my installed extensions the other day. That's when I tried the re-install that led to the current problem.

Kind wishes - Patrick



________________________________

**Comment by ErikEJ** [comment]
Have you tried on another PC?

Can you share your VS activity log?

Are you running the latest VS 2019 update?

**Comment by PatrickRyder** [comment]
Hi, Eric,

Unfortunately, I don't have the facility to try this on a different PC.

I am running the latest version and the Installer reports it is up-to-date.

I have attached an ActivityLog.xml collected while I tried to open the SQLite Toolbox.

Kind wishes - Patrick

________________________________

**Comment by ErikEJ** [comment]
Please upload logs to GiHub, do not attach as emails.

Could you use VS 2022?

**Comment by ErikEJ** [comment]
Which Windows and .NET Framework version (must be .NET 4.7.2 or later) ?

**Comment by ErikEJ** [comment]
Closing as the requested info was not provided.

**Comment by PatrickRyder** [comment]
Sorry, Eric - been away from my computer because of ill-health.

Not sure if you will receive this now it has been closed but I am on the latest Windows update (21H2) and the .NET version is 4.8.

Kind wishes - Patrick


________________________________

**Comment by ErikEJ** [comment]
Never got the activity log...

**Comment by PatrickRyder** [comment]
Hi, Eric,

That's strange, as it is still showing as an attachment in the history of this email. I will attach it again to this email.

I'm probably going to move to VS2022 soon so this whole problem might just go away.

Kind wishes - Patrick
________________________________

**Comment by ErikEJ** [comment]
You cannot send email attachement, you must use the GitHub issue tracker.. https://github.com/ErikEJ/SqlCeToolbox/issues/949

**Comment by PatrickRyder** [comment]
Sorry, didn't know that. Here is the activity log when I tried to open the newly installed toolbox.

Kind wishes - Patrick
[ActivityLog.zip](https://github.com/ErikEJ/SqlCeToolbox/files/9969970/ActivityLog.zip)

**Comment by ErikEJ** [comment]
There is nothing of interest in that activity log.

I am running out of ideas: Have you tried running a VS repair?

**Comment by PatrickRyder** [comment]
I have tried a repair. Don’t worry about it, Eric - as I said, I am about to install VS2022.


  *   Patrick

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
