### ISSUE TITLE
NullReferenceException on creating new SQLite connection

### ISSUE THREAD

**Issue by vasiliy-a-kuznetsov** [ErikEJ/SqlCeToolbox#951]
Describe what is not working as expected.

### Steps to reproduce
Right-click "Data Connections" and select "Add SQLite connection..." option. Error dialog is shown with NullReferenceException. Dialog content is attached.
![22-01-2023 01-22-21](https://user-images.githubusercontent.com/795520/213885856-955e905e-80d2-4ec5-b4f5-0e44485abe29.png)
 

### Further technical details
Toolbox/Power Tools version: Toolbox v4.8.761.0
Further details attached 
![22-01-2023 01-26-12](https://user-images.githubusercontent.com/795520/213885896-87d0270a-4d3c-46c5-8f0b-b1b40f25f977.png)

Database engine: SQlite

Visual Studio or SSMS version: VS 2022 (17.4.4)

**Comment by ErikEJ** [comment]
This looks like a WPF issue, make sure .NET Framework is up to date, and try to go to options and disable: "Autmoatically adjust client experience..."

**Comment by vasiliy-a-kuznetsov** [comment]
Thanks for the quick follow-up.
The issue was solved by itself after a reboot of the PC, so I'm happy; anyhow, decided to let you know about it in case you want to add another `isnull` just in case.

**Comment by ErikEJ** [comment]
Where would I add an is null ?? The error does not happen in my code.
