### ISSUE TITLE
SqlCeToolbox not detecting System.Data.SQLite in GAC

### ISSUE THREAD

**Issue by AndrewMaddock4** [ErikEJ/SqlCeToolbox#952]
Hi all,
After trying to follow the guide to get SQLite working with VS2022, I found that the toolbox would not detect SQlite in the GAC no matter what I've tried. 
After following all steps, I opened the Developer Command Prompt and ran `gacutil -l`, which showed that `System.Data.SQLite`, `System.Data.SQLite.EF6`, and `System.Data.SQLite.Linq` were all present.

Have tried all the suggestions I could find.

Currently trying to have this work on .NET Framework 4.8

**Comment by ErikEJ** [comment]
And you have carefully followed the guide here?.
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider

**Comment by AndrewMaddock4** [comment]
After giving up on using 2022, and going back to 2019, all is working fine. 

Sorry for the inconvenience.

**Comment by eziyoo** [comment]
It worked for me when i changed the version in machine.config from 1.0.116.0 to 1.0.117.0, which is the currently available version you can download from the link in the guide. Now it worked for me with VS2022.

**Comment by ErikEJ** [comment]
@eziyoo maybe I need to update the wiki post?

**Comment by eziyoo** [comment]
@ErikEJ my entry in the machine.config looks like this now:
```
    <system.data>
        <DbProviderFactories> 
            <add name="SQLite Data Provider" 
                invariant="System.Data.SQLite.EF6" 
                description=".NET Framework Data Provider for SQLite" 
                type="System.Data.SQLite.EF6.SQLiteProviderFactory, 
                        System.Data.SQLite.EF6, 
                        Version=**1.0.117.0**, 
                        Culture=neutral, 
                        PublicKeyToken=db937bc2d44ff139" 
            />  
        </DbProviderFactories> 
    </system.data>
```
I just changed the version to the one i downloaded https://system.data.sqlite.org/downloads/1.0.117.0/sqlite-netFx46-setup-bundle-x64-2015-**1.0.117.0**.exe

Maybe you could point that out in the wiki?

@AndrewMaddock4 maybe this works for you too?

**Comment by ErikEJ** [comment]
I will Update the docs and try to make the version match requirement clearer

**Comment by ErikEJ** [comment]
@eziyoo Docs updated, thanks!
