### ISSUE TITLE
Unable to export to SQL CE

### ISSUE THREAD

**Issue by alakifan** [ErikEJ/SqlCeToolbox#953]
This toolbox (ExportSqlCe35) exports .sdf files to SQLite just fine, but it's failing to do the opposite, it won't allow me to turn SQLite files to .sdf files

**Comment by ErikEJ** [comment]
Why would you want to do that? 

You could potentially export to SQL Server and then create an .sdf file form there.

**Comment by alakifan** [comment]
Good afternoon, thanks for your reply
I need to do this with commands and/or programatically as I need to send the .sdf file from an Android device to a backend that only takes these SQL CE files

**Comment by ErikEJ** [comment]
Ok. Did you try my suggestion?

**Comment by alakifan** [comment]
> Ok. Did you try my suggestion?

I have found ways to dump the contents of a sqlite database into a .sql file, but i'm yet to find a tool to export that .sql file to .sdf programatically and/or with commands

**Comment by ErikEJ** [comment]
Run that .sql script against a SQL Server database, and use my tools to export to a .sdf

**Comment by alakifan** [comment]
Sadly I **don't** have access to a SQL Server, as I can only access an API that takes a .sdf file as input. I can generate the .sql from the sqlite database file but can't find a way to export that .sql to a .sdf file.

(Apologies if I'm not being 100% clear, as English is not my mother tongue)

**Comment by ErikEJ** [comment]
You can use the Toolbox to run the generated .sql file against an empty SQL Compact database - but SQLite and SQL Compact are very different and you might have to do manual changes to the script.
