### ISSUE TITLE
Re: VS 2010 version 

### ISSUE THREAD

**Issue by AllisonAMG** [ErikEJ/SqlCeToolbox#954]
Could you let me have a copy of the VS2010 version please

kindest 
Allison

**Comment by ErikEJ** [comment]
Just curious: why do you need it?

**Comment by AllisonAMG** [comment]
Hi, 

 

I am developing in Visual Studio 2010, and was advised to use SqlLite, I then I came across your Toolset and decided I would investigate it.

 

Kindest 

Allison
