### ISSUE TITLE
WinSAT folder permissions required

### ISSUE THREAD

**Issue by pweigand** [ErikEJ/SqlCeToolbox#955]
Export from SQL CE to SQL Server is requiring access to users AppData\Local\Temp\WinSAT folder.

### Steps to reproduce
In SQLite/SQL Server Compact Toolbox right click a SQL CE database, and choose "Migrate to SQL Server". Choose target - SQL Server express 2022 instance with an empty new database.

### Further technical details
Screenshot of the error and a quick workaround:
![2023-03-01 07_55_40- (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/2356450/222067587-d3762393-8ed0-4a86-a99b-96d6a5fd7122.png)

Database engine: SQLLite 4.0 SP1, SQL Server 2022 Express (16.0.1050.5)

Visual Studio or SSMS version: Visual Studio 2022 17.5

Current workaround:
Gave permissions to everyone to folder AppData\Local\Temp\WinSAT

**Comment by ErikEJ** [comment]
Which Windows version - do you know what WinSAT is?

**Comment by ErikEJ** [comment]
I tried to implement a fix for this in the latest daily build, would be grateful if you could try it out.
