### ISSUE TITLE
A question about working with a journal file

### ISSUE THREAD

**Issue by DavidMales** [ErikEJ/SqlCeToolbox#956]
I would like to ask you about working with a journal file. We have an application that infrequently stops working and creates a journal file. 

### Steps to reproduce
Connected to a .db3 file which also have a journal file. When I connect to the .db3 file the journal file disappears, - can you tell me why and if I can reproduce the same programmatically in our app. ?

### Further technical details
Toolbox/Power Tools version: 4.8

VS2022 17.4.4
SQLite version 
sqlite_version()
3.38.5.1

Many thanks
David

**Comment by ErikEJ** [comment]
I am using System.data.Sqlite, so it must be a feature of that driver.

**Comment by ErikEJ** [comment]
https://github.com/dotnet/efcore/issues/14059
