### ISSUE TITLE
Information on visual Studio extension, designer auto generated code

### ISSUE THREAD

**Issue by 1dunnj** [ErikEJ/SqlCeToolbox#959]
In visual studio 2019, VB.Net (.Net Framework 4.x) when creating new DataSet and adding a table adapter through the dataset designer, I can create an appropriate .Fill() method and GetData() method from a "Select * from Tablename" command.
I cannot get EF6 designer to automatically generate Insert Update Delete methods.
If I use syntax like "Select * From Table WHERE ID = '@IdVariable' " to create a FillyByID() method, the autogenerated code does not take any parameters whereby to pass in IdVariable.
These features were usable in 2010 and 2013 from the main sqlite libraries.
Is this a limitation of the extension, or is there specific entity packages that I need to have included?
Thank you.

**Comment by ErikEJ** [comment]
Did you read this: https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider ?
