### ISSUE TITLE
VS 2022 dataset specified Type not supported

### ISSUE THREAD

**Issue by lcslouis** [ErikEJ/SqlCeToolbox#960]
I go to add a new dataset
Set the provider to your provider 
Give it the sqlite database name and location. 

Get Error occurred while retrieving the information from the database. 

The specified type is not supported by this selector. 

Database is SQLite3. 
The toolbox sees it and I can edit and run queries.

**Comment by ErikEJ** [comment]
Yu have to install and use the System.data.SQLite provider, mine is not full featured enough to support typed dataset design.
