### ISSUE TITLE
The specified type is not supported by this selector

### ISSUE THREAD

**Issue by drn57** [ErikEJ/SqlCeToolbox#961]
Hi,
I'm using Visual Studio 2022 to realize simple application for CRUD an sql compact database. I realized a database with 3 table and several fields inside. 
This is the database information.

-- Script Date: 17/05/2023 15:14  - ErikEJ.SqlCeScripting version 3.5.2.94
-- Database information:
-- Locale Identifier: 1040
-- Encryption Mode: 
-- Case Sensitive: False
-- Database: C:\Users\John\Desktop\Bart\bartDb.sdf
-- ServerVersion: 4.0.8876.1
-- DatabaseSize: 128 KB
-- SpaceAvailable: 3,999 GB
-- Created: 17/05/2023 10:48

-- User Table information:
-- Number of tables: 3
-- mixed: 0 row(s)
-- proof: 0 row(s)
-- testet: 0 row(s)

Database is connected but when I place a datagridview on the form the procedure to connect the data source after few steps ends as following..

![imm](https://github.com/ErikEJ/SqlCeToolbox/assets/133880325/8702e70c-e51c-4a73-8074-45bef81ea224)

Any suggestion?
Thanks a lot.
Robin

**Comment by ErikEJ** [comment]
This usage is not supported with the "Simple" provider - you will have to use a code based approach with ObjectDataSource.

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/4169187/eb1b4611-6424-40bb-8db7-ea78e7dd55ae)

**Comment by drn57** [comment]
Hi..
yes you are right... my mistake.
many thanks

*Cordiali Saluti / Kindest Regards*
*Adriano Fusi*



Il giorno gio 18 mag 2023 alle ore 09:29 Erik Ejlskov Jensen <
***@***.***> ha scritto:
