### ISSUE TITLE
Dark toolbar in VS 2022?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [ErikEJ/SqlCeToolbox#962]
Is there a way to set the toolbar to match the rest of the dark theme? Right now it's the only thing in my entire VS that isn't dark, including other extensions, and stands out like a reflector with a flashlight pointed at it. :D 

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/39491297/388a0aa9-9638-4b47-bfb9-5c9d019caf32)

**Comment by ErikEJ** [comment]
To be frank, I have made some failed attempts to implement this, but a PR to fix it would be great 😉

**Comment by YouveGotMeowxy** [comment]
I've never even tried creating an extension, so I'm afraid I'm of no help here. :(

**Comment by ErikEJ** [comment]
Or course  - highly appreciated

**Comment by ErikEJ** [comment]
@isascarc Any plans to submit a PR?
