### ISSUE TITLE
Connection error in Server Explorer in Visual Studio 2022 w/SQLite 1.0.118.0

### ISSUE THREAD

**Issue by davecove** [ErikEJ/SqlCeToolbox#963]
I have the _exact_ same issue as described in Issue #925, except that I am using SQLite 1.0.118.0 

I have followed all of the extra VS2022 notes in the _EF6 workflow with SQLite DDEX provider_ guide. One thing I noticed is that in the installer for 1.0.118.0 the dialog that offers the option to install the assemblies into the GAC is no longer shown in either the Full or Custom installation paths.

What am I missing?

**C:\Windows\Microsoft.NET\Framework64\v4.0.30319\Config\machine.config**
    
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/5158064/8a595420-5db5-4c9a-8c6e-f9fe1a459239)

**packages.config**
      
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/5158064/ac7fb808-f2f1-4414-ba55-2b21d2a754de)

**app.config**
      
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/5158064/476b50e0-e4d3-4e53-aca7-726f8d41a102)

**Comment by ErikEJ** [comment]
Please share the error and the steps to get it and your VS version

**Comment by davecove** [comment]
Thank you for being so responsive!

The steps to reproduce are to follow the instructions in the EF6 workflow with SQLite DDEX provider guide.

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/5158064/56448ec0-df07-4dae-9a1d-14040e8d77b4)

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/5158064/10d7aa6c-931c-4290-b746-f1cb6f29eb15)

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/5158064/ce655ae9-d32b-4baf-a216-1f091b766071)

**Comment by ErikEJ** [comment]
Looks like you missed the step to ensure the EF6 DbProvider is in GAC...

**Comment by davecove** [comment]
I saw that it wasn't in there and followed the special VS2022 special instructions from the guide:

VS 2022 Copy the entry to the 64 bit machince.config located in C:\WINDOWS\Microsoft.NET\Framework64\v4.0.30319\Config
and
Some users report that adding this to app.config solves some runtime issues.

One thing I noticed is that in the installer for 1.0.118.0, the dialog that offers the option to install the assemblies into the GAC is no longer shown in either the Full or Custom installation paths. I could use gacutil if I knew what dlls to install to the GAC.

**Comment by ErikEJ** [comment]
Maybe the SQLite team broke VS 2022 completely then.

**Comment by ErikEJ** [comment]
Maybe consider installing VS 2019 Community instead of all this pain?

**Comment by davecove** [comment]
Yes : sqlite-netFx46-setup-bundle-x64-2015-1.0.118.0.exe

I went back to VS2019 and it is working after running the setup bundle... not ideal, but hey, it works.
