### ISSUE TITLE
SQL compact toolbox for use on windows ARM

### ISSUE THREAD

**Issue by manuel0011** [ErikEJ/SqlCeToolbox#968]
Hi, is there a version that works on windows 11 ARM version (x64) for use on Mac M2 Studio.
I use visual studio 2022 on parallels desktop.
I can't instal the compact toolbox 4.0 because it is x86 version I noticed.
Visual studio 2022 also does not let mee see the plugin when searching for it!

Is there a work around to still use your SQL compact tool on windows ARM?
Are there any other options or to programs for sql compact database programming?

best regards. 
Manuel.

**Comment by ErikEJ** [comment]
SQL Server Compact does not run on ARM. You must use an x64 system.

**Comment by manuel0011** [comment]
Ok, thank you for the fast reply Eric! I have to search for another solution then.
best regards, Manuel.

**Comment by ErikEJ** [comment]
Maybe consider SQLite?
