### ISSUE TITLE
Connection

### ISSUE THREAD

**Issue by hxhgxy** [ErikEJ/SqlCeToolbox#969]
I installed this tool via downloading in VS extensions. I can connect to SQLite database in the toolbox.

![SQLITE1](https://github.com/ErikEJ/SqlCeToolbox/assets/37101628/76abf618-4ee7-421a-b9fa-67721549a34e)
However, this is not correct according to your guide in Wiki. I tried to copy machine.config from Framework to Framework64 or copy "System.data" part only. it still doesn't work.

I tried to use database first to connect a database, it shows incorrectly:
![SQLITE](https://github.com/ErikEJ/SqlCeToolbox/assets/37101628/49925aeb-135b-46a7-b296-1925f096f392)

my environment:
windows 11 professional, 22H2, 22621.2134
VS 2022 professional

What I shall do?

Thanks!

**Comment by hxhgxy** [comment]
test connection is successful by clicking the test connection button. but there is an error "Cannot find .Net Framework Data Provider..." by clicking "OK" button.

**Comment by ErikEJ** [comment]
I following this guide does not work, I cannot suggest anything else.

**Comment by ErikEJ** [comment]
https://github.com/ErikEJ/SqlCeToolbox/wiki/EF6-workflow-with-SQLite-DDEX-provider
