### ISSUE TITLE
.NET Core version?

### ISSUE THREAD

**Issue by philipmat** [ErikEJ/SqlCeToolbox#970]
Are there any plans of moving to .NET Core, in particular for the command line tools?

I'd like to do some prototyping and incorporate this into our CI pipeline (Linux-based) and all our workflow has been .NET Core based for several versions now.

I know we could install Mono in a container and use it that way, but it feels it would be easier to contribute as well if the core library was Core- or Standard-based.

**Comment by ErikEJ** [comment]
I do now, makes a lot of sense.

**Comment by philipmat** [comment]
At a minimum it would be the scripting libraries - the `Sql*Scripting.dll` files.  
The command line tools would be great as well, since they're the most likely candidate to be executed on another platform

**Comment by ErikEJ** [comment]
@philipmat Assume you are aware that only SQlite is cross platform (not SQL Server Compact) ?

**Comment by philipmat** [comment]
Yes, I'm mostly interested in the SQL Server-to-SQLite conversion and that I can make it work on Linux.

To be fair SQL CE/Compact was EOL in 2021, so maybe it would be unrealistic to expect it to work with modern .NET (Core). 

The SQL Server component though, can move forward and it would be a great boon for those like myself who would want to extricate their larger MSSQL DB into a more manageable SQLite DB for integration tests and the like.

If that's outside the scope of this project, I fully understand.

**Comment by ErikEJ** [comment]
No, I think the most valuable part would be a .NET CLI to extract/port a SQL Server db to SQLite

**Comment by philipmat** [comment]
I'd be happy to pitch in and help, whether to start this process (I'll need some guidance on where to start and what parts need updating) or with ancillary work: testing, maybe setting up a CI pipeline to help validate the conversion?

**Comment by ErikEJ** [comment]
I have a feeling that it might be possible to simply create a .NET 6 Console app, include the relevant files and just build it. 

Then set up a pipeline to build a .NET global tool.

**Comment by ErikEJ** [comment]
Design proposal: Port of export2sqlce.exe to a .NET 6/8 global tool

- [ ] Tool name: ErikEJ.ExportMssql2Sqlite (command name: exportmssql2sqlite
- [ ] Only support sqlite export
- [ ] Investigate if System.Data.Sqlite runs on Linux, if not use Microsoft.Data.Sqlite
- [ ] Create github pipeline to build and test (using free SQL Azure?)
- [ ] Create readme.md
- [ ] Publish to NuGet

**Comment by alexey-leonovich** [comment]
> This is actually blocked for now, as System.Data.Sqlite does not run on Linux

What do you mean by that? My sample .NET 8.0 [console application](https://github.com/ErikEJ/SqlCeToolbox/files/14866156/ConsoleApp2.zip) referencing latest [System.Data.Sqlite 1.0.118](https://www.nuget.org/packages/System.Data.SQLite/) runs without any problem on WSL2 (Ubuntu 22.04.3 LTS).

**Comment by ErikEJ** [comment]
@alexey-leonovich Wow - did not realize that. Thanks - are you also interested in the SQL Server => sqlite migration feature?

**Comment by alexey-leonovich** [comment]
> Thanks - are you also interested in the SQL Server => sqlite migration feature?

Almost not interested (I'm a Windows user :)). Just accidently came here.

**Comment by bairog** [comment]
@ErikEJ could you please elaborate why this is not planned? Not enough time or there are technical difficulties?

**Comment by ErikEJ** [comment]
Not high priority, and only a single upvote, and too little value, and not something I feel like supporting.
