### ISSUE TITLE
ExportSqlCe40.exe Error Code: 80004005

### ISSUE THREAD

**Issue by tuccero9** [ErikEJ/SqlCeToolbox#971]
Hello,
I executed the tool ExportSqlCe40.exe to convert a database running on SQL Compact Edition version 4.0.8482.1 but i receive an error code 80004005 with message "_The database file is larger than the configured maximum database size. This setting takes effect on the first concurrent database connection only. [Required Max Database Size (in MB; 0 if unknown) = 0]_"

Do i need to set this "**Max Database Size**" somewhere?

This is the command that i executed:
`ExportSqlCe40.exe "Data Source=C:\ProgramData\Access Control Technology\ACT Enterprise\Database\ACTEnterprise.sdf" ACTEnterprise.sql`

I used "ExportSqlCE40.zip - SQL Compact 4.0 command line utility to generate a script with schema and data" release 3.5.2.
The server  is running on Windows Server 2016 Datacenter.

Database engine: SQL Compact Edition version 4.0.8482.1

Let me know if you need to share some additional information.

**Comment by ErikEJ** [comment]
Set the max database size in the connection string: https://learn.microsoft.com/en-us/previous-versions/sql/compact/sql-server-compact-4.0/ew0d66d7(v=vs.100)

**Comment by tuccero9** [comment]
Thank you Erik. 
Worked like a charm! 


Stavros Tseriotis 

Infrastructure and Operations Department Officer 
Technology and Data Management Division 


Gr. Afxentiou 8, 1096 Nicosia 
T: +357 22743281 
***@***.***

**Comment by ErikEJ** [comment]
@tuccero9 Cool. Can't believe there are still users of this tool! 😅
