### ISSUE TITLE
i need sqlite and sql server compact toolbox for visual studio 2015 update 3

### ISSUE THREAD

**Issue by AbdullahAtiq** [ErikEJ/SqlCeToolbox#972]
Describe what is not working as expected.

### Steps to reproduce
Include a complete description that I can redo to reproduce the issue.

### Further technical details
Toolbox/Power Tools version: (found in About dialog - blue questionmark icon)

Database engine: (SQlite, SQL Compact or SQL Server)

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)

**Comment by ErikEJ** [comment]
Why do you still use VS 2015??

But you can download from the releases here: https://github.com/ErikEJ/SqlCeToolbox/releases/tag/vs2012
