### ISSUE TITLE
i need sql compact server for visual studio 2015

### ISSUE THREAD

**Issue by AbdullahAtiq** [ErikEJ/SqlCeToolbox#973]
sir it's not working and i develop a hospital management system in 2016 and now i change some field so that's why i need sql compact server for visual studio 2015

**Comment by ErikEJ** [comment]
@AbdullahAtiq What does "not woking" mean? I pointed you to the download...

**Comment by AbdullahAtiq** [comment]
i don't know why it's not working on visual studio 2015... my work is stuck because sql server compact extension is not available

**Comment by AbdullahAtiq** [comment]
please help me and tell me how to run sql server compact 4 on visual studio 2015

**Comment by ErikEJ** [comment]
I am happy to help, please contact me by email and I will tell you my hourly rate.

**Comment by ErikEJ** [comment]
Or look at my sponsorship offer actually!
