### ISSUE TITLE
Would it be possible in the future to also read parquet files

### ISSUE THREAD

**Issue by euricocovas** [ErikEJ/SqlCeToolbox#975]
Hi

Congratulations on the great tool, using it for SQLite files, I am using Version 4.8.776.0 

I am using Windows and Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.8.3

Would be great to be able to read/sql query parquet files as well?

Thanks

Eurico

**Comment by ErikEJ** [comment]
It is not something I plan to do.

**Comment by ErikEJ** [comment]
Maybe DuckDB.NET could be used..
