### ISSUE TITLE
Error while try to connect to SQLite DB

### ISSUE THREAD

**Issue by EslamNemr** [ErikEJ/SqlCeToolbox#981]
<img width="581" alt="image" src="https://github.com/ErikEJ/SqlCeToolbox/assets/42042051/10399c36-6593-4d0f-a288-2220afcae4d4">

**Comment by ErikEJ** [comment]
Have you looked at the wiki? Maybe there is a version mismatch.

**Comment by EslamNemr** [comment]
Working now!
reinstall everything thanks.
