### ISSUE TITLE
ExportSqlCE40: Export SqlCe uniqueidentifier column data to SQLite as binary

### ISSUE THREAD

**Issue by alexey-leonovich** [ErikEJ/SqlCeToolbox#982]
Hello.
If I use the following command [to export](https://github.com/ErikEJ/SqlCeToolbox/wiki/Command-line-tools#command-line-samples-for-exportsqlce-exportsqlce40-and-exportsqlce31) my test [SqlCe database](https://github.com/ErikEJ/SqlCeToolbox/files/14867130/test.zip) to SQLite:

> ExportSQLCE40.exe "Data Source=test.sdf;" "test.sql" sqlite

it creates insert statement where uniqueidentifier column data is inserted as text (e. g. `'65c6b3fd-e487-464a-bf79-fb3cebe9c9bf'`).
Is it possible make it to create inserts as binary (e. g. `X'a8828ddfef224d36935a1c66ae86ebb3'`)?
I've tried `Data Source=entities.sdf;BinaryGUID=True;` but looks like your tool doesn't understand that:

> Error: System.ArgumentException: Keyword is not supported: "binaryguid".

Thank you.

**Comment by alexey-leonovich** [comment]
> interested in doing a PR?

I'm afraid I don't have enough skills to try to make these code changes(

**Comment by ErikEJ** [comment]
@alexey-leonovich Is your example above using the same guid value?

If not, could you provide an example that does?

**Comment by alexey-leonovich** [comment]
@ErikEJ sorry, missed your question somehow.
binary form `X'a8828ddfef224d36935a1c66ae86ebb3'` equals to text form `'DF8D82A8-22EF-364D-935A-1C66AE86EBB3'`

**Comment by ErikEJ** [comment]
How do you get from one to the other?

**Comment by ErikEJ** [comment]
Thanks, I will consider implementing an option to use this format

**Comment by ErikEJ** [comment]
@alexey-leonovich I have added a "binaryguid" option to Exportsqlce40, that you can get from here: https://github.com/ErikEJ/SqlCeToolbox/releases/tag/3.5.2
