### ISSUE TITLE
Scripting SQlite database with FTS5 error

### ISSUE THREAD

**Issue by alexey-leonovich** [ErikEJ/SqlCeToolbox#983]
When I open SQLite database with FTS5, select **Script Database** -> **Script Schema** and click **Script to Window** - I get an error:
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/157357768/0a466995-0960-4c2b-bf26-2d15431e0d81)
Toobox info:
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/157357768/5c40d914-220a-4a50-ae6d-7ae88ad54e35)
Other tools (e. g. SQLite Expert Personal) script same database without any problem.
### Steps to reproduce

1. Open database in a toolbox - [test.zip](https://github.com/ErikEJ/SqlCeToolbox/files/14974933/test.zip)
2. Select **Script Database** -> **Script Schema**
3. Click **Script to Window** button

### Further technical details
Toolbox/Power Tools version: SQLite & SQL Server Compact Toolbox extension 4.8.776

Database engine: SQLite

Visual Studio or SSMS version: Visual Studio 2022 17.9.6 Pro

**Comment by ErikEJ** [comment]
What is fts5 ?? Is it supported in Sqlite 3.40?

**Comment by ErikEJ** [comment]
I found this: https://sqlite.org/forum/info/4cf36abaf7011e76cbb73e07591d4a0cae6bcc9b7c2fe5e548f6fed02710e503

**Comment by ErikEJ** [comment]
@alexey-leonovich thoughts?

**Comment by ErikEJ** [comment]
```csharp
                var dllFullFileName = Path.Combine(path, "SQLite.Interop.dll");
                connection.Open();
                connection.EnableExtensions(true);
                connection.LoadExtension(dllFullFileName, "sqlite3_fts5_init");
```

**Comment by alexey-leonovich** [comment]
> I found this: https://sqlite.org/forum/info/4cf36abaf7011e76cbb73e07591d4a0cae6bcc9b7c2fe5e548f6fed02710e503

> ```cs
>                 var dllFullFileName = Path.Combine(path, "SQLite.Interop.dll");
>                 connection.Open();
>                 connection.EnableExtensions(true);
>                 connection.LoadExtension(dllFullFileName, "sqlite3_fts5_init");
> ```

@ErikEJ sorry, again I've missed all github notifications somehow.
That code is correct. I'm working with fts5 SQLite database same way.

**Comment by ErikEJ** [comment]
@alexey-leonovich Thanks for conforming,  I hope to get around to implementing this one day.

**Comment by ErikEJ** [comment]
@alexey-leonovich I implemented a fix for this in the latest daily build, would be grateful if you could give it a try.

**Comment by alexey-leonovich** [comment]
@ErikEJ Thank you for you job.
I've tested latest daily build - now it generates a DDL script:
```
SELECT 1;
PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE [Streets_idx] (
  [segid]  NOT NULL
, [term]  NOT NULL
, [pgno]  NULL
, CONSTRAINT [sqlite_autoindex_Streets_idx_1] PRIMARY KEY ([segid],[term])
);
CREATE TABLE [Streets_docsize] (
  [id] bigint NOT NULL
, [sz] image NULL
, CONSTRAINT [sqlite_master_PK_Streets_docsize] PRIMARY KEY ([id])
);
CREATE TABLE [Streets_data] (
  [id] bigint NOT NULL
, [block] image NULL
, CONSTRAINT [sqlite_master_PK_Streets_data] PRIMARY KEY ([id])
);
CREATE TABLE [Streets_content] (
  [id] bigint NOT NULL
, [c0]  NULL
, [c1]  NULL
, CONSTRAINT [sqlite_master_PK_Streets_content] PRIMARY KEY ([id])
);
CREATE TABLE [Streets_config] (
  [k]  NOT NULL
, [v]  NULL
, CONSTRAINT [sqlite_autoindex_Streets_config_1] PRIMARY KEY ([k])
);
CREATE TABLE [Streets] (
  [Id]  NULL
, [Name]  NULL
);
COMMIT;
```
But it differs from DDL script that SQLite Expert Personal generates (it uses [FTS5 syntax](https://www.sqlite.org/fts5.html)):
```
CREATE VIRTUAL TABLE "Streets" using fts5 (
"Id" unindexed ,
"Name");

CREATE TABLE 'Streets_config'(k PRIMARY KEY, v) WITHOUT ROWID;

CREATE TABLE 'Streets_content'(id INTEGER PRIMARY KEY, c0, c1);

CREATE TABLE 'Streets_data'(id INTEGER PRIMARY KEY, block BLOB);

CREATE TABLE 'Streets_docsize'(id INTEGER PRIMARY KEY, sz BLOB);

CREATE TABLE 'Streets_idx'(segid, term, pgno, PRIMARY KEY(segid, term)) WITHOUT ROWID;
```
BTW. Latest version of System.Data.SQlite nuget [is 1.0.119](https://www.nuget.org/packages/System.Data.SQLite/1.0.119) (released about a month ago).

**Comment by ErikEJ** [comment]
@alexey-leonovich adding explicit support for fts5 is not high on my list, you are the only person asking for it in 9 years.

I have logged an issue to update to 1.0.119
