### ISSUE TITLE
SqlCeToolbox cannot be installed on my system

### ISSUE THREAD

**Issue by edgarsperling** [ErikEJ/SqlCeToolbox#984]
Hi,
SqlCeToolbox cannot be installed on my system
Microsoft Visual Studio Community 2022 (64-bit) Version 17.9.2
In the Logfile i get this:
24.05.2024 09:19:34 - Erweiterungsdetails...
24.05.2024 09:19:34 - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
24.05.2024 09:19:34 - 	Name               : SQLite and SQL Server Compact Toolbox
24.05.2024 09:19:34 - 	Author             : ErikEJ
24.05.2024 09:19:34 - 	Version            : 4.8.787
24.05.2024 09:19:34 - 	Description        : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
24.05.2024 09:19:34 - 	Locale             : en-US
24.05.2024 09:19:34 - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
24.05.2024 09:19:34 - 	InstalledByMSI     : False
24.05.2024 09:19:34 - 	SupportedFrameworkVersionRange : [4.7.2,)
24.05.2024 09:19:34 - 	SignatureState     : Unsigned
24.05.2024 09:19:34 - 	Unterstützte Produkte : 
24.05.2024 09:19:34 - 		Microsoft.VisualStudio.Community
24.05.2024 09:19:34 - 			Version : [15.0,17.0)
24.05.2024 09:19:34 - 			ProductArchitecture : x86
24.05.2024 09:19:34 - 		Microsoft.VisualStudio.Community
24.05.2024 09:19:34 - 			Version : [17.0,18.0)
24.05.2024 09:19:34 - 			ProductArchitecture : amd64
24.05.2024 09:19:34 - 	Verweise           : 
24.05.2024 09:19:34 - 	Voraussetzungen    : 
24.05.2024 09:19:34 - 		-------------------------------------------------------
24.05.2024 09:19:34 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
24.05.2024 09:19:34 - 		Name         : Visual Studio core editor
24.05.2024 09:19:34 - 		Version      : [15.0,)
24.05.2024 09:19:34 - 		-------------------------------------------------------
24.05.2024 09:19:34 - 		Identifier   : Microsoft.VisualStudio.Component.VisualStudioData
24.05.2024 09:19:34 - 		Name         : Data sources and service references
24.05.2024 09:19:34 - 		Version      : [15.0,)
24.05.2024 09:19:34 - 		-------------------------------------------------------
24.05.2024 09:19:34 - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
24.05.2024 09:19:34 - 		Name         : .NET desktop development tools
24.05.2024 09:19:34 - 		Version      : [15.0,)
24.05.2024 09:19:34 - Signaturdetails...
24.05.2024 09:19:34 - 	Extension is not signed.
24.05.2024 09:19:43 - Blocking processes:
24.05.2024 09:19:43 - InstallProgressPage ChangeType: 'SingleInstall' operationCount: '2' Text: 'SQLite and SQL Server Compact Toolbox wird installiert...'
24.05.2024 09:19:43 - Folgende Zielprodukte wurden ausgewählt...
24.05.2024 09:19:43 - 	Visual Studio Community 2022 Preview
24.05.2024 09:19:43 - Die Installation der Erweiterung für Visual Studio Community 2022 Preview wurde gestartet...
24.05.2024 09:19:43 - Instantiate download manager silently: False
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.11.34909.67,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.11.34909.67,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.11.34909.67,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:46 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.11.34909.67,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:47 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:47 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.11.34909.67,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.VisualStudio.Debugger.DbgHelp.Win8: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.3]".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.3]".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.VisualStudio.Debugger.Remote.DbgHelp.Win8: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.3]".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.8: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.2,6.3)".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.81: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.3,6.4)".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Net.4.8.FullRedist: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1.1,10.0.17763]".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Net.4.8.FullRedist.Resources: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1.1,10.0.19042)".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Net.4.8.KB5003306: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[10.0.18362,10.0.18363]".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Net.4.8.KB5003304: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[10.0.19041,10.0.19042)".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.Windows.UniversalCRT.Msu.7: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.2)".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.VisualStudio.NuGet.PowershellBindingRedirect: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.2)".
24.05.2024 09:19:47 - Skipping non-applicable package Microsoft.DiagnosticsHub.KB2882822.Win7: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "[6.1,6.2)".
24.05.2024 09:19:49 - Windows Installer found the package 'Microsoft.VisualStudio.Community.Msi,version=17.9.34511.75,machinearch=arm64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:50 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:50 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.9.34511.75,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:50 - Skipping non-applicable package Microsoft.Ancm.IIS.Msi: Erforderliche Bedingungen nicht erfüllt: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
24.05.2024 09:19:50 - Skipping non-applicable package Microsoft.Ancmv2.IIS.Msi: Erforderliche Bedingungen nicht erfüllt: IISCoreWebEngineInstalledx64 And IISW3SvcInstalledx64
24.05.2024 09:19:50 - Skipping non-applicable package Microsoft.Azure.PowerShell: Erforderliche Bedingungen nicht erfüllt: Not Powershell5
24.05.2024 09:19:50 - Windows Installer found the package 'Microsoft.VisualStudio.Vsto.Msi.x64,version=17.8.34204.178,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:50 - Skipping non-applicable package Microsoft.VisualStudio.OfficeDeveloperTools.WindowsIdentityFoundation.Msu: Die aktuelle Betriebssystemversion 10.0.19045.0 liegt nicht im unterstützten Versionsbereich "(,6.2)".
24.05.2024 09:19:50 - Windows Installer found the package 'Microsoft.NetCore.TargetingPack.5.0.5.0.0,version=17.11.34909.67,chip=x64' superseded but corresponding compatible package information was not found. Attempts to repair will be skipped and that to uninstall may leave the cache behind.
24.05.2024 09:19:50 - Scheduling without hotload: No installation activities were planned
24.05.2024 09:19:50 - Pre-check verification: Visual Studio requires a system restart to continue. Please restart your system and try again.
24.05.2024 09:19:50 - Pre-check verification failed with error(s) :  SoftRebootStatusCheck.
24.05.2024 09:19:50 - Pre-check verification failed with error(s) :  SoftRebootStatusCheck.
24.05.2024 09:19:50 - Installationsfehler: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> Microsoft.VisualStudio.Setup.CanceledByPrecheckException: Pre-check verification failed with error(s) :  SoftRebootStatusCheck.
   bei Microsoft.VisualStudio.Setup.PrecheckManager.RunPrechecks(PrecheckParameters precheckParameters, VariableCollection properties)
   bei Microsoft.VisualStudio.Setup.Engine.RunPrecheck(String destination, Product product, ExecuteAction action, IWindowsRestartManager rmService, ITelemetryOperation installOperation, InstallOperation install)
   bei Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   bei Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei Microsoft.VisualStudio.ExtensionManager.SetupEngineService.Install()
   bei Microsoft.VisualStudio.ExtensionManager.InstallModule.PerformSetupEngineInstall(InstallableExtensionImpl extensionToInstall, Boolean installPerMachine, Boolean isPackComponent, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, IProgress`1 progress, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion, IInstalledExtension& newExtension)
   bei Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallInternal(InstallableExtensionImpl extension, InstallFlags installFlags, IDictionary`2 extensionsInstalledSoFar, List`1 extensionsUninstalledSoFar, IInstalledExtensionList modifiedInstalledExtensionsList, AsyncOperation asyncOp, IProgress`1 progress, Version targetedVsVersion)
   bei Microsoft.VisualStudio.ExtensionManager.InstallModule.BeginInstall(IInstallableExtension installableExtension, InstallFlags installFlags, AsyncOperation asyncOp, Version targetedVsVersion)
   bei Microsoft.VisualStudio.ExtensionManager.InstallModule.InstallWorker(IInstallableExtension extension, InstallFlags installFlags, AsyncOperation asyncOp)
---> (Interne Ausnahme #0) Microsoft.VisualStudio.Setup.CanceledByPrecheckException: Pre-check verification failed with error(s) :  SoftRebootStatusCheck.
   bei Microsoft.VisualStudio.Setup.PrecheckManager.RunPrechecks(PrecheckParameters precheckParameters, VariableCollection properties)
   bei Microsoft.VisualStudio.Setup.Engine.RunPrecheck(String destination, Product product, ExecuteAction action, IWindowsRestartManager rmService, ITelemetryOperation installOperation, InstallOperation install)
   bei Microsoft.VisualStudio.Setup.Engine.Install(Product product, String destination, CancellationToken token)
   bei Microsoft.VisualStudio.ExtensionManager.SetupEngineService.<Install>b__14_0()
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()<---

**Comment by ErikEJ** [comment]
"Visual Studio requires a system restart to continue. Please restart your system and try again."

**Comment by ErikEJ** [comment]
Great news!

If you like my free tools, I would be very grateful for a rating or review on [Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=ErikEJ.EFCorePowerTools&ssr=false#review-details) or even a [one-time or monthly sponsorship](https://github.com/sponsors/ErikEJ?frequency=one-time&sponsor=ErikEJ)
