### ISSUE TITLE
Cant add a dataset on VS2022 and Win11

### ISSUE THREAD

**Issue by juanmanuelsanche** [ErikEJ/SqlCeToolbox#986]
I have tried the steps on the wiki and there is no GAC no matter what I do. Also when I try to add the  dataset everything checks out I even get a connection successful 
![Screenshot 2024-07-05 183947](https://github.com/ErikEJ/SqlCeToolbox/assets/28578187/ea38f4ca-ecac-46ea-b195-c6555688036f)

but the dataset properties goes blank again
![Screenshot 2024-07-05 184031](https://github.com/ErikEJ/SqlCeToolbox/assets/28578187/15d3b7e5-d06a-42c0-8598-787a292a5996)

Im also attaching machine.config file
[machine.zip](https://github.com/user-attachments/files/16114529/machine.zip)

Thanks in advance ! 
### Steps to reproduce
Just try to add  a dataset for reports in VS2022

### Further technical details
Toolbox/Power Tools version: 4.8.776

Database engine: (SQlite)

Visual Studio or SSMS version: 2022

**Comment by ErikEJ** [comment]
You are using Microsoft.Data.Sqlite, that does not work. You need System.Data.Sqlite, and I am not sure it works with the DataSource designer.

**Comment by juanmanuelsanche** [comment]
can you point me in the right direction to do it correctly? Im completely loss here and I appreciate the help

**Comment by ErikEJ** [comment]
You need to point to Sysystem.Data.Sqlite in the Choose your Datasource dialog.

**Comment by juanmanuelsanche** [comment]
![image](https://github.com/ErikEJ/SqlCeToolbox/assets/28578187/c2630842-8f79-45fc-89e8-ca8b2ce654fb)

Sadly it wont show the option...

**Comment by ErikEJ** [comment]
What you are asking for is not supported, as per the wiki:

"The System.Data.SQLite DDEX provider does not support Visual Studio 2017, 2019 and 2022. This post describes how to work with SQLite and Entity Framework 6 in Visual Studio 2017/2019/2022, using the "SQLite Toolbox" DDEX provider for EF6. Notice that this provider only supports the EF 6 Tools, and not other Data Source scenarios, for example Typed DataSets. This requires Visual Studio 2017 15.8 or later."
