### ISSUE TITLE
Helpme  how to join  menu on  sql exec window

### ISSUE THREAD

**Issue by lozn00** [ErikEJ/SqlCeToolbox#987]
How are these implemented? I can't use the code window unless I create a new SQL file

![image](https://github.com/ErikEJ/SqlCeToolbox/assets/14260426/b9913f05-57ec-4294-ad2e-f2a299d6c9fb)

**Comment by ErikEJ** [comment]
That does not look like SQLite Toolbox ??? But looks interesting and overwhelming

**Comment by ErikEJ** [comment]
In SSMS - I have not done that. Which extension has implemented this? Why not reach out to the author?

**Comment by ErikEJ** [comment]
I am unable to help you. You could try decompiling.
