### ISSUE TITLE
How to install SQLite_and_SQL_Server_Compact_Toolbox_v4.8.776.vsix

### ISSUE THREAD

**Issue by mwardell-Katmai** [ErikEJ/SqlCeToolbox#988]
Installation  is failing it shows me the log when in install SQLite_and_SQL_Server_Compact_Toolbox_v4.8.776.vsix

VS Version Version 17.8.1 ARM

### Steps to reproduce
run above .vsix
error log is then displayed as clickable

### Further technical details
the Error log 
7/25/2024 4:52:22 PM - Microsoft VSIX Installer
7/25/2024 4:52:22 PM - -------------------------------------------
7/25/2024 4:52:22 PM - vsixinstaller.exe version:
7/25/2024 4:52:22 PM - 17.8.2365+1ea9c98024
7/25/2024 4:52:22 PM - -------------------------------------------
7/25/2024 4:52:22 PM - Command line parameters:
7/25/2024 4:52:22 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\SQLite_and_SQL_Server_Compact_Toolbox_v4.8.776.vsix
7/25/2024 4:52:22 PM - -------------------------------------------
7/25/2024 4:52:22 PM - Microsoft VSIX Installer
7/25/2024 4:52:22 PM - -------------------------------------------
7/25/2024 4:52:23 PM - Initializing Install...
7/25/2024 4:52:23 PM - Searching for applicable products...
7/25/2024 4:52:24 PM - Found installed product - Visual Studio Professional 2022
7/25/2024 4:52:24 PM - Found installed product - Global Location
7/25/2024 4:52:24 PM - Extension Details...
7/25/2024 4:52:24 PM - 	Identifier         : 41521019-e4c7-480c-8ea8-fc4a2c6f50aa
7/25/2024 4:52:24 PM - 	Name               : SQLite and SQL Server Compact Toolbox
7/25/2024 4:52:24 PM - 	Author             : ErikEJ
7/25/2024 4:52:24 PM - 	Version            : 4.8.776
7/25/2024 4:52:24 PM - 	Description        : SQLite / SQL Server Compact Toolbox extension for Visual Studio. This extension adds several features to help your embedded database development efforts: Scripting of tables and data, import from SQL Server and CSV files and much, much more.
7/25/2024 4:52:24 PM - 	Locale             : en-US
7/25/2024 4:52:24 PM - 	MoreInfoURL        : https://github.com/ErikEJ/SqlCeToolbox
7/25/2024 4:52:24 PM - 	InstalledByMSI     : False
7/25/2024 4:52:24 PM - 	SupportedFrameworkVersionRange : [4.7.2,)
7/25/2024 4:52:24 PM - 	SignatureState     : Unsigned
7/25/2024 4:52:24 PM - 	Supported Products : 
7/25/2024 4:52:24 PM - 		Microsoft.VisualStudio.Community
7/25/2024 4:52:24 PM - 			Version : [15.0,17.0)
7/25/2024 4:52:24 PM - 			ProductArchitecture : x86
7/25/2024 4:52:24 PM - 		Microsoft.VisualStudio.Community
7/25/2024 4:52:24 PM - 			Version : [17.0,18.0)
7/25/2024 4:52:24 PM - 			ProductArchitecture : amd64
7/25/2024 4:52:24 PM - 	References         : 
7/25/2024 4:52:24 PM - 	Prerequisites      : 
7/25/2024 4:52:24 PM - 		-------------------------------------------------------
7/25/2024 4:52:24 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
7/25/2024 4:52:24 PM - 		Name         : Visual Studio core editor
7/25/2024 4:52:24 PM - 		Version      : [15.0,)
7/25/2024 4:52:24 PM - 		-------------------------------------------------------
7/25/2024 4:52:24 PM - 		Identifier   : Microsoft.VisualStudio.Component.VisualStudioData
7/25/2024 4:52:24 PM - 		Name         : Data sources and service references
7/25/2024 4:52:24 PM - 		Version      : [15.0,)
7/25/2024 4:52:24 PM - 		-------------------------------------------------------
7/25/2024 4:52:24 PM - 		Identifier   : Microsoft.VisualStudio.Component.ManagedDesktop.Prerequisites
7/25/2024 4:52:24 PM - 		Name         : .NET desktop development tools
7/25/2024 4:52:24 PM - 		Version      : [15.0,)
7/25/2024 4:52:24 PM - Signature Details...
7/25/2024 4:52:24 PM - 	Extension is not signed.
7/25/2024 4:52:24 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Visual Studio or SSMS version: (e.g. Visual Studio 2017 15.3, SSMS 17.3)
SQLite_and_SQL_Server_Compact_Toolbox_v4.8.776.vsix

**Comment by ErikEJ** [comment]
"This extension is not installable on any currently installed products."

ARM64 is not supported!
