### ISSUE TITLE
Script Database Diff for SQLite in VS Extension

### ISSUE THREAD

**Issue by alexey-leonovich** [ErikEJ/SqlCeToolbox#990]
[SQLite and SQL Server Compact Toolbox VS Extension](https://marketplace.visualstudio.com/items?itemName=ErikEJ.SQLServerCompactSQLiteToolbox) has **Script Database** -> **Script Diff** menu option for SQL Server Compact 
![image](https://github.com/user-attachments/assets/d3b395b6-ce9e-4047-bf4e-742562cbfb6f)
but lacks that option for SQLite:
![image](https://github.com/user-attachments/assets/28c177de-1771-4678-929f-ca99483da025)
Add it please. Thank you.

**Comment by ErikEJ** [comment]
Sorry, due to the huge difference betwee SQL Compact and SQLite, this is not something I plan to do
