### ISSUE TITLE
The SSSCT 4.8 window tab doesn't display an icon in VS 2022.

### ISSUE THREAD

**Issue by opuscula** [ErikEJ/SqlCeToolbox#995]
In Visual Studio 2022 17.11.5, the SSSCT 4.8 window tab doesn't display an icon when sufficiently narrowed.

![SSSCT](https://github.com/user-attachments/assets/442c0e30-eb4d-4234-96f5-095ffd3226f1)

**Comment by ErikEJ** [comment]
It has never had an icon in that area of the screen, so the text based label dissapears, yes, If you make it even more narrov, the images from the other tabs also dissapear.

**Comment by opuscula** [comment]
Adding an icon would be very helpful.

**Comment by ErikEJ** [comment]
Yes, working on it, but having severe issues debugging.

**Comment by ErikEJ** [comment]
![image](https://github.com/user-attachments/assets/0ff35b04-d07d-4816-a6c1-15e1a5657d07)

**Comment by ErikEJ** [comment]
@opuscula This has been fixed in the latest daily build, thanks for bringing it up
